### ISSUE TITLE
添加项目按钮不能用

### ISSUE THREAD

**Issue by 353355756** [YMFE/yapi#1]
火狐(55.0.2 64位)ubuntu 项目空间中的“添加项目”按钮点击没有反应，chromium能够正常使用

**Comment by suxiaoxin** [comment]
@353355756 非常感谢反馈
YApi 接口管理平台是面向开发和 QA 人员的，我们的测试功能也是基于chrome 扩展开发的，推荐使用chrome 浏览器

**Comment by 353355756** [comment]
ok
