### ISSUE TITLE
强烈建议用 PHP+MySQL 重写，这种架构的实在感觉不稳定！

### ISSUE THREAD

**Issue by lxtac** [YMFE/yapi#100]
## Version
~ 

## What is expected
~

## Step to reproduce
~ 

## Environment
~

**Comment by xuliuzhu1834** [comment]
为什么会觉得不稳定呢

**Comment by suxiaoxin** [comment]
我们公司（去哪儿）上千开发者在用，没出现什么问题，很稳定。

**Comment by dullme** [comment]
灰常麻烦 要装 mongodb

**Comment by wengpengfeijava** [comment]
个人感觉文档很清晰，上手容易，安装简易。 @dullme
