### ISSUE TITLE
请求配置修改global环境变量Cannot read property 'dev' of undefined

### ISSUE THREAD

**Issue by TianTian106** [YMFE/yapi#1006]
## 版本号
~ 1.5.11

## 什么问题
~ 获取和设置环境变量值出现问题：context.envParams.环境名称.global.属性名

## 如何复现此问题
~  设置：
    环境配置->环境名称：dev
    环境配置->global：atest = 2
    请求配置： context.envParams.dev.global.atest = 1;
  
    我想测试把global的atest = 2 运行后改为 atest = 1，不知道是否我理解有问题哪里配的不对，
    运行报错：message: Cannot read property 'dev' of undefined

## 什么浏览器
~ chrom 73.0.3683.103

## 什么系统（Linux, Windows, macOS）
Windows

**Comment by hellosean1025** [comment]
升级到最新版试试
