### ISSUE TITLE
Ldap配置后未生效

### ISSUE THREAD

**Issue by krisbai** [YMFE/yapi#1009]
## 版本号
~ 1.3.20
node：v8.11.3
## 什么问题
~ 配置完LDAP后，通过主页输入账号密码登录无响应

## 如何复现此问题
~ 
日志信息：(node:7) UnhandledPromiseRejectionWarning: #<Object>
(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

## 什么浏览器
~ 
chrom
## 什么系统（Linux, Windows, macOS）
linux  （docker）

**Comment by rootrl** [comment]
同出现，解决了吗？网络一直pending状态

**Comment by rootrl** [comment]
解决了，注意config.json写的不对，db的密码项都要删除，参考容器内的例子

**Comment by ahdwdhl** [comment]
> 解决了，注意config.json写的不对，db的密码项都要删除，参考容器内的例子

配置可以贴出下吗，测了下有类似的问题

**Comment by krisbai** [comment]
> > 解决了，注意config.json写的不对，db的密码项都要删除，参考容器内的例子
> 
> 配置可以贴出下吗，测了下有类似的问题

最后看了下是ldap的配置问题，你可以把你的配置贴一下，我看看你哪一块配置的有问题。

**Comment by GreedyPirate** [comment]
@rootrl @krisbai 
```
  "ldapLogin": {
      "enable": true,
      "server": "ldap://ip:port",
      "baseDn": "cn=xxx,dc=xxx,dc=xxx",
      "bindPassword": "xxx",
      "searchDn": "ou=xxx,dc=xxx,dc=xxx",
      "searchStandard": "&(objectClass=user)(cn={0})"
   }
```
 以下是我另一个java项目中的配置
```
spring.ldap.urls=ldap://ip:port
spring.ldap.username=cn=xxx,dc=xxx,dc=xxx
spring.ldap.password=xxx
spring.ldap.base=ou=xxx,dc=xxx,dc=xxx
spring.ldap.userDnPatterns=cn={0}
```
这是db的配置，在没加ldap之前一直稳定运行
```
   "db": {
      "servername": "127.0.0.1",
      "DATABASE": "yapi",
      "port": "27017"
   },
```
现在登录一直pending，请问该如何配置？

**Comment by webkong** [comment]
> @rootrl @krisbai
> 
> ```
>   "ldapLogin": {
>       "enable": true,
>       "server": "ldap://ip:port",
>       "baseDn": "cn=xxx,dc=xxx,dc=xxx",
>       "bindPassword": "xxx",
>       "searchDn": "ou=xxx,dc=xxx,dc=xxx",
>       "searchStandard": "&(objectClass=user)(cn={0})"
>    }
> ```
> 
> 以下是我另一个java项目中的配置
> 
> ```
> spring.ldap.urls=ldap://ip:port
> spring.ldap.username=cn=xxx,dc=xxx,dc=xxx
> spring.ldap.password=xxx
> spring.ldap.base=ou=xxx,dc=xxx,dc=xxx
> spring.ldap.userDnPatterns=cn={0}
> ```
> 
> 这是db的配置，在没加ldap之前一直稳定运行
> 
> ```
>    "db": {
>       "servername": "127.0.0.1",
>       "DATABASE": "yapi",
>       "port": "27017"
>    },
> ```
> 
> 现在登录一直pending，请问该如何配置？

遇到了同样的问题，如何解决呢

**Comment by krisbai** [comment]
> @rootrl @krisbai
> 
> ```
>   "ldapLogin": {
>       "enable": true,
>       "server": "ldap://ip:port",
>       "baseDn": "cn=xxx,dc=xxx,dc=xxx",
>       "bindPassword": "xxx",
>       "searchDn": "ou=xxx,dc=xxx,dc=xxx",
>       "searchStandard": "&(objectClass=user)(cn={0})"
>    }
> ```
> 
> 以下是我另一个java项目中的配置
> 
> ```
> spring.ldap.urls=ldap://ip:port
> spring.ldap.username=cn=xxx,dc=xxx,dc=xxx
> spring.ldap.password=xxx
> spring.ldap.base=ou=xxx,dc=xxx,dc=xxx
> spring.ldap.userDnPatterns=cn={0}
> ```
> 
> 这是db的配置，在没加ldap之前一直稳定运行
> 
> ```
>    "db": {
>       "servername": "127.0.0.1",
>       "DATABASE": "yapi",
>       "port": "27017"
>    },
> ```
> 
> 现在登录一直pending，请问该如何配置？

-------以下是我的配置，仅供参考--------

  "ldapLogin": {
      "enable": true,
      "server": "ldap://IP:389",
      "baseDn": "cn=xx,dc=xx,dc=com",
      "bindPassword": "xxx",
      "searchDn": "dc=xx,dc=com",
      "searchStandard": "mail"
   }

**Comment by krisbai** [comment]
> > @rootrl @krisbai
> > ```
> >   "ldapLogin": {
> >       "enable": true,
> >       "server": "ldap://ip:port",
> >       "baseDn": "cn=xxx,dc=xxx,dc=xxx",
> >       "bindPassword": "xxx",
> >       "searchDn": "ou=xxx,dc=xxx,dc=xxx",
> >       "searchStandard": "&(objectClass=user)(cn={0})"
> >    }
> > ```
> > 
> > 
> > 以下是我另一个java项目中的配置
> > ```
> > spring.ldap.urls=ldap://ip:port
> > spring.ldap.username=cn=xxx,dc=xxx,dc=xxx
> > spring.ldap.password=xxx
> > spring.ldap.base=ou=xxx,dc=xxx,dc=xxx
> > spring.ldap.userDnPatterns=cn={0}
> > ```
> > 
> > 
> > 这是db的配置，在没加ldap之前一直稳定运行
> > ```
> >    "db": {
> >       "servername": "127.0.0.1",
> >       "DATABASE": "yapi",
> >       "port": "27017"
> >    },
> > ```
> > 
> > 
> > 现在登录一直pending，请问该如何配置？
> 
> 遇到了同样的问题，如何解决呢

-------变更ldap最后的参数配置---------
"searchStandard": "mail"
