### ISSUE TITLE
1.7.0-beta.0更新测试用例无效

### ISSUE THREAD

**Issue by liguoqinjim** [YMFE/yapi#1018]
## 版本号
1.7.0-beta.0

## 什么问题
更新测试集合里面的测试更新虽然弹出了更新成功，但是其实没有更新

![image](https://user-images.githubusercontent.com/2113954/56733902-0187ab80-6794-11e9-802e-1832e627c5bc.png)
返回也显示成功，但是其实更新没有更新。。

## 什么浏览器
Chrome

## 什么系统（Linux, Windows, macOS）
macOs

**Comment by liguoqinjim** [comment]
我试了下，退到v.1.5.14更新没问题

**Comment by hellosean1025** [comment]
应该不是 1.7.0 版本问题，升级后请重启服务器和刷新页面
