### ISSUE TITLE
yapi server后，访问ip:9090打不开页面

### ISSUE THREAD

**Issue by wcycxp** [YMFE/yapi#102]
![image](https://user-images.githubusercontent.com/23310275/34483255-3a54abbc-eff8-11e7-91a1-01b153a7ae25.png)
阿里云服务器上安装后使用yapi server命令，本地游览器中使用ip:9090打不开页面，ip已经替换成服务器的地址

**Comment by suxiaoxin** [comment]
查看下内网部署 方式二
