### ISSUE TITLE
【功能需求】邮件发送策略

### ISSUE THREAD

**Issue by frozensoft** [YMFE/yapi#1025]
## 版本号
~ 
1.5.14
## 什么问题
~
接口编辑过程中，每一次保存均发送邮件，太频繁，尤其有随手保存的习惯时。希望提供基于事件的邮件发送策略。
如：send_email_before_complete:false。如果接口未完成，不发送邮件。
        send_email_on_events:['create_api', 'update_api','delete_api',......]
## 如何复现此问题
~ 
1、配置邮箱
2、编辑接口，保存。
## 什么浏览器
~ 
Chrome
## 什么系统（Linux, Windows, macOS）
macOS

**Comment by frozensoft** [comment]
接口编辑最底部有关闭邮件通知的设置，没有看到。

**Comment by zhanfenghai** [comment]
@frozensoft 你好 我想问下这个邮件通知的功能是怎么配置的
