### ISSUE TITLE
npm run install-server执行时提示mongo没有权限怎么处理？

### ISSUE THREAD

**Issue by wcycxp** [YMFE/yapi#103]
npm run install-server执行时提示如下：
![image](https://user-images.githubusercontent.com/23310275/34508393-b41df814-f079-11e7-923c-1a11ea85859f.png)

**Comment by suxiaoxin** [comment]
查下 mongodb 设置用户权限文档

**Comment by dlutwuwei** [comment]
也碰到这个问题，完全不知道为啥没权限，压根还没创建用户

**Comment by dongdongzld** [comment]
创建mongodb db,user
将创建成功的 db及user 配置到config.json文件内即可
如 mongo --port 27017 -u "apidocuser" -p "apidocpwd" --authenticationDatabase "apidoc" 可访问即为配置成功，将相应参数配置到config.json内即可

**Comment by wcycxp** [comment]
谢谢各位的帮助~

**Comment by JanYunkai** [comment]
使用role userAdminAnyDatabase [创建用户失败，替换为dbAdmin](https://www.xttblog.com/?p=3425)
还是提示mongodb Authentication failed
