### ISSUE TITLE
swagger 自动同步插件无效

### ISSUE THREAD

**Issue by z-wyd** [YMFE/yapi#1032]
## 版本号
~ 
v1.7.0
## 什么问题
~
swagger 自动同步插件无效, 服务端有定时器日志打印
![image](https://user-images.githubusercontent.com/10329981/56861137-c8884a80-69d0-11e9-9b45-282cda452017.png)

## 如何复现此问题
~ 

## 什么浏览器
~ 
chrome
## 什么系统（Linux, Windows, macOS）
win10

**Comment by shouldnotappearcalm** [comment]
看下项目的动态里面的内容是什么

**Comment by xuekui8291** [comment]
![image](https://user-images.githubusercontent.com/12760090/57917589-93806100-78c7-11e9-95b1-62d3ac95c6fd.png)

**Comment by shouldnotappearcalm** [comment]
你是不是对这个路径做了鉴权操作什么的，你试试打开个chrome无痕窗口试试访问这个路径能看到内容吗

**Comment by z-wyd** [comment]
好像我我把原来的删除了，就不行了

**Comment by shouldnotappearcalm** [comment]
应该也不会吧，能看下你怎么配置使用的么？截个图

**Comment by z-wyd** [comment]
![TIM图片20190518092325](https://user-images.githubusercontent.com/10329981/57962896-8ad36d80-794f-11e9-90ff-9c44a2d46955.png)

**Comment by shouldnotappearcalm** [comment]
看日志是同步成功的，但是没有更新到接口上吗？

**Comment by z-wyd** [comment]
对 删除后，后面的日志提示是接口没有更新

**Comment by shouldnotappearcalm** [comment]
所以你是代码里删除了一些接口，然后这边没有删除？

**Comment by z-wyd** [comment]
不是 接口文档没变，是我在yapi这边把接口删除了

**Comment by z-wyd** [comment]
![image](https://user-images.githubusercontent.com/10329981/57962970-45fc0680-7950-11e9-9cb9-b1b02efc2157.png)

**Comment by shouldnotappearcalm** [comment]
yapi里面手动删除了一些接口？然后自动同步就同步不过来了？

**Comment by z-wyd** [comment]
嗯

**Comment by shouldnotappearcalm** [comment]
那你可以在设置自动同步那个页面，什么都不用改，就点一下保存试试

**Comment by z-wyd** [comment]
。。。还是没用

**Comment by shouldnotappearcalm** [comment]
要不。。你改一下你项目的某一个接口，注释应该也行，这样生成的swagger数据就会不一样，再点击保存。
主要是我这边会判断，如果你上次同步的数据和这次同步的swagger数据没差别，就不会去执行同步这个操作

**Comment by xuekui8291** [comment]
我这边是可以了， 原因是一部分应用，被访问/v2/api-docs接口时， 在 swagger.json 外包又包了一层actionResult， 是自己应用问题

**Comment by shouldnotappearcalm** [comment]
好的

**Comment by miaoshuaigit** [comment]
@xuekui8291 同步的时候，如果有些接口删除了，可以自动把yapi里面对应的也删除了吗？这样才是完全覆盖吧。

**Comment by liuchaobiao** [comment]
我配置了swagger自动同步，日志里面也有同步日志，但是接口同步没有效果，不知道是什么原因，可以麻烦解答一下吗？谢谢！

**Comment by shouldnotappearcalm** [comment]
动态里面截图看下

**Comment by WangShuXian6** [comment]
接口路径改编，但内容不变也是提示 [自动同步接口状态:成功,合并模式:完全覆盖,更多信息:接口无更新]
