### ISSUE TITLE
高级mock功能的使用体验建议

### ISSUE THREAD

**Issue by gogoyqj** [YMFE/yapi#104]
## Version
all

个人在使用是，开启高级mock功能，期望依旧可以使用 "@word" 之类的功能，建议在 mockServer 内再做一次解析:
```javascript

// from 
return ctx.body = context.mockJson;
// to 
return ctx.body = Mock.mock(context.mockJson);
```

**Comment by suxiaoxin** [comment]
@gogoyqj 请升级到最新版，已经做了 mockjs 解析

**Comment by gogoyqj** [comment]
已经升级到 1.3.3
![image](https://user-images.githubusercontent.com/1776278/34762504-ffe9768e-f622-11e7-92eb-49248e46cc1d.png)

**Comment by suxiaoxin** [comment]
高级 js 那个可以调用 random 函数生成随机字符串
