### ISSUE TITLE
插件机制不完善

### ISSUE THREAD

**Issue by bnubobby** [YMFE/yapi#1040]
目前的插件机制，感觉比较不便
如添加 oauth 的插件，需要编译，会更改视图内容, 那是不是意味着无法更新了？ 
期望插件，即插即用， 视图内容可以由插件自己定义，勾子和中间件都有了，敢不敢更进一步？

**Comment by bnubobby** [comment]
建议：
１.　server/plugin.js
       修改
      let pluginsConfig = initPlugins(yapi.WEBCONFIG.plugins, 'plugin');
      pluginsConfig.forEach(plugin => {
       // ..........
           new_path =  plugin.path ||  plugin_path
           yapi.path.join(new_path , 'yapi-plugin-' + plugin.name + '/server.js')
      //.............
   改为插件路径可自定义
    理由：  在项目中，自主开发的插件，一般都会放在私有仓库中。

2.  server/router.js；  server/utils/common.js

      if (pluginsRouterPath.indexOf(routerPath) > -1) {
             // 这里更改成，插件可重新定义系统路由
         }
     理由：  在oauth中，比如，为项目添加成员等 取用户列表场景中，可以从用户中心中取得数据，而不是依靠本地。
     同理，如果可以重写   /login   的路由，由插件提供视图，这样会更灵活，目前的oauth插件做不到这一点。

**Comment by hellosean1025** [comment]
@bnubobby 支持自定义插件的，可参考下 sso 插件

**Comment by bnubobby** [comment]
@hellosean1025  我看过sso插件啊，比 oauth2 插件更简单
我的意思不是说不支持自定义插件，而是自定义插件的机制不够完善

**Comment by hellosean1025** [comment]
@bnubobby  ...
package.json 支持本地文件，或私有 git 仓库的，google 下吧
