### ISSUE TITLE
提了很多问题，都没有响应，很影响我继续推广这个工具

### ISSUE THREAD

**Issue by sephirothgao** [YMFE/yapi#1044]
## 版本号
1.4.2 

## 什么问题
内部使用，被吐槽了很多问题，如果不解决，很影响此工具继续推广，请开发者们重视

BUG：
	1、在测试集合中连续删除测试用例会导致所有的测试集合成关闭状态。
	2、克隆测试用例偶尔失败，而克隆测试集合经常性失败。
	3、在一个项目中导入另一个项目的接口时，当前页面会跳转到相应的项目中。
	4、在测试集合的搜索状态下无法对测试用例进行拖动排序。
	5、在测试用例与测试集合之间进行切换时偶尔会出现不停地循环跳转。
需求：
	1、批量克隆、导入、删除和排序测试用例。
	2、运行测试集合时应该有相应的控制按钮对其进行控制，比如停止运行按钮。
	3、克隆测试用例和测试集合的位置应该出现在当前相对位置的上方或下方。
	4、测试用例的key值应该方便查看。
	5、编辑接口时能够对路径参数进行保存。
	6、当某接口发生变更时，可以很快的搜出影响的案例。

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by sephirothgao** [comment]
为什么直接关闭了呢？有人用，提出一些问题，不看一看吗？

**Comment by TinChiWay** [comment]
无论次issue存在什么描述性的不妥，但是开发人员在没有给出任何反馈的情况就直接关闭，这对他人对项目都不好，当一个项目不关心使用者时，使用者也会渐渐对此项目失去信心
但失去使用者对项目来说意味着什么呢？
