### ISSUE TITLE
是否支持接口响应体的全局包装，自定义包装结构

### ISSUE THREAD

**Issue by fyzwjd** [YMFE/yapi#1048]
## 版本号
~ 1.7.0

## 什么问题
~是否支持接口响应体的全局包装，比如接口定义返回{ a: 'xxx' }，请求该接口时返回{ code: 200, message: 'success', data: { a: 'xxx' } }

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by fyzwjd** [comment]
用全局mock可实现：
mockJson={
    meta: {
        code: 200,
        message: 'successful'
    },
    data: mockJson
};

**Comment by Lynn-cc** [comment]
@fyzwjd  如果这样改了的话，结构的自动测试用例上是怎么搭配修改呢？
