### ISSUE TITLE
能否提供一个数据导入的接口

### ISSUE THREAD

**Issue by noraincode** [YMFE/yapi#105]
## Version
~ all

## What is expected
~ 能否提供一个接口，用于导入代码中的注释作为文档？

例如使用 JSDOC 编写的接口注释，通过 gulp  打包为 JSON 文件，上传到对应的项目下，并解析为各接口的注释

**Comment by Mrtao1028** [comment]
正计划自己写，
1. 项目编辑初添加一个功能  生成项目token
2. 通过 gulp + jsdoc-api 获取 doclets ,然后上传

**Comment by suxiaoxin** [comment]
接口文档添加和编辑可以调用 /api/interface/add /api/interface/up 接口

接口调用查看下：
controller/interface 
* add
* up

@noraincode @Mrtao1028 你们为什么用 jsdoc ，而不是 apidoc?

**Comment by suxiaoxin** [comment]
@Mrtao1028 可以考虑做成一个通用的插件

**Comment by Mrtao1028** [comment]
用JSDoc 习惯吧， 接口之外的代码也是用的jsdoc。
在公司内网已经实现了， 没有独立写接口：
1. 添加一个账号 tokenEditor
2. projectModel 添加属性 update_token
3. 修改了 baseController 的 checkLogin,   checAuth
4.utils.common.createAction 添加 /api/interface 兼容
其他是走原来的逻辑。用到了下面几个接口：
1.  /api/interface/list_menu
2.  /api/interface/add_cat
3. /api/interface/add
4. /api/interface/up

后面可以弄到插件里面

**Comment by suxiaoxin** [comment]
@Mrtao1028 做好后可以 pr 下
