### ISSUE TITLE
chrome 63.0.3239.108 打开异常

### ISSUE THREAD

**Issue by Mrtao1028** [YMFE/yapi#106]
## Version
~ 1.3.2

##  资源加载失败， 官方Demo也是一样的情况http://yapi.demo.qunar.com/
~ 
![image](https://user-images.githubusercontent.com/7741839/34561915-09ba2ec4-f187-11e7-944d-fd898a9f2fdf.png)

## Step to reproduce
~ 

## Environment
~ 
![image](https://user-images.githubusercontent.com/7741839/34561956-39cd17f2-f187-11e7-99c7-ce6a85c8a7d8.png)

**Comment by gaoxiaomumu** [comment]
您回退到1.3.1试试

**Comment by Mrtao1028** [comment]
其他版本的chrome 没问题， 基本不在公网用。
暂时先用 Firefox 看着， 等下个版本
