### ISSUE TITLE
前端代码引入了cdn资源，内网部署样式异常

### ISSUE THREAD

**Issue by Mrtao1028** [YMFE/yapi#107]
## Version
~ 1.32

##  前端代码引入了cdn资源，内网部署样式异常
![image](https://user-images.githubusercontent.com/7741839/34564167-97fbe6e2-f190-11e7-88a3-df9d0d48ab7d.png)
![image](https://user-images.githubusercontent.com/7741839/34564171-9bf97584-f190-11e7-8756-590d4b73b755.png)

## Environment
~

**Comment by suxiaoxin** [comment]
可能是网络不好，过会就没问题了

**Comment by Mrtao1028** [comment]
我可能没表述清楚。
公司内网跟公网是完全隔离的，
 master分支index@xxxx.css 引入的CDN的资源是永远访问不了的

我现在是临时从 cdn上下载，将缺少的图标 放在 static/t 目录下，
然后 进入 static/prd 目录执行下面两个命令：
```bash
sed -i 's/htts:\/\/at.alicdn.com//g'  index@xxxxx.css 
gizp -c index@xxxxx.css > index@xxxxxx.css.gz 
```
