### ISSUE TITLE
interface/list_menu 接口数据太大

### ISSUE THREAD

**Issue by PichurChill** [YMFE/yapi#108]
## Version
~ 
V1.3.1
## What is expected
~
之前有段时间项目的`接口分类`老是加载很慢，起初以为自己服务器慢，后来一看 `interface/list_menu` 这个接口有好几M，看了一下是因为这个菜单接口（？）把`res_body`字段也带过来了，因为我们项目中有个门店的mock数据非常大，所以导致整个 ``interface/list_menu``就非常非常大
## Step to reproduce
~ 

## Environment
~ 
BTW，系统特别好用！帮了很大忙，谢谢！希望越来越强大！

**Comment by suxiaoxin** [comment]
Fixed. 下个版本更新

**Comment by supuwoerc** [comment]
> Fixed. 下个版本更新

请问一下这个问题修复了嘛，我们这边打算把内网部署的一个旧版本的项目同步修改下。
1.9.2版本：listByMenu调用了嵌套查询导致响应时间非常久。
