### ISSUE TITLE
接口协议设置为https请求不了

### ISSUE THREAD

**Issue by ffx0s** [YMFE/yapi#109]
## Version
~ 1.3.1

## Step to reproduce
~ 环境配置-> 环境域名-> 修改为 https 
chrome network 错误信息： Provisional headers are shown

## Environment
~ https://127.0.0.1:3000/mock/11/***

**Comment by gaoxiaomumu** [comment]
您好，服务器搭建的是http的，如果要用Https的话得加一层反向代理
