### ISSUE TITLE
所有用户名登录提示用户不存在，用邮箱登录时正常的

### ISSUE THREAD

**Issue by miaozilong** [YMFE/yapi#1112]
## 版本号
~ 最新版  刚下载的

## 什么问题
~所有用户名登录提示用户不存在，用邮箱登录时正常的

## 如何复现此问题
~ 

## 什么浏览器
~ chrome

## 什么系统（Linux, Windows, macOS）
win7

**Comment by miaozilong** [comment]
好吧  这系统登录界面上看到的就是要求输入email

**Comment by zero2lin** [comment]
同样发现这问题，而且我注册了多个相同用户名不同邮箱的账号。
还造成添加组员时，看到很多相同名字的用户，没法区分
