### ISSUE TITLE
已经按文档配置邮件，node提示收件人为定义

### ISSUE THREAD

**Issue by dawang90** [YMFE/yapi#112]
error: send mail  error,No recipients defined

**Comment by dawang90** [comment]
知道了，没有给项目添加成员

**Comment by ijustyce** [comment]
我使用最新版本，已经添加了管理员、开发者，依旧这个错误…

**Comment by pluto-er** [comment]
> 我使用最新版本，已经添加了管理员、开发者，依旧这个错误…

解决没？咋个解决的？

**Comment by pluto-er** [comment]
> 我使用最新版本，已经添加了管理员、开发者，依旧这个错误…

咋个解决的
