### ISSUE TITLE
cross-request 3.0 插件被禁用

### ISSUE THREAD

**Issue by rhett030** [YMFE/yapi#1125]
## 版本号
~ 1.5.13     cross-request 3.0 

## 什么问题
~ 
![image](https://user-images.githubusercontent.com/16421522/58933929-6c68d100-879b-11e9-8d0f-4a30a499e0bf.png)

## 如何复现此问题
~ 

## 什么浏览器
~  chrome 版本 74.0.3729.169（正式版本） （64 位）

## 什么系统（Linux, Windows, macOS）
Linux

**Comment by rhett030** [comment]
问题已解决，通过手动下载安装的插件无法识别，必须通过应用商店安装才能使用

**Comment by pengRW** [comment]
可是谷歌商店找不到 这个插件啊
