### ISSUE TITLE
部署后无法登录

### ISSUE THREAD

**Issue by letsky** [YMFE/yapi#1126]
## 版本号
~ 1.7.0和1.5.14

## 什么问题
~ 拉取源码安装以及下载zip包成功部署后，登录出现“Request failed with status code 405”。部署在阿里云服务器。
![Screenshot_20190605_213619](https://user-images.githubusercontent.com/27358450/58960540-f899e900-87d9-11e9-9d5c-cea85f78b037.png)

日志
![Screenshot_20190605_213709](https://user-images.githubusercontent.com/27358450/58960609-1d8e5c00-87da-11e9-8a38-c6f1b7902a4c.png)

## 如何复现此问题
~ 安装过两遍了，都出现此问题。

## 什么浏览器
~ Chrome 74.0.3729.169 x64

## 什么系统（Linux, Windows, macOS）
～ Ubuntu1~16.04.10

**Comment by letsky** [comment]
破案了，关闭代理即可。

**Comment by ydcun** [comment]
梯子不要一直竖在哪里

在 2019年6月5日，21:56，letsky <notifications@github.com<mailto:notifications@github.com>> 写道：


破案了，关闭代理即可。
