### ISSUE TITLE
服务端测试提示message: CryptoJS is not defined

### ISSUE THREAD

**Issue by kira5271** [YMFE/yapi#1129]
## 版本号
~ 1.74

## 什么问题
~ 服务端测试调用js脚本失败，message: CryptoJS is not defined

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by kira5271** [comment]
补充：
![image](https://user-images.githubusercontent.com/4507290/59262989-d76e4800-8c72-11e9-9fb6-523f663ba3cb.png)

**Comment by shouldnotappearcalm** [comment]
我说怎么有点眼熟这ID。。你把你用CryptoJS那段代码截出来啊

**Comment by kira5271** [comment]
> 我说怎么有点眼熟这ID。。你把你用CryptoJS那段代码截出来啊

let sign = CryptoJS.MD5(reqParamsStr).toString();

**Comment by shouldnotappearcalm** [comment]
真的都不去看看文档是不是自己问题的么  https://yapi.ymfe.org/documents/project.html#%E8%AF%B7%E6%B1%82%E9%85%8D%E7%BD%AE

CryptoJS 具体用法
```
var data = [{ id: 1 }, { id: 2 }];

// Encrypt
var ciphertext = context.utils.CryptoJS.AES.encrypt(JSON.stringify(data), 'secret key 123');

// Decrypt
var bytes = context.utils.CryptoJS.AES.decrypt(ciphertext.toString(), 'secret key 123');
var decryptedData = JSON.parse(bytes.toString(CryptoJS.enc.Utf8));

console.log('decryptedData', decryptedData);
```

**Comment by kira5271** [comment]
问题是，我上面的用法，在接口和集合调试都没问题，只是走服务端自动化测试才异常？

**Comment by shouldnotappearcalm** [comment]
那你也是用法不对啊，只是错误的用法在某些场景下还错误地成功了

**Comment by kira5271** [comment]
那我走正规用法再试试QAQ

**Comment by kira5271** [comment]
感谢老哥，问题已经解决了~~~
