### ISSUE TITLE
Swagger定时同步数据到Yapi 完全覆盖模式无效

### ISSUE THREAD

**Issue by tanjie123** [YMFE/yapi#1133]
## 版本号
1.7.0

## 什么问题
Swagger定时同步数据到Yapi时，完全覆盖模式无效。具体而言，当后端删除一个接口后，Yapi中并未同步删除该接口。

## 如何复现此问题
实验工程：https://github.com/tanjie123/yapi-swagger-demo
实验步骤：
1.运行该springboot工程，swagger接口数据地址：http://localhost:8080/v2/api-docs
2.同步swagger接口数据到yapi
3.注释掉deleteItem接口，具体如下所示：
/*
	 * @DeleteMapping("/items/{id}") public ResponseEntity<Void>
	 * deleteItem(@PathVariable Long id) {
	 * log.debug("REST request to delete Item : {}", id);
	 * itemRepository.deleteById(id); return
	 * ResponseEntity.ok().headers(HeaderUtil.createEntityDeletionAlert(ENTITY_NAME,
	 * id.toString())).build(); }
	 */
4.重启应用，等待同步结果

## 什么浏览器
chrome

## 什么系统（Linux, Windows, macOS）
Windows10

**Comment by shouldnotappearcalm** [comment]
这个不关自动同步功能的问题，YApi本身的完全覆盖规则如此，因为真的只保留本次导入swagger数据，那万一我自己手动录入了两个接口，下次完全覆盖导入swagger接口数据，手动录入的接口没了是不是也不太合理，你觉得呢

**Comment by tanjie123** [comment]
嗯，我现在理解了。谢谢

**Comment by chaosforfun** [comment]
手动录入的接口没了怎么就不合理了，这可是完全覆盖模式啊。 要想保留就选智能合并模式啊。

**Comment by chaosforfun** [comment]
目前这个现象就是完全覆盖模式的一个bug

**Comment by itengfei** [comment]
> 目前这个现象就是完全覆盖模式的一个bug

支持!，感觉定义有点模糊啊。。。

**Comment by livem** [comment]
对啊，【完全覆盖】这个定义模糊，要不更换一下文案吧
