### ISSUE TITLE
私有化部署 LDAP 无法建立公开项目

### ISSUE THREAD

**Issue by fenglai0802** [YMFE/yapi#1136]
## 版本号
~ 1.7.0

## 什么问题
通过docker 内网部署，配置了 ldap，但是目前项目只能设置 私有权限。看其他 issue，管理员可以在项目建立之后修改权限，但是通过 ldap 的账户如何设置管理员权限呢，在config.json里添加了adminAccount 貌似没用。

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by shinji3887** [comment]
同样的问题，求解

**Comment by shinji3887** [comment]
> ## 版本号
> ~ 1.7.0
> 
> ## 什么问题
> 通过docker 内网部署，配置了 ldap，但是目前项目只能设置 私有权限。看其他 issue，管理员可以在项目建立之后修改权限，但是通过 ldap 的账户如何设置管理员权限呢，在config.json里添加了adminAccount 貌似没用。
> 
> ## 如何复现此问题
> ~
> 
> ## 什么浏览器
> ~
> 
> ## 什么系统（Linux, Windows, macOS）

你好，我碰到同样的问题，怎么解决的？
