### ISSUE TITLE
服务端测试，修改crossRequest插件，感觉没执行到

### ISSUE THREAD

**Issue by ZhangWei55kai** [YMFE/yapi#1140]
## 版本号
~ 

## 什么问题
~1.由于yapi目前无法支持文件上传功能，所以对crossRequest做了修改，
两种执行方式：
1.通过YAPI平台直接测试，可以成功
2.通过服务端测试执行，直接失败

通过服务端测试时，该传的参数一个没少的传到了crossRequest方法中，但是执行结果却和平台执行不一样，并且服务端测试无法调试crossRequest，请问有什么办法调试这个问题

## 如何复现此问题
~ 打开平台注释的文件上传input选项，上传文件给七牛云，然后存储对应文件名，然后crossRequest通过传递文件名，读取七牛云中的文件，进行文件解析，然后执行对应的请求
![image](https://user-images.githubusercontent.com/20765481/59735247-64bf2700-9287-11e9-9f3b-7e0aed0e4cea.png)
通过平台执行  ↑  

![image](https://user-images.githubusercontent.com/20765481/59735281-86b8a980-9287-11e9-9c9b-92a73dfb1b02.png)
通过服务端执行 ↑ （这个errro自然不多说了，由于传文件失败导致的异常吧，文件为空文件没有啥的异常，总之平台能调用，服务端肯定也能调用了，自然不会是自己业务系统的问题了）

不是很清楚服务端是如何调用这个插件机制的，代码看了半天没看懂，如果知道方便调试的话，应该就知道该怎么解决了

以下是crossRequest中response.js  sendAjaxByBack的代码片段

`for (var name in req.files) {
                    let bodyData = req.files_url
                    let file_url = await get('http://***/upload_download?file_name=',bodyData)
                    console.log(JSON.parse(file_url.res).file_url)
                    docUrl = JSON.parse(file_url.res).file_url
                    let QINIUfile = new Promise(function (resolve, reject){
                        var xhr = new XMLHttpRequest();
                        xhr.open('GET',docUrl,true);
                        xhr.responseType = "blob";
                        xhr.send(null);
                        xhr.onreadystatechange = function(){
                            if(xhr.readyState === 4){
                                let reader = new FileReader();
                                reader.readAsDataURL(xhr.response);
                                reader.onload = function(e){
                                    resolve({fileName:bodyData,is_file:true,name:name,value:e.target.result});
                                }
                            }
                        }
                    })
                    allPromise.push(QINIUfile)
                }
            }
            Promise.all(allPromise).then(function(result){
                formDatas = formDatas.concat(result);
                req.formDatas = formDatas;
                connect.postMessage({
                    id: id,
                    req: req,
                });
            })
        }else {
            req.formDatas = formDatas;
            connect.postMessage({
                id: id,
                req: req,
            });
        }`

## 什么浏览器

谷歌
~ 

## 什么系统（Linux, Windows, macOS）
windows

**Comment by ZhangWei55kai** [comment]
顶顶，希望有大神出马帮忙解答一下，，，

**Comment by ZhangWei55kai** [comment]
顶顶的第二天，好像找到了一丝头绪：
从接口服务端返回的错误信息："Failed to parse multipart servlet request; nested exception is java.io.IOException: org.apache.tomcat.util.http.fileupload.FileUploadException: the request was rejected because no multipart boundary was found",（因为我是测试，java这个异常信息看不懂的。。）从谷歌中查到的结果是由于上传文件自作多情给了个content-type:multipart/form-data的头信息，所以才有会报错的，所以我借此查看background.js中是否在请求时没有将头信息删除掉。一查发现确实删除了：
![image](https://user-images.githubusercontent.com/20765481/59816803-13c73580-9350-11e9-9cc1-78af9065342f.png)

**Comment by ZhangWei55kai** [comment]
现在比较纠结的点是，这个run_auto_test 这个服务端测试的接口，是如何调用crossRequest的。
自己简单理了一下调用关系
server端首先runAutoTest controller 调用了一个叫做handleTest的方法，这个handleTest调用的crossRequest是通过postmanLib.js中导入进来的，和前端运行api调用逻辑如出一辙，
这时我为了验证这个问题，把插件crossRequest的插件删掉了，直接调用之前生成的run_auto_test的url，奇怪的是居然还能继续运行，按照这样来猜测的话，是否服务端测试根本就没有走插件的逻辑，但和之前推导出的结论又相矛盾，再次需要大神指点一二啊。急~~~

**Comment by ZhangWei55kai** [comment]
后端进了httpRequestByNode的方法，已经找到办法了，，，，

**Comment by shouldnotappearcalm** [comment]
老哥你这个会影响接口的原有定义不

**Comment by ZhangWei55kai** [comment]
不会影响接口原始数据，只是在以前的req_form_data字段的基础中加入了一个file_url的字段，实现逻辑很简单：
本地上传文件，如果没点更新按钮用原始base64逻辑上传文件，这个之前有大神分享过，点了更新按钮就请求了七牛云，这时只要保证插件代码response.js中能请求到七牛云文件就好了，然后将下载的文件流再次转base64套用之前逻辑就好.这个过程改动原始代码没有多少的，并且只是加了个字段，个人认为几乎没影响吧

**Comment by shouldnotappearcalm** [comment]
那你还得改插件代码，重新打包插件？

**Comment by ZhangWei55kai** [comment]
> 那你还得改插件代码，重新打包插件？

调试阶段可以直接导文件夹，不需要打包

**Comment by shouldnotappearcalm** [comment]
我看syxx/cross-request可以直接用啊，为什么要使用七牛云先上传文件呢

**Comment by ZhangWei55kai** [comment]
> 为什么要使用七牛云先上传文
不知道你说的可以直接用是什么意思，之前走本地测试确实可以直接用，但是如果页面关闭，或者页面被刷新，文件就没了因为你没落库，下次批量执行测试时，是取不到文件的
另外上传七牛云只是简单的做法，你不怕麻烦自己也可以弄个文件服务，自己存自己去都是没关系的

**Comment by shouldnotappearcalm** [comment]
能看看你cross-request插件的改动么

**Comment by ZhangWei55kai** [comment]
`function get(baseUrl,params) {
    return new Promise(function (resolve,reject) {
        var xhr = new XMLHttpRequest();
        url = baseUrl + params
        xhr.open('GET',url);
        xhr.send()
        xhr.onreadystatechange = function(){
            if(xhr.readyState === 4){
                resolve({res:xhr.response})
            }
        }
    })
}

async function sendAjaxByBack(id, req, successFn, errorFn) {
    successFns[id] = successFn;
    errorFns[id] = errorFn;
    console.log(req)
    if (req.headers['Content-Type'] === 'multipart/form-data') {
        var formDatas = []
        if (req.data) {
            for (var name in req.data) {
                formDatas.push({name, value: req.data[name], is_file: false});
            }
        }
        if (req.files && req.files.file) {
            let allPromise = [];
            if(req.files.file.substr(0,4) === 'file'){
                console.log('原生上传')
                for (var name in req.files) {
                    let fileTransfer = new Promise(function (resolve, reject){
                        var files = document.getElementById(req.files[name]).files;
                        let file = files[0]
                        var reader = new FileReader();
                        reader.name = name;
                        reader.fileName = file.name;
                        reader.onload = function () {
                            resolve({name: this.name, value: this.result,is_file: true, fileName: this.fileName});
                        }
                        reader.readAsDataURL(file);
                    })
                    console.log(fileTransfer)
                    allPromise.push(fileTransfer);
                    }
            }else{
                var docUrl = '';
                console.log('七牛云上传')
                console.log('正在获取七牛云中文件的url')
                for (var name in req.files) {
                    let bodyData = req.files_url
                    let file_url = await get('http://xxx:xxx/upload_download?file_name=',bodyData)
                    console.log(JSON.parse(file_url.res).file_url)
                    docUrl = JSON.parse(file_url.res).file_url
                    let QINIUfile = new Promise(function (resolve, reject){
                        var xhr = new XMLHttpRequest();
                        xhr.open('GET',docUrl,true);
                        xhr.responseType = "blob";
                        xhr.send(null);
                        xhr.onreadystatechange = function(){
                            if(xhr.readyState === 4){
                                let reader = new FileReader();
                                reader.readAsDataURL(xhr.response);
                                reader.onload = function(e){
                                    resolve({fileName:bodyData,is_file:true,name:name,value:e.target.result});
                                }
                            }
                        }
                    })
                    allPromise.push(QINIUfile)
                }
            }
            Promise.all(allPromise).then(function(result){
                formDatas = formDatas.concat(result);
                req.formDatas = formDatas;
                connect.postMessage({
                    id: id,
                    req: req,
                });
            })
        }else {
            req.formDatas = formDatas;
            connect.postMessage({
                id: id,
                req: req,
            });
        }
    } else {
        connect.postMessage({
            id: id,
            req: req
        });
    }
    // connect.postMessage({
    //     id: id,
    //     req: req
    // });
}`
resoponse.js修改的
`function dataURLtoFile(dataurl, filename) {
	var arr = dataurl.split(','), mime = arr[0].match(/:(.*?);/)[1],
		bstr = atob(arr[1]), n = bstr.length, u8arr = new Uint8Array(n);
	while(n--){
		u8arr[n] = bstr.charCodeAt(n);
	}
	return new File([u8arr], filename, {type:mime});
}

function sendAjax(req, successFn, errorFn) {
	var formDatas;
	var xhr = new XMLHttpRequest();

	req.headers = req.headers || {};
	req.headers['Content-Type'] = req.headers['Content-Type'] || req.headers['Content-type'] || req.headers['content-type'];// 兼容多种写法

	xhr.timeout = req.timeout || 1000000;

	req.method = req.method || 'GET';
	req.async = req.async === false ? false : true;
	req.headers = req.headers || {};
	if (req.method.toLowerCase() !== 'get' && req.method.toLowerCase() !== 'head' && req.method.toLowerCase() !== 'options') {
		if (!req.headers['Content-Type'] || req.headers['Content-Type'] == 'application/x-www-form-urlencoded') {
			req.headers['Content-Type'] = 'application/x-www-form-urlencoded';
			req.data = formUrlencode(req.data);
		} else if (typeof req.data === 'object' && req.data) {
			req.data = JSON.stringify(req.data);
		}
	}else{
    delete req.headers['Content-Type'];
  }
	if (req.query && typeof req.query === 'object') {
		var getUrl = formUrlencode(req.query);
		req.url = req.url + '?' + getUrl;
		req.query = '';
	}
	// if (!req.headers['Content-Type'] || req.headers['Content-Type'] == 'application/x-www-form-urlencoded') {
	// 	req.headers['Content-Type'] = 'application/x-www-form-urlencoded';
	// 	req.data = formUrlencode(req.data);
	// }
	else if (req.headers['Content-Type'] === 'multipart/form-data') {
		delete req.headers['Content-Type'];
		let formDatas = new FormData();
		for (var item of req.formDatas) {
			if (item.is_file) {
				formDatas.append(item.name, dataURLtoFile(item.value,item.fileName))
			}else {
				formDatas.append(item.name, item.value);
			}
		}
		req.data = formDatas;
	}`
background.js修改的
现在服务端测试仍然有问题，待会儿有空把问题贴出来，希望会node的大神帮忙解决下

**Comment by ZhangWei55kai** [comment]
最终解决，服务端最终采用请求转发的方式去处理文件上传的接口，

**Comment by ZhangWei55kai** [comment]
> 最终解决，服务端最终采用请求转发的方式去处理文件上传的接口，
由于我react+node之前没怎么用过，导致打包经常会出一些小插曲，所以就不打算动源码了，
事情是这样的：
本来打算用在postmanLib.js中修改代码支持文件上传的，想了2条思路，
1.做法同crossRequest一致，也是去七牛拿文件流然后执行，但是周末在家调试了一天都找不到，node代码直接将文件流放入form-data中的file对象，但是服务器一直识别不了这个流（大概率是写法或者其他什么问题吧）所以这个方法放弃了
2.后面打算用文件读写的方式，先存文件，然后再读文件，由于postmanLib.js文件在common目录下，打包时会检测目录下导入的类库，由于要读写文件，用到了fs的库，这时打包又异常了。最终又放弃了

直到最后还是选择用请求转发，将请求的数据，转发至后台的某个服务去执行该接口。OK就这样了

**Comment by TesterPi** [comment]
> `function get(baseUrl,params) {
> return new Promise(function (resolve,reject) {
> var xhr = new XMLHttpRequest();
> url = baseUrl + params
> xhr.open('GET',url);
> xhr.send()
> xhr.onreadystatechange = function(){
> if(xhr.readyState === 4){
> resolve({res:xhr.response})
> }
> }
> })
> }
> 
> async function sendAjaxByBack(id, req, successFn, errorFn) {
> successFns[id] = successFn;
> errorFns[id] = errorFn;
> console.log(req)
> if (req.headers['Content-Type'] === 'multipart/form-data') {
> var formDatas = []
> if (req.data) {
> for (var name in req.data) {
> formDatas.push({name, value: req.data[name], is_file: false});
> }
> }
> if (req.files && req.files.file) {
> let allPromise = [];
> if(req.files.file.substr(0,4) === 'file'){
> console.log('原生上传')
> for (var name in req.files) {
> let fileTransfer = new Promise(function (resolve, reject){
> var files = document.getElementById(req.files[name]).files;
> let file = files[0]
> var reader = new FileReader();
> reader.name = name;
> reader.fileName = file.name;
> reader.onload = function () {
> resolve({name: this.name, value: this.result,is_file: true, fileName: this.fileName});
> }
> reader.readAsDataURL(file);
> })
> console.log(fileTransfer)
> allPromise.push(fileTransfer);
> }
> }else{
> var docUrl = '';
> console.log('七牛云上传')
> console.log('正在获取七牛云中文件的url')
> for (var name in req.files) {
> let bodyData = req.files_url
> let file_url = await get('http://xxx:xxx/upload_download?file_name=',bodyData)
> console.log(JSON.parse(file_url.res).file_url)
> docUrl = JSON.parse(file_url.res).file_url
> let QINIUfile = new Promise(function (resolve, reject){
> var xhr = new XMLHttpRequest();
> xhr.open('GET',docUrl,true);
> xhr.responseType = "blob";
> xhr.send(null);
> xhr.onreadystatechange = function(){
> if(xhr.readyState === 4){
> let reader = new FileReader();
> reader.readAsDataURL(xhr.response);
> reader.onload = function(e){
> resolve({fileName:bodyData,is_file:true,name:name,value:e.target.result});
> }
> }
> }
> })
> allPromise.push(QINIUfile)
> }
> }
> Promise.all(allPromise).then(function(result){
> formDatas = formDatas.concat(result);
> req.formDatas = formDatas;
> connect.postMessage({
> id: id,
> req: req,
> });
> })
> }else {
> req.formDatas = formDatas;
> connect.postMessage({
> id: id,
> req: req,
> });
> }
> } else {
> connect.postMessage({
> id: id,
> req: req
> });
> }
> // connect.postMessage({
> // id: id,
> // req: req
> // });
> }`resoponse.js修改的`function dataURLtoFile(dataurl, filename) {
> var arr = dataurl.split(','), mime = arr[0].match(/:(.*?);/)[1],
> bstr = atob(arr[1]), n = bstr.length, u8arr = new Uint8Array(n);
> while(n--){
> u8arr[n] = bstr.charCodeAt(n);
> }
> return new File([u8arr], filename, {type:mime});
> }
> 
> function sendAjax(req, successFn, errorFn) {
> var formDatas;
> var xhr = new XMLHttpRequest();
> 
> ```
> req.headers = req.headers || {};
> req.headers['Content-Type'] = req.headers['Content-Type'] || req.headers['Content-type'] || req.headers['content-type'];// 兼容多种写法
> 
> xhr.timeout = req.timeout || 1000000;
> 
> req.method = req.method || 'GET';
> req.async = req.async === false ? false : true;
> req.headers = req.headers || {};
> if (req.method.toLowerCase() !== 'get' && req.method.toLowerCase() !== 'head' && req.method.toLowerCase() !== 'options') {
> 	if (!req.headers['Content-Type'] || req.headers['Content-Type'] == 'application/x-www-form-urlencoded') {
> 		req.headers['Content-Type'] = 'application/x-www-form-urlencoded';
> 		req.data = formUrlencode(req.data);
> 	} else if (typeof req.data === 'object' && req.data) {
> 		req.data = JSON.stringify(req.data);
> 	}
> }else{
> delete req.headers['Content-Type'];
> ```
> 
> }
> if (req.query && typeof req.query === 'object') {
> var getUrl = formUrlencode(req.query);
> req.url = req.url + '?' + getUrl;
> req.query = '';
> }
> // if (!req.headers['Content-Type'] || req.headers['Content-Type'] == 'application/x-www-form-urlencoded') {
> // req.headers['Content-Type'] = 'application/x-www-form-urlencoded';
> // req.data = formUrlencode(req.data);
> // }
> else if (req.headers['Content-Type'] === 'multipart/form-data') {
> delete req.headers['Content-Type'];
> let formDatas = new FormData();
> for (var item of req.formDatas) {
> if (item.is_file) {
> formDatas.append(item.name, dataURLtoFile(item.value,item.fileName))
> }else {
> formDatas.append(item.name, item.value);
> }
> }
> req.data = formDatas;
> }`
> background.js修改的
> 现在服务端测试仍然有问题，待会儿有空把问题贴出来，希望会node的大神帮忙解决下

请问function get(baseUrl,params) 这个是哪个文件里面的方法呢？

**Comment by TesterPi** [comment]
> 不会影响接口原始数据，只是在以前的req_form_data字段的基础中加入了一个file_url的字段，实现逻辑很简单：
> 本地上传文件，如果没点更新按钮用原始base64逻辑上传文件，这个之前有大神分享过，点了更新按钮就请求了七牛云，这时只要保证插件代码response.js中能请求到七牛云文件就好了，然后将下载的文件流再次转base64套用之前逻辑就好.这个过程改动原始代码没有多少的，并且只是加了个字段，个人认为几乎没影响吧

点更新按钮指的是什么？yapi页面上的按钮吗？

**Comment by ZhangWei55kai** [comment]
> > 不会影响接口原始数据，只是在以前的req_form_data字段的基础中加入了一个file_url的字段，实现逻辑很简单：
> > 本地上传文件，如果没点更新按钮用原始base64逻辑上传文件，这个之前有大神分享过，点了更新按钮就请求了七牛云，这时只要保证插件代码response.js中能请求到七牛云文件就好了，然后将下载的文件流再次转base64套用之前逻辑就好.这个过程改动原始代码没有多少的，并且只是加了个字段，个人认为几乎没影响吧
> 
> 点更新按钮指的是什么？yapi页面上的按钮吗？

点更新就是用例的更新接口，如果更新表示将文件内容上传到服务端，下次进来用例界面也能继续用，如果没有点更新按钮，文件只是临时放在谷歌浏览器中运行了一下，没有真实存储到服务端

**Comment by TesterPi** [comment]
> > > 不会影响接口原始数据，只是在以前的req_form_data字段的基础中加入了一个file_url的字段，实现逻辑很简单：
> > > 本地上传文件，如果没点更新按钮用原始base64逻辑上传文件，这个之前有大神分享过，点了更新按钮就请求了七牛云，这时只要保证插件代码response.js中能请求到七牛云文件就好了，然后将下载的文件流再次转base64套用之前逻辑就好.这个过程改动原始代码没有多少的，并且只是加了个字段，个人认为几乎没影响吧
> > 
> > 
> > 点更新按钮指的是什么？yapi页面上的按钮吗？
> 
> 点更新就是用例的更新接口，如果更新表示将文件内容上传到服务端，下次进来用例界面也能继续用，如果没有点更新按钮，文件只是临时放在谷歌浏览器中运行了一下，没有真实存储到服务端



> > 为什么要使用七牛云先上传文
> > 不知道你说的可以直接用是什么意思，之前走本地测试确实可以直接用，但是如果页面关闭，或者页面被刷新，文件就没了因为你没落库，下次批量执行测试时，是取不到文件的
> > 另外上传七牛云只是简单的做法，你不怕麻烦自己也可以弄个文件服务，自己存自己去都是没关系的

七牛云这里的上传地址填什么呢？我注册了一个七牛云，但不知道该怎么替换掉“xxx”那里的接口
![image](https://user-images.githubusercontent.com/77143050/133882847-34644488-d559-4ad9-9062-144af8a114c3.png)
![image](https://user-images.githubusercontent.com/77143050/133882879-ddfa39fc-069b-4e55-b0dd-8c102ef331c0.png)

**Comment by TesterPi** [comment]
> > > 不会影响接口原始数据，只是在以前的req_form_data字段的基础中加入了一个file_url的字段，实现逻辑很简单：
> > > 本地上传文件，如果没点更新按钮用原始base64逻辑上传文件，这个之前有大神分享过，点了更新按钮就请求了七牛云，这时只要保证插件代码response.js中能请求到七牛云文件就好了，然后将下载的文件流再次转base64套用之前逻辑就好.这个过程改动原始代码没有多少的，并且只是加了个字段，个人认为几乎没影响吧
> > 
> > 
> > 点更新按钮指的是什么？yapi页面上的按钮吗？
> 
> 点更新就是用例的更新接口，如果更新表示将文件内容上传到服务端，下次进来用例界面也能继续用，如果没有点更新按钮，文件只是临时放在谷歌浏览器中运行了一下，没有真实存储到服务端

这么理解么，更新是之前上传过文件，刷新了页面，然后重新点击上传文件就算是更新；如果刷新了页面，不点击上传按钮，脚本就会去获取七牛云上传的上一次的文件。是这样吗？

**Comment by TesterPi** [comment]
> > > 不会影响接口原始数据，只是在以前的req_form_data字段的基础中加入了一个file_url的字段，实现逻辑很简单：
> > > 本地上传文件，如果没点更新按钮用原始base64逻辑上传文件，这个之前有大神分享过，点了更新按钮就请求了七牛云，这时只要保证插件代码response.js中能请求到七牛云文件就好了，然后将下载的文件流再次转base64套用之前逻辑就好.这个过程改动原始代码没有多少的，并且只是加了个字段，个人认为几乎没影响吧
> > 
> > 
> > 点更新按钮指的是什么？yapi页面上的按钮吗？
> 
> 点更新就是用例的更新接口，如果更新表示将文件内容上传到服务端，下次进来用例界面也能继续用，如果没有点更新按钮，文件只是临时放在谷歌浏览器中运行了一下，没有真实存储到服务端

确实是，如果要做自动化测试，必须把文件存储起来，不然页面一刷新就没有。
