### ISSUE TITLE
部署完毕后,无法登录~

### ISSUE THREAD

**Issue by lhalcyon** [YMFE/yapi#1142]
## 版本号
~ v1.7.0

## 什么问题
~ 使用docker部署完毕后,重启下可以看见页面 .  可以登录一直没有连接上

## 如何复现此问题
~ 

## 什么浏览器
~ 

## 什么系统（Linux, Windows, macOS）

附nginx配置

![image](https://user-images.githubusercontent.com/21357951/59742299-f3d83900-929f-11e9-999f-be516a5fed73.png)

**Comment by lhalcyon** [comment]
找到问题了  .  现在报504..

**Comment by askie** [comment]
@lhalcyon 请问504如何处理的？我也遇到了，不知道如何解决
