### ISSUE TITLE
求拉微信讨论群 celiay2013

### ISSUE THREAD

**Issue by celiay** [YMFE/yapi#1144]
## 版本号
~ 

## 什么问题
~

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by pencilso** [comment]
开什么玩笑？办公用微信？   你怕不是个xxxxxx

**Comment by celiay** [comment]
我看前面有前面有人说有人个QQ讨论群，但好象不怎么用，说是有个微信讨论群，难道没有吗

**Comment by pencilso** [comment]
文档上就写了个QQ群    没写什么微信群，

**Comment by celiay** [comment]
你search一下issues里，有人说有的。
