### ISSUE TITLE
我想问下这系统上面能不能控制没有权限的项目不能看到这个功能？

### ISSUE THREAD

**Issue by wengpengfeijava** [YMFE/yapi#115]
## Version
~ 1.3.3
## What is expected
~ 能不能控制没有权限的不显示项目？

## Step to reproduce
~ 

## Environment
~

**Comment by suxiaoxin** [comment]
把项目设置为私有项目就行

**Comment by wengpengfeijava** [comment]
设置为私有项目的话不是没人可以参与了 ？

**Comment by gaoxiaomumu** [comment]
你可以将参与的人设置为分组成员或者项目成员，这些人就可以看到这个项目了

**Comment by wengpengfeijava** [comment]
试了下，在不是个人空间中创建私有项目可以达到效果。
有如下操作： 管理员在非个人空间创建一个私有项目，并且将某个账号添加到当前项目中来，此时这个人进入这个项目进行操作，途中管理员将其从当前的项目中移除掉，这个人在那个页面再操作console会报错而不是提示没有权限或者别的处理方式。但是不影响主体的功能就是。。

**Comment by wengpengfeijava** [comment]
还有个问题一并在这里说了吧 。导出api.html 或者api.md的时候不能将parameter之类的东西导出来吗 。

**Comment by gaoxiaomumu** [comment]
第一个问题，如果是非公开项目，不是分组内的成员或者项目成员，其他人都是不可见的。至于直接通过url进入项目的，这个问题我们已经修复，会提示没有权限的。
第二个bug已经修复  会在下一个版本中发布。
感谢提问

**Comment by wengpengfeijava** [comment]
嗯，谢谢
