### ISSUE TITLE
求求开发者，好好写下更新说明吧。。

### ISSUE THREAD

**Issue by solosky** [YMFE/yapi#1157]
## 版本号
~ 

## 什么问题
~

## 如何复现此问题
~ 

## 什么浏览器
~ 

## 什么系统（Linux, Windows, macOS）

看Release记录，全都是`update static files`，没有任何有用的信息。
求求你们好好写写更新记录吧。。。

**Comment by qiyulan** [comment]
看 changelog  https://github.com/YMFE/yapi/blob/master/CHANGELOG.md

**Comment by solosky** [comment]
Thanks.  CHANGELOG.md 这个没看到，抱歉。 
建议你们也同步到Release里面的更新记录吧。 
这个Issue我关掉了。
