### ISSUE TITLE
我是 YApi 开源项目作者，目前在美团优选工作，期待你的加入 #2068

### ISSUE THREAD

**Issue by hellosean1025** [YMFE/yapi#1173]
目前本人所在的公共服务终端组以支撑优选的公共服务业务和基础组件架构为主，提供了统一的B端的架构支撑和数据平台可视化服务，以及公共服务App的大前端架构建设。

简历投递：suwenxiong@meituan.com

## 团队技术亮点
1. 探索LowCode解决方案，自研了**数据积木平台**，基本无需编码，通过配置组件完成数据分析产品的研发；
2. 统一的b端系统**页面渲染网关**，提供了页面登录鉴权，服务端渲染，路由转发，灰度下发等能力，业务团队专注于业务研发；
3. 统一了团队脚手架，所有团队**统一使用一个脚手架**，并且能够支持多个技术场景（React, Vue, RN, 小程序）；

## 挑战：

1、整体优选的B端终端架构的建设和演进，包括统一的工程架构、组件架构、工程化、网关服务、配置化，目前已支持4大业务系统30+应用，日百万级别的访问量，预估未来访问量的千万PV级别。

2、整体优选的数据平台终端架构的建设和演进，包括大数据工具体系、统一的可视化服务，目前已有比较完善的积木配置化平台的实现，支撑事业部数字化。

3、整体优选公共服务的大前端架构的建设和演进，包括独立App大前端架构、动态化和配置化的实现。

## 岗位基础信息：

1) 用人部门：美团优选/系统研发部/公共服务研发组/公共服务终端研发组（对外发布：美团优选*）；

2) 工作城市*：北京；

3) JobGroup：系统开发；

4) 所带团队人数：20人左右；

5) 是否新增岗位：R 新增岗位  £ 离职替补；

6) 岗位目的：参与优选事业部数据、权限、LMS和财务等前端系统和基础公共服务的设计和实现，支撑业务快速发展，不断提升团队研发效率和产品用户体验

## 关于美团优选：
美团优选为美团推出的社区团购业务，重点针对下沉市场，采取“预购+自提”的模式，赋能社区便利店，为社区家庭用户精选高性价比的蔬果、肉禽蛋、乳制品、酒水饮料、家居厨卫等品类商品。用户当天线上下单，次日门店自提。

美团优选使命：让每一餐吃得更好

美团优选愿景：服务一亿家庭

 

## 岗位职责：

1.负责优选事业部前端的技术方案设计、需求把控、核心功能开发，将业务需求拆解细化并实施；

2.参与前端系统的架构规划、性能优化、故障排查和解决、安全加固等工作；

3.驱动团队与产品团队密切合作；

4.构建团队并培养团队成员，组织技术分享，促进团队成员进步。

 

## 岗位要求：

1）岗位基本要求：

深厚的编程功底，强悍的发现问题、解决问题能力；

扎实的前端基础（JavaScript/CSS/HTML），丰富的前端主流框架（React/Vue）实战经验；

熟悉 Node.js，使用过至少一个框架（Express/Koa等）；

熟悉前端的常见构建、发布机制，熟练掌握 Webpack 的使用；

较好的沟通协作能力，较强的主动性和推动能力。

2）具备以下者优先：

丰富的中后台系统、移动端（H5/小程序）开发实践，主导过较复杂前端系统开发；

极强的抽象、共享意识，在开源社区有优质贡献； 

热爱编程，热爱技术，广泛涉猎，在跨端项目中有卓越贡献。

 

## 业务亮点：

有机会全身心地参与社区团购业态，体验并掌握各个环节的核心技术要素，和团队一起对供应链、采销、仓配等行业技能进行全新的升级、再造；

能在急速发展的社区团购业务当中，从0到1地建立对业务和产品技术的认知，构建完整的宏观图景；

能和电商、O2O、物流、零售、人工智能等多元化背景的团队技术大牛一起，综合学习，共同进步。

简历投递：suwenxiong@meituan.com

**Comment by LiuL0703** [comment]
blog站点也挂了

**Comment by weii918** [comment]
https://hellosean1025.github.io/yapi/documents/index.html

**Comment by callmegaga** [comment]
github上面的文档，访问极慢，能不能在国内部署文档服务器

**Comment by geekyouth** [comment]
![image](https://user-images.githubusercontent.com/12899262/78695077-30107f00-7930-11ea-9c53-364932c0b4ed.png)

![image](https://user-images.githubusercontent.com/12899262/78695082-3141ac00-7930-11ea-905c-6296fabb618e.png)

# 至今都没修复吗？？？

**Comment by lizy0329** [comment]
大哥，你这个官网也是打开不能

**Comment by suiriass** [comment]
有没有试用性的网站，试用一下的地方

**Comment by xiaohp** [comment]
能续期么？帮助链接跳过来打不开

**Comment by jiro-zjl** [comment]
打不开官网哦，强烈要求有官网   yapi自我感觉挺好

**Comment by wmq85** [comment]
打不开帮助文档链接。有其他可以查看文档的地址吗？

**Comment by libieqing** [comment]
求官网~

**Comment by wmq85** [comment]
> 打不开帮助文档链接。有其他可以查看文档的地址吗？

域名已经过期了，查询到官网域名的历史解析记录有185.199.111.153，在操作系统的hosts文件里面添加
`185.199.111.153	hellosean1025.github.io`可访问。

**Comment by graceTesterZhang** [comment]
使用教程打不开了

**Comment by CaptainTyL** [comment]
百度pass GitHub都无法登录

**Comment by daoying007** [comment]
加微信群交流互助吧，加我微信好友（备注yapi），拉你进yapi微信群吧
![1](https://user-images.githubusercontent.com/39725475/111908403-19592e80-8a94-11eb-8d46-9d342cc7610b.jpg)
