### ISSUE TITLE
服务会无故停止

### ISSUE THREAD

**Issue by GreedyPirate** [YMFE/yapi#1198]
## 版本号
1.7.1

## 什么问题
服务无故停止，并且日志里没有任何错误，手动重启后又可以了，一次还能接受，经常这样，实在不想每次手动重启，以下为部分日志，看不出任何异常
![image](https://user-images.githubusercontent.com/14834990/61036904-9d709d00-a3fc-11e9-8c58-199f0dff6f25.png)
可以看到从下午4：32之后就停止了，后来我又重启了一次

## 如何复现此问题
无法复现

## 什么浏览器
chrome

## 什么系统（Linux, Windows, macOS）
linux

**Comment by GreedyPirate** [comment]
虽然想通过supervisor自动重启，但是会报以下错误
![image](https://user-images.githubusercontent.com/14834990/61037004-cd1fa500-a3fc-11e9-857e-1f79bed2532d.png)

**Comment by tonypig** [comment]
我这也经常是node进程还在，但是服务访问不了了，1.7.0升级到1.7.1依然存在

**Comment by tangcent** [comment]
是否尝试过使用[pm2](http://pm2.keymetrics.io/)?

**Comment by GreedyPirate** [comment]
> 是否尝试过使用[pm2](http://pm2.keymetrics.io/)?
好东西，我试一试

**Comment by sp0cket** [comment]
> 是否尝试过使用[pm2](http://pm2.keymetrics.io/)?

尝试使用pm2仍然会出现这种情况

**Comment by tangcent** [comment]
> > 是否尝试过使用[pm2](http://pm2.keymetrics.io/)?
> 
> 尝试使用pm2仍然会出现这种情况,yapi版本1.7.2

可以看一下pm2的日志？
使用`pm2 status`查看所有pm2进程
使用`pm2 logs [id|name]`查看对应进程日志

**Comment by idweball** [comment]
机器的装态是否有做监控，比如CPU，内存之类的，如果有，能否把相关时间端的监控数据贴出来一下呢，这样更方便排查问题

**Comment by GreedyPirate** [comment]
忘记close了，使用pm2之后没有出现过该问题，感谢 @tangcent 的帮助
