### ISSUE TITLE
在本地部署 根本就部署不了

### ISSUE THREAD

**Issue by xulie1129** [YMFE/yapi#12]
在本地部署 根本就部署不了

**Comment by mumudev** [comment]
发一下截图，看报什么错呀，我从0部署，一下子就好了呀！
注意下，node版本要大于7.6

**Comment by doyoe** [comment]
@xulie1129 能描述一下具体是哪里出现问题了么？

**Comment by ckdlbc** [comment]
我也是本地部署有问题
node v8.6
![image](https://user-images.githubusercontent.com/20680413/32205659-787fcc72-be2b-11e7-9266-e50ed86ac30a.png)

**Comment by suxiaoxin** [comment]
感谢反馈， v1.2.2 在本地部署时有问题，请下架，请使用 v1.2.0 版本，重新部署时请删除之前部署的所有文件和数据库

**Comment by ckdlbc** [comment]
@suxiaoxin 好的，非常感谢！！给你们点赞~
