### ISSUE TITLE
离开接口编辑页面的 confirm 框有时候会触发两次 & confirm 的 ‘X’ 按钮无效

### ISSUE THREAD

**Issue by PichurChill** [YMFE/yapi#121]
## Version
V1.3.4

## What is expected
 就是在编辑一个接口未保存的时候，再去点其他接口，提示“即将离开编辑页面”的 confrom 框
 1 - confirm 的 ‘X’ 按钮无效
 2 - 偶尔会有两次 confirm，（点了取消，还要再点一次）

## Step to reproduce
~ 

## Environment
~

**Comment by gaoxiaomumu** [comment]
该问题已经解决，将在下一个版本中发布，感谢提问
