### ISSUE TITLE
功能建议，能够增加对弃用接口进行标记的功能吗？

### ISSUE THREAD

**Issue by offSwitch** [YMFE/yapi#1210]
## 版本号
~ 

## 什么问题
~
能够增加对弃用接口进行标记的功能吗？
## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by tangcent** [comment]
Hi,是否有考虑使用tag？
例如:使用deprecated标记接口被弃用

列表效果:
![image](https://user-images.githubusercontent.com/17569144/61216383-ccaa4580-a73f-11e9-9454-398f5158707c.png)

接口效果:
![image](https://user-images.githubusercontent.com/17569144/61216523-1f83fd00-a740-11e9-8aaa-9ae45a57a9a9.png)

**Comment by 4haohansen2033** [comment]
@offSwitch  这样也可以。 tag 感觉面更多的是描述接口版本的信息， 状态更多的是描述当前接口所处的阶段，更能清晰些。并且页面显示的deprecated接口时可以用中划线样式处理。

**Comment by tangcent** [comment]
嗯，这个倒是可以考虑
@hellosean1025 
接口状态增加一种已废弃，列表中使用中划线样式展示
是否可行？有没有已经在计划中?
