### ISSUE TITLE
error: send mail  error,No recipients defined

### ISSUE THREAD

**Issue by pluto-er** [YMFE/yapi#1220]
## 版本号
~ 
1.7.1
## 什么问题
~
error: send mail  error,No recipients defined
## 如何复现此问题
~ 
error: send mail  error,No recipients defined
## 什么浏览器
~ 
chrome
## 什么系统（Linux, Windows, macOS）
Linux

**Comment by zuriyd** [comment]
有解决吗 我也出现这个问题

**Comment by zuriyd** [comment]
已解决 加了成员就好了
