### ISSUE TITLE
关于权限action的疑问

### ISSUE THREAD

**Issue by tangcent** [YMFE/yapi#1226]
## 版本号
1.7.2

## 什么问题
从全局搜索能够使用路径搜索后，我的小伙伴们觉得是个很好的功能。但是从全局搜索能搜索到没有权限的接口，这对我们产生了一定的困扰。所以我准备处理一下。

但是在查看权限相关代码时发现 'site'这个action，
https://github.com/YMFE/yapi/blob/b8e4927b201505db52d1faaffa20386f6a856105/server/controllers/user.js#L690
然而checkAuth中并未对此做处理
https://github.com/YMFE/yapi/blob/b8e4927b201505db52d1faaffa20386f6a856105/server/controllers/base.js#L288-L312
所以我不确定这里的'site'的含义(是否应该是edit?)。

另外，我将尝试从全局搜索结果中过滤掉无权限的接口，如果需要的话，我可以发起一个PR，如果不需要的话，我将保留在内部使用，等待新的解决方案。

@hellosean1025  期待答复，多谢

## 如何复现此问题
创建新的角色，尝试从全局搜索搜索

## 什么浏览器
Chrome

## 什么系统（Linux, Windows, macOS）
MacOS

**Comment by hellosean1025** [comment]
挺需要的，不过对性能影响较大

**Comment by hellosean1025** [comment]
另外，没有权限的接口看到了也没用，打不开的
