### ISSUE TITLE
官方网站的使用文档为什么打不开了？

### ISSUE THREAD

**Issue by JackeyLee007** [YMFE/yapi#1227]
## 版本号
~ 

## 什么问题
打不开使用文档。
https://yapi.ymfe.org/

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by tangcent** [comment]
see #1204
see https://github.com/YMFE/yapi/issues/1173 & https://github.com/YMFE/yapi/commit/fbc8ed9b93a19e57f9f74a8796ab9711eaa3050f
