### ISSUE TITLE
npm run install-server后无法访问1.3.4版本

### ISSUE THREAD

**Issue by dongdongzld** [YMFE/yapi#123]
执行 npm run install-server 后
提示 log: mongodb load success...
初始化管理员账号成功,账号名："***@**com"，密码："ymfe.org"
访问指定端口无法访问（超时）日志下未见异常

说是有一个初始化过程，这个初始化编译过程大概需要多久？
根目录下出现init.lock文件，是不是这个文件消失即初始化完成？

**Comment by fstg0504** [comment]
+1  一样的问题呢
