### ISSUE TITLE
pre-request script 异步响应结果无法存入 Headers

### ISSUE THREAD

**Issue by juicejam** [YMFE/yapi#1245]
## 版本号
~ 版本: 1.7.2

## 什么问题
~
如下图，执行post接口，获取到响应结果了，但是无法将结果存入context.requestHeader.sign。
最终执行的效果是在post请求还没结束就直接跳到请求正式接口，不知道怎么解决。

![image](https://user-images.githubusercontent.com/17326909/61839060-b11d0880-aebe-11e9-8738-120e7cb1b418.png)

![image](https://user-images.githubusercontent.com/17326909/61839215-52a45a00-aebf-11e9-8aaf-d89ac2ec210f.png)

![image](https://user-images.githubusercontent.com/17326909/61839142-ffcaa280-aebe-11e9-8941-2b93c7517341.png)

pre-request代码：
context.requestHeader.timestamp=Math.round(new Date() / 1000);
var requestDataTest={"requestHeader":context.requestHeader,"requestBody":context.requestBody};

function runAsync(){
return new Promise(function(resolve) {
    var api=axios({
      method:'POST',
      url: 'http://localhost:58140/api/Sign/CreatSign',
      data:requestDataTest
      }).
      then(function(result) {
      resolve(result);
      });
});
}

runAsync().then(function(data){
    console.log(data);
    context.requestHeader.sign=data.data;
});

## 如何复现此问题
~ 
执行上述代码

## 什么浏览器
~ 
chrome

## 什么系统（Linux, Windows, macOS）
Windows

**Comment by tangcent** [comment]
await?

**Comment by juicejam** [comment]
headers还没接收到异步响应的结果，pre-request就执行结束了，不知道可不可以等待异步处理完毕后再结束pre-request

**Comment by tangcent** [comment]
-  嗯，我理解你的意思。
-  你这里需要await你的runAsync执行完毕
-  这里可以使用context.promise 
![image](https://user-images.githubusercontent.com/17569144/61843816-c2224580-aecf-11e9-94a0-0ee95f756bd6.png)

- 所以你这里我猜测可以这样写

```

context.requestHeader.timestamp = Math.round(new Date() / 1000);
var requestDataTest = { "requestHeader": context.requestHeader, "requestBody": context.requestBody };

context.promise = axios.post('http://localhost:58140/api/Sign/CreatSign', requestDataTest)
    .then(function (data) {
        console.log(data);
        context.requestHeader.sign = data.data;
    });

```

**Comment by juicejam** [comment]
@tangcent 感谢大佬，完美解决了我的问题！！！
这个文档看了很多遍，context.promise=....这段代码以为是给promise变量赋值，瞎捉摸了大半天。
