### ISSUE TITLE
布局出现错乱，编辑API 出现失败

### ISSUE THREAD

**Issue by newjia** [YMFE/yapi#125]
## Version
~ 1.3.4

## What is expected
~布局完整，编辑API 正常

## Step to reproduce
~ 1.打开我司通过YAPI 部署好的API 文档网址 http://api.haiqihuocang.com:3000
   2. 点击登录会有巨大的布局错乱。
   3. 登录后，左侧侧边栏的各项目标签，跑到屏幕最左下角。
   4. 编辑API： 点击左侧某个api 名，后，右侧的 预览、编辑、运行、高级MOCK 点击后均无反应，下方无内容。

## Environment
~ Mac - safari

**Comment by gaoxiaomumu** [comment]
正常情况下您部署了yapi之后代码是被拉到了本地，出现这种问题我们无法复现，建议您查找一下原因

**Comment by newjia** [comment]
应该是我修改了Title 捎带改到了其他文件。
通过`yapi update`  重新安装，并重启服务，已修复好了。
谢谢
