### ISSUE TITLE
模拟数据可以支持中文吗？

### ISSUE THREAD

**Issue by Shu-Ji** [YMFE/yapi#1252]
## 什么问题
模拟数据可以支持中文吗？

比如像 python 中的 fake 库支持：

https://faker.readthedocs.io/en/master/locales/zh_CN.html

或者能否通过自己编写插件的方式，自己使用 python 包装一层，将结果返回给 yapi 使用呢？

**Comment by tangcent** [comment]
- 你是指这个?

![image](https://user-images.githubusercontent.com/17569144/61934724-967c8980-afbb-11e9-8896-fdd662c5ad66.png)

- 还是这个?

![image](https://user-images.githubusercontent.com/17569144/61935006-215d8400-afbc-11e9-856b-81d4341c11b2.png)

- 抑或这个？

![image](https://user-images.githubusercontent.com/17569144/61935196-90d37380-afbc-11e9-8a3e-ff8408cb9163.png)

- 另外建议花几分钟浏览一下 [mockjs](http://mockjs.com/examples.html)
当找不到现成的方案时，善用array, integer,pick等可以很容易组合出大部分业务需求

**Comment by Shu-Ji** [comment]
@tangcent 我指的是默认的配置，我一般是使用 json/jsonschema ，只定义了字段名和字段类型，没有定义字段值（即默认情况），不使用 mockjs 的情况下，返回的都是 Lorem Ipsum 的英文，这个可以在哪里配置成中文(i18n)吗？

**Comment by tangcent** [comment]
- 嗯，理解。
我看了下代码，没有找到可配置的地方(嗯，我并不能确认一定不可以).
可以尝试二次开发定制

- mock相关代码
https://github.com/YMFE/yapi/blob/e745da6b475daa98b17b46be5ebbf8c57ba2006f/server/controllers/interface.js#L1178-L1187
https://github.com/YMFE/yapi/blob/b54928a3efca2bed243803f00cdd8af5f6667961/server/middleware/mockServer.js#L284-L289
可以看到最后都调用的是
https://github.com/YMFE/yapi/blob/e745da6b475daa98b17b46be5ebbf8c57ba2006f/server/utils/commons.js#L48-L60
所以这里应该可以尝试扩展jsf，例如:
https://github.com/YMFE/yapi/blob/e745da6b475daa98b17b46be5ebbf8c57ba2006f/server/utils/commons.js#L25-L31

**Comment by Shu-Ji** [comment]
明白，其实是想 yapi 原生支持，毕竟中文用户很多，界面模拟数据是英文，对中文界面的布局可能有一些影响。

**Comment by tangcent** [comment]
- 嗯，当前貌似只能用 YApi的 [Mock](https://hellosean1025.github.io/yapi/documents/mock.html) 功能
- 我目前是用 easy-yapi 提供的 [mock配置](https://github.com/tangcent/easy-yapi/wiki/yapi-mock%E9%85%8D%E7%BD%AE)
对于你的需求配置规则是
```
mock.[*|string]=@cword(3,8)
```
但是目前只支持java&spring
- 从你第一个comment来看，你好像用的是py，很抱歉,我暂时没有很好的方法，只能建议你尽量的新建接口的时候为响应的字段增加 `@cword(3,8)` 这样的规则。另一个办法是 利用[自定义 Mock 脚本](https://hellosean1025.github.io/yapi/documents/adv_mock.html#%E8%87%AA%E5%AE%9A%E4%B9%89-mock-%E8%84%9A%E6%9C%AC) 对响应进行处理，正则匹配形如 `Lorem Ipsum `这样的纯英文替换成中文
