### ISSUE TITLE
[BUG] 插件【Swagger 自动同步】的【项目的swagger json地址】无法添加 https 链接

### ISSUE THREAD

**Issue by fjc0k** [YMFE/yapi#1253]
如图：

![image](https://user-images.githubusercontent.com/13151189/61990362-a656a500-b071-11e9-95f3-f6d0754fc4a6.png)

经调查发现，后台在做链接校验时使用了 YApi 内部的 `yapi.commons.createWebAPIRequest` 函数，但 `yapi.commons.createWebAPIRequest` 函数未对 `https` 的链接做特殊处理。

https://github.com/YMFE/yapi/blob/bbf94b7023c18be722527fe5df8ba1a2b9156b52/server/controllers/project.js#L1122-L1132

https://github.com/YMFE/yapi/blob/bbf94b7023c18be722527fe5df8ba1a2b9156b52/server/utils/commons.js#L678-L687

**Comment by fjc0k** [comment]
@gaoxiaomumu

**Comment by Elity** [comment]
面临同样的问题

**Comment by shouldnotappearcalm** [comment]
我这两天修复一下这个bug吧

**Comment by shouldnotappearcalm** [comment]
#1019 
我在这个pr里面有改到这个问题，应该还不会立马合，着急的话建议自己改代码重新打包，或者用nginx做一下代理，适配一下

![image](https://user-images.githubusercontent.com/20592210/62008858-76e78b80-b18a-11e9-901e-6403bb538995.png)

**Comment by hellosean1025** [comment]
@shouldnotappearcalm 这个 pr 功能现在稳定么？
还有为啥不用 axios 请求？

**Comment by shouldnotappearcalm** [comment]
改https改动比较小

**Comment by hellosean1025** [comment]
@shouldnotappearcalm 
建议使用 axios,并且加上 httpsAgent 配置
![image](https://user-images.githubusercontent.com/17695103/62017863-ef7e3480-b1ea-11e9-872a-cb3c6874a4de.png)

**Comment by shouldnotappearcalm** [comment]
行，我晚上回去改一下

**Comment by shouldnotappearcalm** [comment]
@hellosean1025 我改了，大佬有空可以看下
