### ISSUE TITLE
可以支持正则表达式吗？

### ISSUE THREAD

**Issue by mrsai** [YMFE/yapi#126]
希望接口能够支持正则表达式
如后台写了一个这样的东西    /message/message_index/23/
数字是变化的，我可能不能无缝切换
所有能不能支持 /message/message_index/\d/ 的模式或者其他方式

**Comment by gaoxiaomumu** [comment]
![image](https://user-images.githubusercontent.com/21135585/35088479-e388e748-fc6e-11e7-9522-394156d9724c.png)
可以这样把数字设置成query不可以吗

**Comment by mrsai** [comment]
@gaoxiaomumu 是可以了，是我没有找到使用方法，谢谢~~！这个留着给后来者参考吧。
