### ISSUE TITLE
高级mock脚本怎么用，如何调试？

### ISSUE THREAD

**Issue by kiinlam** [YMFE/yapi#1261]
## 版本号
~ 1.8.0

说下需求：
打算针对登录接口，写一段脚本，用来设置响应头里的cookie。

看了文档，没找到方法，也没有参考的案例，完全不知道怎么写，试了下把`resHeader`序列化后，在body里返回，结果是空对象`{}`。

期望：
能否完善下文档，在高级Mock脚本里，`resHeader`怎么用，设置cookie（响应头Set-Cookie）要怎么写。

另外，项目的全局Mock，跟接口的高级Mock脚本是不是一样的？然后请求配置里的`Pre-response Script(响应数据处理脚本)`又是另外一回事，只支持自动化测试？

**Comment by kiinlam** [comment]
改了下，发现原理console.log是打印在当前标签页的控制台了，我以为是插件背景页打印的。

**Comment by warthur1214** [comment]
https://github.com/YMFE/yapi/issues/1262#issuecomment-517112108

**Comment by kiinlam** [comment]
@warthur1214 非常感谢解答。
问题已解决。
设置单个cookie，使用字符串赋值，设置多个，使用字符串数组给'Set-Cookie'属性赋值。

**Comment by AlexanderToner** [comment]
@kiinlam 楼主能分享下怎么解决的吗？我也遇到这个问题

**Comment by kiinlam** [comment]
@AlexanderToner 我现在没有用这个软件了，时间也有点久，忘记了。
如果是多个cookie，应该是每个cookie作为数组的单个元素存放，然后把数组赋值给response header的'Set-Cookie'属性

**Comment by JanYunkai** [comment]
@kiinlam 有更好的？

**Comment by kiinlam** [comment]
> @kiinlam 有更好的？

没有，现在项目不用这个，也没人推广

**Comment by sinpor** [comment]
> @kiinlam 楼主能分享下怎么解决的吗？我也遇到这个问题

### 登陆接口：

高级Mock ---> 脚本 --> 开启

``` javascript
resHeader['Set-Cookie'] = 'SESSION_ID=xxxxx; Max-Age=3600'
```

### 需要鉴权的接口

高级Mock ---> 脚本 --> 开启

``` javascript
if (!cookie.SESSION_ID) {
    httpCode=403
    mockJson=[{"result": "failed"}]
}
```

[相关文档](https://hellosean1025.github.io/yapi/documents/adv_mock.html#%E8%87%AA%E5%AE%9A%E4%B9%89-mock-%E8%84%9A%E6%9C%AC)
