### ISSUE TITLE
How do I use the advanced capabilities of mock scripts ?

### ISSUE THREAD

**Issue by TryRaymond** [YMFE/yapi#1262]
## 版本号
~ 1.8.0

## Demand：
We intend to write a script for the login interface to set the cookie in the response header.

After reading the document, I didn't find the method, nor did I find the reference case, so I didn't know how to write it. After serializing the resHeader, I returned it in the body, and the result was empty object {}.

## Expect :
Can you improve the documentation, how to use resHeader in advanced Mock scripts, and how to Set cookies (response header set-cookie)?

## Other :
Also, is the global Mock for the project the same as the advanced Mock script for the interface? And then the pre-response Script in the request configuration, which only supports automated testing?

**Comment by warthur1214** [comment]
Advanced Mock Script:
resHeader = {
    'Set-Cookie': 'name=warthur'
}

**Comment by PLQin** [comment]
tks ,  like your products very much

**Comment by TryRaymond** [comment]
tks , like your products very much

**Comment by warthur1214** [comment]
I am not the author.  I am a user. haha

**Comment by TryRaymond** [comment]
> I am not the author. I am a user. haha

haha
