### ISSUE TITLE
1. github工程无法运行 2. cli 无法启动服务

### ISSUE THREAD

**Issue by kimyLee** [YMFE/yapi#1270]
## 版本号
~ latest

## 什么问题
~1. 无法运行github工程，2. cli 无法启动服务

## 如何复现此问题
~ master 分支代码npm 各种run 即可

## 什么浏览器
~ chrome

## 什么系统（Linux, Windows, macOS）
macOS

不能支持下载工程然后本地部署么，希望定制化修改，但是没有对应 get start 指引

**Comment by tangcent** [comment]
# 定制化修改？

> 我不是专业的前端开发，对于以下内容，请保持思考

## 如果是指使用代码部署的话,看这里:
https://hellosean1025.github.io/yapi/devops/index.html
![image](https://user-images.githubusercontent.com/17569144/62412501-dedc1d00-b635-11e9-9853-6dbc888c4316.png)

## 如果是指二次开发的话
- see https://github.com/YMFE/yapi/issues/16#issue-270522410
- 注意看package.json: https://github.com/YMFE/yapi/blob/1b25ff4e55bbddb2b5baa45cb86e96daeeba7c89/package.json#L6-L17

- 使用npm或者yarn安装依赖
- 记得运行 `npm run install-server`
- 开发中用到的命令基本是以下三个(我个人使用yarn居多,你可以替换为npm)
本地打包 `yarn run build-client`
本地运行 `yarn run start`
开发者模式 `yarn run dev`
