### ISSUE TITLE
TypeError: Cannot read property 'applyPatch' of undefined

### ISSUE THREAD

**Issue by sunmenglin** [YMFE/yapi#1278]
## 版本号
~ yapi 1.8.0 1.8.1
   node 10.16.1
   mongod 4.0.11
## 什么问题
~  上传postman的json文件和swgger的url和json导入均报”解析数据为空“，console报错：TypeError: Cannot read property 'applyPatch' of undefined

## 如何复现此问题
~ 安装过yapi-plugin-import-swagger-customize导入不行，卸载掉这个插件还是报解析为空

## 什么浏览器
~ chrome

## 什么系统（Linux, Windows, macOS）
Centos7.6

**Comment by sunmenglin** [comment]
> ## 版本号
> ~ yapi 1.8.0 1.8.1
> node 10.16.1
> mongod 4.0.11
> 
> ## 什么问题
> ~ 上传postman的json文件和swgger的url和json导入均报”解析数据为空“，console报错：TypeError: Cannot read property 'applyPatch' of undefined
> 
> ## 如何复现此问题
> ~ 安装过yapi-plugin-import-swagger-customize导入不行，卸载掉这个插件还是报解析为空
> 
> ## 什么浏览器
> ~ chrome
> 
> ## 什么系统（Linux, Windows, macOS）
> Centos7.6

postman导出必须Collection v1才可以，v2导入提示解析数据为空，但是现在v1都快废弃了

**Comment by nosun** [comment]
真正是，postman 只支持 1.1 import
