### ISSUE TITLE
初始化数据库异常

### ISSUE THREAD

**Issue by xxyGoTop** [YMFE/yapi#1281]
## 版本号
~ 1.5.11

## 什么问题
初始化数据库异常

node: 10.4.1
mongodb: 4.0.1

异常如下：
(node:52056) UnhandledPromiseRejectionWarning: MongoError: not authorized on yapi to execute command { insert: "undefined", ordered: true, lsid: { id: UUID("efa21764-a6f2-4f03-ab6a-f82d07f6f978") }, $db: "yapi" }

插入数据undefined

## 如何复现此问题
npm run install-server

## 什么浏览器
~无

## 什么系统（Linux, Windows, macOS）
windows

**Comment by tangcent** [comment]
是否有检查mongo配置？

**Comment by xxyGoTop** [comment]
已查明，mongo用户未授权
