### ISSUE TITLE
更改界面样式无效

### ISSUE THREAD

**Issue by zhangciren** [YMFE/yapi#1296]
## 版本号
~ 
1.8.1
## 什么问题
~
为了更改界面内容，直接修改client中的前端代码，然后重启yapi。但是发现界面并没有显示成更改后的页面效果。
## 如何复现此问题
~ 

## 什么浏览器
~ 
chrome
## 什么系统（Linux, Windows, macOS）
macOS

**Comment by tangcent** [comment]
# 先看一下运行方法
***
- see https://github.com/YMFE/yapi/issues/16#issue-270522410
- 注意看package.json: https://github.com/YMFE/yapi/blob/1b25ff4e55bbddb2b5baa45cb86e96daeeba7c89/package.json#L6-L17

- 使用npm或者yarn安装依赖
- 记得运行 `npm run install-server`
- 开发中用到的命令基本是以下三个(我个人使用yarn居多,你可以替换为npm)
本地打包 `yarn run build-client`
本地运行 `yarn run start`
开发者模式 `yarn run dev`
***

当你使用开发者模式 `yarn run dev`启动时，你的更改立即生效
否则你需要重新本地打包 `yarn run build-client`后运行 `yarn run start`才可以

**Comment by zhangciren** [comment]
多谢解答～

**Comment by Koomita** [comment]
> # 先看一下运行方法
> * see [#16 (comment)](https://github.com/YMFE/yapi/issues/16#issue-270522410)
> * 注意看package.json: https://github.com/YMFE/yapi/blob/1b25ff4e55bbddb2b5baa45cb86e96daeeba7c89/package.json#L6-L17
> * 使用npm或者yarn安装依赖
> * 记得运行 `npm run install-server`
> * 开发中用到的命令基本是以下三个(我个人使用yarn居多,你可以替换为npm)
>   本地打包 `yarn run build-client`
>   本地运行 `yarn run start`
>   开发者模式 `yarn run dev`
> 
> 当你使用开发者模式 `yarn run dev`启动时，你的更改立即生效
> 否则你需要重新本地打包 `yarn run build-client`后运行 `yarn run start`才可以

修改的css有改变，但检查元素引用的index@dev.css仍是旧的代码，重新npm run dev后，index@dev.css还是没有改变。

**Comment by Mr-yin000** [comment]
同样的问题 查了下原因有的人说是二次开发不支持windows系统 需要mac或者linux
