### ISSUE TITLE
高级mock期望

### ISSUE THREAD

**Issue by bhaltair** [YMFE/yapi#13]
高级mock期望是在哪个版本？我已经升级到1.1.2 但是没有发现Mock期望的入口

**Comment by suxiaoxin** [comment]
明天晚上发布，同事误操作更新了线上的文档，不好意思

**Comment by bhaltair** [comment]
@suxiaoxin 高级mock的期望参数试了下参数只能在query中，请问body中的参数如何设置？

**Comment by suxiaoxin** [comment]
@bhaltair 支持 body 的参数，请执行 yapi update 升级到最新版本
