### ISSUE TITLE
question#自动化测试

### ISSUE THREAD

**Issue by xiaobing395845388** [YMFE/yapi#1304]
## 版本号
~ 

## 什么问题
1 测试集合里面如果一个接口想输入不同的参数组合跑多遍应该怎么设置？
2 测试集合想通过定时任务跑哪个版本能支持 很急的需求 如果近期没有计划 我们自己fork开发了

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by liuwenjincoco** [comment]
请问下，您这个问题，做了二次开发嘛？
