### ISSUE TITLE
Swagger自动同步数据过大提示Error: 返回数据格式不是 JSON

### ISSUE THREAD

**Issue by lsw1991abc** [YMFE/yapi#1309]
## 版本号
~ 1.7

## 什么问题
~ 开启Swagger接口自动同步时，如果/v2/api-docs接口的数据过大，会提示“Error: 返回数据格式不是 JSON”。需如何解决

## 如何复现此问题
~ swagger中定义大量接口时，yapi中开启自动同步或从url中导入数据，会复现此问题

## 什么浏览器
~ Chrom，Firefox，Safari

## 什么系统（Linux, Windows, macOS）
macOS，Linux

**Comment by xujiabing-001** [comment]
我也遇到了这个
