### ISSUE TITLE
有没有像 Postman 里面的认证功能，比如 Oauth 2.0？

### ISSUE THREAD

**Issue by dullme** [YMFE/yapi#131]
有没有像 Postman 里面的认证功能，比如 Oauth 2.0？ 现在我要在请求头上加 token 有点麻烦！还有测试的时候可以用之前的代码请求下来数据比如 $.65.body.token 但是我想要在这个变量上加 “Bearer” 字符串拼接需要怎么做？

**Comment by suxiaoxin** [comment]
1. oauth2.0 暂时只能通过其他工具，比如 postman 生成 token，然后把 token 复制到 header 信息实现
2.使用下动态表达式
第一步，点击红色框那里：
![image](https://user-images.githubusercontent.com/17695103/35255792-c1f7ca16-002b-11e8-88cf-9f413a626b5b.png)

第二步：
![image](https://user-images.githubusercontent.com/17695103/35255831-fb6a2e9c-002b-11e8-9c46-4334073ede79.png)

**Comment by dullme** [comment]
{{ $.65.body.token | lconcat : Bearer }}  我这么设置的话 Bearer 和后面的token 怎么设置空格？我现在是没有用空格隔开的。

**Comment by suxiaoxin** [comment]
$.65.body.token | lconcat : " Bearer "
