### ISSUE TITLE
运行界面里的参数经常不显示

### ISSUE THREAD

**Issue by GreedyPirate** [YMFE/yapi#1312]
## 版本号
1.7.1

## 什么问题
运行界面里的参数为空，应该和预览界面里的参数体一致，并且是mock好的，但有的接口运行界面一直是空的，有的接口是有的

## 如何复现此问题
~ 

## 什么浏览器
chrome

## 什么系统（Linux, Windows, macOS）
macOS

## 如图
![image](https://user-images.githubusercontent.com/14834990/63343719-3fcb5b00-c381-11e9-9e01-c522329b8be2.png)
![image](https://user-images.githubusercontent.com/14834990/63343780-68ebeb80-c381-11e9-8859-0751f341a5d0.png)

**Comment by tangcent** [comment]
不是很理解.
如果是访问mock接口，我猜测这里的host应该是`http://127.0.0.1/mock/$projectId` ?

**Comment by GreedyPirate** [comment]
> 不是很理解.
> 如果是访问mock接口，我猜测这里的host应该是`http://127.0.0.1/mock/$projectId` ?

我的意思是说运行界面里的body应该是这样的
```
{
  "params": {
      "point": {
          "lat": 34, // 已经mock好了
          "lon": 31
      }
     ...........
  }
}
```

**Comment by tangcent** [comment]
是否可以在编辑页面查看一下body为空的源码？
形如
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "mock": {
    "mock": "@natural(0,10000)"
  },
  "type": "integer"
}
```

**Comment by GreedyPirate** [comment]
> 是否可以在编辑页面查看一下body为空的源码？
> 形如
> 
> ```
> {
>   "$schema": "http://json-schema.org/draft-04/schema#",
>   "mock": {
>     "mock": "@natural(0,10000)"
>   },
>   "type": "integer"
> }
> ```

你是说运行左边的那个编辑页面吗，如果是，截图如下
![image](https://user-images.githubusercontent.com/14834990/63429637-34456600-c44d-11e9-8443-9fe60afba327.png)

**Comment by tangcent** [comment]
需要点击小齿轮查看源码
![image](https://user-images.githubusercontent.com/17569144/63429769-8edec200-c44d-11e9-858b-9ba3ccdd2709.png)
源码可以让他人快速复现你的情况。

**Comment by GreedyPirate** [comment]
> 需要点击小齿轮查看源码
> ![image](https://user-images.githubusercontent.com/17569144/63429769-8edec200-c44d-11e9-858b-9ba3ccdd2709.png)
> 源码可以让他人快速复现你的情况。

```
{
  "type": "object",
  "properties": {
    "params": {
      "type": "object",
      "properties": {
        "point": {
          "type": "object",
          "required": [
            "lat",
            "lon"
          ],
          "properties": {
            "lat": {
              "type": "number",
              "format": "double",
              "description": "纬度",
              "allowEmptyValue": false
            },
            "lon": {
              "type": "number",
              "format": "double",
              "description": "经度",
              "allowEmptyValue": false
            }
          },
          "title": "Point",
          "$$ref": "#/definitions/Point"
        },
        "radius": {
          "type": "integer",
          "format": "int32"
        },
        "soc_end": {
          "type": "integer",
          "format": "int32",
          "description": "soc 区间结束值",
          "allowEmptyValue": false,
          "maximum": 100,
          "exclusiveMaximum": false
        },
        "soc_start": {
          "type": "integer",
          "format": "int32",
          "description": "soc 区间起始值，不支持小数",
          "allowEmptyValue": false
        }
      },
      "title": "CarNearbyRequest",
      "$$ref": "#/definitions/CarNearbyRequest"
    }
  },
  "title": "InputMessage«CarNearbyRequest»",
  "$$ref": "#/definitions/InputMessage«CarNearbyRequest»"
}
```

**Comment by tangcent** [comment]
- 我猜测应该是由于你的property都是optional/nullable所引起的概率性body被mock为{}
- 你可以尝试设置部分属性为required:
![image](https://user-images.githubusercontent.com/17569144/63431753-29d99b00-c452-11e9-959b-de9595c73ebf.png)

**Comment by GreedyPirate** [comment]
> * 我猜测应该是由于你的property都是optional/nullable所引起的概率性body被mock为{}
> * 你可以尝试设置部分属性为required:
>   ![image](https://user-images.githubusercontent.com/17569144/63431753-29d99b00-c452-11e9-959b-de9595c73ebf.png)

确实是这样的，全是勾选后正常了，但是部分属性非required就mock为{}确实不是我想要的结果，希望考虑优化下
