### ISSUE TITLE
Postman的Json导入过程中，一直处于Loading状态

### ISSUE THREAD

**Issue by MonkeysDaddy** [YMFE/yapi#132]
## Version
~ 
1.3.4
## What is expected
~
我们有旧项目，一直在Postman上维护接口，我导入时，一直Loading，无法把接口导入到Yapi内
## Step to reproduce
~ 

## Environment
~

**Comment by gaoxiaomumu** [comment]
您好，可以发一份数据样例给我们吗？我这边测一下
