### ISSUE TITLE
1.8.3 首次注册-- 退出登录，再次登录报用户不存在，但在用户列表里面有

### ISSUE THREAD

**Issue by walkersing** [YMFE/yapi#1325]
## 版本号
 1.8.3

## 什么问题
首次注册-- 退出登录，再次登录报用户不存在，但在用户列表里面有

## 如何复现此问题
首次注册-- 退出登录，再次登录报用户不存在，但在用户列表里面有
![image](https://user-images.githubusercontent.com/4715142/63819284-45273780-c977-11e9-9b13-ec102b12d1e1.png)
![image](https://user-images.githubusercontent.com/4715142/63819290-4fe1cc80-c977-11e9-8221-9ebc1d29ecf4.png)

## 什么浏览器
chrome

## 什么系统（Linux, Windows, macOS）
linux

**Comment by walkersing** [comment]
只能邮箱登录

**Comment by sky521000** [comment]
同样问题
