### ISSUE TITLE
get请求的请求头为空，设置了也无效

### ISSUE THREAD

**Issue by wzshuang** [YMFE/yapi#1334]
## 版本号
~ 1.8.1

## 什么问题
~ get请求的请求头为空，设置了也无效

## 如何复现此问题
~ 
任意新建一个get的接口，设置Content-Type，点击运行。在DevTools里查看Request Headers发现没有值。由于后端接口会校验Content-Type，导致接口调用失败。
尝试在`请求配置`里赋值，也不起作用
```javascript
if (context.method == 'GET') {
    context.requestHeader['Content-Type'] = 'text/plain;charset=UTF-8';
}
```
![image](https://user-images.githubusercontent.com/8585771/64004128-43f53680-cb40-11e9-853d-51a50b64d98c.png)
![image](https://user-images.githubusercontent.com/8585771/64004179-55d6d980-cb40-11e9-87bb-ea318c4d2401.png)

## 什么浏览器
~ Chrome/76.0.3809.132

## 什么系统（Linux, Windows, macOS）
win10

**Comment by wangchao523** [comment]
后端接口的代码贴下，通过Postman等工具正常吗？

**Comment by wangchao523** [comment]
我在休假，节后可以帮你看。
这块yapi应该有特殊处理，文档上有写。https://hellosean1025.github.io/yapi/documents/api.html#%e6%8e%a5%e5%8f%a3%e9%85%8d%e7%bd%ae

你可以这么验证下：api中去掉consums限制，然后通过head获取对应的值，这样来看看yapi最后传的啥。

**Comment by wzshuang** [comment]
@wangchao523 
感谢回复，去掉consums后，加断点发现yapi没有传Content-Type
![image](https://user-images.githubusercontent.com/8585771/64746724-3e83ed00-d53f-11e9-81ba-b527f6c274cb.png)

从cross-request插件的网络请求里看也是没有传Content-Type
![image](https://user-images.githubusercontent.com/8585771/64746803-94f12b80-d53f-11e9-9670-7a858b651715.png)

**Comment by wzshuang** [comment]
@wangchao523 
大佬休假完了吗，抽空帮忙跟踪下哈，感谢

**Comment by wzshuang** [comment]
@wangchao523

**Comment by Geolem** [comment]
header设置也没携带到后台 [](https://github.com/YMFE/yapi/issues/651)

**Comment by wzshuang** [comment]
@wangchao523

**Comment by wzshuang** [comment]
@wangchao523 能帮忙看下吗

**Comment by Sumnus00** [comment]
@wangchao523  +1 这个问题怎么临时解决。。

**Comment by wangchao523** [comment]
![image](https://user-images.githubusercontent.com/1393365/69044545-0eb9ff80-0a30-11ea-8c3c-1be0bdc68057.png)
我看插件的代码这里会执行delete操作，如果需要建议你们修改插件的js代码，具体逻辑也请自行查看插件源码

**Comment by Sumnus00** [comment]
> ![图片](https://user-images.githubusercontent.com/1393365/69044545-0eb9ff80-0a30-11ea-8c3c-1be0bdc68057.png)
> 我看插件的代码在这里执行删除操作，如果需要建议你们修改插件的js代码，具体逻辑也请自行查看插件源码。
> 
> 在background.js中226行也有同样的代码。

感谢回复，但我找不到对应文件response.js和background.js 版本为master 1.8.6

**Comment by wangchao523** [comment]
> > ![图片](https://user-images.githubusercontent.com/1393365/69044545-0eb9ff80-0a30-11ea-8c3c-1be0bdc68057.png)
> > 我看插件的代码在这里执行删除操作，如果需要建议你们修改插件的js代码，具体逻辑也请自行查看插件源码。
> > 在background.js中226行也有同样的代码。
> 
> 感谢回复，但我找不到对应文件response.js和background.js 版本为master 1.8.6

这个是在Chrome的插件里哈，插件目录参考：https://www.jianshu.com/p/c6448c0ed1d9
找到yapi的插件（cross-request）ID，进到对应的目录就可以看到
