### ISSUE TITLE
【二次开发】请问前端服务器和后端服务器如何运行等问题？

### ISSUE THREAD

**Issue by DonnySLau** [YMFE/yapi#1357]
## 版本号
~ v1.8.3

## 什么问题
- 部署
  - 本人根据官方文档和各种issue参考，在个人服务器（Ubuntu16.04）上尝试搭建，并准备尝试二次开发。操作如下：
    - fork YMFE/yapi 到个人仓库
    - 使用了nvm，设置node和npm版本
    ```shell
    nvm --version # 0.33.11
    node -v # 7.6.0
    npm -v # 5.7.1
    ```
    - 搭建过程
       ```shell
       mkdir ~/yapi
       cd yapi
       git clone git@github.com:DonnySLau/yapi.git vendors
       cp vendors/config_example.json . # 并修改相关配置中的端口为19520，修改了mongodb相关配置且能连通
       cd vendors
       npm install --dev --registry https://registry.npm.taobao.org
       ```
       安装过程中出现了`[server error] Cannot load the stats for react-slick`的错误，尝试删除node_modules目录、清除npm缓存并进行重新安装
       ```shell
       rm -rf vendors/node_modules
       npm cache clean --force
       npm install --dev --registry https://registry.npm.taobao.org
       ```
       安装成功后，初始化数据库，成功
       ```shell
       npm run install-server
       ```
    - 启动开发服务器
       ```shell
       npm run dev
       ```
    - 访问`我的服务器ip:19520`
       在F12中看到
       `GET http://127.0.0.1:4000/prd/index@dev.css net::ERR_CONNECTION_REFUSED`
       `GET http://127.0.0.1:4000/prd/manifest@dev.js net::ERR_CONNECTION_REFUSED`
       等等的错误
     - 访问`我的服务器ip:4000`
        能够打开一个页面，看到目录结构，点击static/dev.html后，在终端可以看到
        `⠼ [Bundler] 1084/1203 build modules`
        这种构建中的状态，很不幸，构建时卡死，只能关掉终端。。。

- 问题
  1. 【重点】如何配置和配置哪些文件才能正常启动后台和前端服务器并正常构建和调试？
  1. 有没有大佬提供一个v1.8.3中各种依赖能够正常运行的版本列表？
  1. 有没有大佬能够讲述一下项目结构？以及二次开发中值得注意的问题

- PS
  纯手打，小白求问，有错误请指出，谢谢大佬们指教。  

## 如何复现此问题
~ 如上

## 什么浏览器
~ Google Chrome

## 什么系统（Linux, Windows, macOS）
~ 阿里云ECS，Ubuntu 16.04

**Comment by tangcent** [comment]
https://github.com/YMFE/yapi/issues/1296#issuecomment-520656364
尝试使用yarn试试?
另外config.json是否有配置?

**Comment by DonnySLau** [comment]
> [#1296 (comment)](https://github.com/YMFE/yapi/issues/1296#issuecomment-520656364)
> 尝试使用yarn试试?
> 另外config.json是否有配置?

**Comment by DonnySLau** [comment]
> [#1296 (comment)](https://github.com/YMFE/yapi/issues/1296#issuecomment-520656364)
> 尝试使用yarn试试?
> 另外config.json是否有配置?

- 用yarn同样能启动开发服务器，但是访问4000端口打开static/index.html时，[Bundle] xxx/xxx build modules仍然会卡住。
- config.json配置成自己的服务器，npm run install-server 配置数据库能成功的。

**Comment by DonnySLau** [comment]
尝试build，卡住并长时间等待后报错。
```
root@DonnyS-Ubuntu:~/yapi/vendors# yarn run build-client
yarn run v1.17.3
$ NODE_ENV=production ykit pack -m
⠇ [Bundler] 713/778 build modules/root/yapi/vendors/node_modules/ykit-config-react/node_modules/happypack/lib/HappyThread.js:163
  throw e;
  ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:636:16)
    at Object.compile (/root/yapi/vendors/node_modules/ykit-config-react/node_modules/happypack/lib/HappyThread.js:138:10)
    at Object.compile (/root/yapi/vendors/node_modules/ykit-config-react/node_modules/happypack/lib/HappyThreadPool.js:72:14)
    at HappyPlugin.compileAndUpdateCache (/root/yapi/vendors/node_modules/ykit-config-react/node_modules/happypack/lib/HappyPlugin.js:350:14)
    at HappyPlugin.compileInBackground (/root/yapi/vendors/node_modules/ykit-config-react/node_modules/happypack/lib/HappyPlugin.js:316:25)
    at HappyPlugin.compile (/root/yapi/vendors/node_modules/ykit-config-react/node_modules/happypack/lib/HappyPlugin.js:241:32)
    at Object.HappyLoader (/root/yapi/vendors/node_modules/happypack/lib/HappyLoader.js:31:15)
    at WEBPACK_CORE_LOADER_EXECUTION (/root/yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:155:71)
    at runSyncOrAsync (/root/yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:155:93)
    at nextLoader (/root/yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at /root/yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at Object.context.callback (/root/yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at Object.module.exports (/root/yapi/vendors/node_modules/eslint-loader/index.js:214:8)
    at WEBPACK_CORE_LOADER_EXECUTION (/root/yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:155:71)
    at runSyncOrAsync (/root/yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:155:93)
    at nextLoader (/root/yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at /root/yapi/vendors/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/root/yapi/vendors/node_modules/ykit/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /root/yapi/vendors/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@DonnyS-Ubuntu:~/yapi/vendors# events.js:174
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at process.target.send (internal/child_process.js:636:16)
    at /root/yapi/vendors/node_modules/ykit-config-react/node_modules/happypack/lib/HappyWorkerChannel.js:33:18
    at /root/yapi/vendors/node_modules/ykit-config-react/node_modules/happypack/lib/HappyWorker.js:50:5
    at apply (/root/yapi/vendors/node_modules/ykit-config-react/node_modules/happypack/lib/applyLoaders.js:262:14)
    at /root/yapi/vendors/node_modules/ykit-config-react/node_modules/happypack/lib/applyLoaders.js:275:9
    at /root/yapi/vendors/node_modules/babel-loader/lib/index.js:159:14
    at /root/yapi/vendors/node_modules/babel-loader/lib/fs-cache.js:87:9
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
Emitted 'error' event at:
    at process.nextTick (internal/child_process.js:640:35)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by DonnySLau** [comment]
> [#1296 (comment)](https://github.com/YMFE/yapi/issues/1296#issuecomment-520656364)
> 尝试使用yarn试试?
> 另外config.json是否有配置?

我想问一下，我再服务器上运行`npm run dev-server` 和 `npm run dev-client` 后，访问前端服务器的dev.html时会出错，
> GET http://127.0.0.1:4000/prd/index@dev.css net::ERR_CONNECTION_REFUSED
> dev.html:15 GET http://127.0.0.1:4000/prd/manifest@dev.js net::ERR_CONNECTION_REFUSED
> dev.html:16 GET http://127.0.0.1:4000/prd/lib3@dev.js net::ERR_CONNECTION_REFUSED
> dev.html:17 GET http://127.0.0.1:4000/prd/lib2@dev.js net::ERR_CONNECTION_REFUSED
> dev.html:18 GET http://127.0.0.1:4000/prd/lib@dev.js net::ERR_CONNECTION_REFUSED
> dev.html:19 GET http://127.0.0.1:4000/prd/index@dev.js net::ERR_CONNECTION_REFUSED
请问如何配置，以在服务器上能够运行开发环境？

**Comment by DonnySLau** [comment]
> > [#1296 (comment)](https://github.com/YMFE/yapi/issues/1296#issuecomment-520656364)
> > 尝试使用yarn试试?
> > 另外config.json是否有配置?
> 
> 我想问一下，我再服务器上运行`npm run dev-server` 和 `npm run dev-client` 后，访问前端服务器的dev.html时会出错，
> 
> > GET http://127.0.0.1:4000/prd/index@dev.css net::ERR_CONNECTION_REFUSED
> > dev.html:15 GET http://127.0.0.1:4000/prd/manifest@dev.js net::ERR_CONNECTION_REFUSED
> > dev.html:16 GET http://127.0.0.1:4000/prd/lib3@dev.js net::ERR_CONNECTION_REFUSED
> > dev.html:17 GET http://127.0.0.1:4000/prd/lib2@dev.js net::ERR_CONNECTION_REFUSED
> > dev.html:18 GET http://127.0.0.1:4000/prd/lib@dev.js net::ERR_CONNECTION_REFUSED
> > dev.html:19 GET http://127.0.0.1:4000/prd/index@dev.js net::ERR_CONNECTION_REFUSED
> 
> 请问如何配置，以在服务器上能够运行开发环境？

修改/static/dev.html中的127.0.0.1:4000为我自己的服务器ip加端口就解决问题了。

**Comment by DonnySLau** [comment]
又出现了如下错误，正在寻找修改的地方：
> http://127.0.0.1:19531/__webpack_hmr

**Comment by tangcent** [comment]
> > [#1296 (comment)](https://github.com/YMFE/yapi/issues/1296#issuecomment-520656364)
> > 尝试使用yarn试试?
> > 另外config.json是否有配置?
> 
> 我想问一下，我再服务器上运行`npm run dev-server` 和 `npm run dev-client` 后，访问前端服务器的dev.html时会出错，
> 
> > GET http://127.0.0.1:4000/prd/index@dev.css net::ERR_CONNECTION_REFUSED
> > dev.html:15 GET http://127.0.0.1:4000/prd/manifest@dev.js net::ERR_CONNECTION_REFUSED
> > dev.html:16 GET http://127.0.0.1:4000/prd/lib3@dev.js net::ERR_CONNECTION_REFUSED
> > dev.html:17 GET http://127.0.0.1:4000/prd/lib2@dev.js net::ERR_CONNECTION_REFUSED
> > dev.html:18 GET http://127.0.0.1:4000/prd/lib@dev.js net::ERR_CONNECTION_REFUSED
> > dev.html:19 GET http://127.0.0.1:4000/prd/index@dev.js net::ERR_CONNECTION_REFUSED
> 
> 请问如何配置，以在服务器上能够运行开发环境？

我是使用: yarn run dev

**Comment by tangcent** [comment]
是否有执行过 `yarn install`?

**Comment by DonnySLau** [comment]
重新搭建和部署了环境，目前暂时能解决大部分问题。
相关命令如下：
```shell
npm cache clean -f
nvm cache clear
git clone git@github.com:DonnySLau/yapi.git vendors
npm install --registry https://registry.npm.taobao.org
npm run dev-server
npm run dev-client
ykit pack -m
```

另外修改以下文件相关项为自己服务器的ip端口：
- config.json的端口
- package.json中dev-client命令的端口
- static/dev.html中的127.0.0.1:4000

仍存在的问题：
无法热更新代码，浏览器F12中有__webpack_hmr的404错误，寻找解决方案中。。

**Comment by chensheng0619** [comment]
![image](https://user-images.githubusercontent.com/34340208/82136317-2afff300-983f-11ea-8a3f-fe2d109fabce.png)
遇到了同样的问题，改完端口之后，在npm run dev-client遇到了报错。。。想问下有遇到吗？

**Comment by DonnySLau** [comment]
> ![image](https://user-images.githubusercontent.com/34340208/82136317-2afff300-983f-11ea-8a3f-fe2d109fabce.png)
> 遇到了同样的问题，改完端口之后，在npm run dev-client遇到了报错。。。想问下有遇到吗？

时间有点久远了... 建议确认一下相关软件的版本，下面是我能部署成功的版本：
- nvm 0.33.11
- npm 5.7.1
- node.js v7.6.0
- mongodb 4.2.0
- git 2.1.4
