### ISSUE TITLE
未处理promise rejection

### ISSUE THREAD

**Issue by jayZOU** [YMFE/yapi#137]
环境
node v8.4.0
npm 5.3.0
mongo  v3.6.2

问题
error: MongoError: Authentication failed.mongodb connect error
(node:69168) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Authentication failed.
(node:69168) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

初步分析
应该是引用的包或者脚本没有处理promise.reject状态引发的错误，node 6.6.0之后的一个特性（或者是BUG）

能否兼容下这个特性？不然就只能尝试其它版本的node了

**Comment by suxiaoxin** [comment]
这个问题应该是因为数据库权限导致的，找个不需要用户名密码的数据试试
