### ISSUE TITLE
请问如何二次开发

### ISSUE THREAD

**Issue by tlzzu** [YMFE/yapi#139]
## Version
~ v1.3.4

## What is expected
~想二次开发，扩展导入我司服务接口格式的插件，但是npm run install-server 有问题，启动mongo之后
`
error: undefined mongodb Authentication failed
log: mongodb load success...
`
我已经配置好了
`
{
  "port": "9113",
  "adminAccount": "xxx@123.com",
  "db": {
    "servername": "localhost",
    "DATABASE": "yapitest",
    "port": 27017,
    "user": "username",
    "pass": "******"
  },
  "mail": {
    "enable": true,
    "host": "smtp.163.com",
    "port": 465,
    "from": "***@163.com",
    "auth": {
      "user": "***@163.com",
      "pass": "*****"
    }
  }
}
`
yapitest数据库可以登录，密码，用户配置正确。

## Step to reproduce
~ 

## Environment
~ 

请问是哪里有问题？二次开发文档能否写全一些？

**Comment by gaoxiaomumu** [comment]
mongodb3.03以上开启认证,解决程序认证连接报
http://blog.csdn.net/ll657418802/article/details/50846313?locationNum=7
