### ISSUE TITLE
非管理员身份登陆，也能添加分组

### ISSUE THREAD

**Issue by chenyanzhi1080** [YMFE/yapi#1392]
## 版本号
版本: 1.8.3、1.8.2
## 什么问题
非管理员身份登陆，也能添加分组
## 如何复现此问题
非管理员账户登陆，个人空间也出现创建分组按钮，并能添加分组

## 什么浏览器
chrome

## 什么系统（Linux, Windows, macOS）
Linux、macOS

**Comment by tangcent** [comment]
see https://hellosean1025.github.io/yapi/documents/manage.html
里面有说 `只有 超级管理员 有权限创建分组`
所以非超级管理员创建分组应该禁止.但不排除文档未及时更新.
如果三天后没有人给出相关PR，我将尝试给出一个.

**Comment by tangcent** [comment]
注意到 [cdb3d3dd028c80ce4c6735aee0a28fab0dff8cc1](https://github.com/YMFE/yapi/commit/cdb3d3dd028c80ce4c6735aee0a28fab0dff8cc1)中:
https://github.com/YMFE/yapi/blob/107d8702126ed2551573351bb6662fe24f151a45/server/controllers/group.js#L129-L133
那么应该是文档未及时更新了.
