### ISSUE TITLE
“运行”进行接口请求，一直是loading状态

### ISSUE THREAD

**Issue by MRddx** [YMFE/yapi#1396]
## 版本号
版本: 1.8.3

## 什么问题
“运行”进行接口请求，一直是loading状态

## 如何复现此问题
安装好

## 什么浏览器
谷歌 73

## 什么系统（Linux, Windows, macOS）
windows 7

安装好cross-request 3.0，写好接口运行时，插件内有报错，运行一直loading
![image](https://user-images.githubusercontent.com/28419223/65816263-1af1bf80-e22c-11e9-9c63-1ea7d6ab8854.png)

![image](https://user-images.githubusercontent.com/28419223/65816277-3bba1500-e22c-11e9-9614-23416c62d64c.png)

**Comment by MRddx** [comment]
![image](https://user-images.githubusercontent.com/28419223/65816287-5a201080-e22c-11e9-9ff9-7c6ece587527.png)

一直这样

**Comment by longshengtang** [comment]
请问解决了吗
