### ISSUE TITLE
部署之后，不能删除测试用例

### ISSUE THREAD

**Issue by laoono** [YMFE/yapi#14]
感谢yapi的开源，已成功部署，使用过程中发现一个问题：测试用例集合不能删除
控制台报错如下：Failed to load resource: the server responded with a status of 404 (Not Found) ：api/col/del_case?caseid=11

**Comment by suxiaoxin** [comment]
![image](https://user-images.githubusercontent.com/17695103/32084427-aa020d82-ba8e-11e7-9bfa-3c2afe51285e.png)
yapi.demo.qunar.com 站点是没有问题的，请确保您的 node 版本>= 7.6, mongodb 版本 >= 2.6

**Comment by laoono** [comment]
![image](https://user-images.githubusercontent.com/11498968/32089271-8f80d87e-baae-11e7-8012-545ea943fdfb.png)
版本没问题，mongo用户我给的readWrite权限，会有关系吗？

**Comment by suxiaoxin** [comment]
如果其他功能没有出现异常，那就没有关系

**Comment by suxiaoxin** [comment]
@laoono 已经发布 v1.2.0版本，执行 yapi update更新下

你的这个问题应该是因为依赖版本不兼容，这个版本修复了

**Comment by laoono** [comment]
嗯。已经执行更新了，现在正常了。辛苦辛苦
