### ISSUE TITLE
自动化测试《配置通用规则》找不到 !!!

### ISSUE THREAD

**Issue by leopardoooo** [YMFE/yapi#1409]
## 版本号
[在线版本](http://yapi.demo.qunar.com/group/4418)

## 什么问题
根据在线教程和在线控制台，我没有找到文章里面提到的自动化测试的《配置通用规则》功能？
[在线教程原文](https://yapi.ymfe.org/documents/case.html#服务端自动化测试)

## 如何复现此问题
~ 

## 什么浏览器
Chrome

## 什么系统（Linux, Windows, macOS）
Windows 10

**Comment by hellosean1025** [comment]
demo 不是最新版
