### ISSUE TITLE
请支持版本管理和与jenkins和git集成

### ISSUE THREAD

**Issue by jinyh1** [YMFE/yapi#141]
## Version
~ 

## What is expected
~需要两个功能，一个是历史版本，也就是首页加上索引，比如1.0期包括哪些修改，1.1期包括哪些修改等等。一个是希望yapi可以和jenkins和git集成。

## Step to reproduce
~ 

## Environment
~

**Comment by chenzi** [comment]
历史版本很实用，居然没有。 开发app经常会维护多个版本的api。
