### ISSUE TITLE
1.8.4版本提示 “当前版本是：1.8.4  可升级到: 1.8.3 ”

### ISSUE THREAD

**Issue by fxf111** [YMFE/yapi#1418]
## 版本号

1.8.4

## 什么问题

版本提示错误
![image](https://user-images.githubusercontent.com/27943136/66695731-9c028980-ecf7-11e9-9131-0bfaeadb06b3.png)

## 如何复现此问题

登录1.8.4版本

## 什么浏览器

Chrome

## 什么系统（Linux, Windows, macOS）

Windows

**Comment by hellosean1025** [comment]
fixed.
