### ISSUE TITLE
执行yapi update无法更新，Error:  connect ETIMEDOUT 120.27.128.131:443

### ISSUE THREAD

**Issue by bowenliang123** [YMFE/yapi#1419]
## 版本号
~ 1.8.3

## 什么问题
~ 无法更新

## 如何复现此问题
~ 执行yapi update

## 什么浏览器
~ 命令行

## 什么系统（Linux, Windows, macOS）
CentOS

**Comment by lighgycloud** [comment]
我也是 等修复

**Comment by lighgycloud** [comment]
@bowenliang123 yapi-cli server 试试这个

**Comment by hellosean1025** [comment]
https://github.com/YMFE/yapi/issues/1403

**Comment by bowenliang123** [comment]
npm i -g yapi-cli
