### ISSUE TITLE
docker中yapi 重启报错

### ISSUE THREAD

**Issue by yizhishang** [YMFE/yapi#1420]
## 版本号
1.8.3

## 什么问题
yapi 重启报错

## 如何复现此问题
在第一次启动初始化之后，mongo已经有了数据
第二次重启后，再次启动，进入初始化进程，会报错
现有的逻辑是生成init.lock文件当做标识，但是在docker中，重新生成一个container，就不存在init.lock，会报此错

**Comment by fjc0k** [comment]
换一个：https://github.com/fjc0k/docker-YApi

**Comment by yizhishang** [comment]
> 换一个：https://github.com/fjc0k/docker-YApi

请问下，您这个是通过什么方式控制的的

**Comment by fjc0k** [comment]
这个对 YApi 原有的安装、升级、重启等进行了封装，更简单易用

**Comment by yizhishang** [comment]
针对Dockerfile中的“RUN apk add --no-cache git bash python make gcc g++” 这个步骤有优化的空间吗？这一步非常耗时

**Comment by fjc0k** [comment]
你直接按文档用就行 非要自己构建干嘛呢？

**Comment by yizhishang** [comment]
拿到代码就有一种自己尝试的兴趣

**Comment by fjc0k** [comment]
哈哈 但是尝试的代价就是你得给 docker 注入翻墙代理 不然国内这网速够呛能成功

**Comment by yizhishang** [comment]
算了，我自己构建一个node，跑一遍RUN apk add --no-cache git bash python make gcc g++，生成新的node镜像就好了

**Comment by fjc0k** [comment]
建议你还是直接用构建好的。。不翻墙的话， apk add，git clone，npm ci 都是漫长旅途，而且极易失败。

**Comment by yizhishang** [comment]
好的

**Comment by yizhishang** [comment]
你有构建好的吗

**Comment by fjc0k** [comment]
项目顶部介绍后面的链接你是无视了嘛 熊迪

**Comment by yizhishang** [comment]
没看到docker镜像啊
