### ISSUE TITLE
email大小写敏感

### ISSUE THREAD

**Issue by yizhishang** [YMFE/yapi#1427]
## 版本号
1.8.4
## 什么问题
1. 修改email数据大小写会创建新的账号，之前的数据丢失
2. 能否忽略email的大小，保证大小写均可登录
## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by yizhishang** [comment]
使用gitlab登录传回来的邮箱账号，和mongo中已经有的账号，在大小写敏感的时候，会被视为两个账号，这种情况下是否可以处理下呢

**Comment by tangcent** [comment]
此问题是否已得到解决？

**Comment by yizhishang** [comment]
我自己改了源码
