### ISSUE TITLE
启动时卡住不动了，想问是什么问题

### ISSUE THREAD

**Issue by AloneHbwang** [YMFE/yapi#144]
按照内网部署，第二种方案，执行到最后node app.js之后就不动了

log: the server is start at port 3000
log: mongodb load success...

想问下可能是什么原因呢

**Comment by suxiaoxin** [comment]
已经启动成功了，在浏览器打开 127.0.0.1:3000 访问

**Comment by AloneHbwang** [comment]
谢谢，还以为哪里卡住了。。
