### ISSUE TITLE
内网部署的，不能通外网。启动服务后，后台提示要连接yapi.demo.qunar.com. 没法进一步部署，怎么处理啊？

### ISSUE THREAD

**Issue by anymoreT** [YMFE/yapi#145]
## Version
~ 

## What is expected
~内网部署的，不能通外网。启动服务后，后台提示要连接yapi.demo.qunar.com. 没法进一步部署，怎么处理啊？

## Step to reproduce
~ 

## Environment
~

**Comment by suxiaoxin** [comment]
参考下文档 内网部署 方式2
