### ISSUE TITLE
为何执行ykit pack -m时报Unknown plugin "transform-runtime" 

### ISSUE THREAD

**Issue by tlzzu** [YMFE/yapi#146]
## Version
~ 

## What is expected
错误信息如下：
Module build failed: ModuleBuildError: Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in "base" at 0, attempted to resolve relative to 

## Step to reproduce
当执行：
`ykit pack -m`
时出现的错误，重新安装ykit也不行，
执行`npm install --save-dev babel-plugin-transform-runtime`也不行
## Environment
~

**Comment by suxiaoxin** [comment]
无法复现
