### ISSUE TITLE
yapi启动成功使用了大约十几分钟后突然崩溃

### ISSUE THREAD

**Issue by idongchen** [YMFE/yapi#1465]
## 版本号
~ 1.8.5
![1572697487](https://user-images.githubusercontent.com/25609949/68070862-dc14d380-fdae-11e9-8f8b-7b4af0a1e24d.png)

## 什么问题
~yapi起来一段时间就会崩溃。
日志：
[json-schema-faker] calling JsonSchemaFaker() is deprecated, call either .generate() or .resolve()

## 如何复现此问题
~ 

## 什么浏览器
~ 不是浏览器的问题，yapi服务会崩

## 什么系统（Linux, Windows, macOS）
centos7

**Comment by tangcent** [comment]
deprecated方法应该不至于使得服务崩溃.有无其他错误日志?
是否考虑过其他原因?
是否采用pm2启动yapi服务?

**Comment by idongchen** [comment]
可能是mongo版本的问题：
（后来日志当中有记录到collection.update和collection.remove的问题）
昨天将my-yapi中所有的this.model.update(替换为this.model.updateMany(
this.model.remove(替换为this.model.removeMany(
替换之后到今天为止都没出问题了
