### ISSUE TITLE
Cast to number failed for value \"第一个路径名\" at path \"_id\" for model \"project\"

### ISSUE THREAD

**Issue by XMBLDB** [YMFE/yapi#1475]
## 版本号
~ yapi  v1.7.0

## 什么问题
~访问mock接口会报
{
  "errcode": 403,
  "errmsg": "Cast to number failed for value \"第一个路径名\" at path \"_id\" for model \"project\"",
  "data": null
}
![image](https://user-images.githubusercontent.com/13642411/68355698-04a02300-014b-11ea-8b72-aee8d10a35a6.png)

## 什么浏览器
~ chrome

**Comment by tangcent** [comment]
- 如下:
![image](https://user-images.githubusercontent.com/17569144/68388208-0bef1d00-019b-11ea-8986-68d8fa58c0af.png)
请从API预览页获取mock地址,

- 一般是

|$yapi_server | mock |  $project_id |  $path|
| ------------ | ------------ | ------------ |------------ |
|http://127.0.0.1:3000|/mock|/96|/user/add|
