### ISSUE TITLE
当前版本 v1.4.1 使用 yapi update 无法升级到当前最新版本

### ISSUE THREAD

**Issue by bugyak** [YMFE/yapi#1479]
## 版本号
~ v1.4.1

## 什么问题
~ 使用 yapi update 无法升级到当前最新版本

## 如何复现此问题
~ 

## 什么浏览器
~ Chrome

## 什么系统（Linux, Windows, macOS）
Ubuntu

**Comment by zuiqingfengyang** [comment]
hi   问题解决了吗
