### ISSUE TITLE
在360极速浏览器下，使用微软拼音输入中文会重复键入

### ISSUE THREAD

**Issue by PichurChill** [YMFE/yapi#148]
## Version
~ 
V1.3.5
win 10
360极速浏览器9.0.1.150
## What is expected
~
在360极速浏览器下，使用微软拼音输入中文会重复键入，（我同事在360浏览器下搜狗输入法也会重复键入，我这没事）
下图中，“s” 我慢速输入了三次，然后按了空格；“1234”各输入了一次
![yapi2](https://user-images.githubusercontent.com/14001242/35839154-c211dfb0-0b29-11e8-9270-c88299fccbb6.gif)

## Step to reproduce
~ 

## Environment
~

**Comment by suxiaoxin** [comment]
使用 chrome
