### ISSUE TITLE
返回数据类型选择array出现报错导致无法使用

### ISSUE THREAD

**Issue by crawt** [YMFE/yapi#1486]
## 版本号
~ 1.8.5

## 什么问题
~ 接口返回数据类型选择array出现报错导致无法使用

## 如何复现此问题
~ 创建任意接口，在返现数据中新增一项，然后类型选择array

## 什么浏览器
~ Chrome 78

## 什么系统（Linux, Windows, macOS）
Windows

![console信息](https://user-images.githubusercontent.com/11565632/68641029-81b10b00-0544-11ea-83c9-ef701e7ae4ed.png)

**Comment by tangcent** [comment]
未能重现，是否也是这种情况? :https://github.com/YMFE/yapi/issues/1476#issuecomment-552468492

**Comment by crawt** [comment]
@tangcent  是的，目前定位到也是 json-schema-editor-visual bug导致的
目前通过修改 json-schema-editor-visual 的SchemaJson.js文件，182行
`value={value.title}` => `value={items.title}`
暂时解决

**Comment by tangcent** [comment]
优秀

**Comment by reggielee** [comment]
这个坑我今天刚刚踩到
