### ISSUE TITLE
打开好慢

### ISSUE THREAD

**Issue by saviorlv** [YMFE/yapi#15]
打开很慢啊

**Comment by saviorlv** [comment]
nginx   具体如何配置

**Comment by suxiaoxin** [comment]
不用 nginx 也可以
打开什么慢，请详细描述下

**Comment by saviorlv** [comment]
在服务器上部署以后，打开页面需要12-25秒左右

**Comment by suxiaoxin** [comment]
@saviorlv 你是用的 yapi server 部署的吗？
启动服务器是 node server/app.js 吗？

**Comment by saviorlv** [comment]
是的 用yapi server部署    启动服务器是 node server/app.js

**Comment by suxiaoxin** [comment]
那你试试打开 yapi.demo.qunar.com 慢不慢，如果这个不慢，说明是你的部署出了问题
