### ISSUE TITLE
希望可以配置全局header

### ISSUE THREAD

**Issue by sunhao-java** [YMFE/yapi#1510]
增加新的需求：能否在项目设置中，可以配置一个全局header，这样在录入接口的时候，不用重复的去录入多次复用的参数，比如Authorization或者Content-Type等。虽然在环境中也可以配置一个全局的header，但是那个必须在运行这个tab页才能看得到

希望在下图位置能有一个全局header参数
![image](https://user-images.githubusercontent.com/2178487/69471821-acba1b00-0dde-11ea-948e-9be247812ca6.png)
下图这里配置的全局header，只能在【运行】中才能看得到
![image](https://user-images.githubusercontent.com/2178487/69471823-b80d4680-0dde-11ea-9882-c124df48059e.png)

**Comment by tangcent** [comment]
管理起来的复杂度会不会变得很大?
有些接口不需要这个全局header的时候如何处理?

---

* 另外相似的问题我在写插件的时候也考虑过
issue: [easy-yapi#78](https://github.com/tangcent/easy-yapi/issues/78)
solution: [method_additional_header](http://easyyapi.com/setting/rules/method_additional_header.html)
* 所以也思考过如何由yapi提供这样的功能该怎样实现为妥

**Comment by sunhao-java** [comment]
我认为是否做成可选的  你项目管理中可配置未来将要使用的一些header，在定义接口的时候，可以去选择使用哪些header，而不是一个个去填写。您认为呢

**Comment by tangcent** [comment]
- 可以考虑
- 不过一般来说小BUG我随手就修了, 大点的功能不好贸然做。 可能做完之后提了PR也可能得不到回应.
- 所以你可能需要通过其他途径联系项目拥有者, 比如QQ、邮件之类的.
