### ISSUE TITLE
yapi安装word插件产生的bug

### ISSUE THREAD

**Issue by zgq7** [YMFE/yapi#1511]
## 版本号
~ 

## 什么问题
~我yapi1.8.0安装了这个插件之后可以用，但是导致了以下几个问题：
1：接口返回类型用array会导致页面崩溃
2：在不卸载插件的情况下，升级到1.8.5，my-yapi/vendors/static/prd 目录会消失，会导致整个yapi页面无法显示。
3：卸载插件后升级yapi到1.8.5，yapi可以正常用，但是插件重新安装后又会出现2的问题。

结果：目前的结果是，想要运行yapi就不装你这个插件，装了插件yapi就没法用了，想问问是不是版本兼容性问题？

## 如何复现此问题
~  上述

## 什么浏览器
~ chrome

## 什么系统（Linux, Windows, macOS）
客户端win10  服务器 linux

**Comment by li-ml** [comment]
是的，我也遇到了这个问题

**Comment by zgq7** [comment]
不用了

**Comment by muye100110** [comment]
怎么卸载插件呀
