### ISSUE TITLE
执行yapi server后访问9090页面白屏

### ISSUE THREAD

**Issue by zhangzhenyu2** [YMFE/yapi#152]
## 版本号
~ 1.3.5最新

## 什么问题
~执行yapi server后访问9090页面白屏，但是通过浏览器查看源码可以看到源码。

## 如何复现此问题
~ 安装即可复现

## 当前环境
~ linux centos6.5   node-v8.9.3-linux-x64.tar.xz     mongodb2.6.1

**Comment by suxiaoxin** [comment]
查下文档 内网部署 方式2

**Comment by zhangzhenyu2** [comment]
感谢
