### ISSUE TITLE
在swagger中设置参数类型为form，但是导入文档后默认body类型为json，需要自己手动修改

### ISSUE THREAD

**Issue by yzxiu** [YMFE/yapi#1524]
## 版本号
~ 
1.8.6
## 什么问题
~
在swagger中设置参数类型为form，但是导入文档后默认body类型为json，需要自己手动修改
## 如何复现此问题
~ 

使用springfox-swagger
    @ApiImplicitParams({
            @ApiImplicitParam(name = "a", value = "参数a的注释", required = true, paramType = "form", defaultValue = "a1")
    })
这里注解标示paramType = "form"，导入之后参数默认还是为json，需要自己编辑，改为form。
## 什么浏览器
~ 
chrome
## 什么系统（Linux, Windows, macOS）
macOS 10.15.1

**Comment by q946666800** [comment]
自己找到原因了，需要在
    @ApiOperation(consumes = "application/x-www-form-urlencoded")
添加 consumes = "application/x-www-form-urlencoded" ，
