### ISSUE TITLE
邮件推送只推送给了创建人

### ISSUE THREAD

**Issue by bhaltair** [YMFE/yapi#154]
## 版本号
1.3.4

## 什么问题
邮件推送只推送给了创建人，是否可以抄送分组所有人？

**Comment by gaoxiaomumu** [comment]
邮件会发送给项目中的所有成员，和关注了该项目的成员

**Comment by winner1207** [comment]
我这边也是只能推送给创建人，其他人都收不到邮件，是哪配置有问题吗
