### ISSUE TITLE
数据管理数据导出，html无法跳转

### ISSUE THREAD

**Issue by obabby** [YMFE/yapi#155]
## 版本号
~ 1.3.5

## 什么问题
~数据管理数据导出，html无法跳转

## 如何复现此问题
~  
![6](https://user-images.githubusercontent.com/34367393/35953665-aa9ec5a8-0cc0-11e8-858c-215f8c562c19.png)

![2](https://user-images.githubusercontent.com/34367393/35953680-b90de952-0cc0-11e8-903f-5d8ec32c7f9a.png)

测试发现生成的html，各个<a>的跳转，是由接口名称的除中文外的字符拼接而成，纯中文出现无法跳转；还会出现<a>提取出来的字符相同，导致跳转错乱

## 什么浏览器
~ 谷歌

## 什么系统（linux, window, macox）
window

**Comment by suxiaoxin** [comment]
尝试重启下服务器
