### ISSUE TITLE
测试集合条目名称更新不及时

### ISSUE THREAD

**Issue by laomu1988** [YMFE/yapi#157]
## 版本号
1.3.5

## 什么问题
测试集合中，多个条目切换时，名称更新不及时（每次总是展示上次的条目）
![image](https://user-images.githubusercontent.com/6356903/35973256-b76edf6c-0d0f-11e8-854a-ec32079b7dfb.png)

## 如何复现此问题
~ 同上

## 什么浏览器
~ chrome 63.0.3239.132

## 什么系统（linux, window, macox）
macox

**Comment by gaoxiaomumu** [comment]
该问题已解决

**Comment by laomu1988** [comment]
具体什么时候把代码更新下？
