### ISSUE TITLE
返回数据格式编辑界面图标重复出现

### ISSUE THREAD

**Issue by intellijboy** [YMFE/yapi#1576]
## 版本号
~ master最新版代码

## 什么问题
~
![image](https://user-images.githubusercontent.com/15668875/71794245-978e0880-307b-11ea-8ba9-2e3e64fad2bd.png)

## 如何复现此问题
~ npm run build-client

## 什么浏览器
~ chrome

## 什么系统（Linux, Windows, macOS）
通用问题。

**Comment by GongZiQi7** [comment]
在context.util里面加了一个加密方法，重新编译后也出现了这个问题。

**Comment by mrweijian** [comment]
这玩意有解决方法吗？

**Comment by lazeyliu** [comment]
升级antd    "antd": "^3.26.20", 解决了重复问题
