### ISSUE TITLE
自动化测试集成 jenkins 功能

### ISSUE THREAD

**Issue by suxiaoxin** [YMFE/yapi#158]
自动化测试集成 jenkins 功能正在开发中，年后发布，敬请期待！

**Comment by zhangzhenyu2** [comment]
期待

**Comment by suxiaoxin** [comment]
@zhangzhenyu2 功能已上线，请升级到 v1.3.6 版本试用

**Comment by wangxitao2273** [comment]
怎么用，哪里有介绍

**Comment by graceTesterZhang** [comment]
尝试集成jenkins，在yapi服务器上用curl命令失败，我的方式是curl+服务端测试生成的那串url，报重新登录的错误，求指点，谢谢！

**Comment by graceTesterZhang** [comment]
补充，我的yapi版本是1.4.1

**Comment by duanuniverse** [comment]
尝试集成jenkins，在yapi服务器上用curl命令失败，我的方式是curl+服务端测试生成的那串url，报重新登录的错误，求指点，谢谢！

**Comment by duanuniverse** [comment]
补充，我的yapi版本是1.9.2   {"errcode":40011,"errmsg":"请登录...","data":null}
