### ISSUE TITLE
【question】在header中添加上一个接口返回的结果作为参数

### ISSUE THREAD

**Issue by zhouzhiqiangzzq** [YMFE/yapi#1589]
## 版本号
~ 
1.8.5

## 什么问题
~
使用问题

A接口返回了 token , 想在B接口的header中加入该参数

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by zhouzhiqiangzzq** [comment]
自己解决了

存localstorage， 用的时候再取
![image](https://user-images.githubusercontent.com/5317865/72604820-98b21600-3956-11ea-8436-e4a068d458df.png)

**Comment by qzzm** [comment]
> 自己解决了
> 
> 存localstorage， 用的时候再取
> ![image](https://user-images.githubusercontent.com/5317865/72604820-98b21600-3956-11ea-8436-e4a068d458df.png)

YAPI中如何 使用 localstorage？还是自己代码中搞啊？
