### ISSUE TITLE
打开运行页面js报错

### ISSUE THREAD

**Issue by mahaixue** [YMFE/yapi#160]
在线网站
~ 

[项目：mhx123/test1，接口initCandidateFromMall，点击编辑tab，再点击运行tab，js报错]
![a1](https://user-images.githubusercontent.com/34730549/36070645-6a680b62-0f3a-11e8-95bf-1e0f795eb788.png)
![a2](https://user-images.githubusercontent.com/34730549/36070646-6be19e22-0f3a-11e8-91a2-9789ef3adeb3.png)

**Comment by suxiaoxin** [comment]
@mahaixue 能复现下你的操作过程吗？本地无法复现此问题
