### ISSUE TITLE
请问一下YApi可不可以针对某些请求才执行Pre-request Script

### ISSUE THREAD

**Issue by xiazhibin** [YMFE/yapi#1636]
有个query参数需要计算动态获得，但是不是每个请求都需要这个query参数，

请问一下YApi可不可以针对某些请求才执行Pre-request Script
我现在只能全局设置，但是不是所有的请求都需要执行Pre-request Script.
好像postman那样，Pre-request Script都是单独针对一些请求

**Comment by guyuedashu** [comment]
加一个请求头，标记一下那些请求
