### ISSUE TITLE
接口中包含!(感叹号)无法保存

### ISSUE THREAD

**Issue by chen8ih** [YMFE/yapi#165]
## 版本号
 1.3.6

## 什么问题
接口中包含!(感叹号)无法保存
![image](https://user-images.githubusercontent.com/12611993/36656292-a4840a8e-1b02-11e8-8174-287e4cdc6898.png)

## 如何复现此问题
如上图所示,去掉car后携带的！，保存成功，否则会报错

## 什么浏览器
chrome  64.0.3282.167

## 什么系统（linux, window, macox）
macox

**Comment by chen8ih** [comment]
已解决，修改server/utils/common.js文件中verifyPath方法，增加！号，重新运行项目

**Comment by suxiaoxin** [comment]
直接修改了源码，不方便以后的升级
