### ISSUE TITLE
获取菜单列表的接口interface/list_menu响应很慢

### ISSUE THREAD

**Issue by wellenzhong** [YMFE/yapi#1654]
## 版本号
1.8.5

## 什么问题
获取菜单列表的接口interface/list_menu响应很慢,在导入了swagger的数据约1600个接口后，响应时间长达18秒

## 如何复现此问题
不知道其他朋友有没有遇到过，本地没有问题。

## 什么浏览器
chrome 80.0.3987.132

## 什么系统（Linux, Windows, macOS）
Windows 10

**Comment by tangcent** [comment]
- 就目前的实现来看`interface/list_menu`中的逻辑是
`project` -> `cats` -> `interfaces`
当一个project下的cat数过多时,这里循环遍历`cat`取`interfaces`消耗很大.

- 另外目前提交PR似乎得不到响应了~,所以这个问题我可能没有办法修复.

- 也许你可以尝试重新规划一下,利用yapi中的`group(分组)`,将当前的组织方式都提升一级
project --> group
cat --> project
这样你的一个yapi`project`下的api数量应该能承受.

**Comment by wellenzhong** [comment]
> * 就目前的实现来看`interface/list_menu`中的逻辑是
>   `project` -> `cats` -> `interfaces`
>   当一个project下的cat数过多时,这里循环遍历`cat`取`interfaces`消耗很大.
> * 另外目前提交PR似乎得不到响应了~,所以这个问题我可能没有办法修复.
> * 也许你可以尝试重新规划一下,利用yapi中的`group(分组)`,将当前的组织方式都提升一级
>   project --> group
>   cat --> project
>   这样你的一个yapi`project`下的api数量应该能承受.

暴力修改了文件i/vendors/server/controllers/interface.js 里的listByMenu，因为这个函数是双循环去数据库拿数据，导致了延时。起初还以为是数据库查询慢，还找了很久原因，添加了索引，结果还是一样。
解决方案是先拿菜单的父级把列表展示出来，在点击时再把子菜单请求出来。

**Comment by tangcent** [comment]
Good job!

**Comment by pubil** [comment]
> @hellosean1025 请教作者，我对比了`1.9.2`和`1.10.2`版本的`api/interface/list_menu`接口的实现，发现`listByMenu`这个方法似乎是去掉了`yapi.commons.translateDataToTree`这个方法来处理`cat`和`interface`数据的逻辑，但依旧是用了双循环去查询，实际场景下我们遇到了一个项目有上千个接口，导致这个`list_menu`的处理时间非常长，这块逻辑改成先查出全量数据，然后再处理成`tree`，而不是多次调用查询，是不是更好点？
> 
> 源码文件：https://github.com/YMFE/yapi/blob/master/server/controllers/interface.js

这个问题有什么结局方案吗

**Comment by supuwoerc** [comment]
> > @hellosean1025 请教作者，我对比了`1.9.2`和`1.10.2`版本的`api/interface/list_menu`接口的实现，发现`listByMenu`这个方法似乎是去掉了`yapi.commons.translateDataToTree`这个方法来处理`cat`和`interface`数据的逻辑，但依旧是用了双循环去查询，实际场景下我们遇到了一个项目有上千个接口，导致这个`list_menu`的处理时间非常长，这块逻辑改成先查出全量数据，然后再处理成`tree`，而不是多次调用查询，是不是更好点？
> > 源码文件：https://github.com/YMFE/yapi/blob/master/server/controllers/interface.js
> 
> 这个问题有什么结局方案吗

等待作者回复，目前团队打算自己实现这里查询方法。

**Comment by tangcent** [comment]
已经是事实上的废弃状态了，考虑维护一个内部版本吧
