### ISSUE TITLE
“运行”返回的数据结构和“编辑”中不一致，没有警告，是不做校验吗

### ISSUE THREAD

**Issue by diyao** [YMFE/yapi#166]
## 版本号
~ 
1.3.5
## 什么问题
~
接口的“编辑”中写好的数据结构，“运行”时候返回的字段不同，没有警告提示 ？
比如：
编辑
{
  "baseUrl": "http://172.27.195.11:7009/public/theme/",
  "code": 200
}
运行返回：
{
  "baseUrl": "http://172.27.195.11:7009/public/theme/",
}

**Comment by suxiaoxin** [comment]
恩，不做校验的。
