### ISSUE TITLE
通过api新增接口接口已存在怎么解决

### ISSUE THREAD

**Issue by xgaxpp** [YMFE/yapi#1660]
## 版本号
~ 

## 什么问题
~
请问通过api新增接口。因为我们在做接口基础迁移。接口已存在。但是我们需要新增我们技术团队的接口。于原接口url地址等完全相同。请问如何解决。
## 如何复现此问题
~ 

## 什么浏览器
~ 

## 什么系统（Linux, Windows, macOS）
windows

**Comment by tangcent** [comment]
- 考虑新建一个项目?
- 路径上增加版本标记? `v1`/`v2`

**Comment by xgaxpp** [comment]
> * 考虑新建一个项目?
> * 路径上增加版本标记? `v1`/`v2`

就是不打算新建项目。看了下代码。通过页面新增接口通过group_id。怎么api就是通过project_id了。没办法么

**Comment by tangcent** [comment]
> > * 考虑新建一个项目?
> > * 路径上增加版本标记? `v1`/`v2`
> 
> 就是不打算新建项目。看了下代码。通过页面新增接口通过group_id。怎么api就是通过project_id了。没办法么

不是很能理解，新增接口应该都是需要精确到`catid`的.

**Comment by xgaxpp** [comment]
> > > * 考虑新建一个项目?
> > > * 路径上增加版本标记? `v1`/`v2`
> > 
> > 
> > 就是不打算新建项目。看了下代码。通过页面新增接口通过group_id。怎么api就是通过project_id了。没办法么
> 
> 不是很能理解，新增接口应该都是需要精确到`catid`的.

是这个样，interface/add接口里面有个checkrepeat方法。我看在检查重复的时候只用到了。project_id, 接口地址等参数作为检查条件。但是没有catid。所以在新增的时候我虽然设置catid但是还是会提示我接口重复。

**Comment by tangcent** [comment]
嗯，目前来说就是这样.必要的话可以自行把`checkrepeat `注释掉.

**Comment by xgaxpp** [comment]
好的。明白了。谢谢。
