### ISSUE TITLE
请求方式为非get方式时，header默认为content-type:application/x-www-form-urlencoded,无法删除、修改

### ISSUE THREAD

**Issue by fansh** [YMFE/yapi#169]
## 版本号
1.3.6

## 什么问题
见标题

## 如何复现此问题
1、新建一个非get方式的接口；
2、编辑该接口，不做任何操作直接保存；
3、返回接口预览

结果：
up接口在header参数里写了默认值；预览里面多了个header参数，并且无法修改和删除

## 什么浏览器
chrome

## 什么系统（linux, window, macox）
Mac

**Comment by chen8ih** [comment]
可以在编辑接口的request header 中指定请求类型
![image](https://user-images.githubusercontent.com/12611993/36779487-1dc07258-1cab-11e8-99a9-72837a6d69d6.png)

**Comment by gaoxiaomumu** [comment]
￼￼￼应该是非get请求的时候，Request_body自动保存格式为form形式，YApi 会自动添加一个header

![image](https://user-images.githubusercontent.com/21135585/36830180-8540b5d4-1d5d-11e8-8ab8-eaab91aaf44f.png)

**Comment by fansh** [comment]
是的，应该是自动保存成form形式，我选择成其他的就可以修改值了
