### ISSUE TITLE
postman的json解析

### ISSUE THREAD

**Issue by ckdlbc** [YMFE/yapi#17]
从postman导入数据，若api的url为 /api/{id} 或 /api/{{id}} ，此类带参的api不会被导入至yapi。
可否定义一个通用的规则去处理此部分api?

**Comment by suxiaoxin** [comment]
我处理下

**Comment by suxiaoxin** [comment]
@ckdlbc 已修复此问题，请升级到 v1.2.4 版本
本次升级先升级下 yapi-cli 
npm install -g yapi-cli
yapi update -v v1.2.4

**Comment by ckdlbc** [comment]
@suxiaoxin ok，非常感谢！辛苦辛苦！！
