### ISSUE TITLE
备注时无法插入修改列和行值的列表

### ISSUE THREAD

**Issue by hongxiao-liu** [YMFE/yapi#170]
## 版本号
~ 

## 什么问题
~　备注里添加列表，只能使用默认值，修改列和行的值，插入无效果

## 如何复现此问题
~ 编辑备注时，修改列表列和行的值，不能插入

## 什么浏览器
~ chome 

## 什么系统（linux, window, macox）
window 7

**Comment by suxiaoxin** [comment]
已解决，下个版本发布
