### ISSUE TITLE
swagger导入-有些接口的入参没有导入

### ISSUE THREAD

**Issue by mahaixue** [YMFE/yapi#171]
## 版本号
最新版本

## 什么问题
有些接口的入参信息没有导入，参照图片说明，api-docs.zip解压后为导入文件

![bug1](https://user-images.githubusercontent.com/34730549/36881034-0a80eada-1e07-11e8-9e18-cdf05ed3f71a.png)
![default](https://user-images.githubusercontent.com/34730549/36881037-0dcc422a-1e07-11e8-9014-ce1a7d290476.png)
![default](https://user-images.githubusercontent.com/34730549/36881039-0fd4dfc8-1e07-11e8-8385-5c8b07ff85a6.png)

[api-docs.zip](https://github.com/YMFE/yapi/files/1773518/api-docs.zip)

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by suxiaoxin** [comment]
Fixed. 请关注下个版本
