### ISSUE TITLE
swagger-auto-sync 插件没有被启用

### ISSUE THREAD

**Issue by xyezir** [YMFE/yapi#1718]
## 版本号
~ 1.8.8

## 什么问题
~ swagger 自动同步插件不见了

## 如何复现此问题
~ docker部署后，swagger自动同步插件没有在设置里出现

## 什么浏览器
~ chrome

## 什么系统（Linux, Windows, macOS）
macOS

![image](https://user-images.githubusercontent.com/5794890/79997795-82cf6680-84ec-11ea-9f9d-adccba158f64.png)

**Comment by uuau99999** [comment]
同样遇到这个问题，有结论吗

**Comment by xyezir** [comment]
没有结论，没人回复

**Comment by uuau99999** [comment]
我的问题找到了，客户端调用initPlugins的时候之前被我屏蔽掉了，现在打开就有了。楼主检查下docker构建过程中是不是漏了初始化插件了

**Comment by anjia0532** [comment]
@uuau99999 能说的详细点么？

**Comment by uuau99999** [comment]
yapi前端插件初始化的逻辑在ykit.config.js的initPlugins里面（server端在vendors/server/plugin.js里面），会读取vendors/common/config.js里面的exts获取系统内置插件列表，然后把插件信息输出到client/plugin-module.js。所以可以看看initPlugins有没被正确调用，然后在容器里面看看是否存在client/plugin-module.js文件

**Comment by anjia0532** [comment]
@uuau99999 好的，多谢，终于知道咋回事了，我没有用他的ykit，想着用npm install 替代，折腾了半天不行。

**Comment by xyezir** [comment]
感谢
