### ISSUE TITLE
初始化数据库mongodb出错

### ISSUE THREAD

**Issue by jasonyush** [YMFE/yapi#1723]
## 版本号
~ 1.8.8

## 什么问题
依赖库安装完成，正在初始化数据库mongodb...
> yapi-vendor@1.8.8 install-server C:\wwwroot\yapi\my-yapi\vendors > node server/install.js
Error: (node:6484) Warning: Accessing non-existent property 'count' of module exports inside circular dependency (Use `node --trace-warnings ...` to show where the warning was created)

## 什么系统（Linux, Windows, macOS）
Windows

**Comment by tangcent** [comment]
检查一下:
nodejs版本
mongo版本

---

尝试使用:`(Use node --trace-warnings ... to show where the warning was created)`

**Comment by jasonyush** [comment]
> 检查一下:
> nodejs版本
> mongo版本
> 
> 尝试使用:`(Use node --trace-warnings ... to show where the warning was created)`
你好，我是从官网下载的最新版本
node.js版本是v14.0.0
mongodb版本是4.2

**Comment by daoying007** [comment]
QQ群交流吧，群号：878275911。 交流互助。

**Comment by epoll-j** [comment]
> 检查一下:
> nodejs版本
> mongo版本
> 
> 尝试使用:`(Use node --trace-warnings ... to show where the warning was created)`
> 你好，我是从官网下载的最新版本
> node.js版本是v14.0.0
> mongodb版本是4.2

同样的问题，版本也一样

**Comment by tangcent** [comment]
似乎已经被修复了.
see #1729
