### ISSUE TITLE
yapi集成ad报错

### ISSUE THREAD

**Issue by huadong204** [YMFE/yapi#1745]
> {“port”：“3000”，“adminAccount”：“admin @ admin.com”，“db”：{“servername”：“mongo”，“DATABASE”：“yapi”，“port”：27017}，“ ldapLogin“：{”enable“：true，”server“：”ldap：//172.16.61.198：389“，”baseDn“：”xieyingbiao“，”bindPassword“：”xyb123456“，”searchDn“：”DC = panda ，DC = com“，”searchStandard“：”＆（（objectCategory = person）（objectclass = user））（sAMAccountName =％s）“，”emailPostfix“：”“，”emailKey“：”“，”usernameKey“： “sAMAccountName”}}

按照上面配置之后，提示：

TypeError: name (string) required
  at Client.bind (/yapi/vendors/node_modules/ldapjs/lib/client/client.js:467:11)
  at Promise.then.searchDn (/yapi/vendors/server/utils/ldap.js:98:16)
  at new Promise (<anonymous>)
  at /yapi/vendors/server/utils/ldap.js:96:12
  at new Promise (<anonymous>)
  at Object.exports.ldapQuery (/yapi/vendors/server/utils/ldap.js:8:10)
  at userController.getLdapAuth (/yapi/vendors/server/controllers/user.js:138:45)
  at /yapi/vendors/server/utils/commons.js:439:28
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
  at async module.exports (/yapi/vendors/server/middleware/mockServer.js:152:15)
请问应该怎么处理？

**Comment by boafantasy** [comment]
> > {“port”：“3000”，“adminAccount”：“admin @ admin.com”，“db”：{“servername”：“mongo”，“DATABASE”：“yapi”，“port”：27017}，“ ldapLogin“：{”enable“：true，”server“：”ldap：//172.16.61.198：389“，”baseDn“：”xieyingbiao“，”bindPassword“：”xyb123456“，”searchDn“：”DC = panda ，DC = com“，”searchStandard“：”＆（（objectCategory = person）（objectclass = user））（sAMAccountName =％s）“，”emailPostfix“：”“，”emailKey“：”“，”usernameKey“： “sAMAccountName”}}
> 
> 按照上面配置之后，提示：
> 
> TypeError: name (string) required
> at Client.bind (/yapi/vendors/node_modules/ldapjs/lib/client/client.js:467:11)
> at Promise.then.searchDn (/yapi/vendors/server/utils/ldap.js:98:16)
> at new Promise ()
> at /yapi/vendors/server/utils/ldap.js:96:12
> at new Promise ()
> at Object.exports.ldapQuery (/yapi/vendors/server/utils/ldap.js:8:10)
> at userController.getLdapAuth (/yapi/vendors/server/controllers/user.js:138:45)
> at /yapi/vendors/server/utils/commons.js:439:28
> at processTicksAndRejections (internal/process/task_queues.js:93:5)
> at async module.exports (/yapi/vendors/server/middleware/mockServer.js:152:15)
> 请问应该怎么处理？

请问有后续吗？解决了吗？
