### ISSUE TITLE
demo 网站 出错

### ISSUE THREAD

**Issue by suyulin** [YMFE/yapi#176]
http://yapi.demo.qunar.com/
示例 demo 网址 ,点击运行直接报错, 

![image](https://user-images.githubusercontent.com/6275411/37186302-c33c233c-237f-11e8-9853-27880deb1a06.png)

![image](https://user-images.githubusercontent.com/6275411/37186333-ec2a00d4-237f-11e8-9fb8-e61325b8f0b6.png)

**Comment by suxiaoxin** [comment]
把具体接口地址发过来

**Comment by suyulin** [comment]
@suxiaoxin http://yapi.demo.qunar.com/project/5114/interface/api/28670

**Comment by suxiaoxin** [comment]
Fix，等下一个版本吧
