### ISSUE TITLE
1.9.1 版本中高级mock不会返回数据

### ISSUE THREAD

**Issue by cdswyda** [YMFE/yapi#1766]
## 版本号
 1.9.1

## 什么问题

版本中高级mock中不会返回数据

## 如何复现此问题

1.9.1版本：

![image](https://user-images.githubusercontent.com/13060680/81888611-47e4be00-95d4-11ea-995c-820a7967b72d.png)
 
zhiqi之前用的1.8.3版本则一切正常：

![image](https://user-images.githubusercontent.com/13060680/81888647-634fc900-95d4-11ea-9667-9cc8080f4cd0.png)

## 什么浏览器

浏览器无关， node请求也是一样的问题。

## 什么系统（Linux, Windows, macOS）

服务器： windows server 2008  node 8.9.4
客户端： windows 10、mac 等情况一样。

## 可能有用的信息

简单调试了下，大致问题是这样的：

1、读取到的高级mock的脚本正常，
2、沙箱执行代码也正常。
3、但是 沙箱中代码对 mockJosn 的赋值似乎未生效：
    `vendors\server\utils\commons.js` 方法中 `context.mockJson = sandbox.mockJson;` 后面的 sandbox.mockJson 值是空的，因此未返回任何mock数据。

**Comment by cdswyda** [comment]
之前一直使用 1.8.3。 今天升级到1.9.1 后发现此问题，后进行了回滚。

为验证问题，重新使用不同端口和相同数据库部署，对比情况如上。

测试代码：

```js
fetch("http://192.168.201.159:3333/mock/213/getSphereMonitorData", {
    headers: {
        accept: "application/json, text/javascript, */*; q=0.01",
        "accept-language": "zh-CN,zh;q=0.9",
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "cross-site",
    },
    referrer: "http://localhost:3000/webapp/frame/projects/nx/brain/video.html",
    referrerPolicy: "no-referrer-when-downgrade",
    body: null,
    method: "POST",
    mode: "cors",
    credentials: "omit",
})
    .then((res) => {
        console.log(res);
        return res.json();
    })
    .then(console.log)
    .catch((e) => console.error(e));
```

```js
fetch("http://192.168.201.159:1199/mock/213/getSphereMonitorData", {
    headers: {
        accept: "application/json, text/javascript, */*; q=0.01",
        "accept-language": "zh-CN,zh;q=0.9",
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "cross-site",
    },
    referrer: "http://localhost:3000/webapp/frame/projects/nx/brain/video.html",
    referrerPolicy: "no-referrer-when-downgrade",
    body: null,
    method: "POST",
    mode: "cors",
    credentials: "omit",
})
    .then((res) => {
        console.log(res);
        return res.json();
    })
    .then(console.log)
    .catch((e) => console.error(e));

```

因内网部署，代码仅供参考

**Comment by lizhanglong** [comment]
我也遇到这个问题了，无效果。

mockJson= {"now":"now"}

**Comment by lizhanglong** [comment]
我这边后来测试发现，返回数据设置为JSON, 这样设置才会生效：

var a = [1,1,1,1,1,1,1,1,1,1]


Object.assign(mockJson,{
    errcode: 0,
    email: Random.email('qq.com'),
    data: a.map(function(item){
        return Random.city() + '银行'
    })
})

**Comment by cdswyda** [comment]
@lizhanglong  感谢，不过对我这来说，不太适合，因为使用有一段时间了，项目多，接口也多，很逗地方都使用了高级mock
![image](https://user-images.githubusercontent.com/13060680/82169445-1e89a200-98f4-11ea-985c-af2a0969c729.png)

**Comment by wangchao523** [comment]
[vm:error] ReferenceError: Random is not defined
    at /Volumes/work/codes/baidu/third-party/yapi/node_modules/vm.js:4:12

我这边看异常是因为Random的问题

**Comment by hellosean1025** [comment]
Fixed by 1.9.2
@wangchao523
@lizhanglong @killpanda @cdswyda

**Comment by MarvellousBaby** [comment]
{
    "errcode": 400,
    "errmsg": "解析出错，请检查。Error: Mock is not defined",
    "data": null
}
请问一下我这边配置了mock，还是会出现这个问题，大概是啥问题？

**Comment by cdswyda** [comment]
> {
> "errcode": 400,
> "errmsg": "解析出错，请检查。Error: Mock is not defined",
> "data": null
> }
> 请问一下我这边配置了mock，还是会出现这个问题，大概是啥问题？

高级mock中是只有Mock下的Random的

**Comment by MarvellousBaby** [comment]
> > {
> > "errcode": 400,
> > "errmsg": "解析出错，请检查。Error: Mock is not defined",
> > "data": null
> > }
> > 请问一下我这边配置了mock，还是会出现这个问题，大概是啥问题？
> 
> 高级mock中是只有Mock下的Random的

了解了，谢谢

**Comment by myNameIsDu** [comment]
我这边遇到的情况是mock的数据全部返回的空对象，检查了一下原因出在 Safeify 上边，它会对函数做一层转换，解决方法就是给它干掉
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/53305259/158675837-298019d9-fe6d-4e70-9a97-b9b2e7acf35f.png">
但是这又出现了之前的安全问题，所以建议在内网玩

**Comment by quicklearning123** [comment]
> 我这边遇到的情况是mock的数据全部返回的空对象，检查了一下原因出在 Safeify 上边，它会对函数做一层转换，解决方法就是给它干掉 <img alt="image" width="1271" src="https://user-images.githubusercontent.com/53305259/158675837-298019d9-fe6d-4e70-9a97-b9b2e7acf35f.png"> 但是这又出现了之前的安全问题，所以建议在内网玩

这样写，script相当于执行了两遍吧
