### ISSUE TITLE
希望能够支持复制项目或继承

### ISSUE THREAD

**Issue by hphua** [YMFE/yapi#177]
## 版本号
1.3.7

## 什么问题
应用场景：项目A有帐号相关接口，项目B的工程是基于项目A做branch。这样项目B的接口是基于项目A做调整的。希望YAPI能够支持项目接口复制或继承。或者支持导出与导入对等的功能。即导出
![](https://user-images.githubusercontent.com/3469555/36656175-013d770c-1b02-11e8-9e30-2e83226c285c.png)

**Comment by hphua** [comment]
@suxiaoxin 这功能是否可以 在后续的版本中实现。 或者指导下如何通过插件方式，进行自我实现。

**Comment by hphua** [comment]
处理方法：
手动操作mongodb，搜索出源项目接口集。导出csv格式，调整ID值（避免重复）、project_id、status(undone)、catid(类别ID，需要预先参照源项目的类别，创建相应的类别）。
导入csv。在导入前先关闭excel，用Notepad++把开CSV文件，操作“格式-->转为UTF-8编码格式”，这步骤是为了解决中文乱码。

**Comment by suxiaoxin** [comment]
已收集
