### ISSUE TITLE
在Pre-request Script 访问context，没有method属性，无法判断是何种请求

### ISSUE THREAD

**Issue by wish4sun** [YMFE/yapi#178]
## 版本号
~  1.3.7

## 什么问题
~ 在Pre-request Script 访问context，没有method属性，无法判断是何种请求

## 如何复现此问题
~ 遍历context对象，发现没有method属性

## 什么浏览器
~ Chrome

## 什么系统（linux, window, macox）
~ macox

**Comment by suxiaoxin** [comment]
好建议，下个版本把 method 加上去

**Comment by suxiaoxin** [comment]
v1.3.8. Fixed
