### ISSUE TITLE
mock数据时，需要生产一个大于当前时间的datetime 如何实现？

### ISSUE THREAD

**Issue by yangjing1127** [YMFE/yapi#1788]
## 版本号
1.8.8

## 什么问题
mock数据时，需要生产一个大于当前时间的datetime 如何实现？

例如：当前时间2020-05-25 10:00:00
需要mock到 2020-05-26 10:00:00 

## 如何复现此问题
~ 

## 什么浏览器
Chrome

## 什么系统（Linux, Windows, macOS）
Windows

**Comment by yangjing1127** [comment]
我暂时使用了global 全局变量写死解决了 。
{{global.expire_datetime}} 设置一个值。然后定期更新这个值吧

**Comment by tangcent** [comment]
> mock数据时，需要生产一个大于当前时间的datetime 如何实现？

没发现mock有这类占位符. 如果仅需要大于当前时间即可的话可以尝试:
`2021-@datetime('MM-dd HH:mm:ss')`或者`2021-@now('MM-dd HH:mm:ss')`
如果不满足的话，可以考虑使用[高级mock功能](https://hellosean1025.github.io/yapi/documents/adv_mock.html)

**Comment by yangjing1127** [comment]
> > mock数据时，需要生产一个大于当前时间的datetime 如何实现？
> 
> 没发现mock有这类占位符. 如果仅需要大于当前时间即可的话可以尝试:
> `2021-@datetime('MM-dd HH:mm:ss')`或者`2021-@now('MM-dd HH:mm:ss')`
> 如果不满足的话，可以考虑使用[高级mock功能](https://hellosean1025.github.io/yapi/documents/adv_mock.html)

谢谢提供思路，用Mock 写法实现了。如下：
{{ @now('MM-dd HH:mm:ss') | lconcat : 2021- }}
