### ISSUE TITLE
@timestamp生成时间戳精度不足

### ISSUE THREAD

**Issue by LQBing** [YMFE/yapi#1789]
## 版本号
~ 1.9.1

## 什么问题

使用@timestamp生成的时间戳是10位，批量测试使用这个@timestamp生成测试序列号的时候会产生序列号重复问题。

如果生成的是13位时间戳，想要10位的话可以通过`{{ @timestamp | substr : 0 , 10 }}`来实现。

反之现在生成的是10位时间戳，而我想要13位时间戳则是无法办到的。

## 如何复现此问题
~ 

## 什么浏览器
~ chrome

## 什么系统（Linux, Windows, macOS）
windows、linux

**Comment by tangcent** [comment]
hi~.
`@timestamp@string("number", 3)`

**Comment by LQBing** [comment]
> hi~.
> `@timestamp@string("number", 3)`

Tks for your answer. But there is still a thousandth probability to repeat. So its not the perfect solution. I need exclude duplicate, not just the 3 more numbers.

**Comment by tangcent** [comment]
What U need is `@now('T')`

**Comment by LQBing** [comment]
> What U need is `@now('T')`

Oops, It's work! Thank you!
