### ISSUE TITLE
yapi.js文件中引用 config.json 路径错误以及其他一些建议

### ISSUE THREAD

**Issue by 18boys** [YMFE/yapi#18]
1.yapi.js文件引用config.json 路径错误
yapi.js文件中引用config.json应该是 require('../config.json’),原来的写法路径写错了,是不能正确引用到的config.json的

2.当前系统看起来不支持 mongo 集群的
我们想要部署这套系统到线上环境,但是我们线上的 mongodb 是集群的,目前看起来不支持

3.当前系统的 cli不支持部署到 多台机器
因为管理员账号的冲突关系,不能用 cli 来部署到两台机器,我只能手动复制已经部署的代码到另一台机器,然后手动修改数据库的配置,比较麻烦.

4.登录校验部分不够独立
一般公司都有一套登录系统,怎么方便将公司的登录系统方便接入此系统希望你们能考虑支持下哈,太感谢了,否则我们接入的话可能需要二次开发

5.对二次开发的支持不太好
期待配置文件可以区分 dev  beta  prod环境

以上问题我们这边也在尝试二次开发,当然更希望你们提供一套更好的方案.
还有,你们的 node 部分能不能采用 ssugar.js 或者 think.js 的目录结构,服务器部分感觉写的不够系统.

以上,有什么说的不妥的地方请原谅.

**Comment by 18boys** [comment]
btw, 原来酒店事业部有一套 api 管理系统(可以找王迎然了解),那套系统看起来比较适宜做二次开发,目录结构比较有系统,采用的 node 端是 ssugar, 如果两套系统的优点能融合一下就完美了.

**Comment by suxiaoxin** [comment]
@18boys config.json 1.引用路径没有问题，建议用 yapi server 在本地部署一套看下文件结构就知道咋回事了
2.不支持集群，yapi 定位是提供给公司内部使用，数据不会太大，不是很有必要使用 mongo 集群。如果是担心数据丢失，可以考虑部署成主从

3.yapi 可以集成第三方登录的，可以参考下 插件 wiki 文档
4.二次开发请运行 npm run dev 启动开发服务器

**Comment by suxiaoxin** [comment]
@18boys qunar 员工直接访问 yapi.corp.qunar.com, 酒店云事业部 api 管理系统在功能上相比 yapi ，功能上缺陷还是挺多的，例如权限管理、项目管理、类 postman 请求功能, mock功能，自动化测试等方面。
