### ISSUE TITLE
改进建议：API状态实现可配置

### ISSUE THREAD

**Issue by hphua** [YMFE/yapi#180]
## 版本号
1.3.7 

## 改进建议
建议将API状态，实现可配置。目前默认的状态有done和undone，这两种状态在实际项目中有不够用。例如：默认状态是“未开发”。后端研发人员开发完成，可转为“开发完成”。前端人员联调成功后，才将状态转为“已完成”。
有可能还有其它场景存在，所以建议将API状态实现可配置。

**Comment by hphua** [comment]
目前处理办法，下载完整工程代码;
搜索关键字"undone"，在相应位置添加新的状态;
打包工程npm run build-client;
覆盖并重启自部署的环境；

**Comment by jszjgqq** [comment]
能自行维护状态列表那是极好的~
