### ISSUE TITLE
系统内可以查看版本号吗？

### ISSUE THREAD

**Issue by xiaohp** [YMFE/yapi#1800]
## 什么问题
应该是一年之前部署的系统，有入口查看版本号吗？方便反馈问题

**Comment by tangcent** [comment]
在你部署的yapi首页:
![image](https://user-images.githubusercontent.com/17569144/83325505-3faca400-a29f-11ea-8c92-02e9e37371d0.png)

**Comment by xiaohp** [comment]
> 在你部署的yapi首页:
> ![image](https://user-images.githubusercontent.com/17569144/83325505-3faca400-a29f-11ea-8c92-02e9e37371d0.png)

好滴，谢谢。
