### ISSUE TITLE
postman格式，导入，response无法解析

### ISSUE THREAD

**Issue by yunfei-yang** [YMFE/yapi#182]
## 版本号
版本： 1.3.5

## 什么问题
postman格式，导入，response无法解析

## 如何复现此问题
~ 

## 什么浏览器
chrome

## 什么系统（linux, window, macox）
mac
[postman_collection.zip](https://github.com/YMFE/yapi/files/1813939/postman_collection.zip)

**Comment by yujintang** [comment]
现在版本只支持Collection v1， Collection v2 与Collection v2.1 还不支持

**Comment by gaoxiaomumu** [comment]
导出postman 的数据结构只能是 Collection V2

**Comment by gaoxiaomumu** [comment]
嗯嗯，错了

**Comment by gaoxiaomumu** [comment]
问题已经解决

**Comment by yunfei-yang** [comment]
在什么版本上fix?
