### ISSUE TITLE
MockJson不生效

### ISSUE THREAD

**Issue by FrankCao1026** [YMFE/yapi#1821]
## 版本号
git代码自己编译的。

## 什么问题
在高级Mock中，使用
var a = [1,1,1,1,1,1,1,1,1,1]

mockJson = {
    errcode: 0,
    email: Random.email('qq.com'),
    data: a.map(function(item){
        return Random.city() + '银行'
    })
}
得不到想要的结果。只会返回随机数据。
if(cookie.type == 'a'){
  mockJson.errcode = 500;
  mockJson.errmsg = 'error';
}
这种模式是工作的。

## 如何复现此问题
~ 

## 什么浏览器
Chrome

## 什么系统（Linux, Windows, macOS）
macOS

**Comment by quicklearning123** [comment]
怎么解决了？
