### ISSUE TITLE
建议接口备注支持Markdown语法

### ISSUE THREAD

**Issue by dujianxin** [YMFE/yapi#183]
## 版本号
~ 
1.3.7
## 什么问题
~
建议接口备注支持Markdown语法，简化内容编辑的复杂度，提高易用性。
## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by suxiaoxin** [comment]
![image](https://user-images.githubusercontent.com/17695103/37454399-6caafab6-2875-11e8-93a0-1ff50bd4f20c.png)

v1.3.7 已经支持
