### ISSUE TITLE
可视化部署失败

### ISSUE THREAD

**Issue by linth2005** [YMFE/yapi#1834]
## 版本号
~ 
node 14.4.0
mongo 4.0.12
npm 6.14.5
git 1.8.3.1
## 什么问题
~ 可视化部署失败

## 如何复现此问题
~ 可视化部署失败

## 什么浏览器
~ Chrome

## 什么系统（Linux, Windows, macOS）
CentOS 7.6

> yapi-vendor@1.9.1 install-server /usr/local/node-v14.4.0-linux-x64/my-yapi/vendors
>  node server/install.js

Error:  (node:24168) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by jimmydye** [comment]
me too!

**Comment by linth2005** [comment]
我已经用手动安装的方式完成了部署，可参见我的部署文档
https://www.yuque.com/yuyiqingchen/qtqg0h/vwmc6o
