### ISSUE TITLE
全局变量设置

### ISSUE THREAD

**Issue by kenWu-github** [YMFE/yapi#184]
## 版本号
~ v1.3.7

## 什么问题
~当前版本能够支持设置全局变量吗？？如果不支持，是否下个版本有提供该功能呢？不然全局变量的设置真的麻烦。。望采纳

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by suxiaoxin** [comment]
参考 https://github.com/YMFE/yapi/issues/204
