### ISSUE TITLE
HAV导入有些数据会导入不成功

### ISSUE THREAD

**Issue by sunyingdong** [YMFE/yapi#185]
## 版本号
~ 

## 什么问题
~在Fiddler中抓包导出HAV文件保存，在YAPI中导入无法导入

## 如何复现此问题
~ 手机连接fiddler，操作应用。抓到的HAV文件内容如下

## 什么浏览器
~ Fiddler抓包

## 什么系统（linux, window, macox）

{"log":{"pages":[], "comment":"exported @ 2018/3/15 9:51:37", "entries":[{"time":156, "serverIPAddress":"122.228.238.110", "connection":"ClientPort:227;EgressPort:3179", "request":{"headersSize":563, "postData":{"params":[{"name":"appid", "value":"1"}, {"name":"data", "value":"{\"appid\":\"1\",\"app_name\":\"R360F\",\"idfa\":\"827C469F-BD93-4C8C-9807-024CDCE3B1B8\",\"app_version\":\"2.9.6\",\"channel\":\"AppStore\",\"rongussd\":\"84190842c2c3421cbeb4a1a387101dca\",\"sys_version\":\"11.0.2\",\"abclass\":\"1521077673_45\",\"api_version\":\"2.0\",\"city_id\":\"4\",\"platform\":\"ios\",\"time_stamp\":\"1521078603\",\"token\":\"df02fb7051a3ee67bc59524ec15b1e50\",\"device_id\":\"84190842c2c3421cbeb4a1a387101dca\",\"nettype\":\"WIFI\",\"device_model\":\"iPhone 6\"}"}, {"name":"sec_level", "value":"0"}], "mimeType":"application/x-www-form-urlencoded"}, "queryString":[], "headers":[{"name":"Host", "value":"bigapp.rong360.com"}, {"name":"Content-Type", "value":"application/x-www-form-urlencoded"}, {"name":"Cookie", "value":"city_id=10001; abclass=1521077673_45; __jsluid=eb4262e884ce5c97c367acea9ead75c8; DEVICE=1; RONGID=84190842c2c3421cbeb4a1a387101dca; __utmz=1521077672.utmcsr=AppStore|utmcmd=R360F_ios_2.9.6"}, {"name":"Connection", "value":"keep-alive"}, {"name":"Accept", "value":"*/*"}, {"name":"User-Agent", "value":"R360BigApp/2.9.6 (iPhone; iOS 11.0.2; Scale/2.00) rong360app R360_api_version_2.6"}, {"name":"Accept-Language", "value":"zh-Hans-CN;q=1"}, {"name":"Content-Length", "value":"647"}, {"name":"Accept-Encoding", "value":"br, gzip, deflate"}], "bodySize":647, "url":"https://bigapp.rong360.com/mapi/appv43/loan_list", "cookies":[{"name":"city_id", "value":"10001"}, {"name":"abclass", "value":"1521077673_45"}, {"name":"__jsluid", "value":"eb4262e884ce5c97c367acea9ead75c8"}, {"name":"DEVICE", "value":"1"}, {"name":"RONGID", "value":"84190842c2c3421cbeb4a1a387101dca"}, {"name":"__utmz", "value":"1521077672.utmcsr=AppStore|utmcmd=R360F_ios_2.9.6"}], "method":"POST", "httpVersion":"HTTP/1.1"}, "timings":{"blocked":-1, "ssl":0, "receive":0, "wait":156, "dns":0, "send":0, "connect":0}, "response":{"headersSize":360, "bodySize":15846, "statusText":"OK", "redirectURL":"", "status":200, "httpVersion":"HTTP/1.1", "cookies":[], "content":{"compression":0, "text":"{\"msg\":\"\",\"data\":{\"toast\":\"\",\"normal_list\":{\"stat\":{\"minExpense\":0,\"maxExpense\":0.1,\"numProduct\":33,\"numOrg\":20,\"bankProduct\":0,\"otherProduct\":0,\"addProduct\":33},\"app_data\":{\"city_id\":\"4\",\"application_type\":9},\"slice\":[{\"product_name\":\"\\u73b0\\u8d37\\u6d3e.\",\"org_name\":\"\\u6e23\\u6253\\u94f6\\u884c\",\"icon_url\":\"https:\\/\\/static.rong360.com\\/pimg\\/be\\/beebf94bab0ed516b7d3a9eb00b13cb7ae56a3ad.jpeg\",\"month_expense\":\"\",\"loan_cycle\":1,\"apply_num\":\"89973\",\"permit_fail\":0,\"online_jinjian\":0,\"other_fees\":{\"1\":[],\"2\":{\"low\":\"\",\"normal\":\"\",\"high\":\"\"},\"4\":{\"low\":\"\",\"normal\":\"\",\"high\":\"\"}},\"guarantee_type\":{\"code\":2,\"name\":\"\\u65e0\\u62b5\\u62bc\"},\"real_loan_quota\":null,\"real_loan_term\":null,\"standard_type\":\"1\",\"month_rate\":\"0.56%\",\"loan_quota_fixed\":\"\",\"loan_quota_max\":\"500000\",\"loan_quota_min\":\"50000\",\"loan_quota_type\":\"1\",\"repayment_type\":{\"code\":1,\"name\":\"\\u5206\\u671f\\u8fd8\\u6b3e\"},\"str_id\":\"45546111ihsxf6i0\"},{\"product_name\":\"\\u4e2a\\u4eba\\u6d88\\u8d39\\u8d37\\u6b3e\",\"org_name\":\"\\u62cd\\u62cd\\u8d37\",\"icon_url\":\"https:\\/\\/static.rong360.com\\/pimg\\/9b\\/9b8b6f95b18f26181354681c343fdef9f09a2952.jpeg\",\"month_expense\":\"\",\"loan_cycle\":1,\"apply_num\":\"111007\",\"permit_fail\":0,\"online_jinjian\":0,\"other_fees\":{\"1\":[{\"from\":\"3\",\"to\":\"6\",\"low\":\"2\",\"normal\":\"2\",\"high\":\"2\"},{\"from\":\"7\",\"to\":\"12\",\"low\":\"4\",\"normal\":\"4\",\"high\":\"4\"}],\"2\":{\"low\":\"1.04\",\"normal\":\"1.04\",\"high\":\"2.18\"},\"4\":{\"low\":\"\",\"normal\":\"\",\"high\":\"\"}},\"guarantee_type\":{\"code\":2,\"name\":\"\\u65e0\\u62b5\\u62bc\"},\"real_loan_quota\":null,\"real_loan_term\":null,\"standard_type\":\"1\",\"month_rate\":\"1.37%\",\"loan_quota_fixed\":\"\",\"loan_quota_max\":\"30000\",\"loan_quota_min\":\"1000\",\"loan_quota_type\":\"1\",\"repayment_type\":{\"code\":1,\"name\":\"\\u5206\\u671f\\u8fd8\\u6b3e\"},\"str_id\":\"34c37102ihn8loz6\"},{\"product_name\":\"\\u623f\\u4ea7\\u62b5\\u62bc\\u8d37\",\"org_name\":\"\\u4e2d\\u4fe1\\u94f6\\u884c\",\"icon_url\":\"https:\\/\\/static.rong360.com\\/pimg\\/69\\/69b61a88aa1ef4dc1d9dc83e25911863df4ad148.jpeg\",\"month_expense\":\"\",\"loan_cycle\":20,\"apply_num\":186,\"permit_fail\":0,\"online_jinjian\":0,\"other_fees\":{\"1\":[],\"2\":{\"low\":\"\",\"normal\":\"\",\"high\":\"\"},\"4\":{\"low\":\"\",\"normal\":\"\",\"high\":\"\"}},\"guarantee_type\":{\"code\":1,\"name\":\"\\u623f\\u5c4b\\u62b5\\u62bc\"},\"real_loan_quota\":null,\"real_loan_term\":null,\"standard_type\":\"1\",\"month_rate\":\"0.32%\",\"loan_quota_fixed\":\"\",\"loan_quota_max\":\"15000000\",\"loan_quota_min\":\"100000\",\"loan_quota_type\":\"1\",\"repayment_type\":{\"code\":1,\"name\":\"\\u5206\\u671f\\u8fd8\\u6b3e\"},\"str_id\":\"1cde011eihu1tnu6\"},{\"product_name\":\"\\u85aa\\u7ca4\\u8d37\\uff08\\u4f18\\u826f\\u5355\\u4f4d\\uff09\",\"org_name\":\"\\u5357\\u7ca4\\u94f6\\u884c\",\"icon_url\":\"https:\\/\\/static.rong360.com\\/pimg\\/1b\\/1b0124c629b5c50469ffa58fb920b80737402f1d.jpeg\",\"month_expense\":\"\",\"loan_cycle\":2,\"apply_num\":3219,\"permit_fail\":0,\"online_jinjian\":0,\"other_fees\":{\"1\":[],\"2\":{\"low\":\"\",\"normal\":\"\",\"high\":\"\"},\"4\":{\"low\":\"\",\"normal\":\"\",\"high\":\"\"}},\"guarantee_type\":{\"code\":2,\"name\":\"\\u65e0\\u62b5\\u62bc\"},\"real_loan_quota\":null,\"real_loan_term\":null,\"standard_type\":\"1\",\"month_rate\":\"0.46%\",\"loan_quota_fixed\":\"\",\"loan_quota_max\":\"500000\",\"loan_quota_min\":\"50000\",\"loan_quota_type\":\"1\",\"repayment_type\":{\"code\":1,\"name\":\"\\u5206\\u671f\\u8fd8\\u6b3e\"},\"str_id\":\"27d7e146ihnglzs0\"},{\"product_name\":\"\\u5c0f\\u5fae\\u91d1\\u878d\",\"org_name\":\"\\u5fae\\u4f17\\u94f6\\u884c\",\"icon_url\":\"https:\\/\\/static.rong360.com\\/pimg\\/a2\\/a2c13bc6f4f97bfb7c24dfc91dd457b6ca735a4a.jpeg\",\"month_expense\":\"\",\"loan_cycle\":1,\"apply_num\":90,\"permit_fail\":0,\"online_jinjian\":0,\"other_fees\":{\"1\":[],\"2\":{\"low\":\"0.9\",\"normal\":\"0.9\",\"high\":\"1.35\"},\"4\":{\"low\":\"\",\"normal\":\"\",\"high\":\"\"}},\"guarantee_type\":{\"code\":2,\"name\":\"\\u65e0\\u62b5\\u62bc\"},\"real_loan_quota\":null,\"real_loan_term\":null,\"standard_type\":\"1\",\"month_rate\":\"0.90%\",\"loan_quota_fixed\":\"\",\"loan_quota_max\":\"3000000\",\"loan_quota_min\":\"50000\",\"loan_quota_type\":\"1\",\"repayment_type\":{\"code\":3,\"name\":\"\\u968f\\u501f\\u968f\\u8fd8\"},\"str_id\":\"978391daihsojcuv\"},{\"product_name\":\"\\u4f18\\u826f\\u5de5\\u85aa\\u8d37\",\"org_name\":\"\\u5e7f\\u53d1\\u94f6\\u884c\",\"icon_url\":\"https:\\/\\/static.rong360.com\\/pimg\\/fe\\/fe08314e73fff704ca75456a0f2dfeebd7a88e82.jpeg\",\"month_expense\":\"\",\"loan_cycle\":3,\"apply_num\":188,\"permit_fail\":0,\"online_jinjian\":0,\"other_fees\":{\"1\":[],\"2\":{\"low\":\"0.33\",\"normal\":\"0.33\",\"high\":\"0.33\"},\"4\":{\"low\":\"\",\"normal\":\"\",\"high\":\"\"}},\"guarantee_type\":{\"code\":2,\"name\":\"\\u65e0\\u62b5\\u62bc\"},\"real_loan_quota\":null,\"real_loan_term\":null,\"standard_type\":\"1\",\"month_rate\":\"0.33%\",\"loan_quota_fixed\":\"\",\"loan_quota_max\":\"500000\",\"loan_quota_min\":\"50000\",\"loan_quota_type\":\"1\",\"repayment_type\":{\"code\":3,\"name\":\"\\u968f\\u501f\\u968f\\u8fd8\"},\"str_id\":\"3827d1f1ihi5jtt6\"},{\"product_name\":\"\\u60a6\\u65f6\\u8d37\\uff08\\u4f18\\u8d28\\u5de5\\u85aa\\u65cf\\uff09\",\"org_name\":\"\\u5e7f\\u5dde\\u519c\\u5546\\u94f6\\u884c\",\"icon_url\":\"https:\\/\\/static.rong360.com\\/pimg\\/30\\/303ea81af0ed7b30a4eaeb71ee7befcb2218bac2.jpeg\",\"month_expense\":\"\",\"loan_cycle\":3,\"apply_num\":13853,\"permit_fail\":0,\"online_jinjian\":0,\"other_fees\":{\"1\":[],\"2\":{\"low\":\"\",\"normal\":\"\",\"high\":\"\"},\"4\":{\"low\":\"\",\"normal\":\"\",\"high\":\"\"}},\"guarantee_type\":{\"code\":2,\"name\":\"\\u65e0\\u62b5\\u62bc\"},\"real_loan_quota\":null,\"real_loan_term\":null,\"standard_type\":\"1\",\"month_rate\":\"0.26%\",\"loan_quota_fixed\":\"\",\"loan_quota_max\":\"300000\",\"loan_quota_min\":\"50000\",\"loan_quota_type\":\"1\",\"repayment_type\":{\"code\":1,\"name\":\"\\u5206\\u671f\\u8fd8\\u6b3e\"},\"str_id\":\"1437f1e7ihnobnu3\"},{\"product_name\":\"\\u623f\\u4ea7\\u62b5\\u62bc\\u8d37\",\"org_name\":\"\\u5e7f\\u53d1\\u94f6\\u884c\",\"icon_url\":\"https:\\/\\/static.rong360.com\\/pimg\\/fe\\/fe08314e73fff704ca75456a0f2dfeebd7a88e82.jpeg\",\"month_expense\":\"\",\"loan_cycle\":7,\"apply_num\":90,\"permit_fail\":0,\"online_jinjian\":0,\"other_fees\":{\"1\":[],\"2\":{\"low\":\"\",\"normal\":\"\",\"high\":\"\"},\"4\":{\"low\":\"\",\"normal\":\"\",\"high\":\"\"}},\"guarantee_type\":{\"code\":1,\"name\":\"\\u623f\\u5c4b\\u62b5\\u62bc\"},\"real_loan_quota\":null,\"real_loan_term\":null,\"standard_type\":\"1\",\"month_rate\":\"0.25%\",\"loan_quota_fixed\":\"\",\"loan_quota_max\":\"10000000\",\"loan_quota_min\":\"100000\",\"loan_quota_type\":\"1\",\"repayment_type\":{\"code\":1,\"name\":\"\\u5206\\u671f\\u8fd8\\u6b3e\"},\"str_id\":\"5be521e3ihuhfzb5\"},{\"product_name\":\"\\u516c\\u79ef\\u91d1\\u8d37\",\"org_name\":\"\\u5efa\\u8bbe\\u94f6\\u884c\",\"icon_url\":\"https:\\/\\/static.rong360.com\\/pimg\\/d9\\/d927efd30f49b406add05ef2ed80998ac9b2628d.jpeg\",\"month_expense\":\"\",\"loan_cycle\":3,\"apply_num\":2438,\"permit_fail\":0,\"online_jinjian\":0,\"other_fees\":{\"1\":[],\"2\":{\"low\":\"0.4\",\"normal\":\"0.4\",\"high\":\"0.4\"},\"4\":{\"low\":\"\",\"normal\":\"\",\"high\":\"\"}},\"guarantee_type\":{\"code\":2,\"name\":\"\\u65e0\\u62b5\\u62bc\"},\"real_loan_quota\":null,\"real_loan_term\":null,\"standard_type\":\"1\",\"month_rate\":\"0.40%\",\"loan_quota_fixed\":\"\",\"loan_quota_max\":\"500000\",\"loan_quota_min\":\"50000\",\"loan_quota_type\":\"1\",\"repayment_type\":{\"code\":1,\"name\":\"\\u5206\\u671f\\u8fd8\\u6b3e\"},\"str_id\":\"52fcf1bbihi1fztz\"},{\"product_name\":\"\\u6613\\u8fbe\\u91d1\",\"org_name\":\"\\u534e\\u590f\\u94f6\\u884c\",\"icon_url\":\"https:\\/\\/static.rong360.com\\/pimg\\/3e\\/3e2bad3f883ab63f6280b5dfc7968fd1bb4dabd7.jpeg\",\"month_expense\":\"\",\"loan_cycle\":4,\"apply_num\":3926,\"permit_fail\":0,\"online_jinjian\":0,\"other_fees\":{\"1\":[],\"2\":{\"low\":\"0.7\",\"normal\":\"0.75\",\"high\":\"0.75\"},\"4\":{\"low\":\"\",\"normal\":\"\",\"high\":\"\"}},\"guarantee_type\":{\"code\":2,\"name\":\"\\u65e0\\u62b5\\u62bc\"},\"real_loan_quota\":null,\"real_loan_term\":null,\"standard_type\":\"1\",\"month_rate\":\"0.75%\",\"loan_quota_fixed\":\"\",\"loan_quota_max\":\"500000\",\"loan_quota_min\":\"50000\",\"loan_quota_type\":\"1\",\"repayment_type\":{\"code\":1,\"name\":\"\\u5206\\u671f\\u8fd8\\u6b3e\"},\"str_id\":\"878ecagu1\"},{\"product_name\":\"\\u516c\\u79ef\\u91d1\\u8d37\",\"org_name\":\"\\u5fae\\u4f17\\u4e92\\u8054\\u7f51\",\"icon_url\":\"https:\\/\\/static.rong360.com\\/pimg\\/3b\\/3b99482c815605c34b3028f4a9edef08163f0ac4.jpeg\",\"month_expense\":\"\",\"loan_cycle\":3,\"apply_num\":117,\"permit_fail\":0,\"online_jinjian\":0,\"other_fees\":{\"1\":[],\"2\":{\"low\":\"0.5\",\"normal\":\"0.65\",\"high\":\"0.65\"},\"4\":{\"low\":\"\",\"normal\":\"\",\"high\":\"\"}},\"guarantee_type\":{\"code\":2,\"name\":\"\\u65e0\\u62b5\\u62bc\"},\"real_loan_quota\":null,\"real_loan_term\":null,\"standard_type\":\"1\",\"month_rate\":\"0.65%\",\"loan_quota_fixed\":\"\",\"loan_quota_max\":\"500000\",\"loan_quota_min\":\"50000\",\"loan_quota_type\":\"1\",\"repayment_type\":{\"code\":1,\"name\":\"\\u5206\\u671f\\u8fd8\\u6b3e\"},\"str_id\":\"bf468105ihu5btu0\"},{\"product_name\":\"\\u5feb\\u4e50\\u6613\",\"org_name\":\"\\u534e\\u6da6\\u94f6\\u884c\",\"icon_url\":\"https:\\/\\/static.rong360.com\\/pimg\\/07\\/071f0a3c7d6d1fe45f173401306c54b079965e01.jpeg\",\"month_expense\":\"\",\"loan_cycle\":4,\"apply_num\":1266,\"permit_fail\":0,\"online_jinjian\":0,\"other_fees\":{\"1\":[],\"2\":{\"low\":\"0.5\",\"normal\":\"0.5\",\"high\":\"1\"},\"4\":{\"low\":\"\",\"normal\":\"\",\"high\":\"\"}},\"guarantee_type\":{\"code\":2,\"name\":\"\\u65e0\\u62b5\\u62bc\"},\"real_loan_quota\":null,\"real_loan_term\":null,\"standard_type\":\"1\",\"month_rate\":\"0.50%\",\"loan_quota_fixed\":\"\",\"loan_quota_max\":\"500000\",\"loan_quota_min\":\"50000\",\"loan_quota_type\":\"1\",\"repayment_type\":{\"code\":1,\"name\":\"\\u5206\\u671f\\u8fd8\\u6b3e\"},\"str_id\":\"bc122137ihngbbu0\"},{\"product_name\":\"\\u623f\\u4ea7\\u62b5\\u62bc\\u8d37\",\"org_name\":\"\\u534e\\u6da6\\u94f6\\u884c\",\"icon_url\":\"https:\\/\\/static.rong360.com\\/pimg\\/07\\/071f0a3c7d6d1fe45f173401306c54b079965e01.jpeg\",\"month_expense\":\"\",\"loan_cycle\":7,\"apply_num\":93,\"permit_fail\":0,\"online_jinjian\":0,\"other_fees\":{\"1\":[],\"2\":{\"low\":\"\",\"normal\":\"\",\"high\":\"\"},\"4\":{\"low\":\"\",\"normal\":\"\",\"high\":\"\"}},\"guarantee_type\":{\"code\":1,\"name\":\"\\u623f\\u5c4b\\u62b5\\u62bc\"},\"real_loan_quota\":null,\"real_loan_term\":null,\"standard_type\":\"1\",\"month_rate\":\"0.24%\",\"loan_quota_fixed\":\"\",\"loan_quota_max\":\"8000000\",\"loan_quota_min\":\"200000\",\"loan_quota_type\":\"1\",\"repayment_type\":{\"code\":1,\"name\":\"\\u5206\\u671f\\u8fd8\\u6b3e\"},\"str_id\":\"ad8df12dihihacog\"},{\"product_name\":\"\\u516c\\u79ef\\u91d1\\u8d37\",\"org_name\":\"\\u5e73\\u5b89\\u94f6\\u884c\",\"icon_url\":\"https:\\/\\/static.rong360.com\\/pimg\\/1f\\/1f98fb774d8a049b6c0cb2a09eb5bf24ba020bc8.jpeg\",\"month_expense\":\"\",\"loan_cycle\":3,\"apply_num\":941,\"permit_fail\":0,\"online_jinjian\":0,\"other_fees\":{\"1\":[],\"2\":{\"low\":\"0.6\",\"normal\":\"0.6\",\"high\":\"0.6\"},\"4\":{\"low\":\"\",\"normal\":\"\",\"high\":\"\"}},\"guarantee_type\":{\"code\":2,\"name\":\"\\u65e0\\u62b5\\u62bc\"},\"real_loan_quota\":null,\"real_loan_term\":null,\"standard_type\":\"1\",\"month_rate\":\"0.60%\",\"loan_quota_fixed\":\"\",\"loan_quota_max\":\"500000\",\"loan_quota_min\":\"50000\",\"loan_quota_type\":\"1\",\"repayment_type\":{\"code\":1,\"name\":\"\\u5206\\u671f\\u8fd8\\u6b3e\"},\"str_id\":\"1886e12dihn5tooq\"},{\"product_name\":\"\\u4e2a\\u4eba\\u6d88\\u8d39\\u8d37\",\"org_name\":\"\\u4e2d\\u56fd\\u94f6\\u884c\",\"icon_url\":\"https:\\/\\/static.rong360.com\\/pimg\\/7c\\/7cab596924e62a552ba07984cb8f00bfa031281d.jpeg\",\"month_expense\":\"\",\"loan_cycle\":5,\"apply_num\":168,\"permit_fail\":0,\"online_jinjian\":0,\"other_fees\":{\"1\":[],\"2\":{\"low\":\"\",\"normal\":\"\",\"high\":\"\"},\"4\":{\"low\":\"\",\"normal\":\"\",\"high\":\"\"}},\"guarantee_type\":{\"code\":2,\"name\":\"\\u65e0\\u62b5\\u62bc\"},\"real_loan_quota\":null,\"real_loan_term\":null,\"standard_type\":\"1\",\"month_rate\":\"0.32%\",\"loan_quota_fixed\":\"\",\"loan_quota_max\":\"500000\",\"loan_quota_min\":\"50000\",\"loan_quota_type\":\"1\",\"repayment_type\":{\"code\":1,\"name\":\"\\u5206\\u671f\\u8fd8\\u6b3e\"},\"str_id\":\"a780b124ihi0jib0\"},{\"product_name\":\"\\u516c\\u52a1\\u5458\\u65b9\\u6848\",\"org_name\":\"\\u5357\\u7ca4\\u94f6\\u884c\",\"icon_url\":\"https:\\/\\/static.rong360.com\\/pimg\\/1b\\/1b0124c629b5c50469ffa58fb920b80737402f1d.jpeg\",\"month_expense\":\"\",\"loan_cycle\":2,\"apply_num\":104,\"permit_fail\":0,\"online_jinjian\":0,\"other_fees\":{\"1\":[],\"2\":{\"low\":\"0.71\",\"normal\":\"0.77\",\"high\":\"0.77\"},\"4\":{\"low\":\"\",\"normal\":\"\",\"high\":\"\"}},\"guarantee_type\":{\"code\":2,\"name\":\"\\u65e0\\u62b5\\u62bc\"},\"real_loan_quota\":null,\"real_loan_term\":null,\"standard_type\":\"1\",\"month_rate\":\"0.77%\",\"loan_quota_fixed\":\"\",\"loan_quota_max\":\"500000\",\"loan_quota_min\":\"50000\",\"loan_quota_type\":\"1\",\"repayment_type\":{\"code\":1,\"name\":\"\\u5206\\u671f\\u8fd8\\u6b3e\"},\"str_id\":\"4d85b1bcihi8stnq\"},{\"product_name\":\"\\u516c\\u79ef\\u91d1\\u8d37\",\"org_name\":\"\\u5174\\u4e1a\\u94f6\\u884c\",\"icon_url\":\"https:\\/\\/static.rong360.com\\/pimg\\/5e\\/5e842102cb64fbf5422c0ff558243ac5907825d4.jpeg\",\"month_expense\":\"\",\"loan_cycle\":3,\"apply_num\":90,\"permit_fail\":0,\"online_jinjian\":0,\"other_fees\":{\"1\":[],\"2\":{\"low\":\"0.35\",\"normal\":\"0.35\",\"high\":\"0.35\"},\"4\":{\"low\":\"\",\"normal\":\"\",\"high\":\"\"}},\"guarantee_type\":{\"code\":2,\"name\":\"\\u65e0\\u62b5\\u62bc\"},\"real_loan_quota\":null,\"real_loan_term\":null,\"standard_type\":\"1\",\"month_rate\":\"0.35%\",\"loan_quota_fixed\":\"\",\"loan_quota_max\":\"500000\",\"loan_quota_min\":\"50000\",\"loan_quota_type\":\"1\",\"repayment_type\":{\"code\":1,\"name\":\"\\u5206\\u671f\\u8fd8\\u6b3e\"},\"str_id\":\"806cb178ihs8ac66\"},{\"product_name\":\"\\u4f18\\u826f\\u5de5\\u85aa\\u8d37\",\"org_name\":\"\\u519c\\u4e1a\\u94f6\\u884c\",\"icon_url\":\"https:\\/\\/static.rong360.com\\/pimg\\/3d\\/3d46eda17e9b506829eb93ef40c4d6f434661906.jpeg\",\"month_expense\":\"\",\"loan_cycle\":1,\"apply_num\":90,\"permit_fail\":0,\"online_jinjian\":0,\"other_fees\":{\"1\":[],\"2\":{\"low\":\"\",\"normal\":\"\",\"high\":\"\"},\"4\":{\"low\":\"\",\"normal\":\"\",\"high\":\"\"}},\"guarantee_type\":{\"code\":2,\"name\":\"\\u65e0\\u62b5\\u62bc\"},\"real_loan_quota\":null,\"real_loan_term\":null,\"standard_type\":\"1\",\"month_rate\":\"0.25%\",\"loan_quota_fixed\":\"\",\"loan_quota_max\":\"500000\",\"loan_quota_min\":\"50000\",\"loan_quota_type\":\"1\",\"repayment_type\":{\"code\":1,\"name\":\"\\u5206\\u671f\\u8fd8\\u6b3e\"},\"str_id\":\"ce694165ihs8zoiv\"},{\"product_name\":\"\\u516c\\u79ef\\u91d1\\u8d37\",\"org_name\":\"\\u4e2d\\u4fe1\\u94f6\\u884c\",\"icon_url\":\"https:\\/\\/static.rong360.com\\/pimg\\/69\\/69b61a88aa1ef4dc1d9dc83e25911863df4ad148.jpeg\",\"month_expense\":\"\",\"loan_cycle\":1,\"apply_num\":90,\"permit_fail\":0,\"online_jinjian\":0,\"other_fees\":{\"1\":[],\"2\":{\"low\":\"\",\"normal\":\"\",\"high\":\"\"},\"4\":{\"low\":\"\",\"normal\":\"\",\"high\":\"\"}},\"guarantee_type\":{\"code\":2,\"name\":\"\\u65e0\\u62b5\\u62bc\"},\"real_loan_quota\":null,\"real_loan_term\":null,\"standard_type\":\"1\",\"month_rate\":\"0.27%\",\"loan_quota_fixed\":\"\",\"loan_quota_max\":\"500000\",\"loan_quota_min\":\"50000\",\"loan_quota_type\":\"1\",\"repayment_type\":{\"code\":1,\"name\":\"\\u5206\\u671f\\u8fd8\\u6b3e\"},\"str_id\":\"0fdf01d0ihu1tni6\"},{\"product_name\":\"\\u5927\\u989d\\u5373\\u4eab\\u8d37\",\"org_name\":\"\\u5e7f\\u5dde\\u94f6\\u884c\",\"icon_url\":\"https:\\/\\/static.rong360.com\\/pimg\\/49\\/4960aed3c1c44ce03657256a39ce9356d86018bb.jpeg\",\"month_expense\":\"\",\"loan_cycle\":5,\"apply_num\":107,\"permit_fail\":0,\"online_jinjian\":0,\"other_fees\":{\"1\":[],\"2\":{\"low\":\"0.5\",\"normal\":\"0.65\",\"high\":\"0.65\"},\"4\":{\"low\":\"\",\"normal\":\"\",\"high\":\"\"}},\"guarantee_type\":{\"code\":2,\"name\":\"\\u65e0\\u62b5\\u62bc\"},\"real_loan_quota\":null,\"real_loan_term\":null,\"standard_type\":\"1\",\"month_rate\":\"0.65%\",\"loan_quota_fixed\":\"\",\"loan_quota_max\":\"500000\",\"loan_quota_min\":\"80000\",\"loan_quota_type\":\"1\",\"repayment_type\":{\"code\":1,\"name\":\"\\u5206\\u671f\\u8fd8\\u6b3e\"},\"str_id\":\"374561cdihi3sosv\"}],\"totalNum\":33},\"loan_entrance\":[{\"icon\":\"https:\\/\\/static.rong360.com\\/upload\\/office-workers.png\",\"name\":\"\\u4e0a\\u73ed\\u65cf\",\"type\":1},{\"icon\":\"https:\\/\\/static.rong360.com\\/upload\\/employed-person.png\",\"name\":\"\\u4e2a\\u4f53\\u6237\",\"type\":2},{\"icon\":\"https:\\/\\/static.rong360.com\\/upload\\/business-owners.png\",\"name\":\"\\u4f01\\u4e1a\\u4e3b\",\"type\":3},{\"icon\":\"https:\\/\\/static.rong360.com\\/upload\\/free-job.png\",\"name\":\"\\u81ea\\u7531\\u804c\\u4e1a\",\"type\":4},{\"icon\":\"https:\\/\\/static.rong360.com\\/upload\\/credit-loan.png\",\"name\":\"\\u4fe1\\u7528\\u8d37\",\"type\":5},{\"icon\":\"https:\\/\\/static.rong360.com\\/upload\\/mortgage-loan.png\",\"name\":\"\\u62b5\\u62bc\\u8d37\",\"type\":6},{\"icon\":\"https:\\/\\/static.rong360.com\\/upload\\/car-loan.png\",\"name\":\"\\u8f66\\u8d37\",\"type\":7},{\"icon\":\"https:\\/\\/static.rong360.com\\/upload\\/mortgage.png\",\"name\":\"\\u623f\\u8d37\",\"type\":8}],\"bank_loan_calculator\":{\"limit\":0,\"limit_unit\":\"\\u94f6\\u884c\\u8d37\\u6b3e\\u9884\\u4f30\\u989d\\u5ea6\\uff08\\u5143\\uff09\",\"limit_desc\":\"\\u6700\\u9ad830\\u4e07\",\"percent\":90,\"layout_type\":0,\"button_desc\":\"\\u53bb\\u62ff\\u94b1\",\"state\":1,\"piechart\":[],\"action_type\":\"r360scheme:\\/\\/newscheme?ios=RLApplicantQualificationViewController&android=com.rong360.loans.activity.LoanDerectTrainActivity\"},\"express_form\":{\"type\":2,\"title\":\"\\u8f93\\u5165\\u60a8\\u8981\\u7684\\u91d1\\u989d \\u4e00\\u952e\\u4e3a\\u60a8\\u63a8\\u8350\\uff08\\u5143\\uff09\",\"loan_limit\":\"\"}},\"status\":0,\"alert_type\":0,\"server_time\":1521078603,\"stamp\":1593580542,\"sec_level\":0}", "size":15846, "mimeType":"text/html; charset=UTF-8"}, "headers":[{"name":"Date", "value":"Thu, 15 Mar 2018 01:50:03 GMT"}, {"name":"Content-Type", "value":"text/html; charset=UTF-8"}, {"name":"Connection", "value":"keep-alive"}, {"name":"Vary", "value":"Accept-Encoding"}, {"name":"X-RONG-REQID", "value":"5aa9d14b0b03f00073b4000071"}, {"name":"Vary", "value":"Accept-Encoding"}, {"name":"Expires", "value":"Thu, 19 Nov 1981 08:52:00 GMT"}, {"name":"Cache-Control", "value":"no-store, no-cache, must-revalidate"}, {"name":"Pragma", "value":"no-cache"}, {"name":"X-Cache", "value":"bypass"}, {"name":"Content-Length", "value":"15846"}]}, "startedDateTime":"2018-03-15T09:50:04.3018758+08:00", "cache":{}}], "creator":{"name":"Fiddler", "comment":"https://fiddler2.com", "version":"5.0.20173.49666"}, "version":"1.2"}}

**Comment by gaoxiaomumu** [comment]
YAPI 目前并不支持HAV导入
