### ISSUE TITLE
设置>请求配置>Pre-request Script(请求参数处理脚本) 中，使用context.method无法获取到请求方法

### ISSUE THREAD

**Issue by xyuanzhi1983** [YMFE/yapi#186]
## 版本号
~ 

## 什么问题
设置>请求配置>Pre-request Script(请求参数处理脚本) 中，使用context.method无法获取到请求方法

## 如何复现此问题
在请求参数处理脚本的输入框中输入如下js代码：
var test = "";
for(var a in context) {
    test = test + "(" + a + "," + context[a] + ")";
}
context.requestHeader.Authorization = test;

然后请求，看到Authorization字段的为
Authorization:(pathname,/p/xxxxxx)(query,[object Object])(requestHeader,[object Object])(requestBody,[object Object])(utils,[object Object])
里面没有"method"字段，与yapi的文档不符

## 什么浏览器
Chrome

## 什么系统（linux, window, macox）
macox

**Comment by gaoxiaomumu** [comment]
测试了一下没有发现问题
![request](https://user-images.githubusercontent.com/21135585/37634879-5e5a3726-2c33-11e8-8857-5b3ed56f0d07.png)

**Comment by suxiaoxin** [comment]
@xyuanzhi1983 https://github.com/YMFE/yapi/issues/178 
method 已经添加，在下个版本发布
