### ISSUE TITLE
改进建议：希望与ydoc结合

### ISSUE THREAD

**Issue by jorycn** [YMFE/yapi#187]
对外接口，或者需要查看简洁接口时，只能导出给商务。
如果和ydoc结合，就完美了~

**Comment by gaoxiaomumu** [comment]
导出html不可以吗

**Comment by smilealgernon** [comment]
最近会遇到这样的场景：接口改动比较频繁，基本上每周需要给客户一份文档，做法是先导出Markdown文件，然后再用别的工具转为PDF。
如果能和ydoc结合，提供一个发布网址，yapi内有了改动，直接同步到ydoc，会方便不少
