### ISSUE TITLE
想了解下yapi的版本管理的开发进度

### ISSUE THREAD

**Issue by shenbinglife** [YMFE/yapi#190]
## 版本号
 v1.3.7
~ 

## 什么问题
我正在寻找API管理系统， 想了解下yapi的版本管理的开发进度，作为是否使用的参考，以及能否导出为swagger配置文件以便更方便的切换其他系统，谢谢。
~

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by suxiaoxin** [comment]
版本管理会极大的增加用户使用成本，还有就算提供了版本管理，是否一定能解决接口管理的问题，这都是未知的，所以暂不考虑开发此功能

**Comment by shenbinglife** [comment]
那么我想可以提供一个项目复制的功能吧？
