### ISSUE TITLE
关于mock数据的问题

### ISSUE THREAD

**Issue by ruixiu** [YMFE/yapi#193]
## 版本号
~ 1.3.7

## 什么问题
~mock的响应结果，预览时没有问题，修改Mock规则后，点击下图的mock地址mock数据为修改前的数据
![image](https://user-images.githubusercontent.com/9940354/37693581-983b4106-2cfb-11e8-88f2-dcd4c370b87a.png)

## 如何复现此问题
~ 参照“什么问题”中的描述

## 什么浏览器
~ chrome

## 什么系统（linux, window, macox）
macox

**Comment by ruixiu** [comment]
发现问题：添加了期望后，之后的修改均无效
另：返回数据是否可以增加设置响应头的功能

**Comment by gaoxiaomumu** [comment]
mock规则的优先级问题 https://yapi.ymfe.org/adv_mock.html
![image](https://user-images.githubusercontent.com/21135585/37696252-3a144aea-2d10-11e8-9db3-bd5873260f0f.png)，


设置响应头功能可以在
![image](https://user-images.githubusercontent.com/21135585/37696295-8663ac6a-2d10-11e8-94a3-82718f33f557.png)

**Comment by ruixiu** [comment]
需求是只对某个接口设置响应头，不是所有接口
