### ISSUE TITLE
建议在 接口列表 加上添加子分类

### ISSUE THREAD

**Issue by hlmd** [YMFE/yapi#1940]
## 版本号
~ 1.9.2

## 什么问题
~建议在接口列表 添加子分类 目前只有一级分类

## 如何复现此问题
~ 添加无限级分类

## 什么浏览器
~

**Comment by iacker** [comment]
附议！

**Comment by mac1023** [comment]
附议！一级分类，接口写多了太难找了！

**Comment by lengshanwlj** [comment]
附议

**Comment by yidaoxiuluo** [comment]
+1

**Comment by BruceAn1978** [comment]
同求该功能，一级分类导致列表太多了，显示和查找很不友好。

**Comment by BruceAn1978** [comment]
怎么没有个回复就直接关闭了？

是不加呢还是下个版本考虑加入这个功能呢？
