### ISSUE TITLE
贡献免费的环境

### ISSUE THREAD

**Issue by Corey-Wang** [YMFE/yapi#1947]
## 内心独白
~ YAPI这两年在百度落地为许多产品线带来了很好的接口管理体验，为回馈社区，从公司申请了计算和存储资源，搭建了YAPI体验环境，贡献给社区开发者们。

## 体验地址
[https://yapi.baidu.com/](https://yapi.baidu.com/)  _使用github登录_

## 环境说明
1、请大家合理使用YAPI，不要进行非正常活动（恶意刷接口、利用YAPI已知漏洞）
2、免费体验环境当前基于github 1.9.1版本，会提供长期服务，版本也会及时与社区对齐（内部版本改造较多不适合放出），MongoDB存储会按天备份，但暂时不提供额外的人工服务
3、针对免费体验环境，未来会增加单个账号的项目数量限制（20个？），单个项目的接口限制（500个？），可以再讨论，反正现在没加限制
4、阉割掉功能：服务端运行测试Case、定时导入Swagger

## 免责声明
1、此次贡献为个人行为，除百度智能云提供计算资源外，其他与公司无关

**Comment by ferhas** [comment]
登陆后，没有入口

**Comment by hellosean1025** [comment]
感谢，帮你放到首页

**Comment by hellosean1025** [comment]
@Corey-Wang github 登录不上

**Comment by Corey-Wang** [comment]
api.github.com经常抽风，下周搞百度账号登陆

**Comment by Corey-Wang** [comment]
api.github.com经常抽风，下周搞百度账号登陆

**Comment by rikan** [comment]
看到是用百度的子域名，吓了一条，以为被收了

**Comment by Corey-Wang** [comment]
> 看到是用百度的子域名，吓了一条，以为被收了

别激动，哈哈

**Comment by Ryan-Miao** [comment]
百度何时接管本项目啊，issue都破1k了

**Comment by China-Drummond** [comment]
登陆不上了 可以麻烦看一下吗 #2070

**Comment by congh** [comment]
求助大神
https://yapi.baidu.com/ 
这几天突然无法登录了，目前只奢求能给一次登录进去的机会我好把自己的文档导出来就可以。万谢，跪谢。

**Comment by Corey-Wang** [comment]
> 求助大神
> https://yapi.baidu.com/
> 这几天突然无法登录了，目前只奢求能给一次登录进去的机会我好把自己的文档导出来就可以。万谢，跪谢。

还不行？加我QQ： 314465434

**Comment by Corey-Wang** [comment]
> 登陆不上了 可以麻烦看一下吗 #2070
> @Corey-Wang 谢谢🙏

![image](https://user-images.githubusercontent.com/1393365/106560861-b0107100-6562-11eb-90e9-0997ba33d2ca.png)

**Comment by Corey-Wang** [comment]
> 登陆不上了 可以麻烦看一下吗 #2070
> @Corey-Wang 谢谢🙏

还不行？加我QQ： 314465434

**Comment by Corey-Wang** [comment]
> 百度何时接管本项目啊，issue都破1k了

不会接管，都是开源的。

**Comment by congh** [comment]
> > 求助大神
> > https://yapi.baidu.com/
> > 这几天突然无法登录了，目前只奢求能给一次登录进去的机会我好把自己的文档导出来就可以。万谢，跪谢。
> 
> 还不行？加我QQ： 314465434

已解决，感谢Corey-Wang老师

**Comment by China-Drummond** [comment]
已经可以了 非常感谢🙏

**Comment by zhangdonghaicn** [comment]
https://yapi.baidu.com/  登陆不上了，文档都没导出来，大佬帮解决一下呗。

**Comment by Corey-Wang** [comment]
由于使用百度域名引起大家误解，故将域名切换到个人域名下。新域名为： http://yapi.smart-xwork.cn 

加入微信群沟通： 关注公众号「代码研习社」，回复yapi，扫码入群。
