### ISSUE TITLE
导 入POSTMAN目录结构有误

### ISSUE THREAD

**Issue by mahaixue** [YMFE/yapi#195]
## 版本号
~ 
1.3.7
## 什么问题
参照图示
postman结构
![postman](https://user-images.githubusercontent.com/34730549/37747183-eff242c4-2db8-11e8-8c5f-2c2021862078.png)

导入结构
![default](https://user-images.githubusercontent.com/34730549/37747195-f9b20a74-2db8-11e8-90ef-0b334a65d0b3.png)
导入文件
QQ 120134242  联系

~

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by mahaixue** [comment]
[haha2.0.postman_collection.txt](https://github.com/YMFE/yapi/files/1835868/haha2.0.postman_collection.txt)

**Comment by gaoxiaomumu** [comment]
bug已经修复，感谢提问

**Comment by qunfm** [comment]
mac 10.13.4 (17E199) 导入postman的数据 在接口列表看到的顺序是乱的，然后手动调整后再导入测试集合顺序又乱了
