### ISSUE TITLE
导入postman的没有带入测试数据的问题

### ISSUE THREAD

**Issue by mahaixue** [YMFE/yapi#196]
## 版本号
1.3.7

## 什么问题
有些接口在POSTMAN的测试数据没有导入。
测试了有些接口是可以导入数据的。
![yapi-1](https://user-images.githubusercontent.com/34730549/37748633-8c1330cc-2dbf-11e8-9329-03d7dce5d59d.png)
![postman-1](https://user-images.githubusercontent.com/34730549/37748635-8e12ad12-2dbf-11e8-8f13-3886680255db.png)
[GUIDE.postman_collection.txt](https://github.com/YMFE/yapi/files/1835926/GUIDE.postman_collection.txt)

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by gaoxiaomumu** [comment]
该bug已修复
