### ISSUE TITLE
关于导入POSTMAN环境域名BUG及建议

### ISSUE THREAD

**Issue by mahaixue** [YMFE/yapi#197]
## 版本号
1.3.7

## 什么问题
1、POSTMAN的URL请求带有域名或者IP的。能自动新增一条环境配置。那么就不需要每条案例都去修改，现在每条都要去改，挺麻烦 的
譬如下面的URL能生成guide.wtoip.com这个域名环境
参考"url": "http://guide.wtoip.com/guide/candidateWord/saveCandidateWord",
2、对于URL的域名是参数的，应能识别,不作为接口路径，现在是当成接口路径，见图。（有时间的话可以支持POSTMAN环境导入，附带了POSTMAN的环境导出信息，在导入数据前可以先导入环境

，
[local.postman_environment.txt](https://github.com/YMFE/yapi/files/1835940/local.postman_environment.txt)
）
"url": "{{order-admin.hosts}}/api/subOrderDetail/getSubOrderInfo",

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by mahaixue** [comment]
![a](https://user-images.githubusercontent.com/34730549/37749034-fb4cd7bc-2dc0-11e8-94c1-ebf819faaadb.png)

**Comment by gaoxiaomumu** [comment]
bug已经修复
