### ISSUE TITLE
swagger数据导入到yapi后，不显示请求参数

### ISSUE THREAD

**Issue by pencilso** [YMFE/yapi#1977]
## 版本号
~ 1.9.2

## 什么问题
~

## 如何复现此问题
~ 导入swagger

## 什么浏览器
~ 谷歌

## 什么系统（Linux, Windows, macOS）
windows

Java代码如下：
```java
    @ApiOperation("用户登录接口")
    @ApiImplicitParams({
            @ApiImplicitParam(paramType = "from", name = "userName", value = "用户名", required = true, dataType = "String"),
            @ApiImplicitParam(paramType = "from", name = "password", value = "密码", required = true, dataType = "String"),
    })
    @PostMapping("/user_login")
```
显示效果如下：
![QQ截图20201105145522](https://user-images.githubusercontent.com/16483654/98207652-f57acd80-1f76-11eb-82bf-e9f74051d12d.png)

**Comment by zwjzxh520** [comment]
+1，我这也出现这这样的情况。swagger3.0

**Comment by Xmas118** [comment]
我也遇到了, 我swagger2.0

**Comment by pencilso** [comment]
`    @ApiImplicitParams({
            @ApiImplicitParam(paramType = "form", name = "userName", value = "用户名", required = true, dataType = "String"),
            @ApiImplicitParam(paramType = "form", name = "password", value = "密码", required = true, dataType = "String"),
    })`
我后来解决了，是因为paramType写错了，应该写form，我之前写的是from

**Comment by 1143571084** [comment]
@ApiImplicitParam 可以显示    @ApiModel和@ApiModelProperty不行，这是什么情况
