### ISSUE TITLE
[error] componentWillMount is deprecated since React 16.9.0

### ISSUE THREAD

**Issue by lizy0329** [YMFE/yapi#1979]
## 版本号
~ 1.9.2

## 什么问题
~npm run dev 后 疯狂报错，

> ~/my-yapi/vendors/client/components/TimeLine/TimeLine.js
  113:3  error  componentWillMount is deprecated since React 16.9.0, use UNSAFE_componentWillMount instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillmount. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components  react/no-deprecated

## 如何复现此问题
~ 

## 什么浏览器
~ chrome

## 什么系统（Linux, Windows, macOS）
ubuntu 20

**Comment by oubeichen** [comment]
你好，我也遇到了 react 的问题，请问怎么解决？

**Comment by zz215** [comment]
我也遇到了 react 的问题，请问怎么解决？
