### ISSUE TITLE
请求参数头中的空格问题

### ISSUE THREAD

**Issue by dumingxin** [YMFE/yapi#199]
## 版本号
~ 1.3.7

## 什么问题
~{{ Bearer  | concat : $.11.body.data.token}}
token是上一个接口返回的，在下次请求头需要携带。Bearer作为一个常量和token进行字符串拼接，在Bearer和token之间有一个空格，现在会被过滤掉，不知道怎么才能加上

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by suxiaoxin** [comment]
Bearer | concat : " $.11.body.data.token"

**Comment by suxiaoxin** [comment]
用引号包起来

**Comment by dumingxin** [comment]
感谢已经解决了
