### ISSUE TITLE
本地调试执行dev-client报错

### ISSUE THREAD

**Issue by ziok2010** [YMFE/yapi#2]
![image](https://user-images.githubusercontent.com/5848256/31374816-0d650b14-add2-11e7-9f07-a94ebebff477.png)

系统win7 node 7.9.0

**Comment by suxiaoxin** [comment]
@ziok2010 安装ykit 没有？没有请 npm install -g ykit下
还有调试请执行 npm run dev,可以同时运行后端和前端

**Comment by ziok2010** [comment]
@suxiaoxin  安装了   我run dev的话  server正常启动  client没反应  单独在执行client 就报上面的错

**Comment by suxiaoxin** [comment]
@ziok2010 没有linux虚拟机吗？开发最好用linux 或者 mac

**Comment by suxiaoxin** [comment]
@ziok2010 还有你这个报错为什么会弹出一个alert,不应该是在命令行下报错吗？

**Comment by suxiaoxin** [comment]
根据错误提示，你在 ykit.js 30行把 ";"  加上试试

**Comment by ziok2010** [comment]
@suxiaoxin 我也奇怪  命令行就一些npm-log 看不出具体的错误信息   
已经试过了不行  但是我奇怪的地方是yapi-cli部署同样的ykit文件 没有任何报错

**Comment by suxiaoxin** [comment]
yapi-cli 部署没有经过ykit编译，直接从github下载编译好的文件
我当时也是考虑到 经过ykit编译，可能会出问题，才这么干的

**Comment by suxiaoxin** [comment]
http://blog.csdn.net/wangjingjing1014/article/details/22413307
可以参考下

**Comment by ziok2010** [comment]
@suxiaoxin 定位到问题了， 把源码根目录下的ykit.js文件命名改一下就正常了
