### ISSUE TITLE
编辑页面报错

### ISSUE THREAD

**Issue by qiqizjl** [YMFE/yapi#200]
## 版本号
~ 
1.3.7
## 什么问题
~
Mixed Content: The page at 'https://yapi.xxx.com/project/18/interface/api/14' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://yapi.xxx.com/api/interface/solve_conflict?id=14'. This request has been blocked; this endpoint must be available over WSS.

## 如何复现此问题
~ 
使用HTTPS 且使用编辑接口页面
## 什么浏览器
~ 
Chrome
## 什么系统（linux, window, macox）
MacOSX

**Comment by gaoxiaomumu** [comment]
这个错误的原因是yapi部署成https以后webSocket启动不成功，如果不影响实际操作可以继续使用

**Comment by qiqizjl** [comment]
但是我是在nginx层上转发的 转发到node层其实已经是http了 一般不会在node上上https。所以这个其实可以是支持wss的
