### ISSUE TITLE
YApi v1.3.8 版本发布，强烈建议大家更新

### ISSUE THREAD

**Issue by suxiaoxin** [YMFE/yapi#201]
#### Feature

* 新增 json 结构可视化编辑器
* pre-script 增加 method 字段数据

#### Bug Fixed

* 点击编辑 tab 可能导致运行功能异常
* 修复postman导入没有分类的问题
* 修复postman参数导入缺失

**Comment by suxiaoxin** [comment]
新功能：
![](https://user-images.githubusercontent.com/17695103/37759027-4d4c8e46-2ded-11e8-818d-82899131fdf7.png)

**Comment by pickleqin** [comment]
使用可视化编辑怎么配置mock。之前可以直接在json字段中设置。现在在字段中设置也可以生效但是可视化中字段名称也带了mock配置

**Comment by suxiaoxin** [comment]
会根据 json-schema 数据结构生成随机数据的
如果想生成 email,mobile,ip 等数据，请在高级设置修改 format 选项

**Comment by xuliuzhu1834** [comment]
![image](https://user-images.githubusercontent.com/8508762/37942749-3d40c928-31a7-11e8-8b32-2802f562cab8.png)
如上图
`data` 其本身是必须字段,但是由于内部对象没有必须字段导致返回没有data字段的数据
希望这种情况可以返回其本身的字段类型,比如这种情况可以返回 `data:[]`

**Comment by xuliuzhu1834** [comment]
![image](https://user-images.githubusercontent.com/8508762/37942881-de07a372-31a7-11e8-8c53-87ce9455814d.png)
![image](https://user-images.githubusercontent.com/8508762/37942895-e9b0abc4-31a7-11e8-8aec-622eae105501.png)
如图 修改父节点的字段名,折叠框会被自动折叠,这个是不是可以优化下,保持原先的状态不变?
ru

**Comment by suxiaoxin** [comment]
https://yapi.ymfe.org/mock.html
json-schema 生成随机数据可参考该文档

**Comment by suxiaoxin** [comment]
@xuliuzhu1834 感谢反馈，后续会优化的

**Comment by jiangchao0304** [comment]
这个赞 一直是想要的功能,完美~团队辛苦了!

**Comment by pickleqin** [comment]
长时间不操作，进程就自动退出了。用的是 mongodb 3.6.3.

**Comment by FoolRabbit** [comment]
字符串能否支持长度设置
数值能否提供精度设置
这样就更完美了

**Comment by jszjgqq** [comment]
@FoolRabbit 可以实现字符串的长度,以及数值的精度   里面有个正则的

比如数值的正则控制 [1-9]\.[0-9]{2}     前提要选择string的

**Comment by shubiao-yao** [comment]
@jszjgqq  我觉得你说的很对，赞👍
