### ISSUE TITLE
配置的header 不生效

### ISSUE THREAD

**Issue by QiuMing** [YMFE/yapi#202]
## 版本号
1.3.7 

## 什么问题
自定义header 不生效，用了浏览器的header，如下图
![image](https://user-images.githubusercontent.com/11348698/37958947-6db8d626-31e4-11e8-9de3-6d1edfbd4885.png)

## 如何复现此问题
~ 

## 什么浏览器
chrome

## 什么系统（linux, window, macox）
win7

**Comment by gaoxiaomumu** [comment]
请安装最新版本的cross-request
