### ISSUE TITLE
接口管理平台所有响应是json的接口都返回[Object Object]

### ISSUE THREAD

**Issue by dora-pan** [YMFE/yapi#2020]
## 版本号
~ 

## 什么问题
~
接口管理平台所有响应是json的接口都返回[Object Object]
## 如何复现此问题
~ 
新建一个响应是json的接口，postman或者浏览器测试，均返回[Object Object]
## 什么浏览器
~ 
Chrome
## 什么系统（Linux, Windows, macOS）
Windows

**Comment by dora-pan** [comment]
https://yapi.baidu.com/

**Comment by mingo0117** [comment]
+1. 俺也一样

> https://yapi.baidu.com/

**Comment by themoonstone** [comment]
+1 https://yapi.baidu.com/

**Comment by xiebl** [comment]
碰到了一样的问题，使用的是官方在线环境。

**Comment by XansamLin** [comment]
一样的问题，也是官方在线环境。

**Comment by jason5149** [comment]
这个问题什么时候能解决一下

**Comment by zhouzhuo810** [comment]
确实，https://yapi.baidu.com/mock/41550/v2/pet/findByStatus，是配置问题么？

**Comment by snice** [comment]
彻底没人管了？

**Comment by waf2311** [comment]
+1

**Comment by SimpleDrunk** [comment]
+1 yapi没人管吗 求替代方案

**Comment by SimpleDrunk** [comment]
+1

**Comment by Corey-Wang** [comment]
已经修复啦。刚发现反馈。后边我整个群吧。
