### ISSUE TITLE
关于环境配置、请求配置的疑问

### ISSUE THREAD

**Issue by ansonhorse** [YMFE/yapi#204]
你好，首先很感谢能分享yapi这样好用而有潜力的工具！

我有这么一个需求，就是在请求登录接口，返回成功登录的信息后，想让授权信息全局可用（比如access token）。暂时没有发现yapi有类似环境变量的概念，就是类似Postman那样的，设置一个环境变量，比如`accessToken=xxx`，然后在接口请求参数值里，把参数accessToken的值设置为`{{accessToken}}`，这个参数值会在发送请求前被替换。

暂时用以下图中的方式实现了这一需求。
<img width="1117" alt="qq20180328-153554 2x" src="https://user-images.githubusercontent.com/7548142/38015265-d99e5884-329d-11e8-8fd1-753a4a2fe0d2.png">

**Comment by suxiaoxin** [comment]
建议设置一个自定义 header，然后把 header 数据传给 query

**Comment by suxiaoxin** [comment]
还有一点，既然你们能把 access_token 存到 localStorge，为什么不直接把 access_token 保存到一个变量

var token = '...'

query.token = token

**Comment by ansonhorse** [comment]
@suxiaoxin 谢谢。
自定义header这个想法应该也是可以的。
下面你说的保存到一个变量，这里不太明白，是在Pre-response Script里定义变量，然后在Pre-request Script里调用这个变量？

**Comment by avasping** [comment]
> 你好，首先很感谢能分享yapi这样好用而有潜力的工具！
> 
> 我有这么一个需求，就是在请求登录接口，返回成功登录的信息后，想让授权信息全局可用（比如access token）。暂时没有发现yapi有类似环境变量的概念，就是类似Postman那样的，设置一个环境变量，比如`accessToken=xxx`，然后在接口请求参数值里，把参数accessToken的值设置为`{{accessToken}}`，这个参数值会在发送请求前被替换。
> 
> 暂时用以下图中的方式实现了这一需求。
> <img alt="qq20180328-153554 2x" width="1117" src="https://user-images.githubusercontent.com/7548142/38015265-d99e5884-329d-11e8-8fd1-753a4a2fe0d2.png">

1.8.0 版本, 该 js 编写有冲突错误
Pre-request Script(请求参数处理脚本):
- **context 设置根据情况是设置在 headers 里面还是设置在 query 里面, 一下例子是直接设置 header 的key 为Authorization的值**

- **localStorage.getItem('_token') 从浏览器缓存中取值, _token 是自己设定的变量名**

`
if (context.requestHeader['Authorization'] !== undefined) {
    context.requestHeader['Authorization'] = `token ${localStorage.getItem('_token')}`;
}
`
Pre-response Script(响应数据处理脚本):

- **判断条件中路径根据自己具体登录地址情况, 来获取 token,并保存在浏览器缓存中**

- **建议不要在判断外层使用 res 变量, 推测与 yapi 的处理返回值的 js 脚本变量名冲突**

`
if (201 == context.responseHeader.status && (/\/sms\/login\/$/).test(context.pathname)) {
    localStorage.setItem('_token', JSON.parse(context.responseData).access_token);
}
`
