### ISSUE TITLE
本地执行ykit s -p 4000编译报错

### ISSUE THREAD

**Issue by jayZOU** [YMFE/yapi#205]
## 版本号
node: v7.10.0
npm: v4.2.0
mongo: v3.6.2
## 什么问题
想在本地跑下客户端代码，改一些视图，但是无法编译通过，本地开发的话是有系统版本的限制么？
![image](https://user-images.githubusercontent.com/8576977/38016960-4ace6ad0-32a3-11e8-8110-2774209ff555.png)

## 如何复现此问题
`npm run dev`

## 什么系统（linux, window, macox）
window

**Comment by suxiaoxin** [comment]
开发环境不支持 window，请使用 linux, mac
