### ISSUE TITLE
https://yapi.baidu.com 无法登陆了，有人可以帮忙解决一下吗

### ISSUE THREAD

**Issue by China-Drummond** [YMFE/yapi#2070]
## 版本号
~ NA

## 什么问题
~ 无法登陆 https://yapi.baidu.com

## 如何复现此问题
~ https://yapi.baidu.com GitHub或者百度Pass登陆

## 什么浏览器
~ Chrome

## 什么系统（Linux, Windows, macOS）
MacOS

**Comment by elegentFrog** [comment]
我这边也是没法登陆，win10 chrome

**Comment by jieke17weiju** [comment]
我也是的，昨天下午开始就不能登陆了

**Comment by yh4922** [comment]
我也是 登不上去

**Comment by isCoding** [comment]
登陆不上去, 我让朋友也试了一下, 同样登陆不上去
同windows10, chrome版本 87.0.4280.66（正式版本） （64 位）
百度账号登陆方式

**Comment by ikgade** [comment]
火狐谷歌、清缓存都尝试了，但授权后就是登录不了，一直跳转首页，付费加Q群也加不了，裂开

**Comment by legend9999** [comment]
同上不去，试了各种，百度，github都不可以

**Comment by songyuzhen** [comment]
我也是各种方式都试过了，付费加Q 都是NAN元，我giao，我还编辑在线文档呢

**Comment by congh** [comment]
https://yapi.baidu.com/ 无法登录了，目前只奢求能给一次登录进去的机会我好把自己的文档导出来就可以。万谢，跪谢。

**Comment by songyuzhen** [comment]
> https://yapi.baidu.com/ 无法登录了，目前只奢求能给一次登录进去的机会我好把自己的文档导出来就可以。万谢，跪谢。

哈哈，我也想，文档都在上面呢，现在项目都停止了

**Comment by Linshengwei1983** [comment]
百度，你个孙子，能不能给我一次机会进去导出JSON

**Comment by songyuzhen** [comment]
> 百度，你个孙子，能不能给我一次机会进去导出JSON

我文档直接重写了

**Comment by changwei-zhang** [comment]
坑啊

**Comment by star7th** [comment]
此环境应该是百度员工贡献的，我建议你们可以尝试直接邮件联系他，他github主页有联系方式 https://github.com/Corey-Wang  

另外我自荐下另一个会长期维护的api管理平台  https://github.com/YMFE/yapi/issues/2097

**Comment by congh** [comment]
> 此环境应该是百度员工贡献的，我建议你们可以尝试直接邮件联系他，他github主页有联系方式 https://github.com/Corey-Wang
> 
> 另外我自荐下另一个会长期维护的api管理平台 #2097

邮件早就发过了，没人回应。大家主要是想导出历史数据，至于平台倒是不愁，大不了自己部署一套那是最靠谱的。问题就是数据。数据。数据。

**Comment by congh** [comment]
> > https://yapi.baidu.com/ 无法登录了，目前只奢求能给一次登录进去的机会我好把自己的文档导出来就可以。万谢，跪谢。
> 
> 哈哈，我也想，文档都在上面呢，现在项目都停止了

别怪我没告诉你哈。赶紧登录吧。

**Comment by congh** [comment]
> 百度，你个孙子，能不能给我一次机会进去导出JSON

别怪我没告诉你哈。赶紧登录吧。

**Comment by China-Drummond** [comment]
已经解决，谢谢@Corey-Wang
