### ISSUE TITLE
无法登陆！！！

### ISSUE THREAD

**Issue by jieke17weiju** [YMFE/yapi#2071]
## 版本号
~ 
19.1
## 什么问题
~登陆失败

## 如何复现此问题
~ Git登陆无反应，登陆成功也被重定向到登录界面

## 什么浏览器
~ chrome

## 什么系统（Linux, Windows, macOS）
Windows

**Comment by songyuzhen** [comment]
我也遇到了这个问题

**Comment by ccquan** [comment]
me too

**Comment by zurmokeeper** [comment]
有报错信息吗？

**Comment by ccquan** [comment]
没有呀，GitHub授权、百度Pass授权都不行，都是授权后就卡在首页

**Comment by songyuzhen** [comment]
> 有报错信息吗?

没有报错，只是重定向到了首页

**Comment by isCoding** [comment]
> 有报错信息吗？

没有报错信息, 是从yapi.baidu.com登陆, github 百度pass两种登陆方式都会重跳回yapi.baidu.com

**Comment by lu-zhishen** [comment]
同样无法登录了, 什么时候能解决呢?

**Comment by CXX19901120** [comment]
同样无法登录了, 什么时候能解决呢?

**Comment by songyuzhen** [comment]
> 同样无法登录了, 什么时候能解决呢?

应该@作者，哈哈

**Comment by congh** [comment]
https://yapi.baidu.com/ 无法登录了，目前只奢求能给一次登录进去的机会我好把自己的文档导出来就可以。万谢，跪谢。

**Comment by gaozijian55555** [comment]
我这两天也遇到这个问题了，一直登录不上，直接跳首页。。。  之前都是好的

**Comment by gaozijian55555** [comment]
好想知道 有什么办法能导出文档。。  登录不进去

**Comment by jieke17weiju** [comment]
> 好想知道 有什么办法能导出文档。。 登录不进去
> 
> group/61427 ， 如果可以，发我邮箱吧，[gaozijian3680@163.com](mailto:gaozijian3680@163.com) 感谢 @hellosean1025
可以登录了呀，你现在去试试
