### ISSUE TITLE
请问Yapi的/interface/save完整接口文档

### ISSUE THREAD

**Issue by MenciusCheng** [YMFE/yapi#2086]
## 版本号
v1.8.5

## 什么问题
请问Yapi的/interface/save完整接口文档是什么？我只能通过看代码大概猜测请求接口的参数，请问哪里可以看到这个接口的完全请求参数是什么？

**Comment by changzhiwin** [comment]
1，新建一个接口，看下网络请求内容
2，看源码

**Comment by MenciusCheng** [comment]
> 1，新建一个接口，看下网络请求内容
> 2，看源码

1. 查询接口拿到的信息，并不代表创建接口也是传这些
2. 源码没有一个结构体定义，我就是看源码大致知道哪些字段，但是希望可以有一个详细准确的接口文档。

PS：一个接口文档的项目，写的接口文档那么不完善吗？

**Comment by changzhiwin** [comment]
你具体是要做什么？我是按照官网文档+看代码使用了save接口的，见https://github.com/changzhiwin/yapi-plugin-import-rap2

**Comment by MenciusCheng** [comment]
> 你具体是要做什么？我是按照官网文档+看代码使用了save接口的，见https://github.com/changzhiwin/yapi-plugin-import-rap2

好的，我只是想知道官方有没有提供完整的接口文档，没有的话就算了，谢谢。
