### ISSUE TITLE
【自荐】如果yapi已放弃维护了的话，可否自荐下另一个api管理平台

### ISSUE THREAD

**Issue by star7th** [YMFE/yapi#2097]
我在另一个 issue里 https://github.com/YMFE/yapi/issues/2092 看到项目原作者回应说yapi放弃维护了。所以在这里能否自荐下另一个api管理平台？如果是继续维护，我就避免利益相关，不发了。

ShowDoc是一个非常适合IT团队的在线API文档、技术文档工具，既有开箱即用的在线托管服务版，也有免费的开源版。通过showdoc，你可以方便地使用markdown语法来书写出美观的API文档、数据字典文档、技术文档、在线excel文档等等。如果不想编辑markdown文档，你还可以利用showdoc的自动化能力，从程序注释中自动生成API文档，或者从搭配的RunApi客户端（类似postman的api调试工具）中一边调试接口、一边自动生成文档。通过分配项目成员和团队成员，你可以很方便地进行项目文档的权限管理和团队协作，也可以分享文档出去给朋友查看。ShowDoc还支持多平台客户端，有win客户端、mac客户端、ios、android等，更方便跨平台使用。目前超过100000+的互联网团队正在使用showdoc，包括知名公司内部的一些团队，比如腾讯、华为、百度、京东、字节跳动等等。

showdoc官网访问地址：https://www.showdoc.com.cn  开源版地址 https://github.com/star7th/showdoc

**Comment by sinpor** [comment]
有计划增加mock吗

**Comment by star7th** [comment]
@sinpor 已经有基础的mock功能。目前根据情况来看使用mock的用户比例不高，所以尚未往深的方向去做。你可以使用下看是否满足需求。使用方式 1 ：在showdoc编辑页面的时候会看到mock按钮。2，runapi客户端调试接口的返回内容的判断有mock按钮

**Comment by sinpor** [comment]
谢谢：）
我们的团队比较小，前后端同步开发的时候只有一份接口文档，前端需要自己写mock规则，之前用easy-mock又不能跟接口文档同步，所以想找一个编辑完文档就能自动生成mock的平台。

**Comment by 5201314999** [comment]
> 我在另一个 issue里 #2092 看到项目原作者回应说yapi放弃维护了。所以在这里能否自荐下另一个api管理平台？如果是继续维护，我就避免利益相关，不发了。
> 
> ShowDoc是一个非常适合IT团队的在线API文档、技术文档工具，既有开箱即用的在线托管服务版，也有免费的开源版。通过showdoc，你可以方便地使用markdown语法来书写出美观的API文档、数据字典文档、技术文档、在线excel文档等等。如果不想编辑markdown文档，你还可以利用showdoc的自动化能力，从程序注释中自动生成API文档，或者从搭配的RunApi客户端（类似postman的api调试工具）中一边调试接口、一边自动生成文档。通过分配项目成员和团队成员，你可以很方便地进行项目文档的权限管理和团队协作，也可以分享文档出去给朋友查看。ShowDoc还支持多平台客户端，有win客户端、mac客户端、ios、android等，更方便跨平台使用。目前超过100000+的互联网团队正在使用showdoc，包括知名公司内部的一些团队，比如腾讯、华为、百度、京东、字节跳动等等。
> 
> showdoc官网访问地址：https://www.showdoc.com.cn 开源版地址 https://github.com/star7th/showdoc

我们上一个系统就是使用showdoc ，结果开发得很烂。 每个需求都是一个单独的项目。没有分组导致 一个很大的方块列表。。确定这个好用，我就是想重新处理才找上yapi的。。

**Comment by star7th** [comment]
@5201314999 showdoc支持无限层级目录，单个项目其实是可以放不少内容的。不建议一个需求就一个单独项目。你可以考虑一个相关的需求就一个目录这种机制。另外，项目分组的功能其实也在考虑中了。一直没做是因为不想给那些“项目没那么多”的人带来额外的视觉空间多余。

**Comment by xmsz** [comment]
你这东西有点烂，为什么不直接改YApi，或者抄Postman，在或者至少和EasyDoc一样？

**Comment by star7th** [comment]
> 你这东西有点烂，为什么不直接改YApi，或者抄Postman，在或者至少和EasyDoc一样？

我感觉你应该没有看完整showdoc的功能，比如说搭配使用的runapi客户端 就是一个类似postman的工具，可以调试接口同时自动生成文档到showdoc网页端。 https://www.showdoc.com.cn/runapi?page_id=30291 
其实在这里发帖，我是意料到会遇到一些产品理念不合的人。因为理念跟我合的人都已经是showdoc用户了，你到showdoc的github项目下也能看到很多issue友好讨论。这里毕竟是另一个使用习惯不太一样的产品，自然会存在很多跟showdoc理念不合的人。我觉得讨论产品时候应该就事论事，showdoc也没说过自身是完美的产品，有什么产品缺点指出来就好。单凭空下结论说烂，个人觉得这并不是一个友好的讨论。

**Comment by xmsz** [comment]
@star7th 

我的话很偏激

大概有几个看法

- 不懂你说的理念不同是什么
是说最终产物是以文档形式
还是使用的时候，把调试和文档分开？

只是个简简单单的Api接口文档工具而已，市面上各种类型的都有，对于开发者来说没必要
从团队角度，要的是稳定功能完善的产品
个人角度就是随便无所谓，找个有免费/安装简单/最好有客户端/写起来方便（反正就自己或者几个人看，没必要那么复杂）

我比较好奇的ShowDoc用户真正的看法是什么？或者用户群体的分析情况。
对我自己来说，我很难找到使用ShowDoc的理由，你可以继续相信这仅是我个人的看法



- 我看了一下issue的内容，感觉就是个客服中心
这一点其实和作者有关系，就是你互动得越多，越放纵。那大家积极性肯定越高，但这不能说明这个产品很好，而且提建议的人，也说明产品很不完善

当然 有issue是正常得，但是还是看内容。最多只能说明作者你很用心在经营而已



- 缺少团队背书
这些工具型产品至少要有知名的团队背书最好，国内的rap2 yapi都有背书。
其他工具基本都是个人背书，例如某个10年经验的程序员说这玩意我用了3年了，我不想改你们都跟我一样用他就行了。

（当然不是说有团队背书的产品就更好，但能至少说明可靠稳定）


- 技术/产品/设计都不行
先放一张图

![image](https://user-images.githubusercontent.com/5879146/106712942-a7886b00-6634-11eb-90b5-df6162a642f4.png)

我就打开2个文档，直接把我电脑跑炸了...

其实作为工具型产品这个倒无所谓，毕竟国内的大家都丑都难用。而且ShowDoc应该也是只有一个主要成员在维护。能实现功能就很好了

但如果技术/产品/交互/设计哪个方面做的好其实就是个壁垒

### 总而言之
确实作为我个人来说，ShowDoc不太适合我

**Comment by star7th** [comment]
@xmsz 
回应下：
1，showdoc的理念是以文档编辑为核心，不提供直接接口调试。这个习惯有些人是不习惯的，他们不想编写markdown文档。这点是我上面说的产品理念不合的意思。然后，showdoc对接口调试这类需求的解决方案是提供额外的runapi客户端。但有些人不习惯再下载一个客户端。这个是主管的想法，每个人的理念不一样。
2，关于issue的问题，好像不算是一个问题，略过回应吧
3，缺少团队背书，在你眼里也许是个缺点，但在某些人的眼里是优点。其实我还在腾讯上班的时候，也有机会让showdoc挂到腾讯开源上，成为公司运营项目。但最终没有这么做。因为，我知道我早晚会从腾讯离职（现在也确认离职了），我不确保后任团队能否像我一样继续维护下去。现在yapi项目停止维护，也是因为原作者离职了。这是公司开源项目面临的共性问题——在原作者离职后，会不会继续维护，完全看公司以及所在团队愿不愿意出人力去支持开源这件可能不会有太多回报的公益事件上。因为做开源很多时候并不能为公司为团队带来更多的kpi和盈利，所以有团队选择继续，有团队选择放弃。
4，你截图的这个资源占用是已知问题。是 mac 版谷歌浏览器有些扩展不兼容 showdoc 所用的前端框架。你可以关闭扩展试试，比如用无痕模式试试。

**Comment by star7th** [comment]
@xmsz 再补充一下，回应你说的“技术/产品/交互/设计不行”。这块你可以提出你的想法，
对于合理的建议，我都会非常虚心接受用户反馈。
性能的问题我回应了，这是浏览器扩展的兼容性问题，由于showdoc换不了前端框架，所以这事我比较难去兼容它们。只能跟小部分用户说清楚情况。
你可以说showdoc有很大改善空间，但你说它不行的话，那么，可能showdoc用户会有些不认同。虽然showdoc用户可能没有yapi多，但使用率是yapi的一半是肯定有的。也有不少用户从yapi迁移过来，邮件里跟我说showdoc更简单易用易部署，心智负担低。这个见仁见智吧，我觉得yapi有它的很多优点。这点留给用户去评价。但可以肯定的一点是，至少有一部分人是认可showdoc的，不会认为showdoc“不行”。

**Comment by xmsz** [comment]
@star7th 你说的观点和角度没有问题我也都赞同

但我还是站在我角度说我的观点

### ShowDoc 以文档为核心
这个确实太奇妙，这为何能替代word文档或者各大协作平台的文档工具？
以文档为核心
一类是像ApiDoc这类，由其他工具自动生成的文档工具。面向是不想写文档的用户
一类是像语雀这种，本身是文档工具，但是拿来写接口也没问题。面向的是喜欢写文档的用户

而ShowDoc就像这中间的产物，即提供在线编辑的ApiDoc，又或者是低配版的语雀。那面向的用户群体就很令人好奇。这点也是我很想知道的，ShowDoc的用户群体是什么样的。（本身是产品，所以很好奇）

然后最神奇的是，Api调试工具功能居然不是重点？这就产生了其他的疑问
- 是用户真的可以不用吗？
- 是用户自己选择的不用吗？
用Api调试工具生成接口的人群占比是多少？如果10个人里8个人都下载了Api调试工具，那是不是意味者以文档为核心是『伪核心』



### 主观看法
我都是主观站在自己角度提出质疑，而我希望的是用数据来反驳我。
最简单的就是说明一下用户群体，可以让我大致了解一些产品的属性


### 产品背书
产品背书的目的并不是来说这个项目一定很厉害。
前面也说了，
- 比个人项目来说死亡率应该更低一些
- 技术保障相对高一些
- 最重要，是在真实业务上跑过的
- 迭代期间已经到达一定阶段并非半成品

作为团队选型这些都是很关键的因素

而小团队或者个人的项目成功率实在太低，也不可能消耗时间成本去等待

而ShowDoc即没有背书，又是一个人在维护。这就又回到第一个问题，ShowDoc的用户群体到底是什么样的。


### 开源
开源要分开来说
- 对于有开发能力的团队，开源的好处是可以定制开发
- 对于个人来说，开源的好处意味着免费

所以并不是一定要强迫别人开源免费用，像我们自己团队选择Rap2和YApi就是我们需要自己去定制一些功能。

开源还有另一个好处，如果是小团队或者个人项目可以有更多的贡献者。所以这取决于你站在哪一方的角度

### 性能问题
这个有点夸张了，我很少听到因为浏览器导致Web应用CPU爆的。
还有我的环境
- 普通Mac电脑
- 正式版Chrome
- 安装几个极度常见插件
这样环境不能说很多，但是也至少是不需要考虑到兼容的情况
还有框架，Vue?React? 都不应该

（10分钟给我耗掉60%的电量，比微信开发者工具还猛）

### 产品/交互/设计
这个在我眼里确实连及格线都不到，或者说效果等同于0。

而且我也说过这类产品这些都不重要，只是如果做得好也可能是条好路子，例如ApiFox就是好例子。


### 总结
ShowDoc确实不适合我，我站在我的角度确实不喜欢ShowDoc，所以我表达了我的观点

**Comment by star7th** [comment]
@xmsz 

你能理性赞同我的观点就行，我就希望能有这样详细的解释而不是一味说产品烂。至于后面的更多疑惑，我就不一一回应了，你不是showdoc的目标用户，我是说服不了你使用showdoc的，不如让你去选择合适你自己的。在稳定性方面，我只能说，showdoc维护五年了，有一个一直稳定可用的官网在线服务，并且开源持续更新，github上的所有issue都能得到回复。这期间我见过不少类似的产品从诞生到停止维护，我并不觉得它们比showdoc更稳定。
我觉得过度关注别人容易让自己的产品失去方向，所以我可能暂时不关注这里了，不如关心怎么提高产品去满足那些真正的忠实目标用户。做产品就是要这样子的，先从自己忠实圈子开始，做好自己的群体，然后才是扩展。不能为了满足所有人而丢失了自己的初始用户。只是说你提出的这些想法，可以作为我后续产品思考的启发，怎么扩展到更多用户。满足更多不同群体的需求。
你如果对showdoc有更多想法，可以去showdoc的github 提issue。如果你只是好奇showdoc的用户群体是哪些，这个我也不好展开。你可以调查下吧。毕竟showdoc存在五年了，在网上总有一些讨论记录，你去搜索引擎搜索下或者去技术论坛跟人了解下也行。showdoc不是最好的，但肯定是有一定亮点的。
在这里的讨论就先到此为止吧。

**Comment by JaneYork** [comment]
> 我在另一个 issue里 #2092 看到项目原作者回应说yapi放弃维护了。所以在这里能否自荐下另一个api管理平台？如果是继续维护，我就避免利益相关，不发了。
> 
> ShowDoc是一个非常适合IT团队的在线API文档、技术文档工具，既有开箱即用的在线托管服务版，也有免费的开源版。通过showdoc，你可以方便地使用markdown语法来书写出美观的API文档、数据字典文档、技术文档、在线excel文档等等。如果不想编辑markdown文档，你还可以利用showdoc的自动化能力，从程序注释中自动生成API文档，或者从搭配的RunApi客户端（类似postman的api调试工具）中一边调试接口、一边自动生成文档。通过分配项目成员和团队成员，你可以很方便地进行项目文档的权限管理和团队协作，也可以分享文档出去给朋友查看。ShowDoc还支持多平台客户端，有win客户端、mac客户端、ios、android等，更方便跨平台使用。目前超过100000+的互联网团队正在使用showdoc，包括知名公司内部的一些团队，比如腾讯、华为、百度、京东、字节跳动等等。
> 
> showdoc官网访问地址：https://www.showdoc.com.cn 开源版地址 https://github.com/star7th/showdoc

issue里并没有官方人员说放弃维护啊？哪里说了？

**Comment by star7th** [comment]
@JaneYork 原作者说了。后来又删除了。至于为什么，不知道。可能他想着自己已经离开公司离开项目，说这话不太合适，维护不维护，由接任团队自己决定更合适。

**Comment by yangtianfu01** [comment]
> 我在另一个 issue里 #2092 看到项目原作者回应说yapi放弃维护了。所以在这里能否自荐下另一个api管理平台？如果是继续维护，我就避免利益相关，不发了。
> 
> ShowDoc是一个非常适合IT团队的在线API文档、技术文档工具，既有开箱即用的在线托管服务版，也有免费的开源版。通过showdoc，你可以方便地使用markdown语法来书写出美观的API文档、数据字典文档、技术文档、在线excel文档等等。如果不想编辑markdown文档，你还可以利用showdoc的自动化能力，从程序注释中自动生成API文档，或者从搭配的RunApi客户端（类似postman的api调试工具）中一边调试接口、一边自动生成文档。通过分配项目成员和团队成员，你可以很方便地进行项目文档的权限管理和团队协作，也可以分享文档出去给朋友查看。ShowDoc还支持多平台客户端，有win客户端、mac客户端、ios、android等，更方便跨平台使用。目前超过100000+的互联网团队正在使用showdoc，包括知名公司内部的一些团队，比如腾讯、华为、百度、京东、字节跳动等等。
> 
> showdoc官网访问地址：https://www.showdoc.com.cn 开源版地址 https://github.com/star7th/showdoc

和Yapi比起来ShowDoc的优势并不明显. 我在20人团队推过ShowDoc, 并且用了一年, 最后改用了Yapi. 

**弃用原因**
* 当项目增多时, ShowDoc管理项目是平铺的, 没有树形结构好管理
* 除了第一批成员按规范写文档(准确, 可用)外, 新来的人既要学习Markdow, 又要学习前后端接口书写规范, 学习成本高, 培训成本高
* 当第一批成员离职, 没有人愿意去接手别人的文档(后续迁移文档还得手动(辛酸泪)~收费也贵)
* Mock功能不完善, 每次看ShowDoc文档, 都得配合PostMan才能解决问题
* 无法接入持续集成体系

**更换Yapi后**
Yapi解决了持续集成问题, 也能够在代码中通过写swagger注解的方式自动生成文档, 通过自动化部署后, 同步到线上, 一键做完. 后续人员离职也不影响接口文档的维护, 新人来只需要复制注解就行了, 啥都不用关心. 另外自带的Mock功能, 能够在测试和生产自动切换, 做到更快的迭代. 我没有理由去用ShowDoc

**Comment by star7th** [comment]
@yangtianfu01 

这个issue关闭了本不想再讨论，不过既然你很认真地讨论，我也认真回复下。
showdoc一年来完善了很多东西，你拿一年前的版本来比较是会有缺陷的。
针对你说的弃用原因，我一一回复下：
1，”ShowDoc管理项目是平铺的, 没有树形结构好管理“——其实我有在计划启用项目分组功能。这个一直不做是因为不想影响那么不需要此功能的人的简洁。我需要从设计上找到一种平衡。
2，你用runapi（一个类似postman的客户端，跟showdoc集成，一年前的showdoc版本可能还没有这个客户端出现）来生产文档的话是不需要成员去学习markdown语法的 https://www.showdoc.com.cn/runapi?page_id=30291 
3 , 不愿意接手的问题跟前一个问题类似，降低学习成本和培训成本即可。
4，现在已经有了mock功能（一年前的版本没有）,支持mockjs语法。
5, showdoc也可以通过写代码注释来生产文档，接入持续集成体系。 https://www.showdoc.com.cn/page/741656402509783  https://www.showdoc.com.cn/page/102098 
目前比较明显的缺陷是还无法做到自动化测试。这块后面再努力吧。
