### ISSUE TITLE
平辈接口拖拽无法修改顺序

### ISSUE THREAD

**Issue by naifen00** [YMFE/yapi#21]
貌似现在同一级别的接口，只有拖拽的动效，并没有实际去修改顺序，望修复，谢谢。

**Comment by suxiaoxin** [comment]
https://yapi.ymfe.org/case.html

看下这个文档的拖动 git 图片，就在 测试列表那

**Comment by naifen00** [comment]
@suxiaoxin 我是指的接口列表，左边的菜单部分

**Comment by suxiaoxin** [comment]
@naifen00 下周一上线的版本可以在左侧菜单移动了
