### ISSUE TITLE
Pre-response Script  设置无效

### ISSUE THREAD

**Issue by jinhui-su** [YMFE/yapi#210]
## 版本号
~ 1.3.8

## 什么问题
~ 自动生成的mock接口访问跨域，想通过改响应header解决，但是设置里面 Pre-response Script(响应数据处理脚本) 配置无效，例如：context.responseHeader.aa = "43"; 在响应头里面就没有此数据

## 如何复现此问题
~ 设置里面 配置 响应预处理脚本（context.responseHeader.aa = "43";或者其他任何header）看响应头里面是否生效，

## 什么浏览器
~ chrome

## 什么系统（linux, window, macox）
~ macox

## 备注
~ 脚本参考的此链接 https://segmentfault.com/a/1190000012599503，如有误请指正，谢谢

**Comment by suxiaoxin** [comment]
Pre-response Script  是用来做自动化测试的，跟 mock 没有任何关系
mock 访问有跨域问题请配置服务器代理

https://yapi.ymfe.org/mock.html#2.3_%E5%9F%BA%E4%BA%8E_ykit_Jerry_%E4%BB%A3%E7%90%86
