### ISSUE TITLE
求推荐牛逼的，鼻尖Yapi的文档管理系统

### ISSUE THREAD

**Issue by Ryan-Miao** [YMFE/yapi#2101]
我就是不想写word，写markdown，写confluence都不愿意。我就想代码生成。swagger很牛逼。
Yapi导入swagger是我的最爱。

现在Yapi停止维护了，大家谁有类似的工具可以推荐下。

我目前的解决方案是用knife4j.  比swagger看起来舒服些，但解决不了离线等问题。

**Comment by shuxiaokai3** [comment]
我写了个开源的接口文档管理工具，但是还是需要手动录入，直接导入swagger生成文档对于个人开发感觉是个不错的方案。项目还在探索阶段如果你感兴趣可以去体验一下
https://github.com/trueleaf/moyu.git

**Comment by susky** [comment]
@shuxiaokai3 尝试了一下好像不能发起本地请求，不知道是我操作不对还是什么问题

**Comment by shuxiaokai3** [comment]
> @shuxiaokai3 尝试了一下好像不能发起本地请求，不知道是我操作不对还是什么问题
需要在electron环境使用，https://gitee.com/shuzhikai/moyu/attach_files/573739/download/Setup.0.1.3.exe

**Comment by gwsh** [comment]
本地部署可以满足你的需求，缺点：后续的bug需要自己修复，因为本项目已经进入了停止维护阶段
