### ISSUE TITLE
部署后,编辑接口,运行请求时,请求异常，请检查 chrome network 错误信息..

### ISSUE THREAD

**Issue by fairyly** [YMFE/yapi#212]
## 版本号
~ 版本： 1.3.8

## 什么问题
~本地部署后,编辑接口,运行请求时,请求异常，请检查 chrome network 错误信息..

## 如何复现此问题
~ 接口运行时

## 什么浏览器
~ Google

## 什么系统（linux, window, macox）
--windows7

**Comment by suxiaoxin** [comment]
![image](https://user-images.githubusercontent.com/17695103/38192775-2b7b09d4-36a1-11e8-8b0f-c89bccbd0df6.png)
打开 chrome 调试工具，查看 console 和 network
