### ISSUE TITLE
1.3.8版本 本地部署后，具体某个项目里面没有成员管理，项目没法让其他用户协作修

### ISSUE THREAD

**Issue by chelsh** [YMFE/yapi#213]
## 版本号
~ 1.3.8

## 什么问题
~本地部署后，具体某个项目里面没有成员管理，项目没法让其他用户协作修改

## 如何复现此问题
~ 

## 什么浏览器
~ chrome

## 什么系统（linux, window, macox）
mac

**Comment by chelsh** [comment]
MongoDB 版本: 3.2.14

**Comment by suxiaoxin** [comment]
不是个人空间的项目吧，成员管理只有在分组新建的项目才有

**Comment by chelsh** [comment]
对的 搞错了，建在个人空间了。

**Comment by lifang218c** [comment]
我也是 搞错了。。一脸懵逼。。还好看到了大家的讨论。。应该先新建分组。。。然后再分组下面 新建项目。。 原来作者是这个意思啊
