### ISSUE TITLE
如何给api添加版本功能呢

### ISSUE THREAD

**Issue by Abirdcfly** [YMFE/yapi#2132]
## 版本号
1.9.2

## 什么问题
如何给api添加版本功能呢？某个api可能只在某些版本存在过。基于历史原因需要保留这个api的格式记录方便查找。

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by daoying007** [comment]
加微信群交流互助吧，加我微信好友（备注yapi），拉你进yapi微信群吧
![1](https://user-images.githubusercontent.com/39725475/111907650-43f5b800-8a91-11eb-917a-15ae55e111a4.jpg)
