### ISSUE TITLE
过滤未完成接口显示问题

### ISSUE THREAD

**Issue by bellchet58** [YMFE/yapi#214]
## 版本号
1.3.9

## 什么问题
接口列表中选未完成的，显示过滤结果不在第一页
## 如何复现此问题
在有两页长度的接口中，在第二页有一条状态为未完成的接口。过滤勾选未完成后，结果显示有两页，并且第一页无结果，未完成的接口在第二列。
![image](https://user-images.githubusercontent.com/7368054/38284529-4f66b7f0-37ee-11e8-8b9a-0b86eb927a92.png)
![image](https://user-images.githubusercontent.com/7368054/38284530-5553cc3e-37ee-11e8-99ed-956514dcc22e.png)

## 什么浏览器
chrome

## 什么系统（linux, window, macox）
window

**Comment by suxiaoxin** [comment]
已收集
