### ISSUE TITLE
自动同步接口状态:成功,合并模式:智能合并,更多信息:数据格式出错，请检查

### ISSUE THREAD

**Issue by qdhaiqiang** [YMFE/yapi#2141]
## 版本号
~ 1.8.0

## 什么问题
~ 配置swagger自动同步，动态中显示【自动同步接口状态:成功,合并模式:智能合并,更多信息:数据格式出错，请检查】
三种合并模式选择任何一种都是这个错误

如果选择导入数据的话，填写swagger.json地址就没有问题

## 如何复现此问题
~ 需要同步的swagger地址：

## 什么浏览器
~ 谷歌浏览器

## 什么系统（Linux, Windows, macOS）
服务部署在Linux系统
网页在MacOS上访问

**Comment by daoying007** [comment]
加微信群交流互助吧，加我微信好友（备注yapi），拉你进yapi微信群吧


![1](https://user-images.githubusercontent.com/39725475/111907456-5de2cb00-8a90-11eb-8ade-bb234f2f44e9.jpg)

**Comment by ulyyyyyy** [comment]
xd，暴露信息了，swagger 接口数据有 小程序的 openId & 个人信息

**Comment by HHH1994** [comment]
关闭时因为已经解决了吗？

**Comment by qdhaiqiang** [comment]
现在已经不知道了，可以先关闭了，以后碰到了问题再说吧
