### ISSUE TITLE
yapi开放api中能否提供单个接口的获取？

### ISSUE THREAD

**Issue by wolcengit** [YMFE/yapi#2166]
## 版本号
~ 

## 什么问题
~

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by Corey-Wang** [comment]
参考OpenAPI文档  --> 获取接口数据（有详细接口数据定义文档）

加入微信群：关注公众号「代码研习社」，点「我要入群」 获取群二维码（由于二维码有有效期，就不放在github上了）
