### ISSUE TITLE
我通过Iframe引用yapi  登录成功以后页面不显示数据

### ISSUE THREAD

**Issue by sionguo** [YMFE/yapi#2168]
## 版本号
~ 1.9.2

## 什么问题
~ 我通过Iframe引用yapi  登录成功以后页面不显示数据

## 如何复现此问题
~ 通过Iframe引用yapi 

## 什么浏览器
~ chrome

## 什么系统（Linux, Windows, macOS）
windows

**Comment by EchoShoot** [comment]
这是因为跨域的问题，在Chrome 80版本起，Chrome会将没有声明SameSite值的cookie默认设置为SameSite=Lax。只有在启用 HTTPS 的情况下，采用SameSite=None; Secure设置的cookie可以从外部访问。

**Comment by EchoShoot** [comment]
> 这是因为跨域的问题，在Chrome 80版本起，Chrome会将没有声明SameSite值的cookie默认设置为SameSite=Lax。只有在启用 HTTPS 的情况下，采用SameSite=None; Secure设置的cookie可以从外部访问。

用 iframe 嵌套，确保目标网站的IP与 iframe的IP一致，就解决了跨域问题，比如 nginx 把YAPI的地址代理映射到 123.123.123.123:8080 然后 iframe 中 src=http://123.123.123.123:8080 然后把 iframe 网页也部署到 http://123.123.123.123:80 虽然端口不同，但是 cookie 可以共享，就没有问题。
