### ISSUE TITLE
swagger3导入yapi，返回值显示不正确

### ISSUE THREAD

**Issue by xushujin** [YMFE/yapi#2179]
## 版本号
1.9.2 

## 什么问题
使用数据导入或者定时同步方式导入swagger3的文档，返回值全部是OK字符串，没有取到真正的返回值数据
![图片](https://user-images.githubusercontent.com/5311716/115957909-b5fd6900-a537-11eb-8fb0-3eceea0d435d.png)

## 如何复现此问题
将swagger3的文档导入就能看到

## 什么浏览器
火狐浏览器

## 什么系统（Linux, Windows, macOS）
Ubuntu20.04

**Comment by xushujin** [comment]
希望能修复下～

**Comment by xushujin** [comment]
swagger文档调整content-type类型就好了

**Comment by shenshb808** [comment]
> swagger文档调整content-type类型就好了

你好，可以给一下调整代码吗？

**Comment by hero-zhanghao** [comment]
@xushujin 我也有这个问题，请问下怎么修复的

**Comment by yetao-git** [comment]
[ssss](https://github.com/YMFE/yapi/issues/2179#issuecomment-855542695)

请问如何解决的有详情教程吗
