### ISSUE TITLE
返回参数 data 应当是 object 类型

### ISSUE THREAD

**Issue by uni1421** [YMFE/yapi#2181]
## 版本号
~ https://yapi.baidu.com/ 1.9.1
自建版本：1.9.2

## 什么问题
~
![image](https://user-images.githubusercontent.com/37495490/116389006-084bcc00-a84f-11eb-982a-53e5351cde0a.png)

![image](https://user-images.githubusercontent.com/37495490/116389183-40530f00-a84f-11eb-90ab-ebee87407e97.png)

## 如何复现此问题
~ 

## 什么浏览器
~ Google Chrome

## 什么系统（Linux, Windows, macOS）
Windows 10

**Comment by uni1421** [comment]
Google Chrome 90.0.4430.93

**Comment by joey998** [comment]
![image](https://user-images.githubusercontent.com/30948534/117617126-acfad180-b19e-11eb-9cf0-973c05416717.png)
前缀地址需要自己配置修改

**Comment by uni1421** [comment]
已解决 谢谢
