### ISSUE TITLE
【Bug】当前分组名名称无法修改 ?

### ISSUE THREAD

**Issue by liyanlong** [YMFE/yapi#22]
yapi 版本： 1.2.3 

我尝试修改了分组名, 但刷新页面后 分组名依然为 **"个人空间"**

![timline 20171106153128](https://user-images.githubusercontent.com/8005864/32429961-eeaa08b4-c307-11e7-9141-522b05ee088f.png)

**Comment by suxiaoxin** [comment]
个人空间每个人都有，无法修改
