### ISSUE TITLE
Json 格式多层字符串嵌套(Body),POST 接口时高级期望功能无法匹配对应的期望返回值.

### ISSUE THREAD

**Issue by quzhixue-Kimi** [YMFE/yapi#2202]
## 版本号
1.9.2

## 什么问题
有如下的一个 json 格式的 body ,我在高级 mock 中添加期望的时候,发现无法根据 messageType 的值获取到对应的返回值数据!
{
  "request": {
    "body": {
      "getSampleMessage": {
        "messageType": "25"
      }
    }
  }
}

## 如何复现此问题
新建POST API接口, 输入参数选择json 类型. 填上以下信息
{
  "request": {
    "body": {
      "getSampleMessage": {
        "messageType": "25"
      }
    }
  }
}

输出参数(作为测试)格式如下:

{
   "id": 1,
  "message": "whatisup?"
}

 mock 高级期望 当 messageType="25"的时候,返回{"id":1,"message":"whatisup?"}
当 messageType="26",返回{"id":2,"message":"hi,man"}

PS:当我把body 改成2层嵌套的 json(格式如下)
{
  "request": {
    "body": "25"
  }
} 就可以匹配上对应的期望结果.

## 什么浏览器
~ 
Chrome 91.0.4472.77

## 什么系统（Linux, Windows, macOS）
MacBook & Windows

BR
Kimi

**Comment by tuihou123321** [comment]
这个问题我也遇到了，可能得自己改源码了
