### ISSUE TITLE
自动化测试断言提示assert.equal is not a function

### ISSUE THREAD

**Issue by lidalifan** [YMFE/yapi#2234]
## 版本号
~ 1.9.2

## 什么问题
~自动化测试断言提示assert.equal is not a function

## 如何复现此问题
~ 1.9.2版本

## 什么浏览器
~ chrome

## 什么系统（Linux, Windows, macOS）
macOS

**Comment by luanweijie** [comment]
bug不能执行，恢复原来代码可以了
`// result = await sandboxFn(context, script);
      result = yapi.commons.sandbox(context, script);`

**Comment by fish982000** [comment]
出现同样问题，怎么解决的

**Comment by Ybbbb** [comment]
我也出现同样问题，怎么解决啊

**Comment by xiaoquan35** [comment]
> bug不能执行，恢复原来代码可以了 `// result = await sandboxFn(context, script); result = yapi.commons.sandbox(context, script);`

补充一下具体路径及修改文件，在/my-yapi/vendors/server/utils下commons.js
![image](https://user-images.githubusercontent.com/7692616/144205588-dc6914e7-dbbf-4a19-b00c-eddcb9d6b2aa.png)
//result = await sandboxFn(context, script);
result = yapi.commons.sandbox(context, script);
修改完后重启服务
node vendors/server/app.js

**Comment by tiyunchen** [comment]
https://mdnice.com/writing/c1a82b5817934d2fad3dbf8aaae93aee

**Comment by tiyunchen** [comment]
https://github.com/Houfeng/safeify/issues/13#issuecomment-530627299
