### ISSUE TITLE
yapi-vendor@1.9.2 install-server 报错

### ISSUE THREAD

**Issue by Leo-July** [YMFE/yapi#2244]
## 版本号
npm 6.14.11
node 14.16.0

## 什么问题
Error: /root/my-yapi/vendors/server/utils/commons.js:25 jsf.extend('mock', function () { ^ TypeError: jsf.extend is not a function at Object.<anonymous> (/root/my-yapi/vendors/server/utils/commons.js:25:5) at Module._compile (internal/modules/cjs/loader.js:1063:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) at Module.load (internal/modules/cjs/loader.js:928:32) at Function.Module._load (internal/modules/cjs/loader.js:769:14) at Module.require (internal/modules/cjs/loader.js:952:19) at require (internal/modules/cjs/helpers.js:88:18) at Object.<anonymous> (/root/my-yapi/vendors/server/install.js:3:17) at Module._compile (internal/modules/cjs/loader.js:1063:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) at Module.load (internal/modules/cjs/loader.js:928:32) at Function.Module._load (internal/modules/cjs/loader.js:769:14) at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) at internal/main/run_main_module.js:17:47

## 什么系统
Linux

**Comment by singapore2020** [comment]
json-schema-faker最新版本被废弃了，换个版本就行。
cd my-yapi/vendors
npm uninstall json-schema-faker
npm install json-schema-faker@0.5.0-rc16
npm run install-server

**Comment by FinleyFeng0606** [comment]
> ## 版本号
> npm 6.14.11
> node 14.16.0
> 
> ## 什么问题
> Error: /root/my-yapi/vendors/server/utils/commons.js:25 jsf.extend('mock', function () { ^ TypeError: jsf.extend is not a function at Object. (/root/my-yapi/vendors/server/utils/commons.js:25:5) at Module._compile (internal/modules/cjs/loader.js:1063:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) at Module.load (internal/modules/cjs/loader.js:928:32) at Function.Module._load (internal/modules/cjs/loader.js:769:14) at Module.require (internal/modules/cjs/loader.js:952:19) at require (internal/modules/cjs/helpers.js:88:18) at Object. (/root/my-yapi/vendors/server/install.js:3:17) at Module._compile (internal/modules/cjs/loader.js:1063:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) at Module.load (internal/modules/cjs/loader.js:928:32) at Function.Module._load (internal/modules/cjs/loader.js:769:14) at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) at internal/main/run_main_module.js:17:47
> 
> ## 什么系统
> Linux



> ## 版本号
> npm 6.14.11
> node 14.16.0
> 
> ## 什么问题
> Error: /root/my-yapi/vendors/server/utils/commons.js:25 jsf.extend('mock', function () { ^ TypeError: jsf.extend is not a function at Object. (/root/my-yapi/vendors/server/utils/commons.js:25:5) at Module._compile (internal/modules/cjs/loader.js:1063:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) at Module.load (internal/modules/cjs/loader.js:928:32) at Function.Module._load (internal/modules/cjs/loader.js:769:14) at Module.require (internal/modules/cjs/loader.js:952:19) at require (internal/modules/cjs/helpers.js:88:18) at Object. (/root/my-yapi/vendors/server/install.js:3:17) at Module._compile (internal/modules/cjs/loader.js:1063:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) at Module.load (internal/modules/cjs/loader.js:928:32) at Function.Module._load (internal/modules/cjs/loader.js:769:14) at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) at internal/main/run_main_module.js:17:47
> 
> ## 什么系统
> Linux
你好 我也是这个问题 请问你怎么解决的 

nodejs 是 12.20
npm 是 6.14.8

**Comment by Leo-July** [comment]
1、cd my-yapi/vendors
2、把 "json-schema-faker":"^0.5.0-rc16" 改为 "json-schema-faker":"0.5.0-rc16"
3、删除 package-lock.json 和 node_modules
4、npm install 
5、npm run install-server

**Comment by Leo-July** [comment]
1、cd my-yapi/vendors
2、把 "json-schema-faker":"^0.5.0-rc16" 改为 "json-schema-faker":"0.5.0-rc16"
3、删除 package-lock.json 和 node_modules
4、npm install 
5、npm run install-server
已解决

**Comment by Leo-July** [comment]
> json-schema-faker最新版本被废弃了，换个版本就行。
> cd my-yapi/vendors
> npm uninstall json-schema-faker
> npm install json-schema-faker@0.5.0-rc16
> npm run install-server

用命令 报错，直接手动改的版本，已解决 谢谢
