### ISSUE TITLE
哪位维护者来 Release 一个 “v1.9.3” 的版本？现在的 tag 开头没加v，yapi-cli server 都不能装 1.9.3

### ISSUE THREAD

**Issue by naiba** [YMFE/yapi#2254]
哪位维护者来 Release 一个 ”v1.9.3“ 的版本？现在的 tag 开头没加v，yapi-cli server 都不能装 1.9.3

**Comment by aweleey** [comment]
done

**Comment by wake-lee** [comment]
怎么解决的呀

**Comment by aweleey** [comment]
打了一个 v1.9.3 的tag啊

--------------原始邮件--------------
发件人："wake-lee ***@***.***&gt;;
发送时间：2021年7月13日(星期二) 上午9:53
收件人："YMFE/yapi" ***@***.***&gt;;
抄送："aweleey ***@***.***&gt;;"State change ***@***.***&gt;;
主题：Re: [YMFE/yapi] 哪位维护者来 Release 一个 “v1.9.3” 的版本？现在的 tag 开头没加v，yapi-cli server 都不能装 1.9.3 (#2254)
-----------------------------------

 

 
怎么解决的呀

**Comment by naiba** [comment]
build-client 任务目前会失败，等有人解决吧

**Comment by wake-lee** [comment]
@aweleey yapi update -v v1.9.3这个命令升级成功后，web页面上显示的版本号是v1.9.1

**Comment by hexiaohei1024** [comment]
用 YApi Pro（ https://github.com/yapi-pro/yapi ）提供的 yapi-pro-cli，即可升级。

    npm install -g yapi-pro-cli --registry https://registry.npm.taobao.org
    yapi update
