### ISSUE TITLE
YAPI 0days漏洞，发现服务器代码占满了

### ISSUE THREAD

**Issue by zdhsoft** [YMFE/yapi#2263]
## 版本号
~ 

## 什么问题
~

## 如何复现此问题
~ 
<img width="519" alt="企业微信截图_16262470172537" src="https://user-images.githubusercontent.com/2012484/125782352-c839400c-bd5b-4e3a-936b-92316ec81b7c.png">

## 什么浏览器
~

**Comment by hexiaohei1024** [comment]
用 YApi Pro（ https://github.com/yapi-pro/yapi ）提供的 yapi-pro-cli，升级到最新版解决。

    npm install -g yapi-pro-cli --registry https://registry.npm.taobao.org
    yapi update

**Comment by SilvaQ** [comment]
今天被这个漏洞中招了，这两天服务300%负载，已排查发现有人挖矿了

**Comment by SilvaQ** [comment]
我们服务器中的挖矿程序情况如图，望对你们也有所帮助：
1. 挖矿程序会存放在/root/c3pool目录中，主要挖矿进程是xmrig.  占用CPU 挖矿的进程就是xmrig
2. 
![image](https://user-images.githubusercontent.com/46706370/126118860-c50da154-68ea-4204-b7e2-f1dd9c3d8c5d.png)
3. 
![image](https://user-images.githubusercontent.com/46706370/126118911-502d2727-ee37-4722-b0bd-9bf923cfd877.png)

**Comment by liub1934** [comment]
top看下进程，发现有个xmrig的进程占用贼高，kill -9 PID杀掉还有，就是说这个玩意的进程杀了又会自动有，可以top看下PID进程号，`cd /proc/PID`，进入到进程的目录，`ll`看下，找到`exe`对应的目录删除，然后将进程kill掉，重新看下应该cpu就降下来了
![image](https://user-images.githubusercontent.com/29849550/126616272-a52ae47e-e542-47ec-a189-ba0a8832e67c.png)
