### ISSUE TITLE
总是有无关用户注册

### ISSUE THREAD

**Issue by yun-li** [YMFE/yapi#2266]
如下图所示，经常会有这些未知来源的用户注册，我之前删除过一次，现在又来了，请问有人遇到过这种问题么？该怎么防止这些无关用户注册呢？这些似乎是有人用自动化脚本注册的，注册的目的是什么呢？会有什么危害么？

![image](https://user-images.githubusercontent.com/12177190/126027281-825bb922-460c-4bb6-b935-3296fee696e8.png)

## 版本号
~ 1.9.1

## 什么问题
~ 总是为有无关用户注册

## 如何复现此问题
~  

## 什么浏览器
~ Chrome

**Comment by tangcent** [comment]
很危险!!!

ref: https://github.com/YMFE/yapi/issues?q=is%3Aissue+is%3Aopen+%E6%BC%8F%E6%B4%9E
当你看到这条回复，请尽快做如下处理。

1. 关闭注册功能或阻止公网访问
2. 可能的话，升级yapi到最新
3. 建议提升mongo安全性，包括不限于: 修改端口，强制用户名密码登录
