### ISSUE TITLE
不能在容器中使用高级mock脚本功能

### ISSUE THREAD

**Issue by yyr03gy** [YMFE/yapi#2267]
## 版本号
~ 1.9.3+

## 什么问题
在docker容器中运行，当使用高级mock脚本时会报如下错误
error: [Error: EROFS: read-only file system, mkdir '/sys/fs/cgroup/cpu/safeify'] {
  errno: -30,
  code: 'EROFS',
  syscall: 'mkdir',
  path: '/sys/fs/cgroup/cpu/safeify'
}
原因是使用了safeify组件。
另外，容器使用特权模式（privileged=true）,暂时可以解决以上问题（使用特权模式会带来好大的安全隐患），但又会出现另外的报错问题，报错如下：
error: TypeError: Cannot read property 'delay' of undefined
    at Object.exports.handleMockScript (/my-yapi/vendors/server/utils/commons.js:637:33)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.<anonymous> (/my-yapi/vendors/exts/yapi-plugin-advanced-mock/server.js:210:5)
    at async Promise.all (index 0)
    at async module.exports (/my-yapi/vendors/server/middleware/mockServer.js:334:7)
原因是使用safeify后，没有正确获取返回，个人修改了server/utils/sandbox.js文件为如下可以正常工作，但不一定是最优代码
--- ./sandbox.js        2021-07-19 13:52:58.227872074 +0800
+++ my-yapi/vendors/server/utils/sandbox.js     2021-07-19 12:46:15.671507926 +0800
@@ -8,9 +8,12 @@
     })
 
     // 执行动态代码
+    script = script + "\nreturn mockJson;"
     const result = await safeVm.run(script, context)
 
     // 释放资源
     safeVm.destroy()
-    return result
+    //return result
+    context.mockJson = result
+    return context
 }

## 如何复现此问题
直接在docker容器中运行必现

## 什么浏览器
chrome 版本 91.0.4472.114（正式版本） (x86_64)

~ ## 什么系统（Linux, Windows, macOS）
linux

**Comment by siwuai** [comment]
出现了一样的问题

**Comment by siwuai** [comment]
按楼主测试有效
![image](https://user-images.githubusercontent.com/9333093/126297572-1cbbf318-287a-40f6-af35-ba55f570ac49.png)

**Comment by xiuxiuing** [comment]
safeify 有限制CPU资源使用的配置，在容器中关闭 限制就可以了，添加参数unrestricted: true
const safeVm = new Safeify({
        timeout: 3000,
        asyncTimeout: 60000,
        // quantity: 4,          //沙箱进程数量，默认同 CPU 核数
        // memoryQuota: 500,     //沙箱最大能使用的内存（单位 m），默认 500m
        // cpuQuota: 0.5,
        unrestricted: true
    });

**Comment by HHH1994** [comment]
> 按楼主测试有效
> ![image](https://user-images.githubusercontent.com/9333093/126297572-1cbbf318-287a-40f6-af35-ba55f570ac49.png)

这样改可能还不够，就只能拿到mockJson的配置。其他配置修改后都不会生效了

**Comment by siwuai** [comment]
> > 按楼主测试有效
> > ![image](https://user-images.githubusercontent.com/9333093/126297572-1cbbf318-287a-40f6-af35-ba55f570ac49.png)
> 
> 这样改可能还不够，就只能拿到mockJson的配置。其他配置修改后都不会生效了

其他什么配置

**Comment by xiuxiuing** [comment]
解决方案你可以看看：https://mp.weixin.qq.com/s/-DxfygSxR9RSAcs6RlgdYQ

**Comment by yyr03gy** [comment]
@xiuxiuing , 使用了unrestricted: true解决了容器的问题了

**Comment by siwuai** [comment]
@xiuxiuing @yyr03gy   这个Safeify的实例化参数必须得配置一下，否则，memoryQuota 过大的话，mock调用频繁会导致内存泄漏。默认参数如下：
```
const safeVm = new Safeify({
  timeout: 50,          //超时时间，默认 50ms
  asyncTimeout: 500,    //包含异步操作的超时时间，默认 500ms
  quantity: 4,          //沙箱进程数量，默认同 CPU 核数
  memoryQuota: 500,     //沙箱最大能使用的内存（单位 m），默认 500m
  cpuQuota: 0.5,        //沙箱的 cpu 资源配额（百分比），默认 50%
});
```
![56f0185ebcc581dbef2457de9a969b8](https://user-images.githubusercontent.com/9333093/130179895-55adf542-c9a4-40ff-ba2f-96dd82a85773.png)


> > > 按楼主测试有效
> > > ![image](https://user-images.githubusercontent.com/9333093/126297572-1cbbf318-287a-40f6-af35-ba55f570ac49.png)
> > 
> > 
> > 这样改可能还不够，就只能拿到mockJson的配置。其他配置修改后都不会生效了
> 
> 其他什么配置

**Comment by xiuxiuing** [comment]
@siwuai 内存的可以配置下，在容器里面启动的话要配置 unrestricted: true, 不受CPU限制，不然启动不了

**Comment by siwuai** [comment]
@xiuxiuing 还有一个致命问题，必须对run方法捕获异常，否则脚本执行错误的话资源不会释放。

**Comment by siwuai** [comment]
> > @xiuxiuing 还有一个致命问题，必须对run方法捕获异常，否则脚本执行错误的话资源不会释放。
> 
> 我遇到了这个问题，具体在哪里捕获呢？

```javascript
/**
 * 沙盒执行 js 代码
 * @sandbox Object context
 * @script String script
 * @return sandbox
 *
 * @example let a = sandbox({a: 1}, 'a=2')
 * a = {a: 2}
 */
exports.sandbox = (sandbox, script) => {
  let filter = '^(process|exec|require)$';
  let reg = new RegExp(filter, "g");
  if (reg.test(script)) {
    throw new Error("执行失败，脚本中含敏感操作....");
  }
  try {
    const vm = require('vm');
    sandbox = sandbox || {};
    script = new vm.Script(script);
    const context = new vm.createContext(sandbox);
    script.runInContext(context, {
      timeout: 3000
    });
    return sandbox
  } catch (err) {
    throw err
  }
};
```
