### ISSUE TITLE
安装时出现问题

### ISSUE THREAD

**Issue by chihuo2104** [YMFE/yapi#2271]
## 版本号
从Github上直接clone的

## 什么问题
运行npm run install-server时出现问题：
`[root@localhost vendors]# npm run install-server

> yapi-vendor@1.9.2 install-server /root/yapi/vendors
>  node server/install.js

(node:17655) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17655) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
(node:17655) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
(node:17655) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency
error: MongoNetworkError: Authentication failed., mongodb Authentication failed
log: mongodb load success...
(node:17655) UnhandledPromiseRejectionWarning: Error: Cannot read property 'collection' of undefined
    at /root/yapi/vendors/server/install.js:151:13
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:17655) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17655) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

## 如何复现此问题
按照Yapi文档的安装教程

## 什么浏览器
无

## 什么系统（Linux, Windows, macOS）
CentOS7(客户端Windows10)

**Comment by GENG824** [comment]
大佬问题解决了吗~报同样的问题了~
