### ISSUE TITLE
更新后无法登录

### ISSUE THREAD

**Issue by muye100110** [YMFE/yapi#2274]
## 版本号
~ 1.9.5

## 什么问题
~因为之前的漏洞问题，今天更新到1.9.5之后，在登录页点击登录无反应。

## 如何复现此问题
~ 按教程更新后出现此问题

## 什么浏览器
~ 谷歌91.0.4472.124

## 什么系统（Linux, Windows, macOS）
linux部署，windows访问

**Comment by muye100110** [comment]
重新部署后解决

**Comment by snowyfang** [comment]
> 重新部署后解决

请问重新部署，之前的数据怎么办呢？

**Comment by muye100110** [comment]
> > 重新部署后解决
> 
> 请问重新部署，之前的数据怎么办呢？

可能是我表述有问题，不是重新部署，是重新按照流程升级了一下。虽然可以登录了，但是还有部分bug，比如编写接口时，字段的+号会变成两个等。不能登录还可能是mongodb的问题，可以先重启mongodb，然后重启yapi后试试

**Comment by snowyfang** [comment]
> > > 重新部署后解决
> > 
> > 
> > 请问重新部署，之前的数据怎么办呢？
> 
> 可能是我表述有问题，不是重新部署，是重新按照流程升级了一下。虽然可以登录了，但是还有部分bug，比如编写接口时，字段的+号会变成两个等。不能登录还可能是mongodb的问题，可以先重启mongodb，然后重启yapi后试试

感谢，我遇到的问题是升级1.9.5之后，原ldap登录方式没有了，可能还需要hotfix版本才能解决 >.<
