### ISSUE TITLE
最新的master 更新了 sandbox漏洞修复的版本，跑步起来自动化测试用例了

### ISSUE THREAD

**Issue by rawbin-** [YMFE/yapi#2275]
## 版本号
~ 

## 什么问题
~

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by xiuxiuing** [comment]
Yapi安全漏洞修复方案：https://mp.weixin.qq.com/s/-DxfygSxR9RSAcs6RlgdYQ

**Comment by rawbin-** [comment]
> Yapi安全漏洞修复方案：https://mp.weixin.qq.com/s/-DxfygSxR9RSAcs6RlgdYQ

@xiuxiuing 解决了 靠谱~👍
