### ISSUE TITLE
JSON-SCHEMA高级设置的format无法筛选

### ISSUE THREAD

**Issue by wangyun122** [YMFE/yapi#228]
## 版本号
~ 1.3.9

## 什么问题
~ JSON-SCHEMA高级设置的format无法筛选。

## 如何复现此问题
~ ![](https://ws3.sinaimg.cn/large/006tKfTcgy1fq8h7cenpbj30lj0hodgy.jpg)
选择format的时候输入值进行筛选会导致页面跳转。

## 什么浏览器
~ chrome 版本 65.0.3325.181（正式版本） （64 位）

## 系统
mac和win都出现了

**Comment by suxiaoxin** [comment]
无法复现。。。

**Comment by gaoxiaomumu** [comment]
已经修复
