### ISSUE TITLE
编辑时websocket连接失败后，点击运行，页面不显示

### ISSUE THREAD

**Issue by dicklwm** [YMFE/yapi#230]
## 版本号
http://yapi.demo.qunar.com/

## 什么问题
编辑时websocket连接失败后，点击运行，页面不显示

## 如何复现此问题
websocket连接失败，我也不知道怎么触发，连接失败后，点击运行，页面就不显示了

## 什么浏览器
65.0.3325.181（正式版本） （64 位）

## 什么系统（linux, window, macox）
macox

附图：
![image](https://user-images.githubusercontent.com/19289258/38595386-0da9f6fc-3d7e-11e8-8e36-eeef0484f22e.png)
![image](https://user-images.githubusercontent.com/19289258/38595389-10e32c26-3d7e-11e8-9649-ade98b41ccc6.png)

**Comment by gaoxiaomumu** [comment]
这个好像不是websocket的问题，出现下图bug的原因是环境变量数组为空，建议另外新建一个项目吧

**Comment by suxiaoxin** [comment]
修复了，在 yapi.demo.qunar.com 再试试
