### ISSUE TITLE
新需求：数据字典功能

### ISSUE THREAD

**Issue by xuquanfa** [YMFE/yapi#2308]
是否有计划添加类似数据字典的这样的管理功能，比如状态码字典、性别字典等等，有个功能专门去管理：增删改查。
![image](https://user-images.githubusercontent.com/47516632/129863333-dadcdf35-dcdd-4f5d-aec2-273d21d34a0f.png)

**Comment by ariesly15** [comment]
请详细描述需求的内容, 比如使用场景
然后我们考虑加入此功能
