### ISSUE TITLE
在测试集合里面点击开始测试，没问题，但是测试结果文档结果是错的

### ISSUE THREAD

**Issue by dicklwm** [YMFE/yapi#231]
## 版本号
http://yapi.demo.qunar.com/

## 什么问题
在测试集合里面点击开始测试，没问题，但是测试结果文档结果是错的
[测试报告地址](http://yapi.demo.qunar.com/api/open/run_auto_test?id=8278&token=27cc02a078f46d225e10&env_name=dev&mode=html&email=false)

## 如何复现此问题
创建一个测试集合，开始测试，对比测试报告的结果与测试集合里面的测试结果

## 什么浏览器
 65.0.3325.181（正式版本） （64 位）

## 什么系统（linux, window, macox）
macos

附图：
![image](https://user-images.githubusercontent.com/19289258/38595440-687ddd00-3d7e-11e8-8dac-cf884f71cae5.png)
![image](https://user-images.githubusercontent.com/19289258/38595445-71eccbb2-3d7e-11e8-9b40-b5483552815b.png)
![image](https://user-images.githubusercontent.com/19289258/38595459-7e4968d4-3d7e-11e8-82c0-601964534eea.png)

**Comment by gaoxiaomumu** [comment]
有可能是项目设置中的请求设置的脚本出现问题

**Comment by dicklwm** [comment]
@gaoxiaomumu 
我也没有配置请求设置的脚本
![image](https://user-images.githubusercontent.com/19289258/38600496-e4a484ac-3d96-11e8-83f0-36b9ef189b39.png)

**Comment by suxiaoxin** [comment]
内网环境？

**Comment by suxiaoxin** [comment]
去 yapi.demo.qunar.com 再试试把

**Comment by dicklwm** [comment]
那按理来说127.0.0.1也不能自动化测试的吧
