### ISSUE TITLE
【建议】Postman版本问题可以使用Postman chrome应用程序临时解决，支持导入V2版本，导出V1版本的json。

### ISSUE THREAD

**Issue by YuanjianZhang** [YMFE/yapi#2317]
版本问题可以使用Postman chrome应用程序临时解决，支持导入V2版本，导出V1版本的json。

https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop/related

![image](https://user-images.githubusercontent.com/33444819/130570099-6fa06a3c-1bac-460b-ad0c-b5aa11ea01ad.png)

_Originally posted by @YuanjianZhang in https://github.com/YMFE/yapi/issues/2187#issuecomment-904370520_

**Comment by dyhack** [comment]
或者可以使用官方的postmanV2转V1的工具
https://github.com/postmanlabs/postman-collection-transformer
