### ISSUE TITLE
导入charles的接口文件har报数据格式有误

### ISSUE THREAD

**Issue by yileye** [YMFE/yapi#232]
## 版本号
~ 1.3.9

## 什么问题
~导入charles的接口文件har报数据格式有误

## 如何复现此问题
~ 导入har文件

## 什么浏览器
~ 谷歌

## 什么系统（linux, window, macox）
macox

**Comment by gaoxiaomumu** [comment]
有har数据用例吗？

**Comment by suxiaoxin** [comment]
Fixed v1.3.11
