### ISSUE TITLE
服务器不停的受到挖矿攻击，能不能认真检查彻底并从根修复！！！！！！！！

### ISSUE THREAD

**Issue by SilvaQ** [YMFE/yapi#2321]
上次服务器利用Yapi漏洞挖矿，发现新版本修复了就升级，现在有出现被挖矿，发现又升级了。
难道.....
我们能否彻底查清楚并修复好这个漏洞了呢？

不然这个项目部署在线上服务器已经不可信了。

不建议大家在重要服务器上使用这个项目~~~！！！！！！！！！！！！！！！！！！！！！！！

**Comment by ethanbing** [comment]
确实经常遇到，现在都不敢开yapi服务了

**Comment by azerothyang** [comment]
> 赶紧把注册功能关闭了！
> 
> 编辑Yapi目录下的 config.json 文件，设置 closeRegister 为 true，关闭Yapi的前台注册功能。
> {
> "closeRegister":true
> }

这个有效吗？

**Comment by qiyulan** [comment]
你得先把服务器重装了才行,不然就算你现在卸载yapi也没用

**Comment by leov1** [comment]
本人亲测，关闭 注册功能后，挖矿攻击消失了

**Comment by zurmokeeper** [comment]
1:v1.9.3之前的版本的确存在漏洞，新版本已经修复了，但是你原来的机器可能还留有后门，最好重装机器，再装新版本，然后关闭注册功能（这个是提高安全性的操作）
2：v1.9.3版本以后，关闭注册以后暂时还未遇到被挖矿。
3：建议，现在已经更新了好几个版本了，建议可以使用最新的版本。
