### ISSUE TITLE
自动化测试报告的一个小问题

### ISSUE THREAD

**Issue by jszjgqq** [YMFE/yapi#233]
## 版本号
~ 1.3.9

## 什么问题
~ 访问自动化测试链接，生成的报告中，用例名称都是一样的。希望能修复。

**Comment by gaoxiaomumu** [comment]
有吗？会不会是你的测试用例名称就是一样的

**Comment by jszjgqq** [comment]
@gaoxiaomumu 不可能犯这么低级的错误......

**Comment by gaoxiaomumu** [comment]
可是我们这边没有复现这个问题
