### ISSUE TITLE
swagger自动导入问题

### ISSUE THREAD

**Issue by hanxi2016** [YMFE/yapi#2330]
## 版本号
~ 1.10.1

## 什么问题
~ swagger中会有分组设置导致swagger json 地址会按分组生成多个地址，自动导入时，只能填写一个地址，如何导入全部的接口呢？

## 如何复现此问题
~ 

## 什么浏览器
~ cheom

## 什么系统（Linux, Windows, macOS）
linux

**Comment by ariesly15** [comment]
@hanxi2016 
请提供 swagger.json 文件
