### ISSUE TITLE
QUERY PARAMETERS 高级参数设置 中的bug

### ISSUE THREAD

**Issue by jszjgqq** [YMFE/yapi#234]
## 版本号
~ 1.3.9

## 什么问题
~ 在QUERY PARAMETERS中，选择高级参数设置，左侧选择“变量”展开，点击测试用例名称的树节点的text文本（注意一定要点在Text文本上，不点左侧的小箭头，因为点小箭头无法复现问题），在展开的树节点中，继续点params或者body的时候，树节点会自动收起隐藏。

## 什么浏览器
~ Chrome

## 什么系统（linux, window, macox）
Windows

**Comment by gaoxiaomumu** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/21135585/39049256-5cb32258-44d3-11e8-84bf-c3e276ff43fd.gif)
没有发现问题啊
