### ISSUE TITLE
运行node server/app.js启动后，显示服务已启动，但是打开网页显示无法连接

### ISSUE THREAD

**Issue by leolion10** [YMFE/yapi#2342]
linux系统
![image](https://user-images.githubusercontent.com/75975291/132629044-8726ed58-123e-43a2-8ad8-8d9c97b6973b.png)

**Comment by zurmokeeper** [comment]
你打开网页的地址是怎么样的？是本机部署，本机打开吗？

**Comment by ariesly15** [comment]
@leolion10 
请详细描述问题场景
