### ISSUE TITLE
tag不支持搜索

### ISSUE THREAD

**Issue by leon19920617** [YMFE/yapi#2343]
## 版本号
~  1.5.10

## 什么问题
~tag不支持搜索，那tag有啥意义呢

## 如何复现此问题
~ 

## 什么浏览器
~tag不支持搜索

## 什么系统（Linux, Windows, macOS）

macOS

**Comment by tangcent** [comment]
- 在列表页可以筛选
![image](https://user-images.githubusercontent.com/17569144/133346735-c17e6352-dbfc-45bb-a276-f71aca07a3bd.png)


- 我目前主要用来标记接口是否废弃，是否为开放接口。

**Comment by leon19920617** [comment]
已解决，tag再列表中搜索
