### ISSUE TITLE
测试集合的使用；

### ISSUE THREAD

**Issue by vanzh** [YMFE/yapi#235]
请问，测试集合API序列中，获取前一个接口的返回数据，需要对返回数据做处理后再作为第二个接口的参数怎么处理？
比如：登录接口，返回成功后得到组织：xx\xx\xx\{orgId}; 
           再以orgId为参数获取到组织信息这种的；

**Comment by gaoxiaomumu** [comment]
https://yapi.ymfe.org/documents/case.html    参考变量参数

**Comment by suxiaoxin** [comment]
暂不支持
