### ISSUE TITLE
使用 可视化部署 出现 mongoose这个包的 upstream dependency conflict

### ISSUE THREAD

**Issue by nakeman** [YMFE/yapi#2352]
## 版本号
~ 几个版本都有

## 什么问题
~

> [keminlau@localhost yapi]$ yapi server
> 在浏览器打开 http://0.0.0.0:9090 访问。非本地服务器，请将 0.0.0.0 替换成指定的域名或ip 
> 当前安装版本： 1.9.2
> 连接数据库成功!
> 开始下载平台文件压缩包...
> http://registry.npm.taobao.org/yapi-vendor/download/yapi-vendor-1.9.2.tgz
> 部署文件完成，正在安装依赖库...
>  npm
>   ERR! ERESOLVE unable to resolve dependency tree
> npm ERR! While resolving: yapi-vendor@1.9.2
> npm ERR! Found: mongoose@5.7.5
> npm ERR! node_modules/mongoose
> npm ERR!   mongoose@"5.7.5" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer mongoose@"^4.1.12" from mongoose-auto-increment@5.0.1
> npm ERR! node_modules/mongoose-auto-increment
> npm ERR!   mongoose-auto-increment@"5.0.1" from the root project
> npm ERR! 
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR! 
> npm ERR! See /home/keminlau/.npm/eresolve-report.txt for a full report.
> 
> 依赖库安装完成，正在初始化数据库mongodb...

## 如何复现此问题
~ 

## 什么浏览器
~ 

FF

## 什么系统（Linux, Windows, macOS）
Linux

**Comment by ariesly15** [comment]
@nakeman 1.9.2 有安全漏洞,部署做新版看是否有问题

**Comment by jerryjiao** [comment]
> @nakeman 1.9.2 有安全漏洞,部署做新版看是否有问题

大佬，1.10.2也有同样的问题。。

**Comment by wangzi1325** [comment]
npm 版本降一下， 用6.x的npm
