### ISSUE TITLE
接口列表筛选建议

### ISSUE THREAD

**Issue by leon19920617** [YMFE/yapi#2366]
## 版本号
1.5.10

## 什么问题
接口列表筛选

## 如何复现此问题
 例子：根据状态或tag筛选接口，在有多页的情况下，没有重新去聚合列表，而只是在每一页去做了一个过滤
这样在筛选时，满足条件的接口到底在哪一页就无从知晓。必须遍历每一页的接口。
如：我们有600个接口，但未完成的接口在第30页。那筛选后，只有翻到第30页，才能知道未完成的接口只有一个，且在第30页，建议改进：列表筛选这个功能

## 什么浏览器
chrome

## 什么系统（Linux, Windows, macOS）
macOS

**Comment by tangcent** [comment]
你用的哪个版本的`yapi`?
我记得这个问题早就解决了: https://github.com/YMFE/yapi/pull/1222

**Comment by leon19920617** [comment]
新版本确实是。。。是我们版本太老了。
