### ISSUE TITLE
建议改进-swagger地址进行配置和自动更新接口信息

### ISSUE THREAD

**Issue by mahaixue** [YMFE/yapi#237]
## 版本号
~ 
1.3.9

## 什么问题
能对swagger的在线地址进行配置，然后定时自动更新。
这个功能还是很有必要。

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by darren-fu** [comment]
嗯嗯，这个有用

**Comment by suxiaoxin** [comment]
已收集

**Comment by sinchang** [comment]
这种 issue 建议不要直接关闭，避免别人重复提。
