### ISSUE TITLE
建议将高级mock的cookie注入的httpOnly属性改成主动设置的

### ISSUE THREAD

**Issue by hugh0524** [YMFE/yapi#239]
## 版本号
~ 1.3.8

## 什么问题
~ 高级mock中设置cookie，属性都是httpOnly， 有些mock接口需要往浏览器注入可供js读取的cookie参数

## 如何复现此问题
~ resHeader["Set-Cookie"] = "a=1"

## 什么浏览器
~ ALL

## 什么系统（linux, window, macox）
ALL

**Comment by suxiaoxin** [comment]
业务 js 代码为什么需要读取 cookie 的值？

**Comment by hugh0524** [comment]
感谢@suxiaoxin回复，比如有个功能，后端注入了一个cookie标准到了前端，前端会读取这个标志做一个简单的判断。 类似的功能应该很多，比如登录判断、访客来源判断、推荐码获取等 都有可能前端直接读取。 而且对于一个mock server， 注入的cookie都变成了httpOnly，感觉没有必要吧

**Comment by suxiaoxin** [comment]
已收集
