### ISSUE TITLE
Error: assert.equal is not a function

### ISSUE THREAD

**Issue by viky88** [YMFE/yapi#2395]
## 版本号
~ 1.10.2

## 什么问题
~  自动化测试断言提示assert.equal is not a function

## 如何复现此问题
~ 1.10.2版本

## 什么浏览器
~ chrome

## 什么系统（Linux, Windows, macOS）
macOS

**Comment by viky88** [comment]
参考issue #2234 解决

修改： server/utils/commons.js

// result = await sandboxFn(context, script); 
result = yapi.commons.sandbox(context, script);

**Comment by tiyunchen** [comment]
> 还是会报这个错哦

https://mdnice.com/writing/c1a82b5817934d2fad3dbf8aaae93aee

看看这个

**Comment by tiyunchen** [comment]
```
 const safeVm = new Safeify({
        timeout: 3000,
        asyncTimeout: 60000,
        unsafe: {
            modules: {
                // 引入assert断言库
                assert: 'assert'
            }
        }
    })
    safeVm.preset('const assert = require("assert");');
```

**Comment by nhdeng** [comment]
我也是遇到此类问题 请问你解决了吗
