### ISSUE TITLE
JSON-SCHEMA模拟数据导入优化建议支持带注释json

### ISSUE THREAD

**Issue by xiangcaozhu** [YMFE/yapi#240]
## 版本号
~ 1.3.9

## 什么问题
~ 带有注释信息的json文件导入到JSON-SCHEMA模拟中的json中，会报错。希望能够自动处理解析json中的注释，至少可以报错。方便开发者能从json模式中直接拷贝json导入json-schema中
## 如何复现此问题
~ 编辑——返回数据设置——JSON-SCHEMA——选中json方式导入——包含注释的json（编辑器会报错）
{
  "msg": "成功!",
  "results": {
    "data": [
      {
        "name": "111133", **//添加注释信息时，无法导入成功**
        "ondelete": "0",
        "remind": "",
        "size": 69742108,
        "status": "0"
      }
    ],
    "totalNum": 10,
    "totalPage": 10,
    "pageSize": 1,
    "currentPage": 1
  },
  "status": "200"
}

## 什么浏览器
~ chrome

## 什么系统（linux, window, macox）
window

**Comment by suxiaoxin** [comment]
带注释的 json 在浏览器 console 做下简单的转换把

![image](https://user-images.githubusercontent.com/17695103/38795713-b2556a36-418b-11e8-89f8-1d6c4ee32572.png)
输出结果在最下面的，另外错误没有提示的问题后续会修复的
