### ISSUE TITLE
权限控制的BUG

### ISSUE THREAD

**Issue by jszjgqq** [YMFE/yapi#241]
## 版本号
~ 1.3.9

## 什么问题
~ 
存在问题：
1、项目中访客权限的账号可以 增、删、改接口中高级mock的设置；
2、高级Mock 中的响应时间值无法保存（实际提示为：保存成功）。

**Comment by gaoxiaomumu** [comment]
问题已修复，感谢提问

**Comment by graceTesterZhang** [comment]
请问哪个版本修复了此bug，我的版本号是：1.9.2， 仍存在访客可以删除接口的问题。

**Comment by graceTesterZhang** [comment]
> 问题已修复，感谢提问

请问哪个版本修复了此bug，我的版本号是：1.9.2， 仍存在访客可以删除接口的问题。
