### ISSUE TITLE
更新到1.3.9版本后，接口内容编辑处不能编辑（页面显示空白！）

### ISSUE THREAD

**Issue by chunyu-zhou** [YMFE/yapi#242]
## 版本号
~ 1.3.9
## 什么问题
~ 更新到1.3.9版本后，接口内容编辑处不能编辑（页面显示空白！）

## 什么浏览器
~ chrome 65

## 什么系统（linux, window, macox）
macos,服务器 centos

**Comment by jszjgqq** [comment]
我也1.3.9，好像没这个问题？

**Comment by chunyu-zhou** [comment]
@jszjgqq 这就很尴尬了。

**Comment by huaxuan** [comment]
我最新拉的代码，也有这个问题。

**Comment by gaoxiaomumu** [comment]
该问题已经修复，更新版本1.3.11
