### ISSUE TITLE
docker-compose部署镜像，高级mock-自定义脚本/断言都是出现错误！

### ISSUE THREAD

**Issue by zhuxiangrong111** [YMFE/yapi#2426]
## 版本号
1.10.2
## 什么问题
docker-compose部署镜像，高级mock-自定义脚本，断言都是出现错误！
## 什么浏览器
版本 92.0.4515.131（正式版本） （64 位）
## 什么系统（Linux, Windows, macOS）
Linux

截图：
![1](https://user-images.githubusercontent.com/62647662/144351129-2eca0471-793d-4cba-b191-9bfba70c0012.png)
![2](https://user-images.githubusercontent.com/62647662/144351135-3c004524-7022-4e50-b212-ac7dba820f78.png)
![3](https://user-images.githubusercontent.com/62647662/144351142-26dbcba9-9ff0-4fd7-8ecb-50d1f8f8e27d.png)

**Comment by zhuxiangrong111** [comment]
解决

**Comment by dingweiqings** [comment]
大兄弟，咋解决的
