### ISSUE TITLE
改进建议

### ISSUE THREAD

**Issue by jszjgqq** [YMFE/yapi#243]
## 版本号
~ 1.3.9

## 什么问题
~ 项目→成员管理→添加成员

优化改进建议:
1、在下拉选择完名字之后，显示的并不是用户名，而是显示的用户ID，如果点选之后，在输入框随便再输入一个字符，原本显示的ID，此时会显示为用户名。
        这个问题有点奇怪，我另外一台服务器搭建的环境就没这个问题，直接显示的用户名。

2、下拉列表一个个选择非常麻烦，如果人员多的话，想哭。

3、删除成员也只能一个个删，想哭。

4、建议 增加角色（或者用户组）的概念，维护角色下的列表成员即可。项目权限管控跟角色捆绑就行。

其他问题：
1、无法直接修改账号的角色（目前直接修改数据库user表的role字段实现）；

2、管理员最好能直接新增账号；

**Comment by gaoxiaomumu** [comment]
第一个问题，我们这里无法复现
2、下拉列表一个个选择非常麻烦，如果人员多的话，想哭。 有批量导入功能

**Comment by xianwei** [comment]
> 第一个问题，我们这里无法复现
> 2、下拉列表一个个选择非常麻烦，如果人员多的话，想哭。 有批量导入功能

批量导入功能在哪个版本有啊，我们用的1.4.0没看到这个功能。
