### ISSUE TITLE
Chrome开发工具 Network看不到请求

### ISSUE THREAD

**Issue by zlab** [YMFE/yapi#244]
## 版本号
~ 1.3.9

## 什么问题
Chrome开发工具 Network看不到请求

## 如何复现此问题
~ 打开开发者工具，测试接口，页面有返回，network没有看到请求

## 什么浏览器
~ chrome

## 什么系统（linux, window, macox）
win8, mac

## ps
1.3.4 没有这个问题，同一个浏览器

**Comment by gaoxiaomumu** [comment]
![8871c6da-a5bb-4269-bae3-70c2907726a6](https://user-images.githubusercontent.com/21135585/38855679-c0439fa2-4256-11e8-9d81-b6cb4a19a669.png)
看了yapidemo network有请求啊

**Comment by zlab** [comment]
https://yapi.zhanqi.net/ 你注册试试，我试过几台电脑了，都看不到

**Comment by gaoxiaomumu** [comment]
有可能是因为你是https的请求，你可以再chrome的扩展程序里面找到cross-request，点击背景页，这里的network可以看到请求
![90ac2c3c-2c1c-4fc3-94c8-a9a209e1c83f](https://user-images.githubusercontent.com/21135585/38863046-1adf0dc2-4269-11e8-995c-ec40e5e1a98c.png)

**Comment by zlab** [comment]
![image](https://user-images.githubusercontent.com/2288630/38863175-76dba0ea-4269-11e8-99de-76c05d340f91.png)

**Comment by gaoxiaomumu** [comment]
![1f27adf6-b35b-41a9-9946-2ffec024f38d](https://user-images.githubusercontent.com/21135585/38863303-c0af1526-4269-11e8-9d97-5373a19ec29a.png)
开发者模式

**Comment by zlab** [comment]
看到请求了，这样太麻烦了啊，有没有办法改进啊

**Comment by gaoxiaomumu** [comment]
把你的https变成http

**Comment by zlab** [comment]
@gaoxiaomumu 什么时候支持https啊

**Comment by nzmd** [comment]
http的现在也看不了，都需要到扩展程序、点击背景页那里看
