### ISSUE TITLE
点击添加接口按钮报错

### ISSUE THREAD

**Issue by sinchang** [YMFE/yapi#245]
## 版本号
~ 1.3.9

## 什么问题
~ 接口列表分类为空的时候，点击添加接口按钮报错，页面出现空白。

![](https://i.loli.net/2018/04/16/5ad4743a7972c.png)

## 如何复现此问题
~ 

## 什么浏览器
~ Chrome

## 什么系统（linux, window, macox）
macOS

**Comment by gaoxiaomumu** [comment]
可以描述的再详细一点吗

**Comment by sinchang** [comment]
@gaoxiaomumu 把接口列表里面的分类删光，再点击添加接口就出现了。

**Comment by gaoxiaomumu** [comment]
分类都删光的话，是点击右侧的添加接口按钮吗？
![fb9e031b-f57e-4583-8466-2bf1d7feb85e](https://user-images.githubusercontent.com/21135585/38860442-c9200e60-4262-11e8-8fae-294de707fc00.png)

**Comment by sinchang** [comment]
是的

**Comment by gaoxiaomumu** [comment]
嗯嗯，问题修复了，一般情况下是先要建立分类再建立接口

**Comment by sinchang** [comment]
ok
