### ISSUE TITLE
项目复制提示主键冲突

### ISSUE THREAD

**Issue by 61292888** [YMFE/yapi#2452]
## 版本号
yapi 1.9.1

## 什么问题
复制项目提示：E11000 duplicate key error collection: yapi.interface index: _id_ dup key: { _id: 372 }

## 如何复现此问题
mongodump备份数据再导入mongo，重新拉起yapi,复制项目时候会报错，

## 什么浏览器
谷歌

## 什么系统（Linux, Windows, macOS）
centos 7.9

**Comment by 61292888** [comment]
> ## 版本号
> 
> yapi 1.9.1
> ## 什么问题
> 
> 复制项目提示：E11000 duplicate key error collection: yapi.interface index: _id_ dup key: { _id: 372 }
> ## 如何复现此问题
> 
> mongodump备份数据再导入mongo，重新拉起yapi,复制项目时候会报错，
> ## 什么浏览器
> 
> 谷歌
> ## 什么系统（Linux, Windows, macOS）
> 
> centos 7.9

**Comment by 61292888** [comment]
还会出现：E11000 duplicate key error collection: yapi.interface_col index: _id_ dup key: { _id: 224 }
                  E11000 duplicate key error collection: yapi.project index: _id_ dup key: { _id: 216 }

**Comment by Aubreyzhong** [comment]
请问你解决这个问题了没有？
