### ISSUE TITLE
LDAP功能问题

### ISSUE THREAD

**Issue by tanzhipeng1210** [YMFE/yapi#2461]
## 版本号
~ 1.10.2

## 什么问题
局域网为Windows Active Directory域环境
~在config.json 文件中配置 LDAP经过两天的反复测试发现 searchDn 字段不能有中文路径否则无法获取到用户(登陆时提示用户不存在)，后来在域控上新建全字母的OU路径后 发现可以正常登陆，用过的其它平台如 Gitea、showdoc等 未见ldap功能有此问题。

## 如何复现此问题
~ 
"ldapLogin": {
      "enable": true,
      "server": "ldap://xxx.com",
      "baseDn": "CN=xxx,CN=Users,DC=lebodc,DC=com",
      "bindPassword": "xxx",
      "searchDn": "OU=xxx(中文),OU=xxx(中文),OU=xxx(中文),DC=lebodc,DC=com",
      "searchStandard": "&(objectClass=user)(cn=%s)",
      "emailPostfix": "@xxx.cn",
      "emailKey": "mail",
      "usernameKey": "sAMAccountName"
   }
另外如果需要测试Active Directory环境作为测试 可以联系我
## 什么浏览器
~ 360、Google

## 什么系统（Linux, Windows, macOS）
服务器 Linux 客户端 Windows

**Comment by tanzhipeng1210** [comment]
经过多番测试已找到问题 
"searchStandard": "&(objectClass=user)(cn=%s)",
此处不能使用cn必须改成"searchStandard": "&(objectClass=user)(sAMAccountName=%s)
因其它系统没有(cn=%s)这段要求所以未出现此类情况
记录下来为后面用户使用AD环境的做个参考

**Comment by ZUCCzwp** [comment]
![image](https://github.com/YMFE/yapi/assets/26847647/bed98741-84c1-427f-8bb9-18a078fe4d87)
我也遇到了此问题 我使用了 ldapsearch返回有结果 但是 yapi给我的错误是用户不存在 我有点疑惑

**Comment by ZUCCzwp** [comment]
@tanzhipeng1210 能帮忙解答下吗
