### ISSUE TITLE
console报错:React is running in production mode, but dead code elimination has not been applied.

### ISSUE THREAD

**Issue by coopercoder** [YMFE/yapi#247]
## 版本号
v1.3.10

## 什么问题
console报错:React is running in production mode, but dead code elimination has not been applied.

## 如何复现此问题
打开yapi.demo.qunar.com后，chrome浏览器开发者工具中会有报错：
VM135:21 Uncaught Error: React is running in production mode, but dead code elimination has not been applied. Read how to correctly configure React for production: https://fb.me/react-perf-use-the-production-build
    at <anonymous>:21:35

## 什么浏览器
chrome

## 什么系统（linux, window, macox）
macos

**Comment by coopercoder** [comment]
这个是不是ykit的问题？我是不是不该在yapi里提问这个问题。。。各位高手知道怎么解决吗

**Comment by jszjgqq** [comment]
完全可以忽略的问题....  并不会影响实际使用效果.

**Comment by zhuyudong** [comment]
同出现此错误

**Comment by jackiewillen** [comment]
同出现此问题
