### ISSUE TITLE
swagger需要授权yapi如何进行数据同步？

### ISSUE THREAD

**Issue by zhaoshunchen** [YMFE/yapi#2488]
## 版本号
1.10.2

## 什么问题
当swagger需要授权输入用户名密码，yapi如何进行同步

## 如何复现此问题
~ 

## 什么浏览器
~ 

## 什么系统（Linux, Windows, macOS）
Linux

**Comment by huangzhenxian** [comment]
https://（账号）:（密码）@www.baidu.com/项目/v2/api-docs

**Comment by huangzhenxian** [comment]
刚刚搜索解决方案  最后我解决了 ，顺便在这里分享下  只要在域名前加一个“（账号）:（密码）@”就行了

**Comment by zhaoshunchen** [comment]
> 

非常感谢！！！
