### ISSUE TITLE
使用 nginx 反代后登录进管理面板刷新后又让重新登录

### ISSUE THREAD

**Issue by Ice-Hazymoon** [YMFE/yapi#249]
## 版本号

1.3.11

## 什么问题

使用 nginx 反代后登录进管理面板刷新后又让重新登录

## 如何复现此问题

假设地址为 111.111.111.111:9090, 用 nginx 反代 111.111.111.111:9090, 使用 域名 直接进行访问, 登录进后台以后刷新浏览器跳转到登录页面, 用 ip +端口号访问没有问题

## 什么浏览器

Chrome 66.0.3346.8（正式版本）（64 位）

## 什么系统（Linux, Windows, macOS）

Windows 10

**Comment by suxiaoxin** [comment]
不要用 Nginx 代理

**Comment by sandheart** [comment]
不使用NGINX会很麻烦，域名、端口就不好解决
