### ISSUE TITLE
接口-高级设置-设置默认值，不起作用，返回的还是随机数据

### ISSUE THREAD

**Issue by chkllchkll** [YMFE/yapi#250]
## 版本号
~ 1.3.9

## 什么问题
~编写接口时，对返回字段 进行高级设置 --默认值设置为0，但是程序调用mock URL时，该字段的值还是随机返回的。

## 如何复现此问题
~ 

## 什么浏览器
~ Chrome

## 什么系统（Linux, Windows, macOS）
服务器 Linux ，客户端 windows
![image](https://user-images.githubusercontent.com/36780317/38847252-4a5aa2d6-4233-11e8-91b9-e548bbe2f330.png)

**Comment by gaoxiaomumu** [comment]
本来就是这样子的，这里的default有点像example，mock的时候不会处理这个default的
