### ISSUE TITLE
运行时请求方式异常（写的POST，发的GET）

### ISSUE THREAD

**Issue by ResistanceTo** [YMFE/yapi#2505]
## 版本号
1.10.2

## 什么问题
编辑时写的请求方式为post，点运行，发的是get请求
![image](https://user-images.githubusercontent.com/48614752/156960738-12facbcc-34d6-4238-994c-002fc1583a59.png)

## 如何复现此问题
每次都如此。

## 什么浏览器
edge 版本 98.0.1108.62 (官方内部版本) (64 位)

## 什么系统（Linux, Windows, macOS）
server：centos（docker）
client：windows11

**Comment by yyltesting** [comment]
你看看运行的network是不是也走的GET，讲道理不会的 应该是服务器给你报的错

**Comment by ResistanceTo** [comment]
> 你看看运行的network是不是也走的GET，讲道理不会的 应该是服务器给你报的错

network确实是post，服务器重定向自己转成get了。
