### ISSUE TITLE
预览页面建议紧凑些，减少多余空白

### ISSUE THREAD

**Issue by laomu1988** [YMFE/yapi#252]
## 版本号
~ v1.3.9

## 什么问题
~ 建议优化预览页面效果，尽量紧凑些，例如返回的json底部空白完全是多余的，查看不太方便，内容较多还需要滚动屏幕
![image](https://user-images.githubusercontent.com/6356903/38908979-2d9b95d4-42f5-11e8-8f3e-c7b3e323fde5.png)

## 什么浏览器
~ all

**Comment by suxiaoxin** [comment]
收集
