### ISSUE TITLE
通过命令行导入接口数据后，在页面上编辑api后保存报错TypeError: Cannot read property 'toObject' of null

### ISSUE THREAD

**Issue by qRainBirdp** [YMFE/yapi#2528]
## 版本号
~ 1.10.2

## 什么问题
~ 通过命令行导入接口数据后，在页面上编辑api后保存页面报错；
    页面报错：
![1](https://user-images.githubusercontent.com/68057739/162353564-8d93da94-fcd6-4db4-bb43-aec02190d597.png)
    后台日志报错：
![2](https://user-images.githubusercontent.com/68057739/162353609-163bf514-443a-4972-9782-c51ebb856d68.png)

## 如何复现此问题
~ 通过yapi import的方式命令行导入接口数据，然后在页面编辑其api后保存

## 什么浏览器
~ Chrome

## 什么系统（Linux, Windows, macOS）
~ Linux

**Comment by kanganxi** [comment]
不要添加tag,这个是已知bug，不知掉啥时间会修复

**Comment by qRainBirdp** [comment]
好的吧。。。那这issue就等什么时候更新修复了再关。。

**Comment by CongDuang** [comment]
`/server/controllers/interface.js`文件下
825行前面加一行`params.project_id = interfaceData.project_id;`

```javascript
...
    yapi.emitHook('interface_update', id).then();
(825->)    params.project_id = interfaceData.project_id;
    await this.autoAddTag(params);

    ctx.body = yapi.commons.resReturn(result);
    return 1;
...
```

不知道什么时候修复，就是查数据库id = null 查出来的就是null 然后验证tag时就报错了
@qRainBirdp @kanganxi

**Comment by qRainBirdp** [comment]
> `/server/controllers/interface.js`文件下 825行前面加一行`params.project_id = interfaceData.project_id;`
> 
> ```js
> ...
>     yapi.emitHook('interface_update', id).then();
> (825->)    params.project_id = interfaceData.project_id;
>     await this.autoAddTag(params);
> 
>     ctx.body = yapi.commons.resReturn(result);
>     return 1;
> ...
> ```
> 
> 不知道什么时候修复，就是查数据库id = null 查出来的就是null 然后验证tag时就报错了 @qRainBirdp @kanganxi
> 
> 加上这一行就不会报错了

非常感谢！这个bug目前也不影响使用，还是希望官网哪天能修复吧
