### ISSUE TITLE
运行yapi server 无法完成部署

### ISSUE THREAD

**Issue by luckyloong** [YMFE/yapi#254]
## 版本号
~ 最新版

## 什么问题
~ 运行yapi server 命令后,输出：

在浏览器打开 http://0.0.0.0:9090 访问。非本地服务器，请将 0.0.0.0 替换成指定的域名或ip 
xdg-open: no method available for opening 'http://0.0.0.0:9090'

然后在外网浏览器访问进行配置····点击安装后···一直转圈···没有任何反应！

## 如何复现此问题
~ 

## 什么浏览器
~ 

## 什么系统（Linux, Windows, macOS）
服务器:CENTOS 7    NGINX 反向代理

**Comment by suxiaoxin** [comment]
https://github.com/YMFE/yapi/issues/16
