### ISSUE TITLE
搜索添加人员显示 id 不显示 name

### ISSUE THREAD

**Issue by gogoyqj** [YMFE/yapi#258]
https://github.com/YMFE/yapi/blob/b7c4268456eda5c778e73c1e637aff4afb1b7760/client/components/UsernameAutoComplete/UsernameAutoComplete.js#L75

改为

```js
id: `${v.uid }`
```

**Comment by gaoxiaomumu** [comment]
我觉得不应该是这个问题，可能是antd  select 插件的

![image](https://user-images.githubusercontent.com/21135585/39041302-15508f76-44bb-11e8-9cac-116a595631ba.png)
这个属性问题，或者是   因为 这里的username是id?
![image](https://user-images.githubusercontent.com/21135585/39041363-31d8c8ac-44bb-11e8-9722-45ce746ebf18.png)

**Comment by gogoyqj** [comment]
no - ant Select 组件 Option 的 key 不能是数字，即便指定了数字，也会被转成 string，因此会存在 `${id}` !== id 导致不能显示选中的用户名的问题
