### ISSUE TITLE
迫切需要数据导入时支持url方式导入，并且支持一键刷新数据

### ISSUE THREAD

**Issue by wish4sun** [YMFE/yapi#259]
## 版本号
1.3.9 

## 什么问题
迫切需要数据导入时，支持url方式导入swagger接口数据，并且支持点击按钮自动更新，要不然每次都要另存一个json文件更新，太麻烦了

## 如何复现此问题
~ 

## 什么浏览器
Chrome

## 什么系统（Linux, Windows, macOS）
Mac OS

**Comment by mahaixue** [comment]
这个之前我提了，我看到回复 已经收录了

**Comment by wish4sun** [comment]
@mahaixue 多谢~

**Comment by angryHair** [comment]
这个功能强烈建议

**Comment by suxiaoxin** [comment]
最近版本支持了
