### ISSUE TITLE
接口不能多级分组

### ISSUE THREAD

**Issue by ChNan** [YMFE/yapi#260]
## 版本号
~ 1.3.9

## 什么问题
~ 接口不能多级分组

## 如何复现此问题
~ 接口不能多级分组

## 什么浏览器
~ Chrome

## 什么系统（Linux, Windows, macOS）
Windows

**Comment by wish4sun** [comment]
由于swagger的文档是按照controller划分的，而导入数据是，一个controller就是一个分类，所以确实隶属于相同业务的controller不能放到一个分类下比较不方便，希望能支持至少手动可以分组，谢谢~
