### ISSUE TITLE
9090端口冲突

### ISSUE THREAD

**Issue by af826** [YMFE/yapi#261]
## 版本号
~ 

## 什么问题
~ server 9090端口被占用无法启动

## 如何复现此问题
~ 

## 什么浏览器
~ 

## 什么系统（Linux, Windows, macOS）
centos7

**Comment by nan403** [comment]
改一下端口就好了。。

**Comment by af826** [comment]
关键我是没有找到地方修改

**Comment by nan403** [comment]
项目目录下config.json文件，里边有一个参数默认是port:3000，官网部署说明里配置邮箱的那个文件。

我的项目目录是/usr/src/nodejs/bin/my-yapi

**Comment by af826** [comment]
@nan403 嗯
