### ISSUE TITLE
希望增加3des加密方法

### ISSUE THREAD

**Issue by loginKing** [YMFE/yapi#262]
## 版本号
~ 
1.3.9
## 什么问题
~
目前应不支持3des加密的处理方式，希望增加
## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by mahaixue** [comment]
还有MD5

**Comment by gaoxiaomumu** [comment]
![image](https://user-images.githubusercontent.com/21135585/39043978-69806d5e-44c1-11e8-83b5-5e96ea491342.png)
md5 不是有吗
