### ISSUE TITLE
建议-------普通mock默认改成json

### ISSUE THREAD

**Issue by mahaixue** [YMFE/yapi#263]
## 版本号
~ 1.3.9

## 什么问题
~

把mock默认改成json，而不是json-schema,因为用json的场景 会比较多，而且更改默认，以前mock那些数据得手动去改成json的。之前的版本应该默认是json的
## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by suxiaoxin** [comment]
最新已经改了
