### ISSUE TITLE
v1.10.2 版本跑测试用例 断言报错

### ISSUE THREAD

**Issue by hanzoi** [YMFE/yapi#2675]
## 版本号
v1.10.2

## 什么问题
测试用例中断言报错

## 如何复现此问题
测试用例增加断言，执行测试时

## 什么浏览器
任何

## 什么系统（Linux, Windows, macOS）
linux

报错如下：

执行脚本:
assert.notEqual(body.session_count, 0)
Error: Method Promise.prototype.then called on incompatible receiver [object Object]
<img width="883" alt="image" src="https://user-images.githubusercontent.com/61114924/223891426-2964d671-30e8-4b27-b93b-fa87c8a1892f.png">

**Comment by iamxwk** [comment]
试试这样改
在/vendors/server/utils下commons.js

result = await sandboxFn(context, script);
改为
result = yapi.commons.sandbox(context, script);

然后重启yapi

**Comment by lmovse** [comment]
> 试试这样改 在/vendors/server/utils下commons.js
> 
> result = await sandboxFn(context, script); 改为 result = yapi.commons.sandbox(context, script);
> 
> 然后重启yapi

可以了，感谢老哥
