### ISSUE TITLE
运行npm run dev-client 报错 Syntax error: Unexpected token m in JSON at position 0

### ISSUE THREAD

**Issue by wind-labs** [YMFE/yapi#2680]
## 版本号
~ 1.11.0

## 什么问题
~运行 npm run dev-client后 报错
$ npm run dev-client

> yapi-vendor@1.11.0 dev-client D:\code\react\yapi\vendors
> npm run dev-copy-icon && ykit s -p 4000

> yapi-vendor@1.11.0 dev-copy-icon D:\code\react\yapi\vendors
> cp -r static/iconfont ./

[ykit] Starting up server, serving at: D:\code\react\yapi\vendors
[info] Available on: http://127.0.0.1:4000
[info] Start hot reloader server.
× [08:07:19] 15 errors in compiling process.
[error] in ../config.json
Syntax error: Unexpected token m in JSON at position 0
    at JSON.parse (<anonymous>)
 @ ./server/yapi.js 12:13-41

√ [08:07:20] 200 GET /prd/manifest@dev.js ( 23.71KB )
√ [08:07:20] 200 GET /prd/index@dev.css ( 621.82KB )
√ [08:07:20] 200 GET /prd/lib3@dev.js ( 6690.25KB )
√ [08:07:20] 200 GET /prd/lib2@dev.js ( 1979.53KB )
√ [08:07:20] 200 GET /prd/lib@dev.js ( 1189.81KB )
√ [08:07:20] 200 GET /prd/index@dev.js ( 23264.25KB )
× [08:07:21] 15 errors in compiling process.
[error] in ../config.json
Syntax error: Unexpected token m in JSON at position 0
    at JSON.parse (<anonymous>)
 @ ./server/yapi.js 12:13-41

√ [08:07:22] 200 GET /iconfont/iconfont.woff
× [08:07:22] 15 errors in compiling process.
[error] in ../config.json
Syntax error: Unexpected token m in JSON at position 0
    at JSON.parse (<anonymous>)
 @ ./server/yapi.js 12:13-41

√ [08:07:36] 200 GET /__webpack_hmr
√ [08:07:36] 200 GET /prd/index@dev.css ( 621.82KB )
√ [08:07:36] 200 GET /prd/manifest@dev.js ( 23.71KB )
√ [08:07:36] 200 GET /prd/lib3@dev.js ( 6690.25KB )
√ [08:07:36] 200 GET /prd/lib2@dev.js ( 1979.53KB )
√ [08:07:36] 200 GET /prd/lib@dev.js ( 1189.81KB )
√ [08:07:36] 200 GET /prd/index@dev.js ( 23264.25KB )
× [08:07:37] 15 errors in compiling process.
[error] in ../config.json
Syntax error: Unexpected token m in JSON at position 0
    at JSON.parse (<anonymous>)
 @ ./server/yapi.js 12:13-41

√ [08:07:38] 304 GET /iconfont/iconfont.woff
× [08:07:38] 15 errors in compiling process.
[error] in ../config.json
Syntax error: Unexpected token m in JSON at position 0
    at JSON.parse (<anonymous>)
 @ ./server/yapi.js 12:13-41

## 如何复现此问题
~ config.json：
{
  "port": "3000",
  "adminAccount": "admin@admin.com",
  "timeout":120000,
  "db": {
    "servername": "192.168.23.254",
    "DATABASE": "yapi-test",
    "port": 27017,
    "user": "yapi",
    "pass": "Yapi2023!@#",
    "authSource": ""
  },
  "mail": {
    "enable": true,
    "host": "smtphz.qiye.163.com",
    "port": 994,
    "from": "test@xxxx.cn",
    "auth": {
      "user": "test@xxxx.cn",
      "pass": "xxxxx"
    }
  }
}

## 什么浏览器
~ chrome

## 什么系统（Linux, Windows, macOS）
windows10

**Comment by wind-labs** [comment]
在centos7上跑npm run dev-client也会有同样的问题，是因为config文件有问题吗？还是环境有问题？
node版本是10.24.1，看代码是因为在
![image](https://user-images.githubusercontent.com/8413919/229725274-d17e8c3f-82ba-469f-82ad-4eb5209a19f2.png)
这里打印的source里已经包含“module.exports = ”所以在后面JSON.parse的时候报错了

浏览器里的错误信息：
`../config.jsonModule build failed: SyntaxError: Unexpected token m in JSON at position 0    at JSON.parse (<anonymous>)    at Object.module.exports (D:\code\react\yapi\vendors\node_modules\json-loader\index.js:4:49) @ ./server/yapi.js 12:13-41./~/fs-extra/lib/empty/index.jsModule not found: Error: Cannot resolve module 'fs' in D:\code\react\yapi\vendors\node_modules\fs-extra\lib\emptyresolve module fs in D:\code\react\yapi\vendors\node_modules\fs-extra\lib\empty  looking for modules in D:\code\react\yapi\vendors\node_modules    resolve 'file' fs in D:\code\react\yapi\vendors\node_modules      resolve file        D:\code\react\yapi\vendors\node_modules\fs doesn't exist        D:\code\react\yapi\vendors\node_modules\fs.js doesn't exist        D:\code\react\yapi\vendors\node_modules\fs.css doesn't exist        D:\code\react\yapi\vendors\node_modules\fs.json doesn't exist        D:\code\react\yapi\vendors\node_modules\fs.string doesn't exist        D:\code\react\yapi\vendors\node_modules\fs.tpl doesn't exist    D:\code\react\yapi\vendors\node_modules\fs doesn't exist (module as directory)[D:\code\react\yapi\vendors\node_modules\fs][D:\code\react\yapi\vendors\node_modules\fs.js][D:\code\react\yapi\vendors\node_modules\fs.css][D:\code\react\yapi\vendors\node_modules\fs.json][D:\code\react\yapi\vendors\node_modules\fs.string][D:\code\react\yapi\vendors\node_modules\fs.tpl][D:\code\react\yapi\vendors\node_modules\fs] @ ./~/fs-extra/lib/empty/index.js 4:11-24./~/nodemailer/lib/mailer/index.jsModule not found: Error: Cannot resolve module 'net' in D:\code\react\yapi\vendors\node_modules\nodemailer\lib\mailerresolve module net in D:\code\react\yapi\vendors\node_modules\nodemailer\lib\mailer  looking for modules in D:\code\react\yapi\vendors\node_modules    resolve 'file' net in D:\code\react\yapi\vendors\node_modules      resolve file        D:\code\react\yapi\vendors\node_modules\net doesn't exist        D:\code\react\yapi\vendors\node_modules\net.js doesn't exist        D:\code\react\yapi\vendors\node_modules\net.css doesn't exist        D:\code\react\yapi\vendors\node_modules\net.json doesn't exist        D:\code\react\yapi\vendors\node_modules\net.string doesn't exist        D:\code\react\yapi\vendors\node_modules\net.tpl doesn't exist    D:\code\react\yapi\vendors\node_modules\net doesn't exist (module as directory)[D:\code\react\yapi\vendors\node_modules\net][D:\code\react\yapi\vendors\node_modules\net.js][D:\code\react\yapi\vendors\node_modules\net.css][D:\code\react\yapi\vendors\node_modules\net.json][D:\code\react\yapi\vendors\node_modules\net.string][D:\code\react\yapi\vendors\node_modules\net.tpl][D:\code\react\yapi\vendors\node_modules\net] @ ./~/nodemailer/lib/mailer/index.js 13:12-26./~/nodemailer/lib/mailer/index.jsModule not found: Error: Cannot resolve module 'dns' in D:\code\react\yapi\vendors\node_modules\nodemailer\lib\mailerresolve module dns in D:\code\react\yapi\vendors\node_modules\nodemailer\lib\mailer  looking for modules in D:\code\react\yapi\vendors\node_modules    resolve 'file' dns in D:\code\react\yapi\vendors\node_modules      resolve file        D:\code\react\yapi\vendors\node_modules\dns doesn't exist        D:\code\react\yapi\vendors\node_modules\dns.js doesn't exist        D:\code\react\yapi\vendors\node_modules\dns.css doesn't exist        D:\code\react\yapi\vendors\node_modules\dns.json doesn't exist        D:\code\react\yapi\vendors\node_modules\dns.string doesn't exist        D:\code\react\yapi\vendors\node_modules\dns.tpl doesn't exist    D:\code\react\yapi\vendors\node_modules\dns doesn't exist (module as directory)[D:\code\react\yapi\vendors\node_modules\dns][D:\code\react\yapi\vendors\node_modules\dns.js][D:\code\react\yapi\vendors\node_modules\dns.css][D:\code\react\yapi\vendors\node_modules\dns.json][D:\code\react\yapi\vendors\node_modules\dns.string][D:\code\react\yapi\vendors\node_modules\dns.tpl][D:\code\react\yapi\vendors\node_modules\dns] @ ./~/nodemailer/lib/mailer/index.js 14:12-26./~/nodemailer/lib/shared/index.jsModule not found: Error: Cannot resolve module 'fs' in D:\code\react\yapi\vendors\node_modules\nodemailer\lib\sharedresolve module fs in D:\code\react\yapi\vendors\node_modules\nodemailer\lib\shared  looking for modules in D:\code\react\yapi\vendors\node_modules    resolve 'file' fs in D:\code\react\yapi\vendors\node_modules      resolve file        D:\code\react\yapi\vendors\node_modules\fs doesn't exist        D:\code\react\yapi\vendors\node_modules\fs.js doesn't exist        D:\code\react\yapi\vendors\node_modules\fs.css doesn't exist        D:\code\react\yapi\vendors\node_modules\fs.json doesn't exist        D:\code\react\yapi\vendors\node_modules\fs.string doesn't exist        D:\code\react\yapi\vendors\node_modules\fs.tpl doesn't exist    D:\code\react\yapi\vendors\node_modules\fs doesn't exist (module as directory)[D:\code\react\yapi\vendors\node_modules\fs][D:\code\react\yapi\vendors\node_modules\fs.js][D:\code\react\yapi\vendors\node_modules\fs.css][D:\code\react\yapi\vendors\node_modules\fs.json][D:\code\react\yapi\vendors\node_modules\fs.string][D:\code\react\yapi\vendors\node_modules\fs.tpl][D:\code\react\yapi\vendors\node_modules\fs] @ ./~/nodemailer/lib/shared/index.js 5:11-24./~/nodemailer/lib/sendmail-transport/index.jsModule not found: Error: Cannot resolve module 'child_process' in D:\code\react\yapi\vendors\node_modules\nodemailer\lib\sendmail-transportresolve module child_process in D:\code\react\yapi\vendors\node_modules\nodemailer\lib\sendmail-transport  looking for modules in D:\code\react\yapi\vendors\node_modules    resolve 'file' child_process in D:\code\react\yapi\vendors\node_modules      resolve file        D:\code\react\yapi\vendors\node_modules\child_process doesn't exist        D:\code\react\yapi\vendors\node_modules\child_process.js doesn't exist        D:\code\react\yapi\vendors\node_modules\child_process.css doesn't exist        D:\code\react\yapi\vendors\node_modules\child_process.json doesn't exist        D:\code\react\yapi\vendors\node_modules\child_process.string doesn't exist        D:\code\react\yapi\vendors\node_modules\child_process.tpl doesn't exist    D:\code\react\yapi\vendors\node_modules\child_process doesn't exist (module as directory)[D:\code\react\yapi\vendors\node_modules\child_process][D:\code\react\yapi\vendors\node_modules\child_process.js][D:\code\react\yapi\vendors\node_modules\child_process.css][D:\code\react\yapi\vendors\node_modules\child_process.json][D:\code\react\yapi\vendors\node_modules\child_process.string][D:\code\react\yapi\vendors\node_modules\child_process.tpl][D:\code\react\yapi\vendors\node_modules\child_process] @ ./~/nodemailer/lib/sendmail-transport/index.js 3:14-38./~/graceful-fs/graceful-fs.jsModule not found: Error: Cannot resolve module 'fs' in D:\code\react\yapi\vendors\node_modules\graceful-fsresolve module fs in D:\code\react\yapi\vendors\node_modules\graceful-fs  looking for modules in D:\code\react\yapi\vendors\node_modules    resolve 'file' fs in D:\code\react\yapi\vendors\node_modules      resolve file        D:\code\react\yapi\vendors\node_modules\fs doesn't exist        D:\code\react\yapi\vendors\node_modules\fs.js doesn't exist        D:\code\react\yapi\vendors\node_modules\fs.css doesn't exist        D:\code\react\yapi\vendors\node_modules\fs.json doesn't exist        D:\code\react\yapi\vendors\node_modules\fs.string doesn't exist        D:\code\react\yapi\vendors\node_modules\fs.tpl doesn't exist    D:\code\react\yapi\vendors\node_modules\fs doesn't exist (module as directory)[D:\code\react\yapi\vendors\node_modules\fs][D:\code\react\yapi\vendors\node_modules\fs.js][D:\code\react\yapi\vendors\node_modules\fs.css][D:\code\react\yapi\vendors\node_modules\fs.json][D:\code\react\yapi\vendors\node_modules\fs.string][D:\code\react\yapi\vendors\node_modules\fs.tpl][D:\code\react\yapi\vendors\node_modules\fs] @ ./~/graceful-fs/graceful-fs.js 1:9-22./~/nodemailer/lib/dkim/index.jsModule not found: Error: Cannot resolve module 'fs' in D:\code\react\yapi\vendors\node_modules\nodemailer\lib\dkimresolve module fs in D:\code\react\yapi\vendors\node_modules\nodemailer\lib\dkim  looking for modules in D:\code\react\yapi\vendors\node_modules    resolve 'file' fs in D:\code\react\yapi\vendors\node_modules      resolve file        D:\code\react\yapi\vendors\node_modules\fs doesn't exist        D:\code\react\yapi\vendors\node_modules\fs.js doesn't exist        D:\code\react\yapi\vendors\node_modules\fs.css doesn't exist        D:\code\react\yapi\vendors\node_modules\fs.json doesn't exist        D:\code\react\yapi\vendors\node_modules\fs.string doesn't exist        D:\code\react\yapi\vendors\node_modules\fs.tpl doesn't exist    D:\code\react\yapi\vendors\node_modules\fs doesn't exist (module as directory)[D:\code\react\yapi\vendors\node_modules\fs][D:\code\react\yapi\vendors\node_modules\fs.js][D:\code\react\yapi\vendors\node_modules\fs.css][D:\code\react\yapi\vendors\node_modules\fs.json][D:\code\react\yapi\vendors\node_modules\fs.string][D:\code\react\yapi\vendors\node_modules\fs.tpl][D:\code\react\yapi\vendors\node_modules\fs] @ ./~/nodemailer/lib/dkim/index.js 10:11-24./~/nodemailer/lib/smtp-connection/http-proxy-client.jsModule not found: Error: Cannot resolve module 'net' in D:\code\react\yapi\vendors\node_modules\nodemailer\lib\smtp-connectionresolve module net in D:\code\react\yapi\vendors\node_modules\nodemailer\lib\smtp-connection  looking for modules in D:\code\react\yapi\vendors\node_modules    resolve 'file' net in D:\code\react\yapi\vendors\node_modules      resolve file        D:\code\react\yapi\vendors\node_modules\net doesn't exist        D:\code\react\yapi\vendors\node_modules\net.js doesn't exist        D:\code\react\yapi\vendors\node_modules\net.css doesn't exist        D:\code\react\yapi\vendors\node_modules\net.json doesn't exist        D:\code\react\yapi\vendors\node_modules\net.string doesn't exist        D:\code\react\yapi\vendors\node_modules\net.tpl doesn't exist    D:\code\react\yapi\vendors\node_modules\net doesn't exist (module as directory)[D:\code\react\yapi\vendors\node_modules\net][D:\code\react\yapi\vendors\node_modules\net.js][D:\code\react\yapi\vendors\node_modules\net.css][D:\code\react\yapi\vendors\node_modules\net.json][D:\code\react\yapi\vendors\node_modules\net.string][D:\code\react\yapi\vendors\node_modules\net.tpl][D:\code\react\yapi\vendors\node_modules\net] @ ./~/nodemailer/lib/smtp-connection/http-proxy-client.js 7:12-26./~/nodemailer/lib/smtp-connection/http-proxy-client.jsModule not found: Error: Cannot resolve module 'tls' in D:\code\react\yapi\vendors\node_modules\nodemailer\lib\smtp-connectionresolve module tls in D:\code\react\yapi\vendors\node_modules\nodemailer\lib\smtp-connection  looking for modules in D:\code\react\yapi\vendors\node_modules    resolve 'file' tls in D:\code\react\yapi\vendors\node_modules      resolve file        D:\code\react\yapi\vendors\node_modules\tls doesn't exist        D:\code\react\yapi\vendors\node_modules\tls.js doesn't exist        D:\code\react\yapi\vendors\node_modules\tls.css doesn't exist        D:\code\react\yapi\vendors\node_modules\tls.json doesn't exist        D:\code\react\yapi\vendors\node_modules\tls.string doesn't exist        D:\code\react\yapi\vendors\node_modules\tls.tpl doesn't exist    D:\code\react\yapi\vendors\node_modules\tls doesn't exist (module as directory)[D:\code\react\yapi\vendors\node_modules\tls][D:\code\react\yapi\vendors\node_modules\tls.js][D:\code\react\yapi\vendors\node_modules\tls.css][D:\code\react\yapi\vendors\node_modules\tls.json][D:\code\react\yapi\vendors\node_modules\tls.string][D:\code\react\yapi\vendors\node_modules\tls.tpl][D:\code\react\yapi\vendors\node_modules\tls] @ ./~/nodemailer/lib/smtp-connection/http-proxy-client.js 8:12-26./~/nodemailer/lib/smtp-connection/index.jsModule not found: Error: Cannot resolve module 'net' in D:\code\react\yapi\vendors\node_modules\nodemailer\lib\smtp-connectionresolve module net in D:\code\react\yapi\vendors\node_modules\nodemailer\lib\smtp-connection  looking for modules in D:\code\react\yapi\vendors\node_modules    resolve 'file' net in D:\code\react\yapi\vendors\node_modules      resolve file        D:\code\react\yapi\vendors\node_modules\net doesn't exist        D:\code\react\yapi\vendors\node_modules\net.js doesn't exist        D:\code\react\yapi\vendors\node_modules\net.css doesn't exist        D:\code\react\yapi\vendors\node_modules\net.json doesn't exist        D:\code\react\yapi\vendors\node_modules\net.string doesn't exist        D:\code\react\yapi\vendors\node_modules\net.tpl doesn't exist    D:\code\react\yapi\vendors\node_modules\net doesn't exist (module as directory)[D:\code\react\yapi\vendors\node_modules\net][D:\code\react\yapi\vendors\node_modules\net.js][D:\code\react\yapi\vendors\node_modules\net.css][D:\code\react\yapi\vendors\node_modules\net.json][D:\code\react\yapi\vendors\node_modules\net.string][D:\code\react\yapi\vendors\node_modules\net.tpl][D:\code\react\yapi\vendors\node_modules\net] @ ./~/nodemailer/lib/smtp-connection/index.js 5:12-26./~/nodemailer/lib/smtp-connection/index.jsModule not found: Error: Cannot resolve module 'tls' in D:\code\react\yapi\vendors\node_modules\nodemailer\lib\smtp-connectionresolve module tls in D:\code\react\yapi\vendors\node_modules\nodemailer\lib\smtp-connection  looking for modules in D:\code\react\yapi\vendors\node_modules    resolve 'file' tls in D:\code\react\yapi\vendors\node_modules      resolve file        D:\code\react\yapi\vendors\node_modules\tls doesn't exist        D:\code\react\yapi\vendors\node_modules\tls.js doesn't exist        D:\code\react\yapi\vendors\node_modules\tls.css doesn't exist        D:\code\react\yapi\vendors\node_modules\tls.json doesn't exist        D:\code\react\yapi\vendors\node_modules\tls.string doesn't exist        D:\code\react\yapi\vendors\node_modules\tls.tpl doesn't exist    D:\code\react\yapi\vendors\node_modules\tls doesn't exist (module as directory)[D:\code\react\yapi\vendors\node_modules\tls][D:\code\react\yapi\vendors\node_modules\tls.js][D:\code\react\yapi\vendors\node_modules\tls.css][D:\code\react\yapi\vendors\node_modules\tls.json][D:\code\react\yapi\vendors\node_modules\tls.string][D:\code\react\yapi\vendors\node_modules\tls.tpl][D:\code\react\yapi\vendors\node_modules\tls] @ ./~/nodemailer/lib/smtp-connection/index.js 6:12-26./~/graceful-fs/fs.jsModule not found: Error: Cannot resolve module 'fs' in D:\code\react\yapi\vendors\node_modules\graceful-fsresolve module fs in D:\code\react\yapi\vendors\node_modules\graceful-fs  looking for modules in D:\code\react\yapi\vendors\node_modules    resolve 'file' fs in D:\code\react\yapi\vendors\node_modules      resolve file        D:\code\react\yapi\vendors\node_modules\fs doesn't exist        D:\code\react\yapi\vendors\node_modules\fs.js doesn't exist        D:\code\react\yapi\vendors\node_modules\fs.css doesn't exist        D:\code\react\yapi\vendors\node_modules\fs.json doesn't exist        D:\code\react\yapi\vendors\node_modules\fs.string doesn't exist        D:\code\react\yapi\vendors\node_modules\fs.tpl doesn't exist    D:\code\react\yapi\vendors\node_modules\fs doesn't exist (module as directory)[D:\code\react\yapi\vendors\node_modules\fs][D:\code\react\yapi\vendors\node_modules\fs.js][D:\code\react\yapi\vendors\node_modules\fs.css][D:\code\react\yapi\vendors\node_modules\fs.json][D:\code\react\yapi\vendors\node_modules\fs.string][D:\code\react\yapi\vendors\node_modules\fs.tpl][D:\code\react\yapi\vendors\node_modules\fs] @ ./~/graceful-fs/fs.js 3:9-22./~/jsonfile/index.jsModule not found: Error: Cannot resolve module 'fs' in D:\code\react\yapi\vendors\node_modules\jsonfileresolve module fs in D:\code\react\yapi\vendors\node_modules\jsonfile  looking for modules in D:\code\react\yapi\vendors\node_modules    resolve 'file' fs in D:\code\react\yapi\vendors\node_modules      resolve file        D:\code\react\yapi\vendors\node_modules\fs doesn't exist        D:\code\react\yapi\vendors\node_modules\fs.js doesn't exist        D:\code\react\yapi\vendors\node_modules\fs.css doesn't exist        D:\code\react\yapi\vendors\node_modules\fs.json doesn't exist        D:\code\react\yapi\vendors\node_modules\fs.string doesn't exist        D:\code\react\yapi\vendors\node_modules\fs.tpl doesn't exist    D:\code\react\yapi\vendors\node_modules\fs doesn't exist (module as directory)[D:\code\react\yapi\vendors\node_modules\fs][D:\code\react\yapi\vendors\node_modules\fs.js][D:\code\react\yapi\vendors\node_modules\fs.css][D:\code\react\yapi\vendors\node_modules\fs.json][D:\code\react\yapi\vendors\node_modules\fs.string][D:\code\react\yapi\vendors\node_modules\fs.tpl][D:\code\react\yapi\vendors\node_modules\fs] @ ./~/jsonfile/index.js 5:8-21./~/nodemailer/lib/mime-node/index.jsModule not found: Error: Cannot resolve module 'fs' in D:\code\react\yapi\vendors\node_modules\nodemailer\lib\mime-noderesolve module fs in D:\code\react\yapi\vendors\node_modules\nodemailer\lib\mime-node  looking for modules in D:\code\react\yapi\vendors\node_modules    resolve 'file' fs in D:\code\react\yapi\vendors\node_modules      resolve file        D:\code\react\yapi\vendors\node_modules\fs doesn't exist        D:\code\react\yapi\vendors\node_modules\fs.js doesn't exist        D:\code\react\yapi\vendors\node_modules\fs.css doesn't exist        D:\code\react\yapi\vendors\node_modules\fs.json doesn't exist        D:\code\react\yapi\vendors\node_modules\fs.string doesn't exist        D:\code\react\yapi\vendors\node_modules\fs.tpl doesn't exist    D:\code\react\yapi\vendors\node_modules\fs doesn't exist (module as directory)[D:\code\react\yapi\vendors\node_modules\fs][D:\code\react\yapi\vendors\node_modules\fs.js][D:\code\react\yapi\vendors\node_modules\fs.css][D:\code\react\yapi\vendors\node_modules\fs.json][D:\code\react\yapi\vendors\node_modules\fs.string][D:\code\react\yapi\vendors\node_modules\fs.tpl][D:\code\react\yapi\vendors\node_modules\fs] @ ./~/nodemailer/lib/mime-node/index.js 7:11-24`

Hello，is anyone here？

**Comment by wangwenbin0035** [comment]
mac、遇到同样的问题

**Comment by Ceselect** [comment]
我也遇到了这个问题，目前是这样解决的：
![截图 2023-04-10 17-03-01](https://user-images.githubusercontent.com/45918610/230870534-fdc09b6a-2ce8-477c-98d3-818acf9b5adc.png)

**Comment by wind-labs** [comment]
前面的问题 
Module not found: Error: Cannot resolve module 'fs'
Module not found: Error: Cannot resolve module 'tls'
这类的错误可以 用这个方法解决 [#2666](https://github.com/YMFE/yapi/pull/2666/commits/92a336d183f54b3f674802bd11045e013c8749d5)

**Comment by bobsam** [comment]
你们得使用node v8版本来 install 和 build-client

**Comment by wind-labs** [comment]
搞了个英文版的带着左侧树形菜单、多级分类，已经在内网服务器上跑了2个月了，没遇到啥错误，若是说问题的话，编辑API的时候多级分类有时候会显示异常，刷新一下或者退出重进就正常了，就这样吧，看以后会不会有更成熟的产品出来
