### ISSUE TITLE
能否增加一个swagger配置自动更新导入的按钮或者url

### ISSUE THREAD

**Issue by 91wangmeng** [YMFE/yapi#281]
比如说我提供一个可以获取swagger配置数据的url,类似http://xxx.xx.xx.xx:xx/v2/api-docs
点击更新可以自动从这个url去获取然后自动导入进去,
或者提供一个类似于自动测试的url,请求这个url就触发自动更新配置,
这样就可以跟持续化集成工具结合起来了,服务启动成功后swagger配置就可以获取了,然后自动触发接口文档更新,

**Comment by suxiaoxin** [comment]
最近版本已经支持
