### ISSUE TITLE
dockerfile

### ISSUE THREAD

**Issue by zhfish** [YMFE/yapi#283]
## 版本号
~ 1.3.12

## 什么问题
~ 贡献一个docker镜像

hub地址  
`https://hub.docker.com/r/zhfish/yapi/`

dockerfile以及使用说明  
`https://github.com/zhfish/Docker-yapi`

**Comment by zhfish** [comment]
为了更好的支持docker，建议目录结构改成这样
```
/
/conf
/vendors
/logs
```
config.json
init.lock
这些运行时的文件，都放在conf
这样可以不映射vendors出去

**Comment by suxiaoxin** [comment]
感谢
