### ISSUE TITLE
如何将yapi运行在127.0.0.1:3000/yapi/ 路径下？

### ISSUE THREAD

**Issue by flyingtimes** [YMFE/yapi#293]
## 版本号
~ all

## 什么问题
~ 我希望将yapi运行在域名的某个子目录下，使用了nginx做代理转发，但是似乎yapi采用的是绝对路径，因此这样转发会导致错误，怎么破？

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by suxiaoxin** [comment]
不支持

**Comment by Gcaufy** [comment]
刚部署运行，发现代码里的静态文件，接口请求全都是使用的绝对路径。是有什么原因需要这样去设计么？
在内网部署通常都是使用一台机器部署多个服务，申请域名成本会相对比较高，因此更多会使用nginx做代理转发，还是希望项目能支持相对路径部署。

**Comment by lanux** [comment]
@flyingtimes @Gcaufy 你们最终有没有解决方案？；我试过改代码，控制台无任何报错，但是页面显示不全

**Comment by Gcaufy** [comment]
@lanux 修改源码解决了

**Comment by osramywj** [comment]
@Gcaufy 把所有src和href都加上前缀吗？那也太多了吧
