### ISSUE TITLE
运行yapi update升级出错

### ISSUE THREAD

**Issue by lichao0** [YMFE/yapi#294]
## 版本号
~ 当前版本1.2.5，最新版本1.3.14

## 什么问题
~ 运行yapi update升级出错
![image](https://user-images.githubusercontent.com/9666904/39500088-a17bd33e-4de4-11e8-863e-febd5ec0ecda.png)

## 如何复现此问题
~ 

## 什么浏览器
~ 

## 什么系统（Linux, Windows, macOS）
Linux

**Comment by suxiaoxin** [comment]
https://github.com/YMFE/yapi/issues/16

**Comment by zheyvsu** [comment]
这个用#16 也无法解决啊

**Comment by zheyvsu** [comment]
yum update -y nss curl libcurl
