### ISSUE TITLE
webpack 代理

### ISSUE THREAD

**Issue by NanShanJi** [YMFE/yapi#297]
下面是使用 vue-cli 创建的 webpack 配置文件  
**build -> config -> index.js**
```JavaScript
    proxyTable: {
      '/api/**': {
        target: `http://yapi.demo.qunar.com/mock/4632`,
        pathRewrite: {
          '^/api': ''
        }
      }
    },
```
请问我这样配置的 mock 代理正确吗？   

访问的时候报如下错误
```sheel
[HPM] Error occurred while trying to proxy request /category/delete from localhost:8080 to http://yapi.demo.qunar.com/mock/4632 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_c
ommon_system_errors)
```

**Comment by NanShanJi** [comment]
问题已解决  
原因：跨域请求失败 [具体参考](https://www.jianshu.com/p/95b2caf7e0da)  
解决方法：按照如下设置即可  
```
proxyTable: {
      '/api': {
        target: `http://yapi.demo.qunar.com/mock/4632`,
        changeOrigin: true
      }
    }
```

**Comment by hitao123** [comment]
我在本地开启 yapi 做后端服务，使用 vue 开发

    proxyTable: {
      '/mock/20/*': {
        target: 'http://localhost:30000',
        path: '/mock/20/App/*',
        changeOrigin: true,
        secure: false
      }
    },
请求 
    axios.get('/mock/20/queryMerchant', {

    });


出现不存在的api, 当前请求path为 ryMerchant， 请求方法为 GET ，请确认是否定义此请求
