### ISSUE TITLE
使用json-schema取的的模拟数据不全？

### ISSUE THREAD

**Issue by liuhuanzhu** [YMFE/yapi#298]
## 什么问题
~使用json-schema取的的模拟数据不全。
`比如我设置的数据格式为一个对象数组，对象中的key为name和id。但是模拟出来的数据经常没有这个对象数组，或者有时候某个对象中缺少一个字段。经常会遇到这种情况`

**Comment by gaoxiaomumu** [comment]
因为该字段可能被你设置成非必须的，所以这个字段的模拟数据是会随机出现的，设置成必须字段就好了
