### ISSUE TITLE
怎么通过ip+端口+项目名的方式启动呢

### ISSUE THREAD

**Issue by 286991105** [YMFE/yapi#299]
部署在docker上，目前启动通过http://192.168.169.129:3000访问
我想通过http://192.168.169.129:3000/yapi作为网站根访问要如何做呢

**Comment by gaoxiaomumu** [comment]
好像做不到吧，你可以申请一个域名   指向http://192.168.169.129:3000/yapi，你可以找一下运维人员帮你看一下

**Comment by 286991105** [comment]
谢谢，nodejs不熟悉，我主要做java web开发的，觉得应该有像java项目部署到tomcat一样，通过ip+端口+项目名的方式访问

**Comment by zhfish** [comment]
和nodejs无关，去看看nginx吧
