### ISSUE TITLE
测试集合同一个集合中的接口能否指定不同的域名

### ISSUE THREAD

**Issue by MattGong** [YMFE/yapi#300]
测试集合同一个集合中的接口能否指定不同的域名
比如我有这样一个流程(流程简化，为了说明问题)。
1. 登录A系统，创建流程单;
2. 登录B系统，审批流程单;

A系统接口的domain 和 B系统的接口domain是不同的， 但是我在Yapi里面选一下A系统登录接口的环境配置中的一个，上面步骤1，2里面的所有接口的domain都会变成一样的。 其实我是想A系统的接口选A系统的，B系统的选B系统。 这个能实现不？ 万分感谢

**Comment by gaoxiaomumu** [comment]
这个应该已经有了，你可以在A接口设置环境1，B接口设置环境2，进行自动化测试的时候
![image](https://user-images.githubusercontent.com/21135585/39693845-fbd78328-5217-11e8-81c7-e6342e9ea173.png)
选择默认环境就好了

**Comment by chenguangcui** [comment]
提问者的问题是先测试接口1，选择了一个域名，测试接口2时域名还是停留在接口1的域名，但是提问者希望得到的时候测试接口2的时候域名自动切换到接口2对应的域名。

**Comment by chenguangcui** [comment]
![image](https://user-images.githubusercontent.com/18319435/129829963-5acfcfb3-9a4a-4217-8e4d-124df2cd474a.png)
每个接口选择对应的环境，之后一定要点更新，集合测试的时候选择默认环境就好了。
