### ISSUE TITLE
希望添加对多种http状态码返回结果的支持

### ISSUE THREAD

**Issue by JL-Code** [YMFE/yapi#302]
支持如下图所示的不同状态码不同返回结果的自定义
![image](https://user-images.githubusercontent.com/14163944/39682725-33269f82-51e4-11e8-8ce1-664350d9cf98.png)

**Comment by gaoxiaomumu** [comment]
你可以在数据返回那里写正则方式的数据返回， 
![image](https://user-images.githubusercontent.com/21135585/39688339-d9a7d676-5204-11e8-8f4b-de0e2f18013c.png)

也可以在高级mock里面进行设置

**Comment by HsiaohuiHsiang** [comment]
请问正则方式的数据返回应该如何使用的？ 一般的，项目文件内的swagger直接包含了success 200对应的数据结构，但错误状态码如400， 500 也有另外的数据结构，这非常重要。

 "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.UserLoginSucResponse"
                        }
                    },
                    "302": {
                        "description": "Found",
                        "schema": {
                            "$ref": "#/definitions/model.UserBindRedirect"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ApiError"
                        }
                    }
                }
