### ISSUE TITLE
HEADER: 设置Access-Control-Allow-Origin不起作用？

### ISSUE THREAD

**Issue by sagittaria** [YMFE/yapi#303]
## 版本号
1.3.14

## 什么问题
Failed to load http://localhost:3000/mock/11/apipath: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://localhost:8282' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
RechargeRecords.vue?e7a0:119 Error: Network Error
    at createError (createError.js?f777:16)
    at XMLHttpRequest.handleError (xhr.js?14ed:87)
在接口编辑界面，设置了Header: Access-Control-Allow-Origin为http://localhost:8282还是报相同错误？不起作用？

## 如何复现此问题
axios.get(`http://localhost:3000/mock/11/apipath`).then(function (resp) {
// ...
        })

## 什么浏览器
chrome

## 什么系统（Linux, Windows, macOS）
windows

**Comment by suxiaoxin** [comment]
不需要设置跨域的 header 信息

建议使用服务端反向代理，https://yapi.ymfe.org/documents/mock.html#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8-mock

**Comment by sagittaria** [comment]
@suxiaoxin 不好意思啊可能我没描述清楚，是在本地部署的，新建了一个接口，在axios.get访问时报 must not be the wildcard '*' when ...，所以我才想去设置这个header，但在接口编辑界面上设置了之后并没有效果，还是报这个错，看到response里Access-Control-Allow-Origin确实还是*。那么问题是，需要对yapi做什么全局设置？

**Comment by algking** [comment]
用了apache的反向代理, e
```
    ProxyRequests Off
    # #   反向代理
    ProxyPassMatch   "^/test/api/([a-zA-Z0-9/]+)$" "http://wkapi.com:3000/mock/11/api/$1"
    ProxyPassReverse "/test/api" "http://wkapi.com:3000/mock/11/api"

```
如果前端带上来credentials = true, 就会报错
```
response must not be the wildcard '*' when the request's credentials mode is 'include'
```
研究了很久, 实在找不到方案, 请教一下

**Comment by algking** [comment]
@sagittaria 后来我也是找到了这个方案, 折腾一晚上,问题解决了, 后端去整前端就是很多不懂..
