### ISSUE TITLE
提个优化点

### ISSUE THREAD

**Issue by wangxin8899** [YMFE/yapi#307]
![image](https://user-images.githubusercontent.com/11817392/39760306-93f2b660-5307-11e8-8192-b447cc884ac8.png)

能否填个的全局变量的列表维护起来，测试用例填参数时填入key。比如一个测试用例集有100个接口，都会用到user_phone，不直接填电话画面，填变量。这样万一号码改了，就好维护了

**Comment by gaoxiaomumu** [comment]
可以写在  请求配置里面添加全局变量
![image](https://user-images.githubusercontent.com/21135585/39793509-61a26310-5378-11e8-8fbc-2323d4a37b11.png)

**Comment by meimeide** [comment]
@gaoxiaomumu 
我有一个用例集是这样的，case01的返回数据中的id值
后续所有用例case02~case80的请求都需要用到这个。
这个该怎么在请求配置里写呀？
