### ISSUE TITLE
方法名称相同

### ISSUE THREAD

**Issue by DroreZZ** [YMFE/yapi#308]
## 任何版本
~ 

## 同一个项目下不同文件夹下保存提示不能出现相同接口路径
~

## 同一个项目下不同文件夹下保存提示不能出现相同接口路径
~ 

## Google浏览器
~ 

## Windows
![tim 20180509085935](https://user-images.githubusercontent.com/36020507/39790216-511a018a-5367-11e8-8ff8-bd4854e0b0ea.png)

**Comment by gaoxiaomumu** [comment]
嗯，确实会这样，为了保证在测试集合中的不会有两个接口有相同的路径

**Comment by DroreZZ** [comment]
是否可以在不同文件夹下，因为有这样的场景存在！

2018-05-09 

zhangz 



发件人：高晓琳 <notifications@github.com>
发送时间：2018-05-09 11:06
主题：Re: [YMFE/yapi] 方法名称相同 (#308)
收件人："YMFE/yapi"<yapi@noreply.github.com>
抄送："DroreZZ"<zhangz@drore.com>,"Author"<author@noreply.github.com>

嗯，确实会这样，为了保证在测试集合中的不会有两个接口有相同的路径

**Comment by gaoxiaomumu** [comment]
应该是不可以的

**Comment by zjzhiqian** [comment]
jsonRpc接口的话 经常都是这样的 注释掉那个repeat校验会不会有问题?

**Comment by suxiaoxin** [comment]
接口路径一样，可以用 query path 做不同的区分
![image](https://user-images.githubusercontent.com/17695103/39854678-4cb96a1e-545b-11e8-8e46-b31a8c09984d.png)
