### ISSUE TITLE
【优化建议】增加状态码说明文档

### ISSUE THREAD

**Issue by maosong** [YMFE/yapi#309]
接口一般会返回多种状态码，分为系统级状态码，以及各接口独立的状态码。状态码一般会存放在http-header或响应数据的json体内。
目前虽然可以在接口备注里说明，但这种无法结构化的数据难以维护，这是我们团队使用yapi比较大的痛点，希望能在新版中考虑。

**Comment by maosong** [comment]
我们在备注状态码时分为常量、状态码、说明三个字段。在程序中通过常量调用状态码。

下面是在yapi中写备注的例子。而系统级状态码的备注要在每个接口里都写一遍，十分痛苦。

# 状态码

| 常量 | 状态码 | 说明 |
| --- | --- | --- |
| COMMON_SUCCESS | 0 | 成功 |
| COMMON_UNKNOWN | -1 | 未知错误 |
| COMMON_PARAM | -100 | 参数错误 |
| COMMON_AUTH | -200 | 身份认证错误 |

**Comment by suxiaoxin** [comment]
可以考虑做一个 wiki 插件，把所有的状态码写到 wiki 里面

**Comment by mailbaoer** [comment]
支持，我们在用的时候也有这样的需求，有时候会有一些关键性的文档需要记录

**Comment by gaoxiaomumu** [comment]
在版本19中，我们将增加项目wiki功能
