### ISSUE TITLE
[request feature]接口备注支持markdown

### ISSUE THREAD

**Issue by shixuev5** [YMFE/yapi#31]
request body 为json时，参数的备注相关信息没有地方备注  只能写在接口备注里面，希望接口备注能支持markdown。参照postman 
![image](https://user-images.githubusercontent.com/3207014/32594854-93546d20-c568-11e7-8547-1593462bbf01.png)

request body 为file 或者 raw的时候 输入框高度太小。
![image](https://user-images.githubusercontent.com/3207014/32594749-23c2cdd0-c568-11e7-89ab-4d552814e6a2.png)

**Comment by suxiaoxin** [comment]
json里面支持直接写注释

**Comment by shixuev5** [comment]
@suxiaoxin  试了下确实可行 但还是希望能支持下markdown... 😀

**Comment by suxiaoxin** [comment]
ok

**Comment by shixuev5** [comment]
@suxiaoxin  
![image](https://user-images.githubusercontent.com/3207014/32597632-38a319bc-c572-11e7-922b-9e2a7ada2820.png)

**Comment by eidonjoe** [comment]
可以在request和response部分分别加入备注, 方便对参数进行枚举和字段说明. 强烈希望支持markdown.

**Comment by mcdongWang** [comment]
强烈希望增加接口备注的markdown

**Comment by suxiaoxin** [comment]
json编辑器可以直接写注释的

**Comment by suxiaoxin** [comment]
@shixuev5 @mcdongWang @eidonjoe

**Comment by eidonjoe** [comment]
@suxiaoxin 备注的富文本编辑里面可以支持markdown解析么, 这样写起接口备注可能更友好一些.

**Comment by suxiaoxin** [comment]
目前不支持

**Comment by shixuev5** [comment]
@suxiaoxin  有未来支持的计划嘛

**Comment by suxiaoxin** [comment]
未来会考虑的
