### ISSUE TITLE
【建议】关于接口运行的一些建议

### ISSUE THREAD

**Issue by snadn** [YMFE/yapi#310]
现在接口的运行需要依赖 cross-request 这个插件，但其实安装这个插件有很大的安全风险，因为安装后，用户打开的任何网页都可以发送跨站请求了！如果后续也按该思路迭代的话，建议优化 cross-request 的配置，让其仅在指定网站生效。

思路2：其实也可以让服务器做反代，而具体的反代配置可以由页面进行管理，这样也可以解决跨域的问题。

**Comment by maosong** [comment]
嗯，这个问题也困扰我，目前已经暂时停用这个插件，用postman测试

**Comment by suxiaoxin** [comment]
@snadn @maosong  已确认此问题，下个版本将会改成只有 yapi 站点才允许跨域请求，请随时关注下个版本的发布！

**Comment by suxiaoxin** [comment]
@snadn @maosong  已修复此问题，请更新  cross-request 扩展
