### ISSUE TITLE
Content-type是multipart/form-data时候，mock 脚本中取到不到body中的参数

### ISSUE THREAD

**Issue by ZiqiWill** [YMFE/yapi#312]
## 版本号
版本： 1.3.14

## 什么问题
Content-type是multipart/form-data时候，mock 脚本中取到不到body中的参数

## 如何复现此问题
body：form格式
参数：
```
name: text
ico: file
```
headers:
```
Content-Type: multipart/form-data
```

返回数据：

```
{
  "errcode": 0, 
  "data": {
    "id": "@guid", 
    "name": "${body.name}" 
  }
}
```
现象：
返回值取不到 body的name值

## 什么浏览器
~ chrome

## 什么系统（Linux, Windows, macOS）
Windows

**Comment by gaoxiaomumu** [comment]
下一个版本会支持  格式为${body.fields.name}

**Comment by gaoxiaomumu** [comment]
下个版本会改正
