### ISSUE TITLE
强烈建议-界面化配置和自动更新swagger的接口

### ISSUE THREAD

**Issue by mahaixue** [YMFE/yapi#313]
## 版本号
~ 1.3.14

## 什么问题
~
现在做了命令行导入swagger的功能与实际应用场景不符。
swagger的路径可以由每个项目的人自行进行配置和修改（可以进行修改），可以手动和设置自动刷新，目的是接口信息变动不用再手动进行导入。

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by junchaozhang** [comment]
可以通过url的方式来导入swagger文档，参考easy-mock

**Comment by suxiaoxin** [comment]
https://juejin.im/post/5af500e251882567096140dd
