### ISSUE TITLE
编辑接口的示例值保存后不生效

### ISSUE THREAD

**Issue by mahaixue** [YMFE/yapi#314]
![yapi](https://user-images.githubusercontent.com/34730549/39872528-df17c7ae-549a-11e8-9e44-7c4d2cb18ced.png)
## 版本号
~ 1.3.14

## 什么问题
~编辑接口的示例值保存后不生效（没有把示例值 进行保存）

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by mahaixue** [comment]
之前保存的示例值都没有了

**Comment by fanxinjie** [comment]
不管是get方法的query参数还是post方法的json数据，保存之后只会保留数据结构，不会保留对应的值

**Comment by gaoxiaomumu** [comment]
那个圈圈里面的只是示例，不是参数值
