### ISSUE TITLE
服务端自动化测试-测试报告页面蓝屏

### ISSUE THREAD

**Issue by liuyu1992** [YMFE/yapi#317]
## 版本号
~1.3.15

## 什么问题
~点击服务端自动化测试，跳转至测试报告页面，页面展示背景色为蓝色

## 如何复现此问题
~ 每次打开服务端自动化测试跳转至测试报告页面都会出现

## 什么浏览器
~ 谷歌浏览器

## 什么系统（Linux, Windows, macOS）
访问系统为window，yapi部署系统为linux

详情见下图
![image](https://user-images.githubusercontent.com/9974103/39914997-3f21d75e-5539-11e8-8fbc-beec08c2786b.png)

**Comment by gaoxiaomumu** [comment]
我怀疑是你请求的接口里面有样式参数才造成这个原因，我们这边无法复现这个bug

**Comment by liuyu1992** [comment]
另外还需要我提供什么内容？

**Comment by gaoxiaomumu** [comment]
有可能你的返回值里面有将全局body color 变蓝色的参数

**Comment by gaoxiaomumu** [comment]
我们这边出现样式错乱发现问题是因为某个接口错误拉到404或者错误页面的时候将页面样式也同时给拉过来了
