### ISSUE TITLE
添加分组功能

### ISSUE THREAD

**Issue by wangyuan0108** [YMFE/yapi#318]
## 版本号

官网1.3.9
## 什么问题
只有一个个人中心分组，没有看到类似教程文档中的添加分组的按钮

## 如何复现此问题
新注册的用户，想团队合作，但是没有团队设置的功能显示。

## 什么浏览器
谷歌

## 什么系统（Linux, Windows, macOS）
Windows

**Comment by wangyuan0108** [comment]
![v8ozzxjhbjedwx8gh h d3x](https://user-images.githubusercontent.com/22407253/39919632-cc0a1a48-5546-11e8-9430-60aa1420ff5e.png)

**Comment by suxiaoxin** [comment]
https://yapi.ymfe.org/documents/manage-team.html

**Comment by wangyuan0108** [comment]
请问超级管理员怎么联系，我想创建个分组

**Comment by gaoxiaomumu** [comment]
找部署yapi 的人帮你建一个分组

**Comment by xianwei** [comment]
@gaoxiaomumu 能不能增加全局分组的功能啊。
