### ISSUE TITLE
关于添加请求参数

### ISSUE THREAD

**Issue by wnstar** [YMFE/yapi#32]
能支持类似于postman那种添加请求参数的方式吗
不然需要一条一条的添加请求

**Comment by suxiaoxin** [comment]
需求已收集

**Comment by Wnstar** [comment]
已更新新版header头在测试中已可以保存 但是现在遇到了一个问题想要问一下
类似于想要实现这样一个效果
token $.21.body.token  在运行测试的时候拼接成 "token 123332112312322"
现在似乎是不支持的 未来是会添加吗？

**Comment by Wnstar** [comment]
尝试自己加了一下这个功能。。。

**Comment by suxiaoxin** [comment]
@Wnstar 
![image](https://user-images.githubusercontent.com/17695103/32821061-1b695c8e-c997-11e7-87b5-6f7e41739586.png)
下个版本支持了{}变量和管道表达式，支持多种加密方式

**Comment by suxiaoxin** [comment]
未来还将会构建一个可视化的表达式生成器，方便填写

**Comment by Wnstar** [comment]
@suxiaoxin 希望能尽快上批量添加参数的功能
我们这每个接口都有5个一样的header头 一个一个添加太麻烦。。。

**Comment by suxiaoxin** [comment]
直接复制接口

**Comment by suxiaoxin** [comment]
@wnstar

**Comment by wnstar** [comment]
有道理。。
