### ISSUE TITLE
不支持自定义域名的邮箱登录

### ISSUE THREAD

**Issue by kevinaskin** [YMFE/yapi#321]
## 版本号
 1.3.15

## 什么问题
前端页面不支持匹配自定义域名的邮箱登录  
邮箱validate规则和后端不符
即 后端生成的admin账号无法在前端登录

e.g.     xxxx@minus.live

## 如何复现此问题

前端登录页面

## 什么浏览器

chrome

## 什么系统（Linux, Windows, macOS）

macOS

**Comment by gaoxiaomumu** [comment]
下一个版本会支持的
