### ISSUE TITLE
能不能根据接口定义直接生成代码

### ISSUE THREAD

**Issue by dumingxin** [YMFE/yapi#322]
## 版本号
~  1.3.14

接口定义好之后，能不能自动生成接口代码，以Java为例，自动生成interface和bean。能不能提供一个思路

**Comment by gaoxiaomumu** [comment]
目前没有这个功能

**Comment by CXL6688** [comment]
读取数据库数据，分析出来参数，请求类型，请求头等数据，然后使用feginclient来生成代码。
