### ISSUE TITLE
当自动化测试时，脚本中使用不了 localStorage

### ISSUE THREAD

**Issue by FurionCS** [YMFE/yapi#323]
## 版本号
~ 

## 什么问题
~
自动化测试错误脚本错误
## 如何复现此问题
~ 
脚本中加入localStorage 操作
使用自动化测试时，可以复现
## 什么浏览器
~ 
chrome

## 什么系统（Linux, Windows, macOS）
macOs

**Comment by suxiaoxin** [comment]
不支持
