### ISSUE TITLE
使用Swagger导入Response 对象嵌套对象时解析失败

### ISSUE THREAD

**Issue by dvsv2** [YMFE/yapi#325]
## 版本号
1.3.15
## 什么问题
使用swagger 导入接口 response 结构没有解析出来 mock报错
![image](https://user-images.githubusercontent.com/17610401/40035784-080ef6e8-5836-11e8-910b-bccd1bf19a6d.png)
![image](https://user-images.githubusercontent.com/17610401/40035796-16b08504-5836-11e8-9060-0886b74c7e62.png)

## 如何复现此问题
swagger代码：
`{
"swagger": "2.0",
"info": {
"description": "仅供测试",
"version": "1.0",
"title": "Swagger2",
"contact": {
"name": "dvsv2"
},
"license": {}
},
"host": "localhost:8081",
"basePath": "/",
"tags": [
{
"name": "user-controller",
"description": "User Controller"
}
],
"paths": {
"/users": {
"get": {
"tags": [
"user-controller"
],
"summary": "获取用户列表",
"operationId": "getUserListUsingGET",
"consumes": [
"application/json"
],
"produces": [
"*/*"
],
"parameters": [
{
"name": "StringT",
"in": "query",
"description": "stringT",
"required": true,
"type": "string"
},
{
"name": "intT",
"in": "query",
"description": "intT",
"required": true,
"type": "integer",
"format": "int32"
},
{
"name": "LongT",
"in": "query",
"description": "longT",
"required": true,
"type": "integer",
"format": "int64"
},
{
"name": "longT",
"in": "query",
"description": "longT_S",
"required": true,
"type": "integer",
"format": "int64"
},
{
"name": "booleanT",
"in": "query",
"description": "booleanT",
"required": true,
"type": "boolean"
},
{
"name": "doubleT",
"in": "query",
"description": "doubleT",
"required": true,
"type": "number",
"format": "double"
},
{
"name": "dateT",
"in": "query",
"description": "dateT",
"required": true,
"type": "string",
"format": "date-time"
}
],
"responses": {
"200": {
"description": "OK",
"schema": {
"type": "array",
"items": {
"$ref": "#/definitions/User"
}
}
},
"401": {
"description": "Unauthorized"
},
"403": {
"description": "Forbidden"
},
"404": {
"description": "Not Found"
}
}
}
}
},
"definitions": {
"User": {
"properties": {
"age": {
"type": "integer",
"format": "int32"
},
"id": {
"type": "integer",
"format": "int64"
},
"name": {
"type": "string"
},
"user": {
"$ref": "#/definitions/ParentUser"
},
"userMap": {
"type": "object",
"additionalProperties": {
"$ref": "#/definitions/User"
}
}
}
},
"Map«string,User»": {
"type": "object",
"additionalProperties": {
"$ref": "#/definitions/User"
}
},
"ParentUser": {}
}
}`

## 什么浏览器
Chrome

## 什么系统（Linux, Windows, macOS）
macOs

**Comment by gaoxiaomumu** [comment]
<img width="1018" alt="4cd88528-b80c-409b-8d0b-a170cf608bd9" src="https://user-images.githubusercontent.com/21135585/40038608-9fdb053e-5845-11e8-84e1-d9da81597b33.png">


你这里的ParentUser是空的，所以才会没有解析出来

**Comment by dvsv2** [comment]
不好意思这个是我这边的问题 我想说的其实是另一个问题 嵌套引用的问题  之前发错json了不好意思 麻烦看下下面这个json
`{
	"swagger": "2.0",
	"host": "http://localhost:3000",
	"basePath": "/",
	"paths": {
		"/test": {
			"get": {
				"summary": "aksjdngawet",
				"operationId": "xxxx",
				"parameters": [{
					"name": "int_t",
					"in": "query",
					"description": "int22211fasd",
					"required": true,
					"type": "integer",
					"format": "int32"
				}, {
					"name": "string_t",
					"in": "query",
					"required": true,
					"type": "string"
				}, {
					"name": "boolean_t",
					"in": "query",
					"required": true,
					"type": "boolean"
				}, {
					"name": "double_t",
					"in": "query",
					"required": true,
					"type": "number",
					"format": "double"
				}],
				"responses": {
					"200": {
						"description": "OK",
						"schema": {
							"type": "object",
							"properties": {
								"msg": {
									"type": "array",
									"items": {
										"$ref": "#/definitions/com.test.docment.mock.ClassA"
									}
								},
								"code": {
									"type": "integer",
									"format": "int32",
									"minimum": 199.0,
									"maximum": 201.0,
									"exclusiveMinimum": true,
									"exclusiveMaximum": true,
									"default": 200
								}
							}
						}
					}
				}
			}
		}
	},
	"definitions": {
		"com.test.docment.mock.ClassA": {
			"required": ["a", "classAAA", "testClass"],
			"properties": {
				"a": {
					"type": "integer",
					"format": "int32"
				},
				"testClass": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/com.test.docment.mock.ClassA"
					}
				},
				"classAAA": {
					"$ref": "#/definitions/com.test.docment.mock.ClassA"
				}
			}
		}
	}
}`

**Comment by gaoxiaomumu** [comment]
你这个明显是递归调用吧，自己调用自己
![image](https://user-images.githubusercontent.com/21135585/40093717-0706a596-58f6-11e8-9056-7897c28c2d9a.png)
swagger编译器也不解析的
![image](https://user-images.githubusercontent.com/21135585/40093698-f896b7da-58f5-11e8-9bd5-e6afd191e236.png)

**Comment by dvsv2** [comment]
嗯 是的 感觉这种页面上展示是不是可以优化下 要不类型直接是空白看起来有些诧异，算是提个建议。 @gaoxiaomumu

**Comment by gaoxiaomumu** [comment]
应该不会这么智能的，我们也是调用swagger的解析方案，没有解析出来就只会是空的，可以自己检查一下swagger是否有问题再导入
