### ISSUE TITLE
导入postman没有分类

### ISSUE THREAD

**Issue by xiaodongning** [YMFE/yapi#326]
## 版本号
~ v1.3.15
  postman 6.0.10

## 什么问题
~ postman导入没有分类，全部导入到选择的分类下；看了更新信息之前版本已经修复，但是我部署的和官网演示的都有此问题
![tim 20180515153645](https://user-images.githubusercontent.com/11451347/40043053-e6bc205e-5855-11e8-82cc-7b80734feb0f.jpg)

## 如何复现此问题
~  

## 什么浏览器
~ 谷歌浏览器

## 什么系统（Linux, Windows, macOS）
linux

**Comment by gaoxiaomumu** [comment]
有demo吗？

**Comment by xiaodongning** [comment]
[demo.txt](https://github.com/YMFE/yapi/files/2003913/demo.txt
在postman导出是两个分类

**Comment by gaoxiaomumu** [comment]
不知道你用的postman是什么版本的，我发现你的demo里面的这个字段，我们处理的时候是按照 collectionId 来处理的，我测试了一下我这边的postman导出的也是这个collectionId字段
![image](https://user-images.githubusercontent.com/21135585/40047849-32159e4c-5863-11e8-8e0b-5f69bc1517c2.png)

**Comment by xiaodongning** [comment]
我用的是官网下的postman 6.0.10，在postman导入导出都没问题。不过问题不大，把collection替换下就好了。

**Comment by winner1207** [comment]
不管用postman v1还是v2导出来再导入进去都没办法分类哦，可以提供一下你们导入的一个demo吗

**Comment by Zeral-Zhang** [comment]
这个问题好像没有解决呀？

**Comment by qunfm** [comment]
mac 10.13.4 postman导入的数据没有按在postman中分类，如图接口全部到了公共分类里，新用户流程集合为空
![image](https://user-images.githubusercontent.com/18373813/63638599-08301c00-c6bd-11e9-9484-c83c78e5c621.png)

![image](https://user-images.githubusercontent.com/18373813/63638579-bdae9f80-c6bc-11e9-9cb8-264353f13760.png)
