### ISSUE TITLE
提个建议： 相同测试集合可能兼容不同系统的接口

### ISSUE THREAD

**Issue by MattGong** [YMFE/yapi#328]
现在相同测试集合所有接口只能设置相同的环境即domain是一样的。 但是我们的系统比较庞大，被拆成了不同的模块，所以域名也不一样。 如果要测试一个流程，现在的yapi没有办法实现。

**Comment by gaoxiaomumu** [comment]
可以的，在每个测试接口里面设置环境变量，自动化测试的时候选默认环境就好
![image](https://user-images.githubusercontent.com/21135585/40056816-1dc2bbf2-587f-11e8-96e0-a0acc3c9bab0.png)

**Comment by MattGong** [comment]
多谢。
