### ISSUE TITLE
[request feature]增加接口文档页面及接口数据导出

### ISSUE THREAD

**Issue by shixuev5** [YMFE/yapi#33]
能否增加一个接口文档的预览页面及接口数据导出的功能或者接口？😋

**Comment by suxiaoxin** [comment]
马上发布这个功能，可以加下qq群

**Comment by suxiaoxin** [comment]
![image](https://user-images.githubusercontent.com/17695103/32650163-597cb666-c5c2-11e7-8712-853636aba2aa.png)
![image](https://user-images.githubusercontent.com/17695103/32650172-6345451e-c5c2-11e7-976a-3f8dc3836762.png)
支持 markdown, html

**Comment by shixuev5** [comment]
👌数据能导出json吗？

**Comment by suxiaoxin** [comment]
不支持，直接去mongodb拿吧
