### ISSUE TITLE
swagger导入数据的文件夹选择

### ISSUE THREAD

**Issue by zhaijg** [YMFE/yapi#330]
## 什么问题

swagger通过命令导入数据的时候,如何指定导入的文件夹

yapi import --config=F:\my-yapi\yapi-import-1.json

config 都有哪些配置

**Comment by gaoxiaomumu** [comment]
如果swagger没有分类的话会导入到yapi项目的第一个分类中
![image](https://user-images.githubusercontent.com/21135585/40161095-3de848fc-59e2-11e8-9d18-0ab4c445a090.png)
