### ISSUE TITLE
导出的文档，文档中返回数据为空

### ISSUE THREAD

**Issue by xieyingbiao** [YMFE/yapi#331]
![image](https://user-images.githubusercontent.com/26758497/40169268-3597d5b2-59f8-11e8-9b26-9fe21bb063df.png)
[图片]
![image](https://user-images.githubusercontent.com/26758497/40169281-3f2c8212-59f8-11e8-9806-2610b8c9355b.png)

**Comment by gaoxiaomumu** [comment]
你的返回数据好像有问题，请问返回数据格式是啥？ json? 吗？

**Comment by gaoxiaomumu** [comment]
![image](https://user-images.githubusercontent.com/21135585/40173988-3ad87b4a-5a06-11e8-8fc9-62d62d6e4564.png)
我猜返回值可能是这个的，可以将json-schema关掉，就会出现这确定的值
这个问题会在下个版本里面被修改
