### ISSUE TITLE
对每个API单独设置邮件通知，不生效。只能通过全局设置邮件通知，才生效

### ISSUE THREAD

**Issue by juveinfo** [YMFE/yapi#332]
## 版本号
~ 

## 什么问题
~

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by gaoxiaomumu** [comment]
对每个接口实施邮件通知必须每次编辑的时候打开邮件通知按钮，否则下一次接口更新的时候邮件通知也是关闭的

**Comment by juveinfo** [comment]
@gaoxiaomumu明白你的意思了，多谢你的介绍。
