### ISSUE TITLE
强列建议： 后面的测试接口可以取前面接口返回的header中的字段，起码可以取返回的Cookie

### ISSUE THREAD

**Issue by MattGong** [YMFE/yapi#334]
强列建议： 后面的测试接口可以取前面接口返回的header中的字段，起码可以取返回的Cookie

我们的登录接口返回的登录信息放在header的cookie里面的，现在前面登录了，后面接口取不到cookie，无法请求。

**Comment by gaoxiaomumu** [comment]
在请求配置里面应该可以获取header值

**Comment by MattGong** [comment]
这个能具体说说怎么弄吗？ 我要获取的是返回结果的header，我在Pre-response Script里面获取到header的cookie之后，怎么让下游其他接口取到呢？

**Comment by qdpiaoliang** [comment]
贴一下服务后台自动化测试的修改代码

**Comment by a-gui** [comment]
我也遇到这个问题，在做服务后台自动化测试时无法解决。
【问题】
后续接口需要用到登录响应数据header里的cookie
在环境配置中，去cookie配置了可以使用，但由于cookies每隔几小时就过期了。造成服务后台自动化测试时，每隔几小时就报错，需要不停去更新这个cookies

【需要帮助】
1.官方目前好像不支持从响应header里获取cookie,其他有个什么方法可以直接获取登录后header里的cookie呢
2.或者在请求脚本里Pre-response Script里面获取到header的cookie，传给下游接口，请教大佬们知道怎么搞吗？查了几天了解决不了了，特此求助。

**Comment by wzshuang** [comment]
第一个接口是查询文章列表，第二个接口是根据id查询文章详情，第二个接口有办法获取到第一个接口里的id吗

**Comment by wzshuang** [comment]
> 第一个接口是查询文章列表，第二个接口是根据id查询文章详情，第二个接口有办法获取到第一个接口里的id吗

官方文档里写了：[测试集合](https://hellosean1025.github.io/yapi/documents/case.html#%e7%ac%ac%e4%b8%80%e6%ad%a5%ef%bc%8c%e6%b5%8b%e8%af%95%e9%9b%86%e5%90%88)

**Comment by eyotang** [comment]
服务端跑自动化的时候，就不行。
确实有必要开放出来呀。

**Comment by fly2tomato** [comment]
已解决，方案如下：
在Pre-request Script(请求参数处理脚本)添加：
`context.requestHeader.authorization = storage.getItem('bearerToken')
console.log('req:', storage.getItem('bearerToken'))`
在Pre-response Script(响应数据处理脚本)添加：
`console.log('rsp: '+context.responseHeader.authorization)
storage.setItem('bearerToken', context.responseHeader.authorization)`
