### ISSUE TITLE
接口的某些Header头不能删除【Bug】

### ISSUE THREAD

**Issue by olderwei** [YMFE/yapi#336]
## 版本号
~ 1.3.15

## 什么问题
~接口编辑页面，如果有一个Content-Type为application/x-www-form-urlencoded的Header头，这个头删除不了

## 如何复现此问题
~ 

## 什么浏览器
~ Chrome

## 什么系统（Linux, Windows, macOS）
Windows
![qq 20180518153049](https://user-images.githubusercontent.com/7620855/40221922-7cc57328-5ab0-11e8-85c9-e26dfe88d63a.jpg)

**Comment by gaoxiaomumu** [comment]
这是因为你的请求body是form格式，yapi自动添加的header

**Comment by olderwei** [comment]
好的,明白了，可以关闭了
