### ISSUE TITLE
请求参数设置，添加Header，Header参数值没有提交到服务器。

### ISSUE THREAD

**Issue by herson-he** [YMFE/yapi#339]
## 版本号
1.3.15

## 什么问题
请求参数设置，添加Header，Header参数值没有提交到服务器。

## 如何复现此问题
添加POST接口，修改Header参数，提交。

## 什么浏览器
~Chrome 66

## 什么系统（Linux, Windows, macOS）
WIN10

![image](https://user-images.githubusercontent.com/7065803/40399158-5762a2e2-5e6e-11e8-8a26-d7bd5360144b.png)

**Comment by gaoxiaomumu** [comment]
是否能够更详尽的描述一下问题

**Comment by gaoxiaomumu** [comment]
![image](https://user-images.githubusercontent.com/21135585/40400140-68c8d86c-5e73-11e8-8c5a-5e1409dd7984.png)
可能是因为你的bod里面的数据类型是text，yapi会自动保存为 application/x-www-form-urlencoded类型，如果你想要multipart/form-data可以在测试集合中重新定义

**Comment by herson-he** [comment]
好的，谢谢。
