### ISSUE TITLE
ui错误

### ISSUE THREAD

**Issue by yuu2lee4** [YMFE/yapi#34]
移动到行程搜索，下面的记账旁边的 几个功能按钮出来了
![image](https://user-images.githubusercontent.com/8046366/32654056-e533a9e4-c644-11e7-9985-ed89a7bdd8a0.png)
只有移动到行程搜索上有这个情况

版本:1.2.5

**Comment by suxiaoxin** [comment]
未来会禁用拖动功能，改成其他方式实现

**Comment by yuu2lee4** [comment]
目前这个问题还有哦 version:1.3.1
