### ISSUE TITLE
Node 10.1 初始化失败.

### ISSUE THREAD

**Issue by crper** [YMFE/yapi#340]
## 版本号
~ V1.3.15

## 什么问题
~ 部署初始化失败,走不下去..试过好多次
![image](https://user-images.githubusercontent.com/8272877/40402504-a938be84-5e7e-11e8-880c-114d66da1871.png)

也换过不同的目录初始化
![image](https://user-images.githubusercontent.com/8272877/40402478-792dbdca-5e7e-11e8-9c16-05ee6370a4c1.png)

## 如何复现此问题
~ 常规操作, 全局安装了 yapi , yapi server

## 什么浏览器
~ Chrome,

## 什么系统（Linux, Windows, macOS）
MACOS 最新版 / Node v10.1.0 /

**Comment by gaoxiaomumu** [comment]
可能是node 版本太高了
