### ISSUE TITLE
需求+优化

### ISSUE THREAD

**Issue by GloomyNAN** [YMFE/yapi#343]
## 版本号

1.3.15

## 什么问题

** 希望增加如下功能 **

1. 接口分类支持无限分类功能
2. 拖动接口更改到其他分类

** 优化 **

1. 已收藏的项目改名字后，我的收藏还是老的名字

**Comment by gaoxiaomumu** [comment]
1. 这个可能不会做改变
2. 目前是支持接口拖动和分类拖动的

**Comment by GloomyNAN** [comment]
好的，感谢。
另外增加一个优化需求，如果动态查询能按照成员来查询就很方便了，有的时候要review一下其他人的改动

**Comment by gaoxiaomumu** [comment]
你可以按照接口查询不是更好？
