### ISSUE TITLE
1.3.16升级后测试集合报404

### ISSUE THREAD

**Issue by bingoyan** [YMFE/yapi#347]
## 版本号
~1.3.16 

## 什么问题
~从1.3.14版本通过命令升级到1.3.16版本后进入项目的测试集合就报404错误，具体链接为：
http://xxxxx.com/api/project/get_env?project_id=7
这个请求404

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by gaoxiaomumu** [comment]
重启一下node服务器
