### ISSUE TITLE
只修改参数 必需/非必需, 文本/文件 时, 查看改动详情, 提示没有改动

### ISSUE THREAD

**Issue by Wyntau** [YMFE/yapi#348]
## 版本号
~ v1.3.15

## 什么问题
~ 只修改参数 必需/非必需, 文本/文件 时, 查看改动详情, 提示没有改动

![image](https://user-images.githubusercontent.com/2631733/40522106-be0c29f2-6001-11e8-9e3d-3b62420c2f62.png)

## 如何复现此问题
~ 只修改参数 必需/非必需, 文本/文件 时, 查看改动详情, 提示没有改动

## 什么浏览器
~ any

## 什么系统（Linux, Windows, macOS）
~ any

**Comment by gaoxiaomumu** [comment]
已修改
