### ISSUE TITLE
导入swagger2的json文件，header的设置丢失

### ISSUE THREAD

**Issue by li-keli** [YMFE/yapi#350]
## 版本号
1.3.12

## 什么问题
导入swagger2的json文件，header的设置并没有导入。

例如：
```json
"/hotel/list": {
            "post": {
                "tags": [
                    "Demo接口"
                ],
                "summary": "Demo接口",
                "description": "Demo接口",
                "operationId": "listUsingPOST",
                "consumes": [
                    **"application/json"**
                ],
                "produces": [
                    **"application/json"**
                ],
                "parameters": [
                   ···
                ],
                "responses": {
                   ···
                }
            }
        }
```

已经定义好了json的content，但是导入后，发现YAPI并没将这项加入head设置。

**Comment by gaoxiaomumu** [comment]
最好有demo,还有详细说明以下问题   ，你希望哪组数据存在但是yapi没有展示出来

**Comment by JerryChaox** [comment]
"consumes": ["application/json"]
![image](https://user-images.githubusercontent.com/20492061/40596758-90f22b04-626f-11e8-93c8-af597740534d.png)
这个属性无法让这里设置请求的header

**Comment by JerryChaox** [comment]
"parameters": [
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "type": "string",
                        "default": "application/json"
                    },
]
这种写法也不行

**Comment by JerryChaox** [comment]
"consumes": ["application/json"]

**Comment by JerryChaox** [comment]
"consumes": ["application/json"]

**Comment by JerryChaox** [comment]
"consumes": ["application/json"]
用这种写法时导出后到编辑界面按一下保存，头部信息就出来了

**Comment by li-keli** [comment]
@JerryChaox 经过测试，我这边也是这样，导入后，在编辑界面看不到关于head content-type的预填信息，但是按一下保存，就可以在预览看到head中已经将content-type设置为json了。

@gaoxiaomumu 请查看一下。

**Comment by gaoxiaomumu** [comment]
这个是导入的时候   Content-Type字段是有的但是  default中的值没有了对吧

**Comment by caiboking** [comment]
导入swagger2文件失败，详细错误提示哪里看？
