### ISSUE TITLE
Feature Request：希望可以增加定义全局通用数据结构的模块

### ISSUE THREAD

**Issue by Nomia** [YMFE/yapi#352]
用了一段时间yapi，飞一般的感觉，谢谢yapi团队。

提议一个功能：需要一个定义通用数据结构的地方

场景：例如，我们写了20个API都跟某个特定的资源(resource)有关，那么，我们为了让前端小伙伴非常清楚的知道这个资源(resource)数据结构里的每一个字段的意思，我们需要对每个字段做注解，那么就要注解20次。一旦这个资源(resource)数据结构在业务发展过程中增加了字段，我们就需要对这20个接口说明进行更新。所以，希望有一个定义`通用数据结构`的地方，定义一次，以后在写接口的时候，只用加上链接就好了。也只用维护一处数据结构。

这个功能不一定要单独实现，

目前编辑功能这么好，能够提供一个脱离API写文档的地方也非常好，现在写文档都是在某个api的定义内。
有些全局性的东西需要写的时候，只能写在API的备注中。希望可以将文档单独出来一个模块，就可以解决很多问题。

谢谢！

**Comment by JerryChaox** [comment]
可以尝试用swagger

**Comment by Nomia** [comment]
谢谢推荐，不开源的东西暂时不大想用😁 @JerryChaox 

另外，yapi已经用了一段时间了，整体感觉不错，自己还可以定制，多好。
如果改掉的话，会被团队打残

**Comment by JerryChaox** [comment]
意思是代码里面集成swagger，通常是注释，导出成swagger.json，导入yapi，和你目前做的不冲突，而且可实现自动化，方便后端及时同步文档

**Comment by Nomia** [comment]
了解，但是不是我想要的功能

**Comment by JerryChaox** [comment]
swagger就有你想要的功能，相当于在另外一块写文档，可以了解一下你们团队是用什么语言吗@Nomia

**Comment by Nomia** [comment]
PHP语言，laravel框架

**Comment by hellosean1025** [comment]
我也建议用 swagger，再配合 yapi

**Comment by Nomia** [comment]
不大想用两个工具，另外不太喜欢swagger的布局。

**Comment by fudali113** [comment]
@JerryChaox 想问下你们使用 swagger 做自动化是怎么做的啊？方便说下么？

**Comment by JerryChaox** [comment]
@fudali113 github的hook 和 命令行导入就可以实现

**Comment by hellosean1025** [comment]
@fudali113 https://juejin.im/post/5af500e251882567096140dd

**Comment by fudali113** [comment]
谢谢 @hellosean1025 
* 那每次更新 swagger 提供的 api 都是提供的全量的 api 数据，我想知道我再进行批量更新的时候，yapi 是否能够正确处理重复的未更改的 api 并且通知和变更记录是否能够正常的工作？
* 包括有些 api 我们可能还会导入后在 yapi 平台上进行修改，那下次导入的时候怎么解决？

如果可以我感觉结合 ci 来做这个事情应该是一个很不错的方案；

**Comment by hellosean1025** [comment]
1. 能够正确处理
2. 这个暂时没有好的处理办法，如果 `merge` 参数为 `true`，会覆盖更新的接口数据，原来的修改会丢失。

**Comment by xjdata** [comment]
@hellosean1025  请考虑下,只是定义接口的人员的需求, 比如我只是管理,并不会真的去写代码.   这样的时候楼主说的需求就比较普遍了.

**Comment by Fantasy9527** [comment]
附议,要是有通用数据格式,维护的时候会方便很多

**Comment by seamounts** [comment]
这个不计划支持吗？通用数据数据结构可以极大的提高效率，是一个非常重要的能力。
