### ISSUE TITLE
交互优化建议

### ISSUE THREAD

**Issue by zhfish** [YMFE/yapi#353]
## 版本号
~ 
All
## 什么问题
~
接口列表，和右边的内容，应该分区域滚动
目前的情况，900个接口，滚到下面选择一个接口，还要滚上来操作-_-# 太绝望了
## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by hellosean1025** [comment]
建议把一个项目拆分成多个项目管理

**Comment by zhfish** [comment]
不多说，一个项目100个接口不算多吧..9个分类，一展开就绝望了..
我900个接口，肯定可以拆，但并不能解决问题

**Comment by FurionCS** [comment]
还是希望能支持多级目录

**Comment by cwj0130** [comment]
目前用的doclever，觉得这个api管理工具功能更强大，唯一担忧的就是多层级文件夹不支持，接口多了真没办法

**Comment by gaoxiaomumu** [comment]
现在测试集合支持多项目接口导入，完全可以将一个项目拆分成多个项目
