### ISSUE TITLE
1.3.15升级到1.3.16后，能够访问但是页面无法正常显示

### ISSUE THREAD

**Issue by JerryChaox** [YMFE/yapi#354]
## 什么问题
![image](https://user-images.githubusercontent.com/20492061/40704655-51964992-641b-11e8-8c4a-b3cd1b251b97.png)

而且出现一处js错误
![image](https://user-images.githubusercontent.com/20492061/40704732-9186f56a-641b-11e8-95e5-fb0dbf86eaea.png)

日志显示正常
[ 2018-5-30 14:59:57 ] [ log ] the server is start at 127.0.0.1:7061
[ 2018-5-30 15:00:51 ] [ log ] the server is start at 127.0.0.1:7061
[ 2018-5-30 15:00:51 ] [ log ] mongodb load success...
[ 2018-5-30 15:02:47 ] [ log ] the server is start at 127.0.0.1:7061
[ 2018-5-30 15:02:47 ] [ log ] mongodb load success...
[ 2018-5-30 15:06:04 ] [ log ] the server is start at 127.0.0.1:7061
[ 2018-5-30 15:06:04 ] [ log ] mongodb load success...

清除浏览器历史记录后显示正常。

## 如何复现此问题
登陆，更新项目，重启服务器，浏览器再次访问正常，但出现白屏无法显示页面，清除历史记录恢复正常

## 什么浏览器
google

## 什么系统（Linux, Windows, macOS）
Linux

**Comment by gaoxiaomumu** [comment]
好像是node-sass-china 的问题，先不要升级了，等下一个版本吧
