### ISSUE TITLE
升级后一直无法搜索到用户

### ISSUE THREAD

**Issue by JerryChaox** [YMFE/yapi#355]
## 什么问题
从1.2.x 升级到了 1.3.15后，无法搜索到用户，提示用户不存在，但是用户确实存在。
重新注册一个新的用户，也无法搜索

本地的mongodb版本是2.6.2
发现
db.user.find(username: {$regex: \^Jerry\})
db.user.find(username: {$regex: \Jerry\})
db.user.find(username: {$regex: \^Jerry\i})
db.user.find(username: {$regex: \Jerry\i})
只有第一个才能正常搜索到Jerry这个用户

于是源码改成这样后才能搜索得到：
{ email: new RegExp("^" + keyword) },
{ username: new RegExp("^" + keyword) }

本人查阅文档之后进行的测试，不太懂mongodb，不知道具体时什么原因

**Comment by hellosean1025** [comment]
重启服务器试试
