### ISSUE TITLE
需求

### ISSUE THREAD

**Issue by wewooo** [YMFE/yapi#358]
## 版本号
~ 
1.3.16
## 什么问题
~
希望增加真实接口返回数据和接口设置中的返回数据结构进行对比，方便测试人员查看接口返回数据是否和YApi平台上设置的返回数据是否一致。

**Comment by cnlzxin** [comment]
这个怎么实现 ?

- 一次性调两个接口 ?
- 先调 YApi 的接口, YApi 再调真实接口 ?

不合适吧

**Comment by wewooo** [comment]
@cnlzxin YApi已经预先设置好了返回字段结构了

**Comment by wewooo** [comment]
@JerryChaox 自己写当然可以，单如果能YApi能集成这样的功能不是更好
