### ISSUE TITLE
接口大小写不一样会认为是不同的url。

### ISSUE THREAD

**Issue by ASkyBig** [YMFE/yapi#361]
## 版本号
~ 1.3.9

## 什么问题
~ getInfo与GetInfo不会认为是同一个url

## 如何复现此问题
~ 新建getInfo与GetInfo两个接口

## 什么浏览器
~ Chrome

## 什么系统（Linux, Windows, macOS）
macOS

**Comment by cnlzxin** [comment]
难道不应该这样吗

**Comment by ASkyBig** [comment]
浏览器不是默认忽略大小写吗？你输入www.baidu.com和WWW.BAIDU.COM或者www.BaiDu.com都是指向www.baidu.com

**Comment by cnlzxin** [comment]
这是前端的 url 吧, YApi 定义的是后端的接口

**Comment by wd** [comment]
域名是没有大小写的，但是 url path 是有的。下面两个你比较下。

https://mbd.baidu.com/newspage/Data/landingsuper?context=%7B%22nid%22%3A%22news_6844273294094452965%22%7D&n_type=0&p_from=1

https://mbd.baidu.com/newspage/data/landingsuper?context=%7B%22nid%22%3A%22news_6844273294094452965%22%7D&n_type=0&p_from=1

**Comment by ASkyBig** [comment]
ok，谢谢各位，应该是yapi内部规则没有实现大小写转换
