### ISSUE TITLE
MacOs使用yapi server安装时一直处在正在部署，请稍后

### ISSUE THREAD

**Issue by jackiewillen** [YMFE/yapi#362]
## 版本号
~ 1.3.14

## 什么问题
~ 使用yapi server安装时一直处在正在部署，请稍后
~ 等待大概20分钟左右还是这样

## 如何复现此问题
~ 无

## 什么浏览器
~ chrome

## 什么系统（Linux, Windows, macOS）
macOs 
<img width="831" alt="wx20180602-130534 2x" src="https://user-images.githubusercontent.com/7625197/40870981-f3a9cfe6-6665-11e8-9d55-56134b0b541d.png">

**Comment by dengxife** [comment]
我也这样，请问你怎么解决的？

**Comment by jackiewillen** [comment]
@dengxife  虽然一直这样，但后来发现也装好了，而且好像没什么问题

**Comment by dengxife** [comment]
@jackiewillen 感谢回复，因为我这边一直没有响应。我最后采用的是先将源码git下来，然后通过命令行进行本地部署成功了。
