### ISSUE TITLE
导出json后再导入提示格式错误？

### ISSUE THREAD

**Issue by cxhuan** [YMFE/yapi#364]
## 版本号
1.3.16

## 什么问题
使用导出功能导出为json格式的文件。
再使用导入功能将该json文件导入。
提示格式错误。

## 如何复现此问题
每次操作都可以复现

## 什么浏览器
~Chrome

## 什么系统（Linux, Windows, macOS）
macOS

**Comment by cxhuan** [comment]
我又测试了不同的情况。是因为我自定义了一个和公共接口平行的分类之后，导出的json数据，第一个节点是null，再导入的话就会报错。
如果是在公共分类下创建接口，导出为如下形式：
![image](https://user-images.githubusercontent.com/3794383/40894783-7bc65484-67de-11e8-9b7d-55502493ea2b.png)
如果自定义分类创建接口，导出为如下形式：
![image](https://user-images.githubusercontent.com/3794383/40894809-9ee5972c-67de-11e8-9313-a168b48c7ad5.png)

**Comment by cxhuan** [comment]
进一步分析：
在公共分类和自定义分类下各添加一个接口，然后再导出，然后再导入，不会出问题。

所以问题应该是：
公共分类没有添加接口的情况下导出再导入会有问题。
公共分类添加接口的情况下导出再导入没有问题。

**Comment by gaoxiaomumu** [comment]
下个版本会修复
