### ISSUE TITLE
多个接口是否可以互相交互。

### ISSUE THREAD

**Issue by zhangwenwu** [YMFE/yapi#369]
## 版本号
~ 最新

## 什么问题
~我从A接口提交了一些数据，怎么样可以在B接口获取到我从A接口提交的数据呢！而不是用导入json的方式！

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by gaoxiaomumu** [comment]
https://yapi.ymfe.org/documents/case.html#%E7%AC%AC%E4%BA%8C%E6%AD%A5%EF%BC%8C%E7%BC%96%E8%BE%91%E6%B5%8B%E8%AF%95%E7%94%A8%E4%BE%8B

你可以详细看一下如何使用变量参数
