### ISSUE TITLE
域名配置指向 root 路径问题

### ISSUE THREAD

**Issue by zhong-1250044515** [YMFE/yapi#370]
你好，现在 `node vendors/server/app.js`  启动后，地址是 http://xxx:3000，如果要单独设置一个域名指向
 3000 端口，nginx.conf 的 `root` 路径要如何写？

**Comment by zhangwenwu** [comment]
不知道

**Comment by zhong-1250044515** [comment]
@gaoxiaomumu 我是不知道这个 nginx的root 要指向项目的哪个目录
