### ISSUE TITLE
复制接口操作，"返回数据设置"开关没有被复制

### ISSUE THREAD

**Issue by tandaly** [YMFE/yapi#371]
## 版本号
 1.3.16

## 什么问题
进行复制接口，复制后的接口"返回数据设置"开关没有被复制
![image](https://user-images.githubusercontent.com/3762187/41030857-d9fab94e-69b1-11e8-9564-9258be0b5b80.png)

## 如何复现此问题
复制接口
![image](https://user-images.githubusercontent.com/3762187/41030942-0d5bb7c0-69b2-11e8-86b3-83cff64a166d.png)

## 什么浏览器
 chrome

## 什么系统（Linux, Windows, macOS）
Windows

**Comment by tandaly** [comment]
@gaoxiaomumu 比如被复制的接口是选中状态，复制后的接口却是未选中状态

**Comment by gaoxiaomumu** [comment]
我们这边没有复现这个问题1.3.16并没有这个问题
