### ISSUE TITLE
api 同步是怎么做到的？

### ISSUE THREAD

**Issue by libra1010** [YMFE/yapi#372]
api 同步是怎么做到的？
比如我选择了swagger 导入
有一个开启同步的选项，这个同步是怎么做的

**Comment by gaoxiaomumu** [comment]
![image](https://user-images.githubusercontent.com/21135585/41087116-686d6bd8-6a6e-11e8-803c-9930cd9f7091.png)
开启数据同步只是说导入的时候遇到相同的接口会覆盖，如果不开启的话相同的接口保留原状

**Comment by libra1010** [comment]
@gaoxiaomumu  thanks

**Comment by dengxife** [comment]
请问一下这个同步是更具请求的接口地址来判定为相同？还是通过名称？
