### ISSUE TITLE
为什么不支持直接填写swagger 的JSON API地址

### ISSUE THREAD

**Issue by libra1010** [YMFE/yapi#373]
为什么不支持直接填写swagger 的JSON API地址
必须要用户上传json文件？

**Comment by gaoxiaomumu** [comment]
不支持，目前支持用命令行导入
https://yapi.ymfe.org/documents/data.html#%E9%80%9A%E8%BF%87%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%AF%BC%E5%85%A5%E6%8E%A5%E5%8F%A3%E6%95%B0%E6%8D%AE
