### ISSUE TITLE
yapi 支持 jsonp 跨域数据么?

### ISSUE THREAD

**Issue by cocody** [YMFE/yapi#374]
## 版本号
~ 最新

## 什么问题
~ yapi 支持 jsonp 跨域数据么? 查看文档并没有就此说明

## 如何复现此问题
~ 

## 什么浏览器
~ chrome

## 什么系统（Linux, Windows, macOS）
~ win10

**Comment by gaoxiaomumu** [comment]
不支持

**Comment by cocody** [comment]
有计划下一版能够支持么? 毕竟很多接口都需要用 jsonp 来跨域访问

**Comment by zhansingsong** [comment]
开发时也遇到此需求，就封装一个小工具：[jsonpify](https://github.com/zhansingsong/node-jsonpify) 。可以尝试一下
