### ISSUE TITLE
自动化文档插件

### ISSUE THREAD

**Issue by mynameisa** [YMFE/yapi#375]
yapi的使用体验很好，如果有一些配套的自动化文档的插件相信会有更多人使用，虽然你们支持swagger文档，而swagger已经有了这方面的配套功能，但是有没有考虑过推出自己的插件，生成yapi格式的json文档

**Comment by gaoxiaomumu** [comment]
我们支持用户自己写插件

**Comment by LichFaker** [comment]
@gaoxiaomumu 自己写插件的文档有吗？找了半天没找到

**Comment by jasonjoo2010** [comment]
@LichFaker 
https://yapi.ymfe.org/documents/plugin-dev.html
