### ISSUE TITLE
添加请求参数自动加1

### ISSUE THREAD

**Issue by tandaly** [YMFE/yapi#379]
## 版本号
 v1.3.17

## 什么问题
接口添加参数时，参数后面默认加1，而且还去掉不了

![image](https://user-images.githubusercontent.com/3762187/41215590-96e18ffe-6d83-11e8-8075-acbca57f81f5.png)

群里也有人出现了
![image](https://user-images.githubusercontent.com/3762187/41215857-df17cdb4-6d84-11e8-923f-6f92db26455c.png)

## 如何复现此问题

接口添加参数

## 什么浏览器
chrome

## 什么系统（Linux, Windows, macOS）
Windows

**Comment by gaoxiaomumu** [comment]
回退到1.3.16

**Comment by gaoxiaomumu** [comment]
现在应该好了
