### ISSUE TITLE
[BUG]接口路径参数问题

### ISSUE THREAD

**Issue by Wnstar** [YMFE/yapi#38]
接口路径参数一旦保存 就没办法在删除掉 在接口路径里删掉并不会修改数据库里的数据

还有mock的时候 无法获取接口路径里的参数

**Comment by suxiaoxin** [comment]
mock 还没支持获取路径参数数据

接口路径参数没法删掉文档，我查下

**Comment by suxiaoxin** [comment]
@Wnstar 路径参数已增加，下个版本更新
