### ISSUE TITLE
1.3.17版本创建接口问题

### ISSUE THREAD

**Issue by treeyh** [YMFE/yapi#381]
## 版本号
~  1.3.17

## 什么问题
~ 问题1：返回参数输入后面都跟1，如下图。点击退格提示“The field "m1s1g1a" already exists.”
![image](https://user-images.githubusercontent.com/916594/41224927-2acf4db6-6da0-11e8-9784-183fa33a5e59.png)
~ 问题2：path参数点击保存提示如下。
![image](https://user-images.githubusercontent.com/916594/41225075-8f847498-6da0-11e8-8a9f-08e05f80a6c6.png)

## 如何复现此问题
~ 新安装，

## 什么浏览器
~ chrome

## 什么系统（Linux, Windows, macOS）
~ 部署系统：Linux，操作：macOS

**Comment by gaoxiaomumu** [comment]
现在应该已经修好了，可以重新update一下

**Comment by gaoxiaomumu** [comment]
路径不是这么写的  应该是 
![image](https://user-images.githubusercontent.com/21135585/41228860-6d99bb2a-6dac-11e8-89c7-ef1e9cffdaae.png)
