### ISSUE TITLE
运行接口时不提交设置的body中参数

### ISSUE THREAD

**Issue by whhxz** [YMFE/yapi#384]
## 版本号
~ v1.3.17

## 什么问题
~ 在接口编辑完成后，运行接口，不提交body中数据，同样的数据在postman中正常

## 如何复现此问题
~ 1、编辑接口
   2、请求参数设置、body
   3、选择raw，参数：data={"storeId":"1001","itemNoList":["661978"]}
   4、设置Header：Content-Type=application/x-www-form-urlencoded
   5、点击运行、chrome打开调试
   6、点击发送，network中有请求信息，但是没有request body
   7、重新设置请求参数、body，选择form，添加data字段，重新发送，设置data字段val为上面json，请求正常，request body中存在数据

## 什么浏览器
~ chrome

## 什么系统（Linux, Windows, macOS）
~ Linux、macOS都不行

**Comment by gaoxiaomumu** [comment]
原因是设置Header：Content-Type=application/x-www-form-urlencoded  , 这个header使得数据没有办法带过去

**Comment by whhxz** [comment]
算个bug吗，在postman中，设置该Header是正常的

**Comment by gaoxiaomumu** [comment]
嗯，下个版本会修好

**Comment by choecode** [comment]
然而并没有修复好呀，我这边复现了。最新版本的yapi
