### ISSUE TITLE
环境配置的header中能否填写变量?

### ISSUE THREAD

**Issue by xjchenhao** [YMFE/yapi#386]
![image](https://user-images.githubusercontent.com/5373111/41332995-939961ba-6f12-11e8-9cb0-1b2f9ba5eacb.png)

开发团队你们好，
我想问下`环境配置的header中能否填写变量?`，为了做csrf防范，我的api接口会在cookie中注入名叫`csrfToken`的值。后续所有的api都要带上这个值。

不知道yapi能否实现这个需求。

>ps: 我目前使用的版本是1.3.16

**Comment by gaoxiaomumu** [comment]
这里不可以下变量，你可以在请求配置里面进行操作

**Comment by xjchenhao** [comment]
我上午试过在请求配置里操作。https://github.com/YMFE/yapi/issues/385

它没办法获取到api请求set-cookie进来到cookie，它只能拿到当前浏览器F12中Application中的cookie。这也就意味着我没办法在请求配置中注入`csrfToken`。

**Comment by gaoxiaomumu** [comment]
打印下 context.responseHeader 看看，如果服务端 set-cookie了，在这里应该能查到

**Comment by xjchenhao** [comment]
是的 可以看到，但是set-cookie只会在请求第一个接口的时候存在。需要有个地方把它存储起来呢？

**Comment by gaoxiaomumu** [comment]
如果是浏览器里面测试的话可以将变量存在localStorage  里面  window.localStorage.setItem('1', '23');

服务端测试不行

**Comment by xjchenhao** [comment]
如果服务器上设置两个`set-cookie`(如下图)，`context.responseHeader`里面只有第一个的`set-cookie`

![image](https://user-images.githubusercontent.com/5373111/41579143-4530cf08-73c8-11e8-860b-8deaf7dc8ea2.png)

**Comment by knktc** [comment]
我之前在用postman的时候有类似的需求，只是当时cookie和header可以设置为变量，在登录后执行一个test把这两个值给设置好。
现在的话，就是自己把测试环境的超时设置长，然后登录一次，自己手动改了……

**Comment by xjchenhao** [comment]
我现在的处理方式就是在代码的config里设置了csrf白名单（设置ip地址）。
也是临时方案，蛮不方便的，网络环境发生变化、或者新来个测试之类的，都要人工去修改这个。
