### ISSUE TITLE
关于 LDAP 登陆的问题

### ISSUE THREAD

**Issue by chenlingmin** [YMFE/yapi#387]
## 版本号

1.3.17

## 什么问题

* LDAP 登陆时，用户如果自己修改了用户名，再次登陆会是一个新的用户
* LDAP 配置能否区分 userName 与 email，因很多时候用户名与邮箱是分开的

## 如何复现此问题

1. 集成 ldap 登陆
2. ldap 中 cn 作为用户名， email 另一个字段存储
3. 用户登陆后修改自己的用户名，或者邮箱

**Comment by gaoxiaomumu** [comment]
第三方登陆用户自己是无法修改用户名的邮箱的

**Comment by gaoxiaomumu** [comment]
![image](https://user-images.githubusercontent.com/21135585/41343616-aa62b60c-6f31-11e8-98b1-f4667f51593a.png)
 最好用邮箱登陆

**Comment by chenlingmin** [comment]
每次第一次登陆时，是可以修改用户名的，刷新页面后就不能修改了
![ldap](https://user-images.githubusercontent.com/8233283/41345505-7536a664-6f36-11e8-8990-b87976b278a9.gif)

**Comment by gaoxiaomumu** [comment]
那有可能是我们的问题，我这边看一下，正常情况下是不可以修改的
