### ISSUE TITLE
选择接口就出现白屏，并且这个接口之后再也无法查看了，严重

### ISSUE THREAD

**Issue by wheelxxx** [YMFE/yapi#388]
## 版本号
~ 1.3.17

## 什么问题
~ 点击接口进入详情整个页面就变成了白屏，并且无法通过刷新解决该问题，之后此接口就无法继续查看了，这个问题很严重啊。
![2](https://user-images.githubusercontent.com/22809336/41341958-a374f412-6f2d-11e8-81d5-d3172c0b79ea.png)
![3](https://user-images.githubusercontent.com/22809336/41341966-aa5bf672-6f2d-11e8-936b-02c86bdaeae3.png)

## 如何复现此问题
~ 我不知道。。随机的，

## 什么浏览器
~ 谷歌浏览器66.0.3359.139

## 什么系统（Linux, Windows, macOS）
~部署是在Linux Centos

**Comment by gaoxiaomumu** [comment]
看一下控制台报什么错误

**Comment by wheelxxx** [comment]
可能是我用的方法有问题，导致了 页面鼠标悬浮提示的主键和数据库的主键不一致导致的无法查询到接口信息，先close了
