### ISSUE TITLE
继续刚刚的白屏issues

### ISSUE THREAD

**Issue by wheelxxx** [YMFE/yapi#389]
## 版本号
~ 1.3.17

## 什么问题
~ 还是白屏

## 如何复现此问题
~ 新建一个接口
![image](https://user-images.githubusercontent.com/22809336/41343635-b27afa48-6f31-11e8-809d-984310598156.png)
添加请求参数
![image](https://user-images.githubusercontent.com/22809336/41343667-c52975fc-6f31-11e8-9f11-0d51609fcc15.png)
我是通过直接生成json schema来生成接口字段信息的，因为我的接口数据来源于一个excel所以我写了一个脚本去读取该excel然后生成这个json schema
![image](https://user-images.githubusercontent.com/22809336/41343785-0da03fe6-6f32-11e8-86e0-f89136fd9e14.png)
很明显的成功了
![image](https://user-images.githubusercontent.com/22809336/41343815-213ea48e-6f32-11e8-82a9-677678d34c6e.png)
此时点击该接口查看是没有问题的
![image](https://user-images.githubusercontent.com/22809336/41343850-3f329b26-6f32-11e8-8b39-af2b96b75281.png)
数据库的确有一条该记录
![image](https://user-images.githubusercontent.com/22809336/41343874-4c83f2d4-6f32-11e8-859b-67cd360d03e3.png)
然后用同样的手法，生成响应的字段
![image](https://user-images.githubusercontent.com/22809336/41343903-6341f782-6f32-11e8-86ab-b2276ac9a48e.png)
但是保存完再查看该接口就白屏了
![image](https://user-images.githubusercontent.com/22809336/41343995-9d63a6a4-6f32-11e8-9328-93edb917aced.png)
但是数据库里这条记录是依然在的
然后又试验了下 只添加请求字段就不会有这个问题，
又试验了下 只添加响应字段就会白屏
所以现在看来和响应字段的关系很大，而且就只有我直接通过编辑json schema源码的方式添加字段才会有这个问题，正常通过页面添加没有该问题，请教下大佬们

## 什么浏览器
~ 谷歌浏览器66.0.3359.139

## 什么系统（Linux, Windows, macOS）
~部署是在Linux Centos

**Comment by gaoxiaomumu** [comment]
看一下控制台报什么错误

**Comment by wheelxxx** [comment]
我不知道控制台怎么看啊。。我已经nohup &后台运行了 怎么看控制台啊

**Comment by gaoxiaomumu** [comment]
打开chrome的开发者浏览器
![image](https://user-images.githubusercontent.com/21135585/41347730-2afc07a4-6f3d-11e8-9e91-42b980721574.png)

**Comment by gaoxiaomumu** [comment]
开发者工具

**Comment by wheelxxx** [comment]
![image](https://user-images.githubusercontent.com/22809336/41386236-1233a29c-6fb3-11e8-91e6-cf3653786f44.png)
出现白屏后，控制台报这个错

**Comment by wheelxxx** [comment]
看到了。。。。原来是我自己的问题，因为响应的字段有层级结构我跑的脚本写的有问题没有考虑到这个，导致子节点的object的maxlength设置为了null，所以导致抛出了这个异常，感谢大佬。。耽误大家时间了
