### ISSUE TITLE
 全局的cookie 设置

### ISSUE THREAD

**Issue by xiaofeihe** [YMFE/yapi#39]
标题不知道 说法是否合适。
我描述一下场景。

服务器端都是PHP 做开发， 登陆后 给浏览器写入cookie 。 因为不同人员或部门登陆，看到接口返回的结果内容不同。  我们想 在 Yapi 中 运行接口测试时候 带上cookie 。 这样就能方便的模拟不同部门调用接口了。

 但 使用中发现，每一个接口  模拟 运行前都要 修改接口的 HEADERS  修改cookie 内容。 

能否 再项目的配置中 定义一个全局的配置，或者变量。 配置一次cookie  后 ，本项目的全部 接口都带有这一个cookie 了。

我今天第一次使用 YAPI 也许是我没有看明白， 望各位能够帮忙 指导一下。

**Comment by suxiaoxin** [comment]
未来是有这个计划的，一个简单方法是你下载个 chrome设置cookie扩展，给要请求的域名设置下cookie，然后在接口编辑删掉cookie字段，为避免覆盖。

这样请求时候就能实现带上cookie

**Comment by xiaofeihe** [comment]
谢谢，  安装插件后， 可以满足我们需求。

**Comment by suxiaoxin** [comment]
我们计划的三期版本可以在环境配置设置 cookie , header 等
