### ISSUE TITLE
测试某具体接口，发送测试时，界面无任何反馈

### ISSUE THREAD

**Issue by caiboking** [YMFE/yapi#391]
## 版本号
1.3.17

## 什么问题
测试集合状态下，测试某具体接口，发送测试时，界面无任何反馈

## 如何复现此问题
进入项目中，选择测试集合，选择某个具体接口，点击发送，界面没看到任何响应，但是F12能看到任务的发送。

## 什么浏览器
chrome 66

## 什么系统（Linux, Windows, macOS）
windows 10

**Comment by gaoxiaomumu** [comment]
接口发送，有数据返回吗

**Comment by caiboking** [comment]
返回了，状态码200

**Comment by gaoxiaomumu** [comment]
但是，我们这边无法复现这个问题

**Comment by caiboking** [comment]
呃，好吧，我再多试试。
我用的docker方式安装，理论上应该没关系。https://www.jianshu.com/p/a97d2efb23c5

**Comment by tjudadc** [comment]
解决了吗？我也是docker安装的，也出现这个问题了。点击 发送 之后 返回200  没有数据。postman和浏览器都能返回数据。
