### ISSUE TITLE
demo网站无法访问

### ISSUE THREAD

**Issue by AlvinYuXT** [YMFE/yapi#393]
## 版本号
~ 

## 什么问题
~
demo网站无法访问
## 如何复现此问题
~ 

## 什么浏览器
~ 
Chrome
## 什么系统（Linux, Windows, macOS）
Mac

**Comment by gaoxiaomumu** [comment]
可以访问啊

**Comment by Jvr0771** [comment]
不可以，广西南宁长城宽带、移动数据都不行，打开都是一片灰色

**Comment by lilililee** [comment]
+1 广州移动 

页面console报错如下
(index):27 GET http://yapi.demo.qunar.com/prd/lib3.min.js net::ERR_CONTENT_LENGTH_MISMATCH
(anonymous) @ (index):27
(index):30 GET http://yapi.demo.qunar.com/prd/lib2.min.js net::ERR_CONTENT_LENGTH_MISMATCH
(anonymous) @ (index):30
(index):33 GET http://yapi.demo.qunar.com/prd/lib.min.js net::ERR_CONTENT_LENGTH_MISMATCH
(anonymous) @ (index):33
(index):37 GET http://yapi.demo.qunar.com/prd/index@ab40b4a1453e9cf776e6.js net::ERR_CONTENT_LENGTH_MISMATCH

**Comment by gaoxiaomumu** [comment]
现在可以了
