### ISSUE TITLE
希望接口列表增加分类层级，一个分类下，可以多个分类，跟Postman类似。谢谢！

### ISSUE THREAD

**Issue by longhualiu** [YMFE/yapi#395]
## 版本号
~ 1.3.16

## 什么问题
~接口列表显示文件夹分类问题

## 如何复现此问题
~ 

## 什么浏览器
~ 
chrome
## 什么系统（Linux, Windows, macOS）
linux

**Comment by gaoxiaomumu** [comment]
yapi ,应该不会支持多层级
