### ISSUE TITLE
YAPI导入API接口无法覆盖

### ISSUE THREAD

**Issue by vperson** [YMFE/yapi#396]
## 版本号
~  1.3.14

## 什么问题
~ 导入API是根据url来判断是否相同，导致，该url下面的参数发生变化还是判断为重复的api

## 如何复现此问题
~  多导几次相同的swagger文件就好了

## 什么浏览器
~  谷歌浏览器

## 什么系统（Linux, Windows, macOS）
Linux

**Comment by gaoxiaomumu** [comment]
可以开启导入数据同步功能
