### ISSUE TITLE
Demo无法访问

### ISSUE THREAD

**Issue by zpnotes** [YMFE/yapi#397]
## 版本号
~ 无关

## 什么问题
Demo访问不了
<img width="515" alt="2018-06-15 10 48 39" src="https://user-images.githubusercontent.com/17735379/41447935-760f3cae-708a-11e8-8727-50e2d513cbd1.png">

## 如何复现此问题
6月15日

## 什么浏览器
Chrome

## 什么系统（Linux, Windows, macOS）
macOS

**Comment by gaoxiaomumu** [comment]
已经恢复
