### ISSUE TITLE
升级到 1.3.16 版本时，在浏览器打不开页面

### ISSUE THREAD

**Issue by leecz** [YMFE/yapi#399]
## 版本号
~ 1.3.16

## 什么问题
~ 从1.3.14 升级到1.3.16 启动服务正常，在浏览器打开页面报错：
lib.min.js:51103 Uncaught TypeError: keysFunc is not a function
    at lib.min.js:51103
    at Object.<anonymous> (index@54b1a9f9844371285cc7.js:48)
    at i (manifest.min.js:1)
    at Object.<anonymous> (index@54b1a9f9844371285cc7.js:5)
    at i (manifest.min.js:1)
    at window.webpackJsonp (manifest.min.js:1)
    at index@54b1a9f9844371285cc7.js:1

## 如何复现此问题
~ 升级

## 什么浏览器
~ chrome

## 什么系统（Linux, Windows, macOS）
macOS

**Comment by gaoxiaomumu** [comment]
可以升级到17试试

**Comment by leecz** [comment]
17 也是不行的，错误和 16 一样

**Comment by gaoxiaomumu** [comment]
删掉node_modules  重新安装

**Comment by leecz** [comment]
依然不行，我的 node 版本 v8.9.4

**Comment by gaoxiaomumu** [comment]
那就试试单独安装 node-sass 试试，再不行我们也不知道原因了

**Comment by leecz** [comment]
没事，辛苦了，我先用着 14 版本吧
