### ISSUE TITLE
 容错性

### ISSUE THREAD

**Issue by gogoyqj** [YMFE/yapi#4]
https://github.com/YMFE/yapi/blob/master/client/containers/Project/Interface/InterfaceList/Edit.js#L73

new WebSocket 可以用 try catch 包起来，web 服务部署的是 https 的话， ws 协议就会报错

**Comment by suxiaoxin** [comment]
@gogoyqj 不建议部署成 https 服务器，这会导致 chrome-extension（cross-request ）文件上传功能异常，无法正常使用

**Comment by suxiaoxin** [comment]
已使用 try catch 做容错性处理
