### ISSUE TITLE
几点优化建议

### ISSUE THREAD

**Issue by colincatsu** [YMFE/yapi#402]
## 版本号
yapi --1.3.17版本
centos 7
node v9.8.0
chrome
mongodb3.6
## 什么问题
首先，非常感谢这个产品，功能很实用，
现提出以下几点优化建议：
1.mock的时候把导入的JSON数据作为默认值
2.希望可以在编辑页面中修改默认值，这样操作起来更方便一点
望采纳，辛苦了

**Comment by gaoxiaomumu** [comment]
mock的时候把导入的JSON数据作为默认值  ？ 没明白您的意思
编辑页面不是啥都可以修改吗

**Comment by zhang5171291** [comment]
mock 默认值，我是通过 高级设置里设置的，例如 
`{
  "type": "integer",
  "default": 200
}`

为什么出来的数据还是  跟没有设置一样
`{
"code": -77373312,
"msg": "Tlgwqiivk Vabq Dteyqvp Kdxj",
"success": true,
"data": {
"name": "deserunt",
"id": 58063102
}
}`

**Comment by gaoxiaomumu** [comment]
高级mock里面不能写json -schema  ， 还有json-schema 里面的default字段并不能解析https://github.com/json-schema-faker/json-schema-faker

**Comment by zhang5171291** [comment]
![image](https://user-images.githubusercontent.com/495785/41954053-cbcaeac8-7a0b-11e8-8f89-279c4c8f87cc.png)
![image](https://user-images.githubusercontent.com/495785/41954079-f2b8602a-7a0b-11e8-94e1-8ca2f65f7d46.png)

我没有使用 高级mock， 我就是按照文档说明里设置的默认值， 请看截图， 我不确定是不是我使用的问题，

**Comment by colincatsu** [comment]
和 @zhang5171291 说的差不多，每次都需要在设置中设置默认值，按理说导入的时候就应该有默认值，而且mock出来的有很多不规范的字符串

**Comment by gaoxiaomumu** [comment]
json-schema 解析的时候defaul并不被解析，我们使用的json-schema 解析库
https://github.com/json-schema-faker/json-schema-faker

**Comment by zhang5171291** [comment]
int类型还可以  但是  boolean类型呢？ 除非我在高级mock里的  脚本里每个去赋值，， 否则我都目前测试下来都无法 设置 mock的默认值

**Comment by gaoxiaomumu** [comment]
确实，这里的默认值只是一个展示作用，因为我们的schema解析库是调用别人的，这个没有这种解析我们也没办法

**Comment by zhang5171291** [comment]
好的， 期待你们后面优化这个功能， 谢谢！
