### ISSUE TITLE
最新版本，编辑mock数据时，输入@后不会自动联想出string之类的类型了

### ISSUE THREAD

**Issue by wcycxp** [YMFE/yapi#403]
最新版本，编辑mock数据时，输入@后不会自动联想出string之类的类型了。我记得早些时候的版本是可以的。这个功能是去掉了吗？

**Comment by gaoxiaomumu** [comment]
好像一直都没有吧

**Comment by gaoxiaomumu** [comment]
可能是因为有json schema 所以将这个功能关掉了，下个版本会放开的
