### ISSUE TITLE
为什么在线版，我找不到分组

### ISSUE THREAD

**Issue by RocWangPeng** [YMFE/yapi#404]
## 版本号
~ 

## 什么问题
为什么在线版，我找不到分组，没办法创建分组，也就没办法邀请成员
~

## 如何复现此问题
~ 

## 什么浏览器
chrome
~ 

## 什么系统（Linux, Windows, macOS）
Windows

**Comment by gaoxiaomumu** [comment]
分组只有管理员可以创建，个人中心没有邀请成员的功能，建议你本地部署尝试

**Comment by damonsuo** [comment]
自安装版本，新注册用户也可以创建分组。这是没有做控制吗？
