### ISSUE TITLE
Json格式Body参数取值问题

### ISSUE THREAD

**Issue by 512433465** [YMFE/yapi#406]
## 版本号
 v1.3.17

## 什么问题
接口参数为json格式的Body参数。
json参数里面写固定值时，接口请求OK
但是json参数值，想取上面接口执行结果时，报错
例1：
{
    "orderId":123487
}
这样是通过的。

由于我的orderid是不固定的。需要从前面接口的返回值中取
例2：
{
    "orderId":{{$.2610.body.orderid}}
}
这样直接页面校验就报错。 执行当然也是报错的。
例3：
{
    "orderId":“{{$.2610.body.orderid}}”
}
这样显然也是不对的。

##不知道算不算一个Bug，烦请各位查看一下，谢谢了

## 如何复现此问题
参照上述例子复现。

## 什么浏览器
 Chrome

## 什么系统（Linux, Windows, macOS）
Linux, Windows, macOS

**Comment by gaoxiaomumu** [comment]
测试了一下，发现{{ $.7494.params.aa }} 的返回值类型和  测试接口7494下的参数aa的类型是一样的


￼￼所以应该是你的{{$.2610.body.orderid}} 是一个string类型的
￼

**Comment by 512433465** [comment]
不是这个类型的问题，是我接口需要传一个json数组作为body的参数
{
"orderId":123487
}
{
"orderId":“123487”
}
都可以，只要能把参数：{"orderId":123487}，传给接口。但是这个orderId又需求从7494取得。
也就是，要测试的接口Body参数应该传下面这样的整体作为参数：
{
"orderId":{{ $.7494.params.aa }} 
}
但是，这样写在yapi的前台页面校验，就会提示出错，也不不提交给后台接口。不知道表达清楚没，哈哈哈，感觉有点绕

**Comment by luckygqx** [comment]
试下这样"orderId":"{{ $.2610.body.orderid }}"
