### ISSUE TITLE
环境配置不够详细

### ISSUE THREAD

**Issue by git510961914** [YMFE/yapi#408]
## 版本号
截至目前的版本
## 什么问题
关于内网部署的方式一、二太笼统简略，绕了好大一圈弯路，最后才弄好
## 如何复现此问题
找一个新手在win7系统下配置一遍
## 什么浏览器
傲游、360、扣扣、火狐
## 什么系统（Linux, Windows, macOS）
win7

**Comment by git510961914** [comment]
使用教程可不可以做成pdf或者word文档以供下载

**Comment by gaoxiaomumu** [comment]
网页版本不可以吗
