### ISSUE TITLE
关于部分功能建议

### ISSUE THREAD

**Issue by 26597925** [YMFE/yapi#412]
## 版本号
~ 

## 什么问题
~我看了这个项目，简直很完美。但是缺少一些，我觉得很常用的功能，如果能把这个功能加上那么就更完美。第一个功能，能支持导出接口文档，能加上对接口的描述以及参数说明。第二个功能是返回数据，能支持常用的加解密设置，因为有些项目，特别针对移动项目，有些数据会处理。

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by gaoxiaomumu** [comment]
目前支持导出接口文档，接口描述可以写在备注里面
返回数据加密的问题，可以去请求配置里面进行https://yapi.ymfe.org/documents/project.html#%E8%AF%B7%E6%B1%82%E9%85%8D%E7%BD%AE

**Comment by 26597925** [comment]
非常感谢
