### ISSUE TITLE
1.3.17版本，编辑接口异常,添加子节点后缀自动多1，且删除报错

### ISSUE THREAD

**Issue by MofiU** [YMFE/yapi#413]
## 版本号
1.3.17 

## 什么问题
编辑接口的时候，勾选json-scheme，添加子节点，自动出现1后缀， 删除报错， 1.3.16版本无此现象

## 如何复现此问题
编辑接口

## 什么浏览器
chrome , firefox都有

**Comment by gaoxiaomumu** [comment]
这个问题已经解决了，你可以重新update一下，如果你用别人的docker 部署的话请回退到16
