### ISSUE TITLE
修改了部分代码，重启，发现没有生效。也没有找到加日志调试的方法，consolelog没有输出

### ISSUE THREAD

**Issue by retindErCn** [YMFE/yapi#415]
我因为工作上的需要，修改了
InterfaceCol.js.
添加了自动化测试每次运行的结果的header中的cookies。方便下个接口调用。

`this.records[curitem_id]={
        params:result.params,
        body:result.res_body,
        cookies:res_headers
}`

发现直接在测试中使用，无法取到值。加consol.log无法调试，请问这个地方如何打印日志

**Comment by gaoxiaomumu** [comment]
去你启动代码的终端查看是否有console
