### ISSUE TITLE
user "root" does not have permission to access the dev dir

### ISSUE THREAD

**Issue by kyleduo** [YMFE/yapi#418]
## 版本号

1.3.17

## 什么问题

内网命令行部署，死循环该错误 user "root" does not have permission to access the dev dir "/www/my-yapi/vendors/node_modules/dtrace-provider/.node-gyp/8.11.1"

## 如何复现此问题

root用户执行

## 什么系统（Linux, Windows, macOS）

centOS

**Comment by kyleduo** [comment]
参考 [这里](https://github.com/nodejs/node-gyp/issues/454)
执行`npm install`时，加上`--unsafe-perm`可以解决问题。（手动部署也需要加上该参数）

**Comment by gaoxiaomumu** [comment]
可能是你的root用户没有权限执行这个文件夹，建议对文件夹进行 chown 设置，这种问题建议问一下公司的运维比较好

**Comment by kyleduo** [comment]
目录权限没有问题，是由root用户创建的。

高晓琳 <notifications@github.com>于2018年6月28日周四 下午7:10写道：

**Comment by kyleduo** [comment]
这个issue并没有解决啊，怎么就被关掉了？
