### ISSUE TITLE
建议一个项目支持多环境域名

### ISSUE THREAD

**Issue by hejunrex** [YMFE/yapi#419]
## 版本号
~ 当前最新版本

## 什么问题
~ 在实际项目中一个项目中使用的接口可能有多个域名baseurl，当前只能在项目中设置一个域名，造成必须再开一个项目去支持那些接口，由于我们的微服务架构造成接口比较分散，需要来回切换项目

## 建议
~ 1.在增加多个域名组（里面设置自己定义本地开发环境、测试环境等）
~ 2.在接口创建的时候可以选择一个域名组
~ 3.在接口预览的界面可以显示域名组第一个域名或者组名，这样好辨别是哪个服务的

**Comment by gaoxiaomumu** [comment]
在运行里面或者在测试集合里面都有环境变量配置这个选项，您也可以在项目->设置 -> 环境配置里面设置
![image](https://user-images.githubusercontent.com/21135585/42030717-5b1d9dd8-7b06-11e8-8c26-3721eb48f365.png)

**Comment by gaoxiaomumu** [comment]
在运行里面或者在测试集合里面都有环境变量配置这个选项，您也可以在项目->设置 -> 环境配置里面设置
![image](https://user-images.githubusercontent.com/21135585/42030801-914504dc-7b06-11e8-9dd1-d56a73b15212.png)

**Comment by hejunrex** [comment]
这个不是我想要的
例如有接口
a.xx.com/aaa/info
b.xx.com/bbb/info
c.xx.com/ccc/info
由于在一个项目中有多个微服务器的baseUrl，我希望能够点击/ccc/info接口的时候自动选择到 c.xxx.com，因为这种baseUrl很多，有20多个，所以每次都进行选择的话太复杂了

**Comment by gaoxiaomumu** [comment]
那个选一次就可以了，在测试集合里面有保存功能，你可以将不同的接口选择不同的url然后保存一下，下次用的时候就不需要再选择了，或者将这些接口划分成不同的项目里面，测试集合可以跨项目导入接口

**Comment by MaxCode-fan** [comment]
如果能把测试集内的环境切换只是单纯做环境切换就好了,不同环境的地址在文档编写的时候配置就好,这样就可以一键切换不同环境,也不需要做很多测试集的分类添加
