### ISSUE TITLE
yapi 支持 raml格式的接口数据导入吗 ？

### ISSUE THREAD

**Issue by xuyangxy** [YMFE/yapi#427]
目前postman是支持导入raml格式    但没找到yapi导入raml格式的入口    不知道是否支持呢？

**Comment by gaoxiaomumu** [comment]
不支持，目前只支持，下面这四种形式的
![image](https://user-images.githubusercontent.com/21135585/42148897-89e0801a-7e06-11e8-849e-128f9a8a205c.png)

**Comment by xuyangxy** [comment]
好的，知道啦

**Comment by youngjuning** [comment]
能否支持一下导入 yml格式呢
