### ISSUE TITLE
小建议，在“运行”界面可临时添加QUERY PARAMETERS

### ISSUE THREAD

**Issue by knktc** [YMFE/yapi#428]
## 版本号
1.3.17

## 什么问题
感谢提供YAPI如此优秀的项目！

有一个小建议，在进行GET方式请求时，可否在“运行”界面中的QUERY PARAMETERS部分添加一个按钮，用于临时添加查询参数。当前的情况是必须得在“请求参数设置”中添加的参数才会出现在运行界面中。

谢谢！

**Comment by gaoxiaomumu** [comment]
这个是为了确保接口的一致性，如果在运行的时候将接口参数数量都改变了，这个接口和原接口之间就会存在差异，还有建议去编辑里面修改接口参数
