### ISSUE TITLE
我是管理员，我把自己删了~咋整

### ISSUE THREAD

**Issue by wengpengfeijava** [YMFE/yapi#43]
如题，权限处理的不是很得当啊~

**Comment by suxiaoxin** [comment]
该数据库吧，这方面确实考虑不周

**Comment by wengpengfeijava** [comment]
啊！！那你们这个我能二次开发使用吗，有些功能还是要调优下！例如角色权限控制。还是说最近的新版本会做bug修复？

**Comment by suxiaoxin** [comment]
你自己可以简单二次开发下，没问题pull request

有问题我们这边也会修复

**Comment by wengpengfeijava** [comment]
嗯啊~功能很赞，操作人性化

**Comment by suxiaoxin** [comment]
http://yapi.demo.qunar.com 刚更新的 1.2.6 版本修复了删除管理员问题

**Comment by wengpengfeijava** [comment]
好的谢谢

**Comment by wengpengfeijava** [comment]
没权限的操作希望能做到不显示。
