### ISSUE TITLE
测试集合需要增加多级目录

### ISSUE THREAD

**Issue by AntonyBi** [YMFE/yapi#430]
## 版本号
1.3.16

## 什么问题
当拥有大量的测试集合，每个集合中也有很多接口。
这个时候，测试集合页的列表就非常多。

对一类情况做几组测试去覆盖情况，是典型的多级目录结构。
只有一级目录，没有分级，浏览起来就很困难。
但是搜索的话，左边的菜单会拉很长，也很难看。

## 如何复现此问题
增加30组测试用例，每组测试用例10个接口
（我们实际环境有几千组测试用例）

## 什么浏览器
chrome

## 什么系统（Linux, Windows, macOS）
Windows

**Comment by gaoxiaomumu** [comment]
不支持
