### ISSUE TITLE
ykit 打包错误

### ISSUE THREAD

**Issue by jsspace** [YMFE/yapi#432]
## 版本号
~ 1.3.17， node 8.9.4 webpack 3.3.0

## 什么问题
~ 安装好依赖之后，运行 ykit s -p 4000，会报如图所示错误
![qq 20180704113350](https://user-images.githubusercontent.com/14964790/42255410-28838302-7f7e-11e8-99a5-2f038abc11b2.png)

## 如何复现此问题
~ 

## 什么浏览器
~ chrome

**Comment by jsspace** [comment]
更新了一下npm版本，ykit版本，出来以下下错误
![image](https://user-images.githubusercontent.com/14964790/42270466-8850d41c-7fb3-11e8-9eac-c5ca5892fab3.png)
好像是ykit配置里 happypack/loader 模块没有找到

**Comment by jsspace** [comment]
又试了一下，按照流程，在mac上打包一点问题都没有，在windows上就报这个错。。。

**Comment by gaoxiaomumu** [comment]
二次开发不推荐使用Windows  ，要额外装很多插件
