### ISSUE TITLE
ldaps   error: once: Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by LuanLouis** [YMFE/yapi#433]
## 版本号
~ 1.3.17

## 什么问题
~  当尝试使用ldaps 构造登录时，报error: once: Error: unable to verify the first certificate
![image](https://user-images.githubusercontent.com/7589877/42261538-21e38516-7f9b-11e8-9133-d45024422f78.png)

## 如何复现此问题
~ 使用ldaps 证书

## 什么浏览器
~ Chrome

## 什么系统（Linux, Windows, macOS）
  Linux

**Comment by gaoxiaomumu** [comment]
ldaps登陆的话需要添加tlsOptions，  目前yapi的ldap登陆没有这项数据
![image](https://user-images.githubusercontent.com/21135585/42267089-ae9be944-7faa-11e8-906e-5925b09c5d96.png)
