### ISSUE TITLE
分组设置下面的自定义字段是什么作用？

### ISSUE THREAD

**Issue by icanfly** [YMFE/yapi#436]
## 版本号
~ v1.3.18

## 什么问题
~ 分组设置下面的自定义字段是什么作用？

## 如何复现此问题
~ 
![image](https://user-images.githubusercontent.com/1010797/42436730-92b19148-838d-11e8-81ac-d690b38d7161.png)

## 什么浏览器
~

**Comment by gaoxiaomumu** [comment]
![image](https://user-images.githubusercontent.com/21135585/42438453-b4ca6a20-8392-11e8-877d-68d57bf2a7ce.png)
![image](https://user-images.githubusercontent.com/21135585/42438530-ddf24bfc-8392-11e8-8880-6f8f61a35f0a.png)

在每个接口下面就会有一个针对该自定义的字段的变量

**Comment by icanfly** [comment]
@gaoxiaomumu 支持多字段自定义吗？比如用什么分隔?

**Comment by gaoxiaomumu** [comment]
不支持多字段
