### ISSUE TITLE
对返回的数据进行编辑时编辑不了

### ISSUE THREAD

**Issue by zhoupenghui** [YMFE/yapi#437]
## 版本号
~  最新版本

## 什么问题
~
编辑时,更新不了接口, 并且在接口字段后面会加一个1,有bug
## 如何复现此问题
~ 

## 什么浏览器
~ 谷歌

## 什么系统（Linux, Windows, macOS）
linux

编辑的时候,删除不了, 增加节点时会自动在字母后面加一个1,删除时报错,见下图:
![_546](https://user-images.githubusercontent.com/15656570/42484177-3d32d7c6-8424-11e8-81e8-fac52c8d4bbe.png)
![_547](https://user-images.githubusercontent.com/15656570/42484178-3d716bc6-8424-11e8-814e-54463261c026.png)
![_548](https://user-images.githubusercontent.com/15656570/42484179-3dad56ae-8424-11e8-924c-8938116ba524.png)

**Comment by gaoxiaomumu** [comment]
这个问题很早之前就已经修改过了，版本18和版本17应该都没有这个问题了，还是升级一下版本吧
