### ISSUE TITLE
用户处于登录状态时, 访问/login路由时, 登录页面会显示用户信息

### ISSUE THREAD

**Issue by wuranxu** [YMFE/yapi#439]
## 版本号

1.3.18

## 什么问题

在登录状态下, 访问/login页面, 右上角仍然显示用户的登录信息。

## 如何复现此问题

1. 登录yapi
2. 在浏览器地址栏输入服务部署的域名(ip:port)+/login

预期结果: 提示"用户XXX已登录, 即将进入项目首页" 或不提示直接进入项目首页。
实际结果: 在登录状态下用户仍然可以访问登录页面, 且右上角会带有用户的登录信息。

备注: 在注销之后无此问题。

## 什么浏览器

Chrome 67.0.3396.99

## 什么系统（Linux, Windows, macOS）

macOS 10.13.2

## 截图

![image.png](https://upload-images.jianshu.io/upload_images/6053915-32c4c19287d11140.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by gaoxiaomumu** [comment]
如果在登陆状态下用户就是想进入登陆/注册页面，用另一个账号登陆呢？这个没毛病吧

**Comment by wuranxu** [comment]
哈哈···正常情况来讲不是应该注销后再登录么，按用户的思维肯定不会直接进login页面吧, 进这个页面是因为我改了home跳转到login页面，普通用户都会先退出这个号，再登录其他账号。
