### ISSUE TITLE
[request feature] 接口请求参数能否设置数据类型

### ISSUE THREAD

**Issue by reniaL** [YMFE/yapi#44]
挺不错的API管理工具。

在demo (http://yapi.demo.qunar.com) 上看，接口的请求参数貌似不能设置数据类型，请问能否加上？可以为参数设置数据类型，例如 string, int, boolean 这样。

**Comment by suxiaoxin** [comment]
参数数据类型写到参数示例，可否？

**Comment by reniaL** [comment]
如果只是用来看，感觉写到“参数示例”那里也可以。

但如果后续要考虑再完善参数功能的话，数据类型的支持似乎是必须的。例如支持对象类型参数、数组类型参数。

**Comment by suxiaoxin** [comment]
恩，后续我们会考虑完善该功能的
