### ISSUE TITLE
新注册的用户角色能否设置成管理员

### ISSUE THREAD

**Issue by treeyh** [YMFE/yapi#441]
## 版本号
~ 1.3.18

## 什么问题
~ 1.新注册的用户角色能否设置成管理员

## 如何复现此问题
~ 新注册的用户角色只能是会员, 无法更改为管理员

## 什么浏览器
~ chrome

## 什么系统（Linux, Windows, macOS）
- ubuntu

**Comment by gaoxiaomumu** [comment]
管理员只在部署的时候有一个，如果需要添加管理员需要去数据库添加

**Comment by treeyh** [comment]
了解 谢谢
