### ISSUE TITLE
docker 的镜像源更新不及时

### ISSUE THREAD

**Issue by crper** [YMFE/yapi#442]
最新版已经发布七天了... 阿里云上的docker镜像还没有更新;

[Aliyun Yapi](https://dev.aliyun.com/detail.html?spm=5176.1972343.2.26.I97LV8&repoId=139034)

**Comment by gaoxiaomumu** [comment]
这个你可以去群里面呼吁一下，镜像不是我们在管理的

**Comment by crper** [comment]
@gaoxiaomumu  申请过,加群直接给拒绝了..
![image](https://user-images.githubusercontent.com/8272877/42671119-0d8e3a78-8691-11e8-8dd9-f522c7dac8c5.png)
