### ISSUE TITLE
关于yapi的dockerfile问题

### ISSUE THREAD

**Issue by RudyChow** [YMFE/yapi#445]
## 版本号
~ 1.3.18

## 什么问题
~`yapi install`部署成功后返回code 1导致Dockerfile无法继续执行
本意在部署成功后直接开启服务,但由于install成功但返回code不符合预期导致步骤分开进行

## 如何复现此问题
~ 直接在docker容器内进行`yapi install`

## 什么浏览器
~ 无

## 什么系统（Linux, Windows, macOS）
docker,alpine

**Comment by zhfish** [comment]
用这个
https://hub.docker.com/r/zhfish/yapi/
