### ISSUE TITLE
LDAP无法登陆

### ISSUE THREAD

**Issue by cellcb** [YMFE/yapi#449]
## 版本号
~ 1.3.19

## 什么问题
~LDAP配置完成后无法登陆，提示 Request failed with status code 404
  手工注册同名用户后，就可以用LDAP登陆
## 如何复现此问题
~ 

## 什么浏览器
~ chrome

## 什么系统（Linux, Windows, macOS）
   服务器oracle linux 6.9 客户端 win10 ,chrome

**Comment by gaoxiaomumu** [comment]
手工注册以后，是用ldap登陆还是 普通登陆？404一般表示找不到资源，你可以看一下控制台上的network中接口login_by_ldap

**Comment by cellcb** [comment]
login_by_ldap 控制台 response 显示 NOT FOUND
手工注册以后 用ldap登陆是可以的

**Comment by gaoxiaomumu** [comment]
https://github.com/YMFE/yapi/issues/453
