### ISSUE TITLE
接口文档按分类组织接口

### ISSUE THREAD

**Issue by shixuev5** [YMFE/yapi#45]
* 接口按分类组织
![image](https://user-images.githubusercontent.com/3207014/32936704-4e4e4676-cbb0-11e7-9b85-7c809e02c0c1.png)
* 导出的接口文档html 如下:
> 并且接口排列顺序是mongo中存储顺序 不是页面展示的顺序

![image](https://user-images.githubusercontent.com/3207014/32936739-6c73beba-cbb0-11e7-81a0-651d7def6f91.png)

### 希望，能生成类似这样的文档：
![image](https://user-images.githubusercontent.com/3207014/32936849-e49b01c8-cbb0-11e7-999b-7de82c0b5254.png)

**Comment by suxiaoxin** [comment]
未来会优化的
