### ISSUE TITLE
返回数据不支持jsonp解析

### ISSUE THREAD

**Issue by hplegend** [YMFE/yapi#450]
## 版本号
1.3.18

## 什么问题
添加接口的时候，添加jsonp类型的返回数据无法保存

![cfe08ac8cdc6a52b9778429174f0a65f](https://user-images.githubusercontent.com/24842574/42880513-28c973ae-8ac7-11e8-8659-c19358660d00.png)

**Comment by gaoxiaomumu** [comment]
yapi不支持jsonp

**Comment by zhfish** [comment]
为什么要支持jsonp？

**Comment by zhansingsong** [comment]
开发时也遇到此需求，就封装一个小工具：[jsonpify](https://github.com/zhansingsong/node-jsonpify) 。可以尝试一下😆
