### ISSUE TITLE
v1.3.19升级成功启动失败

### ISSUE THREAD

**Issue by ruixiu** [YMFE/yapi#451]
## 版本号
~ v1.3.19

## 什么问题
~升级启动后访问白屏

## 如何复现此问题
~ yapi update后直接启动，浏览器访问白屏，服务器控制台输入  caseData null

## 什么浏览器
~ chrome

## 什么系统（Linux, Windows, macOS）
Linux

**Comment by ruixiu** [comment]
无奈回退到了1.3.18

**Comment by gaoxiaomumu** [comment]
解决办法是清空浏览器缓存，不过你可以升级到1.3.20  我们重新发布了一个版本来解决这个问题
