### ISSUE TITLE
LDAP 登陆有问题

### ISSUE THREAD

**Issue by zhangmengpl** [YMFE/yapi#453]
## 版本号
~1.3.19
1.3.20
## 什么问题
~LDAP 登陆有问题

## 如何复现此问题
~ 1.3.18 登陆正常

## 什么浏览器
~ 
chrome
## 什么系统（Linux, Windows, macOS）
ubuntu14

**Comment by gaoxiaomumu** [comment]
ldap    这里的逻辑进行了修改，登陆完成后会将用户信息全部返回，然后用户名和邮箱都是从ldap数据库里面获取的，不知道是哪里出现了问题？

**Comment by gaoxiaomumu** [comment]
你是用邮箱登陆还是用户信息登陆的？ 我这边测试没有问题，

**Comment by zhangmengpl** [comment]
用户登陆的  "searchStandard": "cn" 

 

发件人: <noreply@github.com> 代表 高晓琳 <notifications@github.com>
答复: YMFE/yapi <reply@reply.github.com>
日期: 2018年7月19日 星期四 16:13
收件人: YMFE/yapi <yapi@noreply.github.com>
抄送: zhangmengpl <zhangmengpl@163.com>, Author <author@noreply.github.com>
主题: Re: [YMFE/yapi] LDAP 登陆有问题 (#453)

 

你是用邮箱登陆还是用户信息登陆的？ 我这边测试没有问题，

**Comment by gaoxiaomumu** [comment]
是否方便QQ上详细聊

**Comment by zwp201301** [comment]
third_login: server instance pool was destroyed   
每次都是依靠重启my-api解决的，不太会修改nodejs源码， 很多是说mongodb的连接失效导致的
