### ISSUE TITLE
对于同一路径带不同参数来表示多个接口的应该如何处理

### ISSUE THREAD

**Issue by fuckingcode** [YMFE/yapi#455]
rt
因为接口名不能重复，目前想到啥办法是在路口中多带一个表示某接口的字符串，然后在请求预处理的时候删掉这个字符串。
想问有没有更好的办法

**Comment by gaoxiaomumu** [comment]
在一个项目里面通常情况路径是唯一的， 如果是版本管理的话那就另外说了

支持通过 query 区分不同 path 的接口
/api/path?c=a
/api/path?c=b

**Comment by Yalhu** [comment]
接口路径path 第一位必须是`/` 吗？ 比如上面`/api/path?c=a` ，定义跟路径`/api/path` , 写接口的时候路径直接写`?c=a` 或者`c=a&d=1`
