### ISSUE TITLE
安装失败，Cannot find module 'fs-extra'

### ISSUE THREAD

**Issue by sandheart** [YMFE/yapi#458]
## 版本号
~ V1.3.20

## 什么问题
使用淘宝的镜像库也不行

[root@aaaa yapi]# yapi server
在浏览器打开 http://0.0.0.0:9090 访问。非本地服务器，请将 0.0.0.0 替换成指定的域名或ip 
当前安装版本： v1.3.20
连接数据库成功!
开始下载平台文件压缩包...
http://yapi.demo.qunar.com/publicapi/archive/v1.3.20
部署文件完成，正在安装依赖库...
 npm
  ERR! code 128

 npm 
 ERR! Command failed: /usr/bin/git clone -q https://github.com/nhnent/raphael.git /root/.npm/_cacache/tmp/git-clone-c8bc6a1d
npm
  ERR! warning: templates not found /tmp/pacote-git-template-tmp/git-clone-6774dd90

 npm ERR!
  error: RPC failed; result=18, HTTP code = 200
npm ERR!
  fatal: The remote end hung up unexpectedly
npm
  ERR! fatal: early EOF

 npm ERR!
  fatal: index-pack failed
npm 
 ERR! 

 

 npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-07-20T03_32_43_227Z-debug.log

依赖库安装完成，正在初始化数据库mongodb...
 
> yapi@1.3.20 install-server /data/yapi/my-yapi/vendors
>  node server/install.js

Error:  module.js:549
    throw err;
    ^

Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/data/yapi/my-yapi/vendors/server/install.js:1:74)
    at Module._compile (module.js:652:30)
~

## 如何复现此问题
~ 使用可视化部署就可以看到

## 什么浏览器
~chrome 
## 什么系统（Linux, Windows, macOS）
Distributor ID:	CentOS
Description:	CentOS Linux release 7.2.1511 (Core) 
Release:	7.2.1511

**Comment by gaoxiaomumu** [comment]
![image](https://user-images.githubusercontent.com/21135585/42985624-dd2b20dc-8c24-11e8-9cf0-24ed4818bb26.png)
请确保以上这些都已经安装完成了

**Comment by sandheart** [comment]
需要的依赖都有了：
[root@aaa yapi]# node -v
v8.11.3
[root@aaa yapi]# mongo --version
MongoDB shell version v3.4.16
git version: 0d6a9242c11b99ddadcfb6e86a850b6ba487530a
OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
allocator: tcmalloc
modules: none
build environment:
    distmod: rhel70
    distarch: x86_64
    target_arch: x86_64
[root@aaa yapi]# npm -v
6.2.0
[root@aaa yapi]# git --version
git version 1.8.3.1
[root@aaa yapi]# 
[root@aaa yapi]# node-gyp list
gyp info it worked if it ends with ok
gyp info using node-gyp@3.7.0
gyp info using node@8.11.3 | linux | x64
No node development files installed. Use `node-gyp install` to install a version.
gyp info ok 


装低版本还是不行：
部署日志
当前安装版本： v1.3.12
连接数据库成功!
开始下载平台文件压缩包... http://yapi.demo.qunar.com/publicapi/archive/v1.3.12
部署文件完成，正在安装依赖库...
> dtrace-provider@0.8.6 install /data/yapi/my-yapi/vendors/node_modules/dtrace-provider > node-gyp rebuild || node suppress-error.js
gyp
ERR! configure error gyp ERR! stack Error: EACCES: permission denied, mkdir '/data/yapi/my-yapi/vendors/node_modules/dtrace-provider/build' gyp ERR! System Linux 3.10.0-327.el7.x86_64 gyp ERR! command "/usr/local/node/node-v8.11.3-linux-x64/bin/node" "/usr/local/node/node-v8.11.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" gyp ERR! cwd /data/yapi/my-yapi/vendors/node_modules/dtrace-provider gyp ERR! node -v v8.11.3 gyp ERR! node-gyp -v v3.7.0 gyp ERR! not ok
> jsonpath@1.0.0 postinstall /data/yapi/my-yapi/vendors/node_modules/jsonpath > node lib/aesprim.js > generated/aesprim-browser.js
sh: generated/aesprim-browser.js: Permission denied
npm WARN
yapi@1.3.12 license should be a valid SPDX license expression
npm ERR! code
ELIFECYCLE npm ERR! errno 1 npm
ERR! jsonpath@1.0.0 postinstall: `node lib/aesprim.js > generated/aesprim-browser.js` npm ERR! Exit status 1 npm ERR! npm ERR!
Failed at the jsonpath@1.0.0 postinstall script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in: npm ERR! /root/.npm/_logs/2018-07-20T07_29_08_957Z-debug.log
依赖库安装完成，正在初始化数据库mongodb...
> yapi@1.3.12 install-server /data/yapi/my-yapi/vendors > node server/install.js
Error: module.js:549 throw err; ^ Error: Cannot find module 'json-schema-faker' at Function.Module._resolveFilename (module.js:547:15) at Function.Module._load (module.js:474:25) at Module.require (module.js:596:17) at require (internal/module.js:11:18) at Object.<anonymous> (/data/yapi/my-yapi/vendors/server/utils/commons.js:23:13) at Module._compile (module.js:652:30) at Object.Module._extensions..js (module.js:663:10) at Module.load (module.js:565:32) at tryModuleLoad (module.js:505:12) at Function.Module._load (module.js:497:3) at Module.require (module.js:596:17) at require (internal/module.js:11:18) at Object.<anonymous> (/data/yapi/my-yapi/vendors/server/install.js:3:17) at Module._compile (module.js:652:30) at Object.Module._extensions..js (module.js:663:10) at Module.load (module.js:565:32)

**Comment by gaoxiaomumu** [comment]
`
ERR! configure error gyp ERR! stack Error: EACCES: permission denied, mkdir '/data/yapi/my-`     permission denied  应该是你的文件夹没有权限

**Comment by sandheart** [comment]
按照这个说明安装成功了，用的cnpm，比npm好用：
https://github.com/liuyuan1989/yapi_user_guide/blob/master/YAPI%E5%88%9D%E6%AC%A1%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97_MacOS.md

**Comment by sandheart** [comment]
/data/yapi/
设了 777也不行，我用的root账户

**Comment by gaoxiaomumu** [comment]
chown -R  $USER:$GROUP $webpath   你应该用chrown 来变更一下文件夹的权限，并且最好用

npm install --production --registry https://registry.npm.taobao.org   来安装，cnpm 虽然成功了但是有可能缺包

**Comment by sandheart** [comment]
好的

**Comment by wwwxy80s** [comment]
记录一下，我也遇到了跟楼主一模一样的情况，应该是权限问题，但是不敢乱改，暂时是在执行`npm install`时加上了`--unsafe-perm`安装好了依赖，但是不知这样做后面升级或者其他操作会不会有坑。

**Comment by yeongjet** [comment]
遇到过 `Cannot find module 'fs-extra'` 错误，原因是内存空间不足导致npm install时执行node-gyp的过程中被kill，增加内存就解决了

**Comment by nilmeme** [comment]
after this error you can do
`cd $pathOfYourServer/vendors`
`npm install`
`node server/install.js`
