### ISSUE TITLE
公开文档不以导出的形式，而是以直接访问的形式

### ISSUE THREAD

**Issue by 81519434** [YMFE/yapi#460]
提一些不成熟的意见....
场景是这样的，我们开发了一些接口，需要给第三方调用。按照目前的做法，必须导出成html然后部署到nginx上面给开发者访问。
这样修改的api每次都要导出重新发布到nginx，很麻烦。
假设yapi自带http服务可以直接访问 接口文档，那就好了。
类似[apiManager](http://api.crap.cn/project.do#/152739463796407001938/interface/list/152739490702409001941)这样的方式。

**Comment by gaoxiaomumu** [comment]
你们可以自己写一个开放接口网站   来拉取yapi 的项目接口

**Comment by chendeben** [comment]
@gaoxiaomumu 怎么自己写一个接口？表示不会node.js

**Comment by gaoxiaomumu** [comment]
可以找会的人帮你们，不用加接口直接调用yapi的接口就可以了
