### ISSUE TITLE
关于接口错误码管理

### ISSUE THREAD

**Issue by icanfly** [YMFE/yapi#466]
## 版本号
~ 

## 什么问题
~ 目前关于接口错误码管理似乎还没有任何功能实现？

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by gaoxiaomumu** [comment]
可以写在接口备注里面或者项目wiki中

**Comment by maosong** [comment]
目前还是写在接口备注中，如果是公共错误码可以写在项目wiki中（v1.3.19新增功能）

但希望官方将此功能标准化:)
