### ISSUE TITLE
无法访问

### ISSUE THREAD

**Issue by fstg0504** [YMFE/yapi#469]
## 版本号
~ 最新版clone的仓库

## 什么问题
~ npm run dev 启动开发环境 浏览器无法访问；启动端口是3000
访问127.0.0.1:3000 时候页面空白
f12 看页面的元素script标签加载的js地址居然是127.0.0.1:4000/prd/manifest@dev.js
先不说项目里面没有prd文件夹，加载的端口为什么是4000呢？

## 如何复现此问题
~ 正常走官网教程 clone项目 安装依赖包 npm run dev启动

## 什么浏览器
~ 谷歌浏览器

## 什么系统（Linux, Windows, macOS）
window10

**Comment by fstg0504** [comment]
找到了原因 但是无法解决：
/server/app.js里面 
let indexFile = process.argv[2] === 'dev' ? 'dev.html' : 'index.html';
去加载了dev.html 然而
dev.html里面都写死了端口为4000的
`<!DOCTYPE html>
<html>
<head>
<meta id="cross-request-sign" charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="keywords" content="yapi接口管理,api管理,接口管理,api,接口,接口文档,api文档,接口管理系统" />
<meta name="description" content="YApi 是高效、易用、功能强大的 api 管理平台，旨在为开发、产品、测试人员提供更优雅的接口管理服务。可以帮助开发者轻松创建、发布、维护 API，YApi 还为用户提供了优秀的交互体验，开发人员只需利用平台提供的接口数据写入工具以及简单的点击操作就可以实现接口的管理。" />
<title>YApi-高效、易用、功能强大的可视化接口管理平台</title>
<link rel="icon" type="image/png" sizes="192x192" href="/image/favicon.png">
<link rel="stylesheet" href="http://127.0.0.1:4000/prd/index@dev.css">
</head>
<body>
<div id="yapi" style="height: 100%;"></div>

<script src="http://127.0.0.1:4000/prd/manifest@dev.js"></script>
<script src="http://127.0.0.1:4000/prd/lib3@dev.js"></script>
<script src="http://127.0.0.1:4000/prd/lib2@dev.js"></script>
<script src="http://127.0.0.1:4000/prd/lib@dev.js"></script>
<script src="http://127.0.0.1:4000/prd/index@dev.js"></script>



</body>
</html>`
而且 prd文件夹里面 没有 manifest@dev.js 这些文件的 那么开发环境 怎么配置啊

**Comment by gaoxiaomumu** [comment]
加载接口当然是4000， 因为npm run dev  开启了两个接口一个是3000的后端接口，一个是 4000的前端接口，具体原因可以看pageage.json   

可以看看控制台有没有报错

其次，win不支持二次开发

**Comment by piaokongyu** [comment]
+1

**Comment by lizy0329** [comment]
> 加载接口当然是4000， 因为npm run dev 开启了两个接口一个是3000的后端接口，一个是 4000的前端接口，具体原因可以看pageage.json
> 
> 可以看看控制台有没有报错
> 
> 其次，win不支持二次开发

真搞笑，歧视 win

**Comment by lizy0329** [comment]
> 加载接口当然是4000， 因为npm run dev 开启了两个接口一个是3000的后端接口，一个是 4000的前端接口，具体原因可以看pageage.json
> 
> 可以看看控制台有没有报错
> 
> 其次，win不支持二次开发

问题是后端开了 3000 端口，但前台请求是根据前台域名来的 是 4000/api/user/status 这样，会导致请求出错，怎么破？
