### ISSUE TITLE
"closeRegister":true

### ISSUE THREAD

**Issue by gaoyangy** [YMFE/yapi#470]
config.json 文件里json一级key的禁止注册并没有生效
"closeRegister":true
问一下关于禁止注册是不是有其他原因

## 什么浏览器
~ 谷歌

## 什么系统（Linux, Windows, macOS）
windows mac

**Comment by gaoxiaomumu** [comment]
只有你点击注册的时候才会弹出禁止注册的提示，还有设置config.json之后需要重启node端服务
