### ISSUE TITLE
环境变量的配置

### ISSUE THREAD

**Issue by aimuz** [YMFE/yapi#471]
## 版本号
1.3.20

## 什么问题
环境变量的配置是否太过限制呢，在postMan中，环境变量的配置，可以随意使用，而在 yapi，要么设置域名的环境变量，要么就是header。不应该是设置了什么，在哪里使用就可以吗

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by gaoxiaomumu** [comment]
这里只是针对环境的，有更多要求去请求配置里面写

**Comment by aimuz** [comment]
版本21 大概什么时候发布呢

**Comment by gaoxiaomumu** [comment]
明天
