### ISSUE TITLE
几个交互情况

### ISSUE THREAD

**Issue by xmsz** [YMFE/yapi#472]
1. 输入同名属性名的时候，先不要提示不让输入
因为比如我先输入了 value ， 然后我想输入个 value_2 
结果我打到valu的时候，就不让打了，这个很坑爹

2. 增加可调整顺序的

**Comment by xmsz** [comment]
3. 无法粘贴上传图片

4. 如何在http://yapi.demo.qunar.com/上创建分组？

**Comment by gaoxiaomumu** [comment]
1.  这个因为我们json schema 是双向绑定的，所以在输入之前会进行校验，你可以去看一下http://yapi.demo.qunar.com/editor/，可以复制进去你要写的值

2. 接口列表和测试集合都是可以调节顺序的，如果你说的是json schema 的话，目前正在考虑不一定会支持

3. 不知道你要去哪里上传图片

4. demo里面只有管理员有权限创建分组，demo只是展示不要在里面写项目，个人中心里面的功能和分组里面是一样的，除了没有成员管理
