### ISSUE TITLE
需求 希望增肌接口路径搜索功能

### ISSUE THREAD

**Issue by af826** [YMFE/yapi#473]
虽然有了接口名称搜索，但是在开发过程中大家普遍还是直接根据接口路径搜索，希望增加

**Comment by gaoxiaomumu** [comment]
接口路径可以搜索啊
![image](https://user-images.githubusercontent.com/21135585/43248391-4816260c-90ea-11e8-9698-34fb5b7cf3ab.png)
测试集合不可以
