### ISSUE TITLE
URL使用全局变量

### ISSUE THREAD

**Issue by aimuz** [YMFE/yapi#475]
## 版本号
1.3.20

## 什么问题
希望能在URL使用全局变量，类似于postman 这种用法
![355ce3bb-654f-495b-85aa-61a1bb6022fe](https://user-images.githubusercontent.com/17666471/43254727-95d5219e-90fa-11e8-8a10-628d5dbb3c38.png)

## 如何复现此问题
~ 

## 什么浏览器
Chrome 

## 什么系统（Linux, Windows, macOS）
MacOS

**Comment by gaoxiaomumu** [comment]
版本21 已经有了

**Comment by aimuz** [comment]
我更新发现，URL哪里还是只能一个，不能使用全局变量

**Comment by aimuz** [comment]
有的时候项目是通过 域名来区分服务的，一个APP里面，然后很多接口通过域名来区分

**Comment by gaoxiaomumu** [comment]
你说的这个环境变量不可以吗
![image](https://user-images.githubusercontent.com/21135585/43297921-5cfbd282-9186-11e8-9062-cac115174655.png)
![image](https://user-images.githubusercontent.com/21135585/43297932-6caa78d2-9186-11e8-8189-cab2e2304815.png)


可以啊，url 里面定义变量，  运行的时候变量值用{{global.name}}来表示

**Comment by aimuz** [comment]
我这里只能下拉选着，不能使用变量值来表示

**Comment by aimuz** [comment]
只能选择环境域名

**Comment by aimuz** [comment]
是这样的比如有个 环境 `Test`
然后 `Test` 里面含有全局变量

AAURL https://baidu.com
BBURL https://google.com

然后还有另外一个环境是 `Pro`

`Pro` 里面同样含有全局变量

AAURL https://paypal.com
BBURL https://github.com

然后就是有接口
`/api/aa` 它的接口地址使用的是 `AAURL`
`/api/bb` 它的接口地址使用的是 `BBURL`

当环境是 `Test` 的时候 
`/api/aa` 的正确地址应该是 `https://baidu.com/api/aa`
`/api/bb` 的正确地址应该是 `https://google.com/api/bb`

环境切换成Pro 的时候
`/api/aa` 的正确地址应该是 `https://paypal.com/api/aa`
`/api/bb` 的正确地址应该是 `https://github.com/api/bb`

**Comment by gaoxiaomumu** [comment]
你将这两个接口再复制一份， 定义4个环境变量就好了吧，定义好以后保存或者更新到测试集合你可以随便测试了，

**Comment by aimuz** [comment]
这样会不会太过麻烦呢，新版本没有可能加上这个需求，就是上述的那种用法

**Comment by aimuz** [comment]
好的，
