### ISSUE TITLE
没有历史测试报告展示的地方，没有测试通过率趋势情况

### ISSUE THREAD

**Issue by sephirothgao** [YMFE/yapi#476]
## 版本号
~ 

## 什么问题
点击“开始测试”，只会有单个case的当前执行报告，既看不到历史执行情况，也没有一个整合所有用例的报告。
服务端测试，只能看到本次测试执行情况，如果关掉页面，要再找本次执行记录，就找不到了，没有历史执行情况，且没有通过率变化趋势。

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by gaoxiaomumu** [comment]
没有的，这个需要自己统计
