### ISSUE TITLE
yapi 自动化测试是否可以整合到Jenkins?

### ISSUE THREAD

**Issue by Minglong** [YMFE/yapi#479]
## 版本号
~ 

## 什么问题
~请问yapi是否支持命令行执行自动化测试？是否可以整合到Jenkins?

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by gaoxiaomumu** [comment]
用服务端测试

**Comment by graceTesterZhang** [comment]
> 用服务端测试

尝试做了下，在centos上部署的yapi，用curl命令+yapi生成的url，总是报登录超时，求指点~~
