### ISSUE TITLE
特意登录来感谢并且提一个问题！！！

### ISSUE THREAD

**Issue by liu419249629** [YMFE/yapi#48]
首先非常感谢大大的这个开源的项目！

UI非常的赞，比之大多同类项目赏心悦目很多！

但是有个问题很影响使用体验！就是我是后端准备用这个来测试api的使用，在返回的数据body里面，都是乱吃一坨显示！

没有格式化！
`
{ "cookie": [], "Date": "Sat, 18 Nov 2017 03:14:17 GMT", "Server": "Apache/2.4.10", "Cache-Control": "private, no-cache", "X-Catalyst": "5.90075", "Content-Length": "678", "Connection": "close", "Content-Type": "text/html; charset=utf-8", "Proxy-Connection": "keep-alive" }`

就是如上一坨的没有格式化！希望得到的效果是：
```
{
    "cookie": [],
    "Date": "Sat, 18 Nov 2017 03:14:17 GMT",
    "Server": "Apache/2.4.10",
    "Cache-Control": "private, no-cache",
    "X-Catalyst": "5.90075",
    "Content-Length": "678",
    "Connection": "close",
    "Content-Type": "text/html; charset=utf-8",
    "Proxy-Connection": "keep-alive"
}

```
还有一个问题就是修改源码不知道为什么没有效果！
我修改的是：yapi/client/components/Postman/Postman.js

刷新后是没有效果的！！！

**Comment by suxiaoxin** [comment]
后端返回的 content-type 不是 application/json

**Comment by suxiaoxin** [comment]
如果要做简单的二次开发调试，参考插件 wiki -> 二次开发 文档

**Comment by liu419249629** [comment]
后端返回的就是： application/json

我希望得到的格式是如：

> {
    "msg":"操作成功",
    "data":{
        "token":"",
        "open_advert":{
            "advert_img_link":"https://static-test-old.shikee.tv/uploads/fadf900d/396dfb42/6a776c6e/c214193d/c214193d.jpeg",
            "link":""
        },
        "version_check":[
        ],
        "cate_data":[
            {
                "cid":"101",
                "name":"最新",
                "pid":"0",
                "sort":"1",
                "path":null,
                "title":"最新",
                "keyword":"最新",
                "descr":null,
                "is_allow_public":"1",
                "create_time":null,
                "is_enable":"1",
                "is_sort":"0",
                "icon_url":"new_1.png?version=1",
                "picurl":"https://static-test-old.shikee.tv/app/img/new_1.png?version=1"
            },
            {
                "cid":"102",
                "name":"最热",
                "pid":"0",
                "sort":"2",
                "path":null,
                "title":"最热",
                "keyword":"最热",
                "descr":null,
                "is_allow_public":"1",
                "create_time":null,
                "is_enable":"1",
                "is_sort":"0",
                "icon_url":"hot_1.png?version=1",
                "picurl":"https://static-test-old.shikee.tv/app/img/hot_1.png?version=1"
            },
            {
                "cid":"100",
                "name":"关注",
                "pid":"0",
                "sort":"3",
                "path":null,
                "title":"关注",
                "keyword":"关注",
                "descr":null,
                "is_allow_public":"1",
                "create_time":null,
                "is_enable":"1",
                "is_sort":"0",
                "icon_url":"follow_1.png?version=1",
                "picurl":"https://static-test-old.shikee.tv/app/img/follow_1.png?version=1"
            },
            {
                "cid":"18",
                "name":"健康",
                "pid":"0",
                "sort":"4",
                "path":null,
                "title":"健康",
                "keyword":"健康",
                "descr":null,
                "is_allow_public":"1",
                "create_time":null,
                "is_enable":"1",
                "is_sort":"1",
                "icon_url":"health_1.png?version=1",
                "picurl":"https://static-test-old.shikee.tv/app/img/health_1.png?version=1"
            },
            {
                "cid":"20",
                "name":"心理咨询",
                "pid":"0",
                "sort":"5",
                "path":null,
                "title":"心理咨询",
                "keyword":"心理咨询",
                "descr":null,
                "is_allow_public":"1",
                "create_time":null,
                "is_enable":"1",
                "is_sort":"1",
                "icon_url":null,
                "picurl":"https://static-test-old.shikee.tv/app/img/"
            },
            {
                "cid":"21",
                "name":"音乐治疗",
                "pid":"0",
                "sort":"6",
                "path":null,
                "title":"音乐治疗",
                "keyword":"音乐治疗",
                "descr":null,
                "is_allow_public":"1",
                "create_time":null,
                "is_enable":"1",
                "is_sort":"1",
                "icon_url":null,
                "picurl":"https://static-test-old.shikee.tv/app/img/"
            },
            {
                "cid":"22",
                "name":"养生",
                "pid":"0",
                "sort":"7",
                "path":null,
                "title":"养生",
                "keyword":"养生",
                "descr":null,
                "is_allow_public":"1",
                "create_time":null,
                "is_enable":"1",
                "is_sort":"1",
                "icon_url":null,
                "picurl":"https://static-test-old.shikee.tv/app/img/"
            },
            {
                "cid":"23",
                "name":"育儿",
                "pid":"0",
                "sort":"8",
                "path":null,
                "title":"育儿",
                "keyword":"育儿",
                "descr":null,
                "is_allow_public":"1",
                "create_time":null,
                "is_enable":"1",
                "is_sort":"1",
                "icon_url":null,
                "picurl":"https://static-test-old.shikee.tv/app/img/"
            },
            {
                "cid":"24",
                "name":"中医",
                "pid":"0",
                "sort":"9",
                "path":null,
                "title":"中医",
                "keyword":"中医",
                "descr":null,
                "is_allow_public":"1",
                "create_time":null,
                "is_enable":"1",
                "is_sort":"1",
                "icon_url":null,
                "picurl":"https://static-test-old.shikee.tv/app/img/"
            },
            {
                "cid":"25",
                "name":"其它",
                "pid":"0",
                "sort":"10",
                "path":null,
                "title":"其它",
                "keyword":"其它",
                "descr":null,
                "is_allow_public":"1",
                "create_time":null,
                "is_enable":"1",
                "is_sort":"1",
                "icon_url":null,
                "picurl":"https://static-test-old.shikee.tv/app/img/"
            }
        ],
        "special_check":{
            "is_foreign":0,
            "open_pay":1
        },
        "user_item":null,
        "my_live":[
        ],
        "user_sig":"",
        "synchronize":[
        ]
    },
    "code":200,
    "ext":84
}

而不是：

> { "msg":"操作成功", "data":{ "token":"", "open_advert":{ "advert_img_link":"https://static-test-old.shikee.tv/uploads/fadf900d/396dfb42/6a776c6e/c214193d/c214193d.jpeg", "link":"" }, "version_check":[ ], "cate_data":[ { "cid":"101", "name":"最新", "pid":"0", "sort":"1", "path":null, "title":"最新", "keyword":"最新", "descr":null, "is_allow_public":"1", "create_time":null, "is_enable":"1", "is_sort":"0", "icon_url":"new_1.png?version=1", "picurl":"https://static-test-old.shikee.tv/app/img/new_1.png?version=1" }, { "cid":"102", "name":"最热", "pid":"0", "sort":"2", "path":null, "title":"最热", "keyword":"最热", "descr":null, "is_allow_public":"1", "create_time":null, "is_enable":"1", "is_sort":"0", "icon_url":"hot_1.png?version=1", "picurl":"https://static-test-old.shikee.tv/app/img/hot_1.png?version=1" }, { "cid":"100", "name":"关注", "pid":"0", "sort":"3", "path":null, "title":"关注", "keyword":"关注", "descr":null, "is_allow_public":"1", "create_time":null, "is_enable":"1", "is_sort":"0", "icon_url":"follow_1.png?version=1", "picurl":"https://static-test-old.shikee.tv/app/img/follow_1.png?version=1" }, { "cid":"18", "name":"健康", "pid":"0", "sort":"4", "path":null, "title":"健康", "keyword":"健康", "descr":null, "is_allow_public":"1", "create_time":null, "is_enable":"1", "is_sort":"1", "icon_url":"health_1.png?version=1", "picurl":"https://static-test-old.shikee.tv/app/img/health_1.png?version=1" }, { "cid":"20", "name":"心理咨询", "pid":"0", "sort":"5", "path":null, "title":"心理咨询", "keyword":"心理咨询", "descr":null, "is_allow_public":"1", "create_time":null, "is_enable":"1", "is_sort":"1", "icon_url":null, "picurl":"https://static-test-old.shikee.tv/app/img/" }, { "cid":"21", "name":"音乐治疗", "pid":"0", "sort":"6", "path":null, "title":"音乐治疗", "keyword":"音乐治疗", "descr":null, "is_allow_public":"1", "create_time":null, "is_enable":"1", "is_sort":"1", "icon_url":null, "picurl":"https://static-test-old.shikee.tv/app/img/" }, { "cid":"22", "name":"养生", "pid":"0", "sort":"7", "path":null, "title":"养生", "keyword":"养生", "descr":null, "is_allow_public":"1", "create_time":null, "is_enable":"1", "is_sort":"1", "icon_url":null, "picurl":"https://static-test-old.shikee.tv/app/img/" }, { "cid":"23", "name":"育儿", "pid":"0", "sort":"8", "path":null, "title":"育儿", "keyword":"育儿", "descr":null, "is_allow_public":"1", "create_time":null, "is_enable":"1", "is_sort":"1", "icon_url":null, "picurl":"https://static-test-old.shikee.tv/app/img/" }, { "cid":"24", "name":"中医", "pid":"0", "sort":"9", "path":null, "title":"中医", "keyword":"中医", "descr":null, "is_allow_public":"1", "create_time":null, "is_enable":"1", "is_sort":"1", "icon_url":null, "picurl":"https://static-test-old.shikee.tv/app/img/" }, { "cid":"25", "name":"其它", "pid":"0", "sort":"10", "path":null, "title":"其它", "keyword":"其它", "descr":null, "is_allow_public":"1", "create_time":null, "is_enable":"1", "is_sort":"1", "icon_url":null, "picurl":"https://static-test-old.shikee.tv/app/img/" } ], "special_check":{ "is_foreign":0, "open_pay":1 }, "user_item":null, "my_live":[ ], "user_sig":"", "synchronize":[ ] }, "code":200, "ext":84 }
