### ISSUE TITLE
编辑时，删除掉body-form中的所有参数，保存失败

### ISSUE THREAD

**Issue by xulinfeng1991** [YMFE/yapi#480]
## 版本号
~ 
1.3.19
## 什么问题
~
接口无法保存
## 如何复现此问题
~ 
编辑一个已有接口，删除掉body-form中的所有参数，保存失败
## 什么浏览器
~ 
chrome
## 什么系统（Linux, Windows, macOS）
windows10

**Comment by gaoxiaomumu** [comment]
这里应该有个问题， 我们下个版本会修改， 目前你想保存可以添加一个空的form数据
![image](https://user-images.githubusercontent.com/21135585/43574255-4542fd60-9676-11e8-9b98-905c03b90ee6.png)
