### ISSUE TITLE
关于HOOK的若干问题

### ISSUE THREAD

**Issue by qiqizjl** [YMFE/yapi#481]
## 版本号
master

## 什么问题
目前正在开发钉钉推送的插件,遇到以下几个坑:
1:``interface_del`` 这个接口是否可在删除前触发?删除之后触发，无法找到对应的接口数据。或者增加一个``interface_del_after``之类的
2:目前执行hook的时候，无法确定是谁操作的。是否j将用户数据存入ctx,并在执行hook的时候带入ctx.
3:hook支持拦截操作，我们可以根据hook做一些拦截的操作，比如说不让修改 不让删除之类的等等

## 什么浏览器
Chrome

## 什么系统（Linux, Windows, macOS）
macOS

**Comment by gaoxiaomumu** [comment]
在 interface_del这里修改成能返回删除接口的详情，关注下个版本吧

**Comment by qiqizjl** [comment]
@gaoxiaomumu 第二条和第三条呢~
