### ISSUE TITLE
测试post有问题

### ISSUE THREAD

**Issue by liuhuanzhu** [YMFE/yapi#483]
我使用http://yapi.demo.qunar.com来进行接口测试。
测试get的时候是没问题的，当测试post的时候，后台会报403的错误，一直有跨域的问题。需要配置什么东西吗？

怎么来设置Response的参数。

谢谢。

**Comment by gaoxiaomumu** [comment]
file:///Users/qitmac000476/Documents/yapi-antd3.1.6/vendors/static/doc/documents/mock.html

**Comment by gaoxiaomumu** [comment]
https://yapi.ymfe.org/documents/mock.html

**Comment by liuhuanzhu** [comment]
应该不是mock返回的问题，现在的问题是跨域出错，如果能解决跨域问题就可以了。
我是在http://yapi.demo.qunar.com这个网站上开通了一个账号，然后新建了一个post方法，然后在我本地启动一个服务访问这个接口，这时候会报403错误。握手失败。
我想确认的是在http://yapi.demo.qunar.com这个网站上可以新建一个post方法，然后进行通信吗？如果出现跨域问题，如何处理？还是条件需要在自己的服务器上创建一个yapi服务，然后在进行调试等。

**Comment by gaoxiaomumu** [comment]
文档里面有几种mock 请求的使用方式，不知道你开启的服务是什么样子的， 我测试了一下是可以的，用charles进行的转发

**Comment by liuhuanzhu** [comment]
谢谢回答，应该是我使用的axios的问题，用jquery就没有问题。需要设置content-type。
