### ISSUE TITLE
请求的参数只能保存名字，不能保存参数值

### ISSUE THREAD

**Issue by sunwavebest** [YMFE/yapi#484]
新建一个接口后，习惯是直接就可以发请求，而不是在每次发请求前都要再填一遍参数值，这样太麻烦了。

大部分接口是不需要每次改参数值的，少数需要改，但可以用全局变量来设置，这样更方便。

**Comment by gaoxiaomumu** [comment]
你可以将你写好的请求，保存在测试集合里面，下次测试的时候就不需要重新再写一遍了
![image](https://user-images.githubusercontent.com/21135585/43695735-fbded906-996c-11e8-8631-e6379ed5fc6f.png)

**Comment by sunwavebest** [comment]
常用的场景是一个接口被多个测试集合调用，那不是要保存多次吗？




| |
Sunbo
|
|
Sunwavebest@126.com
|

Signature is customized by Netease Mail Master

在2018年08月06日 11:38，高晓琳 写道：

你可以将你写好的请求，保存在测试集合里面，下次测试的时候就不需要重新再写一遍了

**Comment by gaoxiaomumu** [comment]
是的，测试集合里面可以重复保存多个测试用例

**Comment by sunwavebest** [comment]
我知道现在不能，只是提一个建议




| |
Sunbo
|
|
Sunwavebest@126.com
|

Signature is customized by Netease Mail Master

在2018年08月08日 18:02，高晓琳 写道：

Closed #484.
