### ISSUE TITLE
请求异常，请检查 chrome network 错误信息...

### ISSUE THREAD

**Issue by wuzhitian** [YMFE/yapi#486]
## 版本号
~ v1.3.21

## 什么问题
~ chrome 运行 postman 导入的接口报错
`请求异常，请检查 chrome network 错误信息...`

## 如何复现此问题
~ 

## 什么浏览器
~ chrome 68 以上的版本
 
## 什么系统（Linux, Windows, macOS）
macOS

**Comment by gaoxiaomumu** [comment]
那你就看一下 chrome 浏览器下的network 对这个接口的请求有什么报错

**Comment by BayesZou** [comment]
碰到了类似的问题，警告 `Provisional headers are shown`，提示错误 `(failed)
net::ERR_TUNNEL_CONNECTION_FAILED`

测试的接口为 HTTPS，YAPI 的部署已通过反向代理设置为 HTTPS

希望有提供帮助 :) @gaoxiaomumu
