### ISSUE TITLE
权限bug：分组开发者成员可以随意修改组内项目的接口

### ISSUE THREAD

**Issue by qorzj** [YMFE/yapi#487]
## 版本号
1.3.21

## 什么问题
分组内的成员如果角色是开发者，他就可以修改分组内任意项目的任意接口。这对于公司级的应用是很大的安全隐患（也许是我的用法不对？）

## 什么浏览器
Chrome 

## 什么系统（Linux, Windows, macOS）
yapi 部署在 ubuntu(docker)

### 还是要给yapi点赞！

**Comment by cnlzxin** [comment]
@qorzj 如果不想让对方修改接口, 设置`访客`权限试试

**Comment by qorzj** [comment]
@gaoxiaomumu 也就是说分组的开发者、组长自动就是分组里面所有项目的开发者和组长？
@cnlzxin 希望组内成员不能看到和修改自己没有参与的项目，但是又能新建项目。貌似怎么弄都不行。

**Comment by cnlzxin** [comment]
@qorzj 希望组内成员不能看到和修改自己没有参与的项目

**Comment by cnlzxin** [comment]
@qorzj 

> 希望组内成员不能看到和修改自己没有参与的项目

可以把对方添加到指定`项目成员列表`, 但不添加到`组成员列表`, 组成员对组内所有项目都有相同权限

> 但是又能新建项目

这个就做不到了, 只能组内成员才有权限新建项目
