### ISSUE TITLE
有些链接不能访问了

### ISSUE THREAD

**Issue by bhaltair** [YMFE/yapi#488]
## 版本号
v1.3.4

## 什么问题
https://yapi.ymfe.org/case.html
https://www.ymfe.org/about

## 如何复现此问题
点击上面的链接

## 什么浏览器
chrome

## 什么系统（Linux, Windows, macOS）
mac

**Comment by gaoxiaomumu** [comment]
请升级一下yapi吧，我们现在的版本到1.3.21了，以前的文档站已经取消了
