### ISSUE TITLE
提问：是否能够支持Postman v2的格式

### ISSUE THREAD

**Issue by mijiawei** [YMFE/yapi#489]
## 版本号
v1.3.21

## 什么问题
Postman v1不支持文件夹中的上下级关系
Postman v2支持

## 如何复现此问题
功能不支持

## 什么浏览器
Chrome

## 什么系统（Linux, Windows, macOS）
macOS

**Comment by gaoxiaomumu** [comment]
如果需要可以自己仿照postman插件写一个可以支持 v2的postman导入插件   https://yapi.ymfe.org/documents/plugin-index.html
