### ISSUE TITLE
能否不登录就能够查看接口文档和接口的mock功能

### ISSUE THREAD

**Issue by wangchangsong** [YMFE/yapi#490]
能否不登录就能够查看接口文档和接口的mock功能

**Comment by gaoxiaomumu** [comment]
数据mock是不需要登录就可以拉取数据的， 接口文档是什么？ 帮助文档吗？

**Comment by wangchangsong** [comment]
举个例子，我是这个文档的编辑者，我把文档编辑完毕并且部署好了。其他人如果想看文档的内容，不需要登录就可以直接看到文档内容

**Comment by gaoxiaomumu** [comment]
yapi 是一个接口文档，需要有权限设置的，这个做不到。 感觉你想要的是那种开放接口文档的形式
