### ISSUE TITLE
json-schema返回数据在预览页能否直接显示全部节点内容？

### ISSUE THREAD

**Issue by bowenliang123** [YMFE/yapi#491]
## 版本号
~ 1.3.22

## 什么问题
~ 接口预览页面对json-schema的返回数据展示不友好，能否直接显示全部节点？

目前：要一层一层打开object节点才能完全了解返回数据
这已经成为决定是否使用该服务的痛点。

![image](https://user-images.githubusercontent.com/1935105/43937947-88348922-9c93-11e8-952d-61df10ae411c.png)

期待：直接在预览页展示所有子节点内容。
![image](https://user-images.githubusercontent.com/1935105/43937968-b1b83532-9c93-11e8-85b9-0ff869b876c3.png)

## 如何复现此问题
~ 使用json-schema的返回数据

## 什么浏览器
~ Chrome

## 什么系统（Linux, Windows, macOS）
macOS

**Comment by bowenliang123** [comment]
或者有没有什么配置开关可以做到自动展开的效果？

**Comment by gaoxiaomumu** [comment]
没有

**Comment by gaoxiaomumu** [comment]
没办法，antd 就是这样的， 普通json 可以写注释

**Comment by bowenliang123** [comment]
请问antd是ant design吗，这个json schema的展示具体用了antd的什么组件实现，我可以帮忙看一眼吗

**Comment by gaoxiaomumu** [comment]
这个明显是antd 的table  ,如果你想要这种形式可以二次开发
