### ISSUE TITLE
请求设置的post ，但是点击运行会变成get

### ISSUE THREAD

**Issue by fairytaleordemon** [YMFE/yapi#492]
## 版本号
~ 

## 什么问题
~请求设置的post，点击后发送的请求变成get。postman调用没有该现象。

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by fairytaleordemon** [comment]
chrome 67.0，windows 7

**Comment by gaoxiaomumu** [comment]
有可能是你的服务是https 但是你在yapi上的环境变量是 http ,这个问题应该不是yapi的问题，很可能是你自己设置的问题，请仔细检查

**Comment by fairytaleordemon** [comment]
今天找到了，非常感谢！




原始邮件
发件人:高晓琳notifications@github.com
收件人:YMFE/yapiyapi@noreply.github.com
抄送:fairytaleordemonbefairytale@163.com; Authorauthor@noreply.github.com
发送时间:2018年8月13日(周一) 11:59
主题:Re: [YMFE/yapi] 请求设置的post ，但是点击运行会变成get (#492)


有可能是你的服务是https 但是你在yapi上的环境变量是 http ,这个问题应该不是yapi的问题，很可能是你自己设置的问题，请仔细检查
