### ISSUE TITLE
其他接口需要获取登录接口的token,然后进行加密

### ISSUE THREAD

**Issue by guoxin123** [YMFE/yapi#493]
## 版本号
~ 1.3.22

## 什么问题
~

## 如何复现此问题
~ 我们公司有很多接口都需要在headers中传一个叫sign的参数，sign = md5(登录后产生的token + 密钥 + 时间戳)，我在heders中使用md5函数使用不了啊？

## 什么浏览器
~ chrome

## 什么系统（Linux, Windows, macOS）
yapi搭建在linux上，我自己写yapi是在windows上

##备注：
比如定单接口，接口的headers中需要传sign，这个sign = md5(登录后产生的token + 密钥 + 时间戳)，我在headers的参数行使用md5函数，使用不了。而且我在pre-request中使用$.41.body.token也不支持这种语法。。。我不知道该怎么做了。。。。。。。其实我需要的就是拿登录后返回的token进行加密，然后放在其他接口的headers中。。。。。。。。谁能告诉我怎么做啊？还是yapi没有这有这种功能呢？

我的QQ：562389830，微信：g562389830

**Comment by gaoxiaomumu** [comment]
https://yapi.ymfe.org/documents/project.html#%E8%AF%B7%E6%B1%82%E9%85%8D%E7%BD%AE，请求配置的使用方法

**Comment by guoxin123** [comment]
@gaoxiaomumu   我个文档我以前看过，并不满足啊

![image](https://user-images.githubusercontent.com/9880420/44020193-b81c4ba2-9f13-11e8-9796-ecb1cf52fa6c.png)

**Comment by gaoxiaomumu** [comment]
把token值存到localStorage 里面， $.global 并没有这种表示方式

**Comment by guoxin123** [comment]
@gaoxiaomumu 我也有想过这个方法，但不知道怎么操作，可以具体说下吗？ 贴上代码最好了，哈哈（我用这种思路之前写了点js,但没成功。。。。）

**Comment by gaoxiaomumu** [comment]
![image](https://user-images.githubusercontent.com/21135585/44021876-85f48400-9f18-11e8-9616-a57f8912bc6f.png)

**Comment by guoxin123** [comment]
@gaoxiaomumu 完美解决，多谢大神，最好把这些也放在帮助文档上，哈哈

**Comment by gaoxiaomumu** [comment]
服务端测试不能使用
