### ISSUE TITLE
建议在项目图标上标识出是私有还是公开

### ISSUE THREAD

**Issue by ZerryZhong** [YMFE/yapi#494]
当项目比较多时，权限管理就比较重要了；现在是需要点进去项目，查看设置，才知道该项目是私有还是公开；建议在项目图标上标识出是私有还是公开，这样就在外层也能一目了然知道项目的权限了。

**Comment by gaoxiaomumu** [comment]
如果你没有这个项目的权限却能够看到这个项目，说明他是公开项目
