### ISSUE TITLE
是否会考虑添加状态码

### ISSUE THREAD

**Issue by guanrongYang** [YMFE/yapi#495]
接口返回值中,总是会有状态码, 以表示结果的不同状态. 而该系统现在还没有状态码的管理, 是否会考虑添加状态码呢?

**Comment by gaoxiaomumu** [comment]
如果需要定义状态可以在返回数据设置里面写随机数据，或者在json schema 中定义枚举都是可以的，如果还是不能满足你可以去高级mock里面自定义， 状态码的描述可以写在 备注里面

**Comment by guanrongYang** [comment]
```js
{
    "code": "10000A",
    "msg": "用户不存在或者密码错误"
}
```
我想表达以上的意思, 但这个code会是一个比较大的列表, 为了方便开发人员查询到所有的code, 我觉得应该有一个地方可以存放这个列表才好吧. 就像下面一样.

### 用户相关
| 状态码 | 描述 | 备注 |
| ----------| ------ | ------ |
|   10000A |  用户不存在或者密码错误 |   |
|  ... |  ...  | ....  |

另外关于枚举方面, 由于常量的值在不同的接口中都会用到, 所以一旦一个枚举的值发生了变化, 那么就要更新所有的接口, 会不会有点麻烦或者容易出现遗漏部分接口没有更新的情况? 我之前的做法是另外使用一个文档来记录这些常量, 以及状态码. 不知道这些在接口文档的设计中是否需要考虑呢?

**Comment by gaoxiaomumu** [comment]
项目公共的描述信息可以写的wiki里面

**Comment by guanrongYang** [comment]
> 项目公共的描述信息可以写的wiki里面

这确实是个不错的想法. 如果wiki能够像github的wiki那样的话, 可以拓展开得内容会多很多, 但苦于只有一页, 如果写的列表行数过多, 或者内容的类别过多, 这样也挺不好管理的.
