### ISSUE TITLE
邮件通知的BUG

### ISSUE THREAD

**Issue by zl939144892** [YMFE/yapi#497]
## 版本号
~ 1.3.22

## 什么问题
~ 收到通知邮件的人, 点开接口名的超链接, 会变成127.0.0.1的地址

## 如何复现此问题
~ 我是用的域名解析, nginx转发的方式, 平时使用域名进行访问

## 什么浏览器
~ chrome

## 什么系统（Linux, Windows, macOS）
Linux

希望能配置这个地址

**Comment by gaoxiaomumu** [comment]
这里的链接信息用的是域名

**Comment by zl939144892** [comment]
并不是啊
![tim 20180815202505](https://user-images.githubusercontent.com/18364560/44148132-83097824-a0c9-11e8-8fcc-078daaf61b36.png)

**Comment by gaoxiaomumu** [comment]
因为你用 127.0.0.1:3000 访问的yapi

**Comment by zl939144892** [comment]
我是用域名访问的, 这个部署在服务器上, 我根本不可能通过127.0.0.1的方式访问到!

**Comment by zl939144892** [comment]
我是用nginx转发到127.0.0.1:3000上的

**Comment by gaoxiaomumu** [comment]
那就有可能是你nginx配置的问题，我们线上线下都没有这个问题

**Comment by tabunnnn** [comment]
是不是没有转发Host？

**Comment by yuqingc** [comment]
@gaoxiaomumu 我也遇到了这个问题，请问你是如何解决的？

**Comment by FalconIA** [comment]
关闭的莫名其妙……

**Comment by Asmallcabbage** [comment]
proxy_set_header  Host  $host;
proxy_set_header  X-real-ip $remote_addr;
proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;

nginx配置转发host就可以了

**Comment by zl939144892** [comment]
> proxy_set_header Host $host;
> proxy_set_header X-real-ip $remote_addr;
> proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> 
> nginx配置转发host就可以了

Thx
