### ISSUE TITLE
单个接口运行后，也有必要显示Request和脚本断言结果

### ISSUE THREAD

**Issue by sunwavebest** [YMFE/yapi#498]
如题。
方便查看发送的Request信息（如：header/url/parameter/body等）是否正确，以及返回值的断言结果是否如预期。另外，除了返回值的json-schema验证，还需要对返回值本身做验证，比如是否包含“success”等。

**Comment by gaoxiaomumu** [comment]
单个接口运行这些可以肉眼观察吧， header 等信息去控制台network里面查看就好了

**Comment by gandao** [comment]
我们好好的解释，你有意见可以提，不要说些什么"就自己玩吧“这种话，这个产品开源出来是方便大家，大家有什么需求我们这里会统计，但是我们会以我们公司自己使用的角度出发，来判断这个需求值不值得做，你觉得不满意，可以，我们有没有强制要你使用，那请你用你的Word呗！

**Comment by sunwavebest** [comment]
你那也叫好好解释？？不想多说了，已经找到更好的开源项目了，拜拜了！！




| |
Sunbo
|
|
Sunwavebest@126.com
|

Signature is customized by Netease Mail Master

在2018年08月16日 14:34，gandao 写道：

我们好好的解释，你有意见可以提，不要说些什么"就自己玩吧“这种话，这个产品开源出来是方便大家，大家有什么需求我们这里会统计，但是我们会以我们公司自己使用的角度出发，来判断这个需求值不值得做，你觉得不满意，可以，我们有没有强制要你使用，那请你用你的Word呗！

**Comment by gandao** [comment]
不送！
