### ISSUE TITLE
能否考虑增加以下两个功能

### ISSUE THREAD

**Issue by smilealgernon** [YMFE/yapi#499]
1.接口标签功能，可以根据标签在列表中展示、过滤。这样比如有些接口是需要授权的，有些不需要的，打个标签，看起来直观点。
2.Response定义里，增加类似于swagger model的功能。有些参数是重复出现的，比如说用户信息，定义好了model就可以在其他接口里引用。

**Comment by gaoxiaomumu** [comment]
第一个功能正在制作中

**Comment by smilealgernon** [comment]
第二个我写在mock里试试，多谢~

**Comment by gaoxiaomumu** [comment]
不过我觉得对于前端同学来说他们应该更希望在接口返回值那里看到完整的数据结构

**Comment by smilealgernon** [comment]
是的，我试过全局mock了，在Random.extend里面定义，可以在接口编辑器里用占位符引用。发现几个不方便的地方 
1.接口编辑器里的预览里看不到自定义占位符的效果，只能运行看到 
2.在某个接口里定义的占位符，在其他接口里似乎也可以引用 
3.如果想定义个复杂点的变量(占位符)，比如用户信息，还是要通过js的方式写，占位符不能用

所以，还是老老实实的多些几遍吧
