### ISSUE TITLE
请问是否可用增加，通过url的swagger.json，每天动态刷新接口呢？？

### ISSUE THREAD

**Issue by xieyingbiao** [YMFE/yapi#500]
开发swagger.json实时都在变化，每次都需要重新导入一次，达不到实时同步的作用，能否增加功能，在配置的接口目录下指定一个url类的就送，每次进入都会动态刷新文档，保证文档的同步

**Comment by gaoxiaomumu** [comment]
swagger 导入支持命令行导入 https://yapi.ymfe.org/documents/data.html#%E9%80%9A%E8%BF%87%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%AF%BC%E5%85%A5%E6%8E%A5%E5%8F%A3%E6%95%B0%E6%8D%AE
