### ISSUE TITLE
是否考虑增加三级目录的功能，接口过多，很难管理

### ISSUE THREAD

**Issue by wangshuai0** [YMFE/yapi#501]
## 版本号
~ 

## 什么问题
~

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by gaoxiaomumu** [comment]
我们提倡扁平化管理接口，可以将项目拆分成多个子项目

**Comment by wangshuai0** [comment]
多个子项目的 项目ID 是不一样的，没办法写成统一的 baseUrl ，这点不知道怎么解决

**Comment by gaoxiaomumu** [comment]
可以后期统一修改

**Comment by gaoxiaomumu** [comment]
将baseUrl  抽出来， 联调的时候修改baseUrl 就好了
