### ISSUE TITLE
能否支持参数化？

### ISSUE THREAD

**Issue by zhangwk02** [YMFE/yapi#503]
## 版本号
~ 

## 什么问题
~

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by gaoxiaomumu** [comment]
什么意思？

**Comment by gaoxiaomumu** [comment]
你可以好好看一下[接口配置](https://yapi.ymfe.org/documents/api.html#%E6%8E%A5%E5%8F%A3%E9%85%8D%E7%BD%AE)和 [高级mock](https://yapi.ymfe.org/documents/adv_mock.html)
