### ISSUE TITLE
用 nginx 代理，cas登录不可用

### ISSUE THREAD

**Issue by sandheart** [YMFE/yapi#508]
如果不用代理，就很难解决域名和端口的问题

## 版本号
~v1.3.22

## 什么问题
~用 nginx 代理后，cas登录不可用

## 如何复现此问题
~ 用 nginx 代理

## 什么浏览器
~ chrome

## 什么系统（Linux, Windows, macOS）
Linux

**Comment by sandheart** [comment]
解决了，代理时把域名透过去就可以了

**Comment by lvbaocheng** [comment]
> 解决了，代理时把域名透过去就可以可以了

请问你这是怎么配置的呢，我nginx代理本地的yapi，通过内网穿透出去，访问502
