### ISSUE TITLE
RAP迁移到YAPI有什么好的建议没

### ISSUE THREAD

**Issue by huqiliang** [YMFE/yapi#509]
## 版本号
~ 
无
## 什么问题
~
从RAP迁移，不知道从哪里下手
## 如何复现此问题
~ 
无
## 什么浏览器
~ 
无
## 什么系统（Linux, Windows, macOS）
无

**Comment by hellosean1025** [comment]
写一个 rap 数据导入插件

**Comment by wuchengwei0122** [comment]
咋们的YAPI数据格式有公开文档吗？ @hellosean1025
