### ISSUE TITLE
HTTP status 不是200时接口运行返回结果Body有问题

### ISSUE THREAD

**Issue by boyaq** [YMFE/yapi#51]
hey, 项目不错哦。
不过遇到一个问题。
接口返回的HTTP Status不是**200**的时候，接口运行返回结果body里不显示json反而显示错误Title. 
我们公司规范中requst validation error 的时候要返回**422**并把错误返回给客户端的。Postman处理的非常不错，你们能不能要调整一下哦 多谢了

**Comment by suxiaoxin** [comment]
ok,我调整下

**Comment by suxiaoxin** [comment]
@boyaq 已确实问题，感谢反馈，本周五发布的 v1.2.7 版本修复
