### ISSUE TITLE
忘记管理员密码该怎么重置

### ISSUE THREAD

**Issue by AriaLyy** [YMFE/yapi#510]
## 版本号
1.3.22

## 什么问题
忘记管理员密码了

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by gaoxiaomumu** [comment]
去数据库修改

**Comment by zoulux** [comment]
数据库密码是加盐的，所以你要找一个同事的密码，将 password 和 passsalt 复制到admin的字段上即可
