### ISSUE TITLE
安装模块报jsonpath错误

### ISSUE THREAD

**Issue by droidxiao** [YMFE/yapi#511]
## 版本号
~ 1.3.7

## 什么问题
~一直报Failed at the jsonpath@1.0.0 postinstall script.

## 如何复现此问题
~ npm install --production --registry https://registry.npm.taobao.org

## 什么浏览器
~ 

## 什么系统（Linux, Windows, macOS）
Linux

**Comment by droidxiao** [comment]
<img width="765" alt="wx20180827-144232 2x" src="https://user-images.githubusercontent.com/3190398/44644747-c61bbe00-aa07-11e8-9dee-08967b7b0764.png">

**Comment by gaoxiaomumu** [comment]
错误提示里面有说你的权限不够，建议新建一个有自己权限的文件夹，在该文件夹下安装yapi

**Comment by droidxiao** [comment]
![image](https://user-images.githubusercontent.com/3190398/44657889-1a876380-aa31-11e8-8407-1cb1dcbdfde8.png)


不行，还是报错

**Comment by fail2010** [comment]
我用root 权限也一样
试过删除node_module文件夹, 都不行, 重新装也不行

**Comment by fail2010** [comment]
gyp ERR! stack Error: EACCES: permission denied, mkdir './yapi/vendors/node_modules/node-sass/.node-gyp'
gyp ERR! System Linux 3.13.0-130-generic
gyp ERR! command "/usr/local/node-v10.15.3-linux-x64/bin/node" "./yapi/vendors/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd ./vendors/node_modules/node-sass
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
