### ISSUE TITLE
;被转义为%3B

### ISSUE THREAD

**Issue by suyilearn** [YMFE/yapi#513]
## 版本号
~ v1.3.22
## 什么问题
~ 引用前一测试的body返回值 token 中的;被转义为%3B
## 如何复现此问题
~ 下一个测试引用上一个测试的返回值,返回值中包含; 当被引用为新的测试的参数值时被转义为%3B

如上一个测试的token值为:

"token": "bearer;eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyVHlwZSI6Iuezu-e7n-euoeeQhuWRmCIsInVuaXF1ZV9uYW1lIjoiYWRtaW4iLCJ1c2VySWQiOjEsImV4cCI6MTUzNTUzNzkzMywibmJmIjoxNTM1NDUxNTMzfQ.z8yx05pDdISNBL7ZQGx2rwlXtyyfNwXHMBALeuPGb04"

下一个测试进行引用:
$.81.body.token

那么请求参数为:
/login/validate?__vt_param__=bearer%3BeyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyVHlwZSI6Iuezu-e7n-euoeeQhuWRmCIsInVuaXF1ZV9uYW1lIjoiYWRtaW4iLCJ1c2VySWQiOjEsImV4cCI6MTUzNTUzODE1MCwibmJm...

## 什么浏览器
~ Chrome
## 什么系统（Linux, Windows, macOS）
任何平台都会出现....

**Comment by gaoxiaomumu** [comment]
出现在url上的特殊字符好想都会被转译，但是转译后并不会影响后续的处理啊
![image](https://user-images.githubusercontent.com/21135585/44972317-53708c80-af8b-11e8-9e16-54de21cfb2cf.png)
