### ISSUE TITLE
测试集合管理很不方便

### ISSUE THREAD

**Issue by sephirothgao** [YMFE/yapi#516]
## 版本号
2.1

## 什么问题
比如在公共测试集合下写了很多测试用例，现在产生了把这些测试用例分组的需求，也就是A集合下面的某些用例，需要快速转移到B集合下，目前并没有很好的办法。

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by gaoxiaomumu** [comment]
拖动

**Comment by sephirothgao** [comment]
接口确实可以拖动，但测试集合无法拖动，难道是我拖动的姿势不对么

**Comment by sephirothgao** [comment]
刚又试了一下，有些能拖动，有些无法拖动，应该是和克隆失败同一个问题，对用例里面某些字段解析出现的问题，导致无法克隆或者拖动成功。

**Comment by sephirothgao** [comment]
即使可以拖动，还有一个前端使用体验的问题，就是如果用例很多，超过一屏，那么拖动时用例栏的滚动条无法随着鼠标往下移动而自动滚动，造成用例无法拖动到下方其它集合中，希望能够优化。

**Comment by gaoxiaomumu** [comment]
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/21135585/44964557-c49c4980-af63-11e8-83e9-1d8dfb1afc4f.gif)
我测试了一下向上滚和向下滚还是可以滚动的，如果觉得不方便可以将要交换的分类先拖动到邻近的位置再对里面的用例进行拖动
