### ISSUE TITLE
一个用户被删除后不会自动从项目组成员列表被删除

### ISSUE THREAD

**Issue by eden214** [YMFE/yapi#517]
## 版本号
1.3.22

## 什么问题
一个用户被删除后不会自动从项目组成员列表被删除，点用户的名字跳到一个空白页没有任何提示，看请求是说不存在该用户。
建议最好能做到自动从项目组和项目的成员列表删除，另外在被删除的用户详情页提示不存在该用户。

## 如何复现此问题
将一个用户添加到项目的成员列表，然后删除该用户

## 什么浏览器
chrome

## 什么系统（Linux, Windows, macOS）
Windows

**Comment by xiehongxin** [comment]
问题同上。从项目组删除该成员后该成员依然能看到项目
浏览器： chrome
系统：Centos7

**Comment by xiehongxin** [comment]
个人浅见：
作者的设计应该是用户被删除了相当于从数据库删除了该用户信息，所以该用户不存在，需要重新注册，重新注册帐号密码跟之前一样也没问题。  
如果只是要该用户看不见项目组的内容，在用户组及项目的“成员管理”把该用户删除即可

**Comment by xiehongxin** [comment]
噢噢，明白了
