### ISSUE TITLE
建议增加注册时限制邮箱后缀的功能

### ISSUE THREAD

**Issue by eden214** [YMFE/yapi#518]
## 版本号
~ 

## 什么问题
建议增加注册时限制邮箱后缀的功能

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by gaoxiaomumu** [comment]
因为邮箱后缀很繁多，没发特定限制，建议二次开发

**Comment by eden214** [comment]
@gaoxiaomumu 不是要在程序里直接限制，是想说能不能在配置文件里可以配置想要限制的邮箱后缀，禁止注册的功能都能配置，限制注册的功能应该也可以这么搞

**Comment by gaoxiaomumu** [comment]
只是我们这边觉得这个功能是非必要的

**Comment by sealinger** [comment]
> 只是我们这边觉得这个功能是非必要的

说实话，真的很有必要。不然注册后的用户不知道是谁，清理用户时会很麻烦。

**Comment by zycfcn** [comment]
> > 只是我们这边觉得这个功能是非必要的
> 
> 说实话，真的很有必要。不然注册后的用户不知道是谁，清理用户时会很麻烦。

+1

**Comment by zhouhs0019** [comment]
+1
