### ISSUE TITLE
如果前端请求的字段格式既可以是字符串也可以是列表，接口文档怎样编写？

### ISSUE THREAD

**Issue by xiehongxin** [YMFE/yapi#519]
## 版本号
1.3.22

## 什么问题
如果前端请求的字段格式既可以是字符串也可以是列表，又开启了严格模式，接口文档怎样编写？

## 如何复现此问题
~ 

## 什么浏览器
~chrome

## 什么系统（Linux, Windows, macOS）
Linux

**Comment by gaoxiaomumu** [comment]
不开启吧，那还能怎么写
