### ISSUE TITLE
Stored XSS in Project Name

### ISSUE THREAD

**Issue by sowish** [YMFE/yapi#520]
## Version
~ 1.3.22

## Problem
~ Stored XSS in Project Name

## 如何复现此问题
1. Register a account in the demo domain http://yapi.demo.qunar.com/
 Then new a project:
![](https://wps2015-1252123187.cos.ap-chengdu.myqcloud.com/aaa.png)
Insert the paload `xss"><img src=1 onerror=alert(/xss/)>` in project name  and set the project as public.
2. Then put the project to as public group ,such as `test2`, so every one can view the project
![](https://wps2015-1252123187.cos.ap-chengdu.myqcloud.com/bbb.png)
3. When the someone including the managers & administrators views the operation dynamics of the project,  malicious js code will execute.
![](https://wps2015-1252123187.cos.ap-chengdu.myqcloud.com/ccc.png)
![](https://wps2015-1252123187.cos.ap-chengdu.myqcloud.com/fff.png)

## 什么浏览器
~ chrome

## 什么系统（Linux, Windows, macOS）
~ Linux

**Comment by gaoxiaomumu** [comment]
感谢建议

**Comment by sowish** [comment]
Please confirm it or not.

**Comment by sowish** [comment]
@gaoxiaomumu Does the issue have been fixed ? If it does, please show me the commit.Thanks
