### ISSUE TITLE
不同空间下面的项目该如何拷贝或者克隆

### ISSUE THREAD

**Issue by sephirothgao** [YMFE/yapi#521]
## 版本号
~ 

## 什么问题
在系统里建立了几个不同空间，在A空间里面创建了项目a，里面包含接口和测试集合，现在需要把项目a整个迁移到或者克隆到B空间下。请问有没有办法实现？实际的需求就是这样。

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by gaoxiaomumu** [comment]
同一个yapi  里面 项目迁移就可以了https://yapi.ymfe.org/documents/project.html#%E9%A1%B9%E7%9B%AE%E8%BF%81%E7%A7%BB
 也可以数据管理那边导出json  再导入  json
