### ISSUE TITLE
json-schema默认开启且无法关闭

### ISSUE THREAD

**Issue by t-jesus** [YMFE/yapi#523]
## 版本号
 1.3.22

## 什么问题
json-schema默认开启状态且无法关闭？

## 如何复现此问题
 编辑接口时就能看到json-schema是开启的，且灰色无法点击关闭

## 什么浏览器
 chrome

## 什么系统（Linux, Windows, macOS）
Windows

**Comment by gaoxiaomumu** [comment]
项目  设置里面

**Comment by t-jesus** [comment]
感谢。
