### ISSUE TITLE
富文本编辑器有问题，总是莫名其妙的多出星号，而且格式保存查看就乱了

### ISSUE THREAD

**Issue by chen1chen2** [YMFE/yapi#529]
## 版本号
1.3.18

## 什么问题
富文本编辑器有问题，总是莫名其妙的多出星号，而且格式保存查看就乱了

## 如何复现此问题
富文本编辑器编辑文本，加粗

## 什么浏览器
chrome

## 什么系统（Linux, Windows, macOS）
Windows

**Comment by gaoxiaomumu** [comment]
请问是哪里的富文本编辑器？ 可以截图吗

**Comment by chen1chen2** [comment]
文档编辑里面，备注位置，备注加粗后，保存，查看文档，发现格式变动了，而且有些字变成了**星号，这个里面不能截图啊

**Comment by gaoxiaomumu** [comment]
这样是markdown的问题，你可以写完之后 看一下  这里面的markdown和  preview


![image](https://user-images.githubusercontent.com/21135585/45014743-2f2bb300-b052-11e8-89ef-9fd32d763d9f.png)
