### ISSUE TITLE
数据导入功能在chrome下的bug

### ISSUE THREAD

**Issue by hearain528** [YMFE/yapi#53]
![image](https://user-images.githubusercontent.com/9366481/33071566-020e1792-cef7-11e7-8fd9-c44ea0ee024b.png)

**Comment by suxiaoxin** [comment]
方便的话，发下导入的文件

**Comment by hearain528** [comment]
不是文件的问题，我还没上传呢。。点那个下拉框选择按钮就不能点，然后查看控制台有报错

**Comment by suxiaoxin** [comment]
@hearain528 我这边没问题, 示例站点 yapi.demo.qunar.com 也没问题

**Comment by hearain528** [comment]
恩恩，，不知道为啥，同样的代码，我windows上部署就有那个问题，centos上面部署就好了

**Comment by hearain528** [comment]
不过生成的response能不能加上每个字段的注释，swagger.json文件里面有描述，导进来就没字段描述了

**Comment by suxiaoxin** [comment]
目前实现不了，这里不兼容
