### ISSUE TITLE
【BUG】接口存在同名参数，可以正常编辑保存，但在运行时设置不同value却会被置为相同的值

### ISSUE THREAD

**Issue by mijiawei** [YMFE/yapi#533]
## 版本号
1.3.22

## 什么问题
GET请求中存在同名参数，接口可以正常编辑保存，但在运行时设置不同value进行测试，同名参数被自动置为相同的值（第一个值）；查看request，也只发送了一个参数

## 如何复现此问题
使用传参中存在同名参数key的接口，对其中的key设置不同的value1,value2,.....进行测试，查看request

## 什么浏览器
Chrome

## 什么系统（Linux, Windows, macOS）
macOS

**Comment by gaoxiaomumu** [comment]
为啥参数是同名的，这个设置本来就不是很合理

**Comment by mijiawei** [comment]
同名参数传入可以由框架处理组成为List的
