### ISSUE TITLE
项目下，测试集合下，总的测试用例数，没有地方可以看到

### ISSUE THREAD

**Issue by sephirothgao** [YMFE/yapi#535]
## 版本号
~ 

## 什么问题
项目下，测试集合下，总的测试用例数，没有地方可以看到，别人问有多少用例，需要自己去数吗？

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by gaoxiaomumu** [comment]
服务端测试会有测试用例数，其他的没有
