### ISSUE TITLE
在返回数据中无法设置图片的大小

### ISSUE THREAD

**Issue by fengbaozhiling** [YMFE/yapi#536]
## 版本号
~ 
版本: 1.3.22
## 什么问题
~
返回数据设置中可以设置某个字段为图片，但是无法设置图片的大小

## 如何复现此问题
~ 
总是
## 什么浏览器
~ 
chrome
## 什么系统（Linux, Windows, macOS）
Windows

**Comment by gaoxiaomumu** [comment]
确实不能
