### ISSUE TITLE
mock接口-返回参数模板中设置的默认值不生效

### ISSUE THREAD

**Issue by dpshen** [YMFE/yapi#538]
## 版本号
~  1.3.22

## 什么问题
~返回参数模板中设置的默认值不生效

## 如何复现此问题
~ 接口编辑-模板-设置 默认值
请求mock接口

## 什么浏览器
~ chrome

## 什么系统（Linux, Windows, macOS）
服务器linux，mac使用

**Comment by gaoxiaomumu** [comment]
默认值只起展示作用，想要固定值可以写枚举
