### ISSUE TITLE
接口path中有"!"会出现错误

### ISSUE THREAD

**Issue by Strongerss** [YMFE/yapi#539]
## 版本号
 1.3.17

## 什么问题
接口路径中写/interface!test1.do会出现下面的错误
![image](https://user-images.githubusercontent.com/24241769/45196561-836fa680-b28f-11e8-94ee-e68982ba6c30.png)
## 如何复现此问题
在配置接口名称得时候包含“!”就会出现这个问题，如输入/interface!test1.do

## 什么浏览器
所有

## 什么系统（Linux, Windows, macOS）
所有

**Comment by gaoxiaomumu** [comment]
升级版本吧
