### ISSUE TITLE
[BUG]用户管理里面没办法编辑用户的用户名和email项

### ISSUE THREAD

**Issue by branchzero** [YMFE/yapi#54]
遇到问题的版本: 1.2.6

管理员账号登录后进入用户管理
点开一个用户之后
用户名和email旁边有一个修改，点击修改后出input框，但是里面的内容不能改（怀疑相关事件被拦截了，现在暂时只能手工f12到input value处改完值再点提交...）

**Comment by suxiaoxin** [comment]
感谢反馈

**Comment by suxiaoxin** [comment]
已经修复，下个版本更新
