### ISSUE TITLE
运行无法保存参数和无法取默认值

### ISSUE THREAD

**Issue by gxing19** [YMFE/yapi#540]
## 版本号
1.3.22

## 什么问题
1. 请求参数是 from-data 类型，运行时，无法读取默认值；
2. 请求参数是 json 字符串(application/json)， 在运行的 body 写入了json字符串参数：{"loginName":"user1","password": 123456} ，第一执行发送正常成功，但切换页面或标签后，参数的值没有保存，变成了好像是随机数{"loginName": "ullamco aute aliquip culpa","password": -91277442.81087206}。如果把运行保存到测试集，值有保存。

如果JSON解析不好处理的话，建议把运行改成测试集中对应的接口

## 如何复现此问题
必须

## 什么浏览器
Chrome 

## 什么系统（Linux, Windows, macOS）
Windows

**Comment by gaoxiaomumu** [comment]
运行的时候本来就不会有值，query和form里面的示例都不会有，是空的，要用户自己填写

如果用户运行后发现没有问题可以将数据保存到测试用例里面保存

我们这里的逻辑是这样子的
