### ISSUE TITLE
swagger接口数据量大时，无法导入，报错network error

### ISSUE THREAD

**Issue by czy779509408** [YMFE/yapi#543]
## 版本号
~ 2.0

## 什么问题
~

## 如何复现此问题
~ 从这个swagger地址导入http://api-qa3.yonghuivip.com/api/v2/api-docs

## 什么浏览器
~ Chrome

## 什么系统（Linux, Windows, macOS）
macOS

**Comment by gaoxiaomumu** [comment]
这个不是接口大量的原因，这个是接口不允许跨域的原因
![image](https://user-images.githubusercontent.com/21135585/45489521-06fd2c00-b797-11e8-82af-a2057583adc9.png)

**Comment by cnlzxin** [comment]
@czy779509408 这是你们公司的接口? 暴露出来不合适吧

**Comment by zxdmrg** [comment]
大概几百条后就会报错
POST http://****:3000/api/interface/save net::ERR_MANDATORY_PROXY_CONFIGURATION_FAILED

**Comment by zxdmrg** [comment]
@gaoxiaomumu

**Comment by zxdmrg** [comment]
只要有一条数据报错了,可能是当时网络问题,就不会继续往下执行了.可以考虑catch错误.不然对数据量大的要重复导入很多次
`lib2@b41e63d….js:15 Uncaught (in promise) Error: Network Error
    at e.exports (lib2@b41e63d….js:15)
    at XMLHttpRequest.m.onerror (lib2@b41e63d….js:15)`

**Comment by zxdmrg** [comment]
通过命令行导入接口数据 解决了这个问题
https://yapi.ymfe.org/documents/data.html#通过命令行导入接口数据
