### ISSUE TITLE
 请求参数中的mock如何设置

### ISSUE THREAD

**Issue by geeyu** [YMFE/yapi#544]
## 版本号
~ 1.3.22

## 什么问题
~ 请求参数中的mock如何设置

## 如何复现此问题
~ 
![image](https://user-images.githubusercontent.com/20036057/45477401-1ae36680-b774-11e8-9120-85bf260ac3f2.png)

## 什么浏览器
~ chrome

## 什么系统（Linux, Windows, macOS）
macOS

谢谢

**Comment by gaoxiaomumu** [comment]
https://yapi.ymfe.org/documents/case.html#%E7%AC%AC%E4%BA%8C%E6%AD%A5%EF%BC%8C%E7%BC%96%E8%BE%91%E6%B5%8B%E8%AF%95%E7%94%A8%E4%BE%8B
