### ISSUE TITLE
能否支持选择导入其他接口中的部分参数和返回值

### ISSUE THREAD

**Issue by eden214** [YMFE/yapi#545]
有些时候一个功能模块的很多接口需要的参数都是相似的，返回值也有固定的格式，这样需要重复输入很多次

**Comment by gaoxiaomumu** [comment]
目前只能重复输入，建议和swagger  配合使用

**Comment by FalconIA** [comment]
是否考虑能够支持导入导出RAML

**Comment by gaoxiaomumu** [comment]
可以自己写 导入插件 ，参考swagger 导入
