### ISSUE TITLE
最新版的chrome停用了未在chrome商店上架的插件，是否考虑提供商店版的cross-request?

### ISSUE THREAD

**Issue by DoubleRayWang** [YMFE/yapi#546]
## 版本号
~ 1.3.22及其他

## 什么问题
~ 插件被停用

## 如何复现此问题
~ 升级最新版的chrome

## 什么浏览器
~ chrome

## 什么系统（Linux, Windows, macOS）
**

**Comment by DoubleRayWang** [comment]
https://support.google.com/chrome_webstore/answer/2811969?visit_id=636727434294894780-3569819127&p=ui_remove_non_cws_extensions&hl=zh-Hans&rd=2

**Comment by hellosean1025** [comment]
https://chrome.google.com/webstore/detail/cmnlfmgbjmaciiopcgodlhpiklaghbok
有啊
