### ISSUE TITLE
YAPI是否可以解析接口返回值是html/xml的数据？

### ISSUE THREAD

**Issue by 512433465** [YMFE/yapi#547]
## 版本号
1.3.16

## 什么问题
接口返回值是Html或者Xml时，可否解析其中参数来做断言？
例如，判断 返回的html包含某个值。
PostMan有这个功能，不知道我们的Yapi是否支持。

PostMan添加断言，检查点介绍：https://jingyan.baidu.com/article/3065b3b6b8d28abecff8a421.html
执行效果如下：
![image](https://user-images.githubusercontent.com/19570115/45609733-be41bd80-ba8b-11e8-9fe8-5d45606095d7.png)

尝试用YAPI的mock做同样事情发现，YAPI无法获得返回的HTML，不知道是我姿势不对，还是YAPI尚未支持。
麻烦大师指点一二，多谢！

## 如何复现此问题
获得接口返回的html或者xml，判断内容包含某个字符串。

## 什么浏览器
火狐，谷歌

## 什么系统（Linux, Windows, macOS）
Linux服务

**Comment by gaoxiaomumu** [comment]
yapi 目前不支持对 xml和 html的断言解析

**Comment by 512433465** [comment]
@gaoxiaomumu 后续有支持计划么？

**Comment by gaoxiaomumu** [comment]
应该还没有考虑支持

**Comment by gxnualbert** [comment]
> 应该还没有考虑支持

针对不支持吗？我们这边有些响应的返回值是xml的格式的

**Comment by 512433465** [comment]
期待能支持

**Comment by mbsunflower** [comment]
期待支持，我们的返回有html格式的
