### ISSUE TITLE
命令行导入数据异常 unexpected token

### ISSUE THREAD

**Issue by czy779509408** [YMFE/yapi#549]
## 版本号
~ yapi-cli 1.2.8

## 什么问题
~ 在非服务器电脑上执行命令行导入，提示异常： unexpected token

## 如何复现此问题
~ 

## 什么浏览器
~ 

## 什么系统（Linux, Windows, macOS）
macOS

**Comment by gaoxiaomumu** [comment]
可能是你的导入字段写的 json 有问题
