### ISSUE TITLE
未登录状态下,没有找回密码或修改密码的操作.

### ISSUE THREAD

**Issue by huachaoliu** [YMFE/yapi#550]
## 版本号
~ 

## 什么问题
~

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by gaoxiaomumu** [comment]
如果用户忘记密码，可以请管理员修改密码，如果管理员忘记密码只能去数据库修改

**Comment by ansonhorse** [comment]
@gaoxiaomumu 怎么修改？方便把加密算法说一下么？

**Comment by jasonjoo2010** [comment]
sha1(password + sha1(passsalt))


其中，passsalt是注册该用户时随机生成的一个随机串

**Comment by ansonhorse** [comment]
@jasonjoo2010 谢谢！已修改成功
