### ISSUE TITLE
高级Mock，对期望去重判断有问题

### ISSUE THREAD

**Issue by czonechan** [YMFE/yapi#551]
## 版本号
1.3.22

## 什么问题
高级Mock中，对期望去重的判断有问题。
查了下代码，是因为新建用的时候save，更新用的是update
当params没有填时，默认写入的是{}，但save 和 update 对于 空对象的处理不一致，save会直接过滤掉这字段，update会原样写入。
导致在判断期望是否重复时，根据params = null的条件，没有办法覆盖到 params = {}的期望
```javascript
  let findRepeat, findRepeatParams;
    findRepeatParams = {
      project_id: data.project_id,
      interface_id: data.interface_id,
      ip_enable: data.ip_enable
    };

    if (data.params && typeof data.params === 'object' && Object.keys(data.params).length > 0) {
      for (let i in data.params) {
        findRepeatParams['params.' + i] = data.params[i];
      }
    } else {
      findRepeatParams.params = null;
    }
````
~

## 如何复现此问题
新建一个期望，设置params a = 1
编辑这个期望，删除 params
再新建一个期望，不设置params，可以创建成功，实际上不应该创建成功，因为他们的条件都是一样的

## 什么浏览器
任何浏览器都会

## 什么系统（Linux, Windows, macOS）
任何操作系统都会

**Comment by gaoxiaomumu** [comment]
感谢提问，会解决的
