### ISSUE TITLE
什么时候能支持postman的v2版本的collection？

### ISSUE THREAD

**Issue by Wlmtest** [YMFE/yapi#552]
如题，postman对同一个测试项目里面做了文件分级管理，这个功能挺实用的，对于一个项目是模块化的划分，希望Yapi也能支持类似功能

**Comment by gaoxiaomumu** [comment]
可以自己写postman v2导入插件，仿照postman数据导入机制就可以了

**Comment by ruanjiayou** [comment]
一楼是意思是,对多级文件夹的支持.比如有admin/user/public三个角色,搞三个文件夹,然后admin里有子文件夹,分别对应模块

**Comment by Wlmtest** [comment]
> 可以自己写postman v2导入插件，仿照postman数据导入机制就可以了

我比较常用postman，现在postman的collection已经到2.1了，1和2有很多地方不兼容，如果觉得postman还是比较常用的话，希望Yapi团队可以看看
