### ISSUE TITLE
部署报错

### ISSUE THREAD

**Issue by wjw8860** [YMFE/yapi#553]
## 版本号
当前安装版本： v1.3.22
## 什么问题
/usr/lib/node_modules/yapi-cli/node_modules/mongodb-core/lib/connection/commands.js:446 this.documents = new Array(this.numberReturned); ^ RangeError: Invalid array length at new Response (/usr/lib/node_modules/yapi-cli/node_modules/mongodb-core/lib/connection/commands.js:446:20) at Socket.<anonymous> (/usr/lib/node_modules/yapi-cli/node_modules/mongodb-core/lib/connection/connection.js:363:35) at emitOne (events.js:116:13) at Socket.emit (events.js:211:7) at addChunk (_stream_readable.js:263:12) at readableAddChunk (_stream_readable.js:250:11) at Socket.Readable.push (_stream_readable.js:208:10) at TCP.onread (net.js:597:20)
## 如何复现此问题
~ 

## 什么浏览器
~ chorme

## 什么系统（Linux, Windows, macOS）
Windows

**Comment by gaoxiaomumu** [comment]
https://github.com/YMFE/yapi/issues/16   看一下这里，是否能帮你解决问题

**Comment by ppanphper** [comment]
同样的错误，装不上
