### ISSUE TITLE
编辑接口动态参数时的一个小bug

### ISSUE THREAD

**Issue by lzxin1** [YMFE/yapi#56]
<img width="765" alt="2017-11-22 1 47 11" src="https://user-images.githubusercontent.com/18070909/33112281-612ab064-cf8d-11e7-876a-54a0d40ece3b.png">

保存后显示正常:
<img width="893" alt="2017-11-22 1 48 01" src="https://user-images.githubusercontent.com/18070909/33112304-7ecb3d00-cf8d-11e7-9036-d09c35610eb8.png">

但是再次编辑时会出现一个小bug:
<img width="748" alt="2017-11-22 1 48 19" src="https://user-images.githubusercontent.com/18070909/33112325-a392c20c-cf8d-11e7-8738-89b98d0ae877.png">

**Comment by suxiaoxin** [comment]
这个问题已经修复，下个版本更新
