### ISSUE TITLE
同样的接口，同样的参数，在postman中返回的值正确，但是在YAPI的测试中返回的不对

### ISSUE THREAD

**Issue by dyc87112** [YMFE/yapi#560]
## 版本号

1.3.22

## 什么问题

同样的接口，同样的参数，在postman中返回的值正确，但是在YAPI的测试中返回的不对

![image](https://user-images.githubusercontent.com/3391170/46188780-c74d4d00-c31d-11e8-82fc-376dde12d236.png)

同时在body中维护这个数据，保存后也会变为：1040895753266175100

![image](https://user-images.githubusercontent.com/3391170/46188793-d9c78680-c31d-11e8-8299-28704c702625.png)

## 什么系统（Linux, Windows, macOS）

macOS

**Comment by gaoxiaomumu** [comment]
这个应该是数据太大的问题， 建议写成字符串
