### ISSUE TITLE
接口列表分类能否做成多级嵌套

### ISSUE THREAD

**Issue by csyangwen** [YMFE/yapi#563]
接口列表分类能否做成多级嵌套，这样接口分类能够更加清晰，谢谢。

**Comment by gaoxiaomumu** [comment]
这个yapi 不支持，yapi 只支持一级分类

**Comment by fyzwjd** [comment]
> 这个yapi 不支持，yapi 只支持一级分类

请问后期规划有没有考虑支持呢，分类多级嵌套功能确实挺有必要的

**Comment by zhangpeng-cn** [comment]
多级分类很有必要，建议考虑扩展，谢谢。

**Comment by turnerguo** [comment]
@gaoxiaomumu 请问是出于什么原因yapi不支持多级分类？大型复杂项目接口繁多如何管理？有什么好的经验share一下吗？

**Comment by CooperFu** [comment]
同遇到这个问题, 有想法升级嘛 或者有人已经实现了嘛 求fork
