### ISSUE TITLE
在高级mock里使用Random.pick，报栈溢出

### ISSUE THREAD

**Issue by mushan0x0** [YMFE/yapi#565]
## 版本号
1.3.21

## 什么问题
在高级mock里使用Random.pick，报栈溢出

## 如何复现此问题
在高级mock里只要调用Random.pick()，就会报错：解析出错，请检查。Error: Maximum call stack size exceeded

## 什么浏览器
chrome

## 什么系统（Linux, Windows, macOS）
macOS

**Comment by gaoxiaomumu** [comment]
你应该是用错了吧

![image](https://user-images.githubusercontent.com/21135585/46602186-08b1d980-cb22-11e8-9cac-d7e35f3867df.png)
￼￼￼
![image](https://user-images.githubusercontent.com/21135585/46602321-66462600-cb22-11e8-8eda-00d9640614da.png)

**Comment by mushan0x0** [comment]
@gaoxiaomumu 我是这样用的
![image](https://user-images.githubusercontent.com/29084441/46603233-16b52980-cb25-11e8-8410-754dbc6cf726.png)

**Comment by mushan0x0** [comment]
脚本里面

**Comment by gaoxiaomumu** [comment]
![image](https://user-images.githubusercontent.com/21135585/46606052-1c633d00-cb2e-11e8-9bf6-123fde2989a8.png)
![image](https://user-images.githubusercontent.com/21135585/46606062-2be28600-cb2e-11e8-8b0d-d1322047f7a5.png)

**Comment by mushan0x0** [comment]
@gaoxiaomumu 我不行，你是什么版本，是后面更新修复了吗
![image](https://user-images.githubusercontent.com/29084441/46642030-78b67300-cba7-11e8-9a19-c26ef6fedcac.png)

**Comment by gaoxiaomumu** [comment]
最新版本，这里并没有什么改动，你发给我的这个高级mock 脚本，这里需要开启，否则没有用的

![image](https://user-images.githubusercontent.com/21135585/46643332-33e20a80-cbae-11e8-89f5-7eec019c18e3.png)

**Comment by mushan0x0** [comment]
@gaoxiaomumu 开了的，只是开启报错，所以我关了

**Comment by mushan0x0** [comment]
为什么关了。。。
