### ISSUE TITLE
数据导入中对于 Postman 导出版本 v2.1 不兼容

### ISSUE THREAD

**Issue by hugoxia** [YMFE/yapi#568]
## 版本号
~ 所有版本

## 什么问题
~ 数据导入中对于 Postman 导出版本 v2.1 不兼容，支持 Postman 导出的v1

## 如何复现此问题
~ 导入v2.1版本的Postman

## 什么浏览器
~ Chrome

## 什么系统（Linux, Windows, macOS）
Windows

![image](https://user-images.githubusercontent.com/11880181/46723975-a553b300-ccab-11e8-8863-7613e9685132.png)

**Comment by mijiawei** [comment]
之前问过，说只支持v1
