### ISSUE TITLE
导入swagger接口数据无法实现智能合并

### ISSUE THREAD

**Issue by haohaoxiansen** [YMFE/yapi#571]
## 版本号
~ 
1.3.23
## 什么问题
~
导入swagger接口数据后进行修改，由于后端更新接口，我重新导入数据，选择导入的规则也是智能合并，导致我之前修改的接口都被覆盖了，相当于所有的接口我都要重新写。没起到智能合并的效果
## 如何复现此问题
~ 
先导入swagger接口数据，然后修改某一个接口的code 的值为 200，然后再导入swagger数据，发现之前修改的code值已经没了
## 什么浏览器
~ 
谷歌浏览器
## 什么系统（Linux, Windows, macOS）
window7 我把yapi部署在linux系统上面

**Comment by gaoxiaomumu** [comment]
你可能没有明白智能合并的意思  ， z智能合并是对同一个字段的不同的配置信息进行合并的过程
![image](https://user-images.githubusercontent.com/21135585/46927637-ff1bfa80-d068-11e8-99f7-5d0ffa4ea0d1.png)

**Comment by gaoxiaomumu** [comment]
1.3.23 智能合并并不会冲掉 mock 字段里面的设置

**Comment by haohaoxiansen** [comment]
反正我的swagger文件是会这样，难道swagger文件问题？但是swagger文件那么大，完全找不到哪里有问题，哎
