### ISSUE TITLE
1.3.23版本下的搜索有问题

### ISSUE THREAD

**Issue by h-senan** [YMFE/yapi#573]
## 版本号
1.3.23

## 什么问题
部分项目页面内的左侧搜索栏搜索接口的时候，没反应。
这些项目一般都有好多接口。
1.3.22版本没有这个问题
查看console.log里面没有报错信息。

## 什么浏览器
chrome

## 什么系统（Linux, Windows, macOS）
mac，windows

**Comment by gaoxiaomumu** [comment]
![image](https://user-images.githubusercontent.com/21135585/46927482-36d67280-d068-11e8-83e6-89f2a17e7f40.png)
是这个样子吗？ 点击左侧的三角型按钮就可以了

**Comment by gaoxiaomumu** [comment]
是这个样子吗？ 点击左侧的三角型按钮就可以了

￼
![image](https://user-images.githubusercontent.com/21135585/46927548-8ae15700-d068-11e8-8abb-f3fb502d81f3.png)

**Comment by FurionCS** [comment]
建议官方修改搜索结果方式，至少把结果排前面

**Comment by gaoxiaomumu** [comment]
这里是因为修改一个搜索bug造成的，考虑下版本修改一下
