### ISSUE TITLE
【功能建议】接口响应数据支持导入预置json schema

### ISSUE THREAD

**Issue by felbry** [YMFE/yapi#575]
比如说 我这个项目返回格式是统一的：
```json
{
  "code": 0,
  "msg": "ffff",
  "data": {}
}
```
那是不是意味着每次创建一个接口我都要重新输入这样的结构以及写入描述信息及其他。
目前采取的方式将一段json schema保存在另一处地方，每创建一个接口就复制进来一次，再做修改。

想法：一个项目应该提供创建预置json schema的地方，在导入的时候直接可以选中导入

**Comment by gaoxiaomumu** [comment]
可以去全局mock功能那里看看是否满足你的需求

**Comment by felbry** [comment]
> 可以去全局mock功能那里看看是否满足你的需求

既然是全局mock，自然是基于mock了。
我描述的场景是在一开始写文档的时候。我没有去读教程，不知道全局mock是否能直接生成文档。
也可能我这个想法本身就是伪需求吧哈哈。
感谢回复
