### ISSUE TITLE
接口列表按tag筛选后分页没有更新

### ISSUE THREAD

**Issue by xlybaba** [YMFE/yapi#577]
## 版本号
~ 1.3.23

## 什么问题
~如果有多页接口时，按tag筛选后，分页还是按没有筛选前分的页，导致看接口不方便

**Comment by gaoxiaomumu** [comment]
因为分页是后台实现的，而tag筛选是前端过滤，所以这里只能按照分页一页一页的查看

**Comment by xlybaba** [comment]
感觉这样处理体验不好，标签功能很实用的，也会经常用到。 个人建议能改为通过后台筛选更好。

**Comment by xlybaba** [comment]
> 因为分页是后台实现的，而tag筛选是前端过滤，所以这里只能按照分页一页一页的查看

感觉这样处理体验不好，标签功能很实用的，也会经常用到。 个人建议能改为通过后台筛选更好。
