### ISSUE TITLE
单入口的接口？

### ISSUE THREAD

**Issue by kwens** [YMFE/yapi#578]
## 什么问题
~ 单入口的接口不能支持吗？有一些业务情况只有单个接口入口，然后用参数code区分不同业务的。

**Comment by hellosean1025** [comment]
目前支持使用 query 参数区分，比如接口路径可以写成 /api/xx?module=a

**Comment by naifen00** [comment]
> 目前支持使用 query 参数区分，比如接口路径可以写成 /api/xx?module=a

@hellosean1025 1.3.23版本开始，会提示错误 “已存在的接口...”

**Comment by hellosean1025** [comment]
@naifen00 @kwens 
已确认是修复bug导致的，下个版本修复，你们可以先回滚之前版本先用着。。。
