### ISSUE TITLE
搜索功能

### ISSUE THREAD

**Issue by zlab** [YMFE/yapi#58]
右上角的搜索现在只能搜分组和项目，应该改为搜索接口吧，项目和分组点几下就找到了，打字更麻烦

## 关注功能
项目就那么多，关不关注没什么用啊，接口更需要关注，收藏

**Comment by suxiaoxin** [comment]
在我们公司，yapi 已经管理在几百个项目了
接口搜索可以进入到项目里面，进行搜索
