### ISSUE TITLE
用了很久了，今天打开接口页面显示空白，所有项目都是，控制台有报错

### ISSUE THREAD

**Issue by inewlife** [YMFE/yapi#581]
## 版本号
~ 
1.3.17
## 什么问题
~
![image](https://user-images.githubusercontent.com/13137254/47126539-ac864c80-d2bb-11e8-9f42-4e9d030204f7.png)
## 如何复现此问题
~ 
![image](https://user-images.githubusercontent.com/13137254/47126539-ac864c80-d2bb-11e8-9f42-4e9d030204f7.png)

## 什么浏览器
~ 
Chrome
## 什么系统（Linux, Windows, macOS）
Windows

**Comment by hellosean1025** [comment]
尝试升级版本
