### ISSUE TITLE
url参数默认值

### ISSUE THREAD

**Issue by cx00000** [YMFE/yapi#582]
## 版本号
~ 
1.3.123
## 什么问题
~
生成的swagger json文件有默认值，使用运行操作的时候参数为空
## 如何复现此问题
~ 

## 什么浏览器
~ 

## 什么系统（Linux, Windows, macOS）
Windows

**Comment by gaoxiaomumu** [comment]
运行操作的参数需要自己填写， 如果运行测试成功可以将接口保存到测试用例里面

**Comment by keniushadu** [comment]
默认值插件,可以看看 https://github.com/keniushadu/yapi-plugins
