### ISSUE TITLE
接口编辑那边好像有个bug。

### ISSUE THREAD

**Issue by wengpengfeijava** [YMFE/yapi#59]
接口路径为restfull 风格的时候，下面的示例文本无法修改，（修改成功后下次进来还是原来的样子）
![image](https://user-images.githubusercontent.com/5634425/33119395-d4ac512a-cfa9-11e7-8a6e-be17b724c46c.png)

**Comment by suxiaoxin** [comment]
这个 bug 在下次更新的 1.2.7版本修复了
