### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by rocky9988** [YMFE/yapi#6]
Error: Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.

mongo 是2.6.9的版本
系统环境centos 6

**Comment by suxiaoxin** [comment]
这只是警告信息吧，系统启动正常吗？

**Comment by suxiaoxin** [comment]
刚查了下，这是因为 package.json 依赖的 mongoose 版本过高导致的，感谢反馈
