### ISSUE TITLE
接口状态改成完成后, 可以指定数据来源吗

### ISSUE THREAD

**Issue by lzxin1** [YMFE/yapi#60]
如果接口已经完成, mock的数据就不是很需要了

**Comment by lzxin1** [comment]
这样的话前端就可以不用切换, 直接调用实际数据

**Comment by eidonjoe** [comment]
觉得理论上这样不是很合理, mock平台本来是做mock数据用, 并不是来做请求转发.将mock平台作为中间层的话也不方便问题排查.
