### ISSUE TITLE
[建议]希望提供手选覆盖接口和新增接口的方式

### ISSUE THREAD

**Issue by kyan54** [YMFE/yapi#607]
目前有一部分接口都是手工调整的模式。我们通过swagger导入的时候回覆盖手工调整的接口。这样覆盖后，又要重新调整。。好麻烦。。
能否提供手选导入哪些接口，自动更新或新增手选的接口呢？

**Comment by gaoxiaomumu** [comment]
智能合并， 目前没有可以控制导入接口的方法，可以在swagger导入那里进行控制
![image](https://user-images.githubusercontent.com/21135585/47700225-afd0ef00-dc50-11e8-8767-679684872dfd.png)
