### ISSUE TITLE
自动化测试支持form表单文件上传吗?我的自动化测试显示没有文件

### ISSUE THREAD

**Issue by 1033673266** [YMFE/yapi#612]
## 版本号
~ 版本: 1.3.21

## 什么问题
~
 自动化测试文件上传功能, 不能上传文件

**选择domain 测试时候**
过程会卡住:
![image](https://user-images.githubusercontent.com/18611222/47709621-9db07a00-dc6b-11e8-8fc2-e71b0fb4aad7.png)

浏览器报错:
![image](https://user-images.githubusercontent.com/18611222/47709567-7c4f8e00-dc6b-11e8-9ab1-8ce835a7a2c8.png)

**选择localhost 测试时候**
后端会收不到文件

## 如何复现此问题
~ 

## 什么浏览器
~ chrome

## 什么系统（Linux, Windows, macOS）
Ubantu

**Comment by aurthurxlc** [comment]
我也遇到同样的问题，后端接收报错：
 ```bash
no multipart boundary param in Content-Type
```
看起来是 yapi 未发送文件内容，同环境 Postman 可以发送成功

**Comment by jasonjoo2010** [comment]
得加header

Content-type: multipart/form-data

**Comment by 1033673266** [comment]
测试单个接口的时候, 用localhost 是不行的, 后端会收不到文件, 用domain是没有问题的, 那我就用domain好了,
但是测试集合是跑不起来, 到那一个上传文件的接口就会卡住报错,  我看编辑测试接口, 我选择了文件, 点击更新
![image](https://user-images.githubusercontent.com/18611222/47760440-39cf9500-dcef-11e8-80b8-6bc7ca333f40.png)
然后刷新页面是不显示之前保存的图片的, 测试集合跑起来的时候是没有地方让你选文件, 所以文件上传跑自动化测试会失败, 
显示这样
![image](https://user-images.githubusercontent.com/18611222/47760494-7f8c5d80-dcef-11e8-83a6-e64301af0c3f.png)
不知道有没有什么办法解决

**Comment by aurthurxlc** [comment]
@jasonjoo2010 header 我加了，但是我不是这个引起的错误，错误原因如下
yapi 发送文件请求用 localhost 和 127.0.0.1 都不行，设置一个本地的 hosts 就可以了

@1033673266 自动化测试时，yapi 最好能把选定的测试文件保存在服务器端，这样就算在服务器端跑测试也是可以运行的

**Comment by 1033673266** [comment]
@aurthurxlc  这个改怎么操作, 因为我在本地是选择文件的,
![image](https://user-images.githubusercontent.com/18611222/47767572-377d3300-dd0f-11e8-937c-07f80cf4409e.png)
是说我这边选着了文件, 然后在把这个文件保存在服务起端某个文件夹下吗,  这样我更新能生效吗

**Comment by 1033673266** [comment]
@aurthurxlc 了解了, 需要待开发,

**Comment by 1033673266** [comment]
> > @jasonjoo2010 header 我加了，但是我不是这个引起的错误，错误原因如下
> > yapi 发送文件请求用 localhost 和 127.0.0.1 都不行，设置一个本地的 hosts 就可以了
> > @1033673266 自动化测试时，yapi 最好能把选定的测试文件保存在服务器端，这样就算在服务器端跑测试也是可以运行的
> 
> 应该是有别的问题吧？
> 
> <img alt="screen shot 2018-10-31 at 14 23 43" width="662" src="https://user-images.githubusercontent.com/17573073/47769932-87142c80-dd18-11e8-9cf0-8627a21db195.png">
> 
> <img alt="screen shot 2018-10-31 at 14 24 59" width="433" src="https://user-images.githubusercontent.com/17573073/47769969-95fadf00-dd18-11e8-8b61-fa40e1d78067.png">

我把改成localhost  请求时候, 在chrome network 是看不到网络请求的, 改成domain 方式请求才看到有网络请求, 不是道它的localhost 请求方式是什么样的, 应该没有chrome 网络请求

**Comment by jasonjoo2010** [comment]
> > > @jasonjoo2010 header 我加了，但是我不是这个引起的错误，错误原因如下
> > > yapi 发送文件请求用 localhost 和 127.0.0.1 都不行，设置一个本地的 hosts 就可以了
> > > @1033673266 自动化测试时，yapi 最好能把选定的测试文件保存在服务器端，这样就算在服务器端跑测试也是可以运行的
> > 
> > 
> > 应该是有别的问题吧？
> > <img alt="screen shot 2018-10-31 at 14 23 43" width="662" src="https://user-images.githubusercontent.com/17573073/47769932-87142c80-dd18-11e8-9cf0-8627a21db195.png">
> > <img alt="screen shot 2018-10-31 at 14 24 59" width="433" src="https://user-images.githubusercontent.com/17573073/47769969-95fadf00-dd18-11e8-8b61-fa40e1d78067.png">
> 
> 我把改成localhost 请求时候, 在chrome network 是看不到网络请求的, 改成domain 方式请求才看到有网络请求, 不是道它的localhost 请求方式是什么样的, 应该没有chrome 网络请求

我这用localhost也是一样

不然你先ping一下看看localhost是否有绑吧，避免低级错误

<img width="257" alt="screen shot 2018-10-31 at 14 52 05" src="https://user-images.githubusercontent.com/17573073/47770978-749bf200-dd1c-11e8-8045-156fd39b2ba0.png">
<img width="385" alt="screen shot 2018-10-31 at 14 52 15" src="https://user-images.githubusercontent.com/17573073/47770979-749bf200-dd1c-11e8-8d6f-2cdbf5fb4bbf.png">
<img width="571" alt="screen shot 2018-10-31 at 14 52 24" src="https://user-images.githubusercontent.com/17573073/47770980-749bf200-dd1c-11e8-96bc-89008a34b5f6.png">

**Comment by gaoxiaomumu** [comment]
自动化测试不支持文件上传

**Comment by 1033673266** [comment]
> 自动化测试不支持文件上传

我看YAPI 挺好用的,文档自动化测试一体, 希望开发团队以后可以加上这个功能, 让它功能更加强大

**Comment by caiboking** [comment]
挖坟，复议，很需要这个功能。最好是有个全局资源文件管理，通过URL来引用文件资源，然后再通过浏览器上传。

**Comment by luman2013** [comment]
自动化测试不支持文件上传啊，啥时候能改改呢，着急用

**Comment by rujinshi** [comment]
希望增加文件上传。

**Comment by rhett030** [comment]
请问什么时候才能支持文件上传？这个功能很重要，缺少了这个功能我们的业务在整个自动化测试过程无法串联起来

**Comment by Tibalt** [comment]
2022年了，这个功能怎么样了？
