### ISSUE TITLE
忘记密码

### ISSUE THREAD

**Issue by lightClouds917** [YMFE/yapi#615]
## 版本号
1.3.1

## 什么问题
忘记密码如何处理

## 如何复现此问题
忘记密码后无法处理，没有修改密码功能按钮

## 什么浏览器
谷歌

## 什么系统（Linux, Windows, macOS）
Windows

**Comment by gaoxiaomumu** [comment]
如果是管理员忘记密码，需要去数据库修改， 可以先注册一个普通用户再去数据库将该用户的权限修改成管理员，

如果是普通用户，可以通知管理员修改自己的密码

**Comment by lightClouds917** [comment]
好的，谢谢
