### ISSUE TITLE
服务启动后自己会挂掉，没有有效日志输出，问题原因不明

### ISSUE THREAD

**Issue by Pastel001** [YMFE/yapi#62]
问题：启动服务后，过一段时间网站就无法访问了，查看进程已经没有了，查看nohup.out文件没有有效输出，不知道是什么原因，能帮忙确定下原因，然后帮忙解决吗？谢谢
版本号V1.2.5
安装方式：方式二. 命令行部署
启动方式：nohup node app.js &
nohup日志：
root@iZ2zebfrq7qd5faagqmmktZ:/opt/yapi/vendors/server# cat nohup.out 
load websocket...
log: the server is start at port 3000
log: mongodb load success...
log: MockServer Running...
log: MockServer Running...
log: MockServer Running...
log: MockServer Running...
log: MockServer Running...
log: MockServer Running...
log: MockServer Running...
log: MockServer Running...
log: MockServer Running...
root@iZ2zebfrq7qd5faagqmmktZ:/opt/yapi/vendors/server#

**Comment by suxiaoxin** [comment]
试试用 pm2 管理

**Comment by lzxin1** [comment]
我用的是`forever`:
```
npm install -g forever --registry https://registry.npm.taobao.org
```

以服务的形式启动:
```
forever strat {path}/vendors/server/app.js
```

列表:
```
forever list
````

停止:
```
forever stopall
```

**Comment by suxiaoxin** [comment]
可以尝试下老版本

**Comment by Pastel001** [comment]
好的，我试试pm2和forever，不会nodejs，之前都没用过
谢谢大家

**Comment by Pastel001** [comment]
使用forever半天，没有挂掉
