### ISSUE TITLE
服务器迁移问题

### ISSUE THREAD

**Issue by pawnisfather** [YMFE/yapi#626]
## 版本号
~ 
1.3.23
## 什么问题
~
想请教一下服务器迁移了yapi怎么跟着迁移过去，是直接拷贝数据库就可以了吗？
## 如何复现此问题
~ 
暂无
## 什么浏览器
~ 
谷歌浏览器
## 什么系统（Linux, Windows, macOS）
linux

**Comment by gaoxiaomumu** [comment]
建议看一下 mongodb  数据库迁移
