### ISSUE TITLE
功能建议：建议对输出结果,能增加json格式化功能

### ISSUE THREAD

**Issue by keepnode** [YMFE/yapi#63]
由于目前做API这块，输出结果大部分是json格式，建议增加JSON格式化功能，方便查看json字符串

**Comment by suxiaoxin** [comment]
已经做了，检查下返回 header, content type是不是 application/json

**Comment by keepnode** [comment]
我的意思是请求结果，不是请求内容。您看图片
![image](https://user-images.githubusercontent.com/8043218/33198302-3afab95e-d125-11e7-8ab7-b2499156ff4b.png)
我目前需要对输出的结果进行序列化操作。
我希望输出的结果能更友好的排版。
如这种：
![image](https://user-images.githubusercontent.com/8043218/33198335-77edd6ca-d125-11e7-9f5a-48de51b2fb91.png)

**Comment by suxiaoxin** [comment]
根据这个决定
![image](https://user-images.githubusercontent.com/17695103/33198887-535e7c96-d0b3-11e7-89d0-2ae801199f49.png)

**Comment by suxiaoxin** [comment]
下一个版本内容只要是 json 格式，就会被格式化
