### ISSUE TITLE
请求一个接口时间过长时，在7s以上，测试集合执行会显示‘执行异常’

### ISSUE THREAD

**Issue by konamistan** [YMFE/yapi#64]
请求一个接口时间过长时，在7s以上，测试集合执行会显示‘执行异常’。

**Comment by suxiaoxin** [comment]
暂不支持自定义超时时间

**Comment by konamistan** [comment]
主要是我们的产品是跨系统的，接口调用会消耗点时间，7s响应时间是很常见的事情。

**Comment by suxiaoxin** [comment]
@konamistan 已经改成不限时间了，请更新到 v1.2.7
