### ISSUE TITLE
官网教程，权限列表链接失效

### ISSUE THREAD

**Issue by Sealwk** [YMFE/yapi#641]
## 版本号
~ 

## 什么问题
~

## 如何复现此问题
~ 
![wx20181116-152959](https://user-images.githubusercontent.com/24579280/48604463-ec247f00-e9b4-11e8-9369-2d54a82df9d5.png)

![wx20181116-153047](https://user-images.githubusercontent.com/24579280/48604437-d747eb80-e9b4-11e8-81ae-70773cb2c59b.png)

## 什么浏览器
~

**Comment by gaoxiaomumu** [comment]
感谢提问，下次版本会修改的
