### ISSUE TITLE
Content-type配置后不生效，始终是默认的application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by yanlingli3799** [YMFE/yapi#650]
## 版本号
1.4.1

## 什么问题
Content-Type改为application/json保存后不生效，一直是默认值application/x-www-form-urlencoded

## 如何复现此问题
修改Content-Type 为 application/json，保存，到运行页默认的 Content-Type写的是application/x-www-form-urlencoded，再回到编辑页，发现编辑页的 ContentType又变回application/x-www-form-urlencoded了。

## 什么浏览器
Chrome、Safri

## 什么系统（Linux, Windows, macOS）
MacOS

**Comment by gaoxiaomumu** [comment]
![image](https://user-images.githubusercontent.com/21135585/48843305-a4955d00-edd1-11e8-9b03-9c3b33fe47d1.png)

**Comment by yang131323** [comment]
windows也有这种情况
