### ISSUE TITLE
可以添加支持protobuf吗

### ISSUE THREAD

**Issue by lilisheng** [YMFE/yapi#655]
## 版本号
~ 1.4.1

## 什么问题
~ 公司的项目需要几种语言开发，中间的数据交换，如果使用JSON交互会存在数据一致性问题；最后确定使用谷歌的protobuf，当次系统好像不支持，期望后能支持上。贵公司的此系统很好用

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by gaoxiaomumu** [comment]
是的，目前不支持呢

**Comment by GpingFeng** [comment]
请问现在业内有没有其他的实现方案呢？
