### ISSUE TITLE
部署Error:  (node:23035) 

### ISSUE THREAD

**Issue by wufengbin** [YMFE/yapi#668]
版本号
1.4.1
问题
Error:  (node:23035) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
经验证，可以启动服务，建议修改log级别，不要用Error，引发误判。
查了好久说是mongoose一个版本bug，但实际并不影响项目启动
复现此问题
最新版本本地部署即可复现
浏览器
chrome
系统（Linux, Windows, macOS）
windows10

**Comment by youbl** [comment]
https://github.com/YMFE/yapi/issues/658
