### ISSUE TITLE
定义带pah参数的接口报错

### ISSUE THREAD

**Issue by IvanCai** [YMFE/yapi#679]
## 版本号
1.41

## 什么问题
定义带pah参数的接口报错
![yapi-issue](https://user-images.githubusercontent.com/8352980/49206066-d74fde80-f3eb-11e8-8391-c49ff90a53d7.png)

## 什么浏览器
chrome

## 什么系统（Linux, Windows, macOS）
MacOs

**Comment by gaoxiaomumu** [comment]
这种接口定义方式不支持
![image](https://user-images.githubusercontent.com/21135585/49209692-1daa3b00-f3f6-11e8-9b36-86b510ecef18.png)
