### ISSUE TITLE
请求body中子json的"{"被过滤

### ISSUE THREAD

**Issue by brooks2018** [YMFE/yapi#68]
我请求时body为json格式，含子json，如：
{
   "type": "2",
   "hand_cnt": 8,
   "name": "testname",
   "max_player": 3,
   "info": "{\"max_player\":3}"
}
但实际后端收到的请求信息中子json格式被破坏，｛没了，无法decode,收到的结果如下：
｛
hand_cnt:8
info:""max_player":3"
max_player:3
name:"testname"
type:"2"
｝

**Comment by suxiaoxin** [comment]
@brooks2018 已经修复，请重新升级 
yapi update -v v1.2.7
