### ISSUE TITLE
强烈需求：测试case可以复制，测试集合可以一起跑

### ISSUE THREAD

**Issue by caiboking** [YMFE/yapi#686]

**Comment by 1win** [comment]
+10086

**Comment by caiboking** [comment]
这是拉拢QA最后的屏障了，复制功能大大提升效率

**Comment by XuDaojie** [comment]
+10001

**Comment by sephirothgao** [comment]
你们不加我就自己加了

**Comment by huqiliang** [comment]
+10086 应该是支持同一接口可以有多个测试用例,然后可以一起跑

**Comment by caiboking** [comment]
> 你们不加我就自己加了

静静的等待你提交代码

**Comment by caiboking** [comment]
> 你们不加我就自己加了

@sephirothgao 静静的等待提交代码

**Comment by huqiliang** [comment]
@sephirothgao 坐等

**Comment by sephirothgao** [comment]
楼上各位，测试集合一起跑我们在yapi之外，自己搭建平台解决了，测试用例复制这个我们可以再看看。

**Comment by caiboking** [comment]
@sephirothgao 这就没意思了

**Comment by huqiliang** [comment]
我也自己搞定了。。。

**Comment by caiboking** [comment]
搞定了就MR，官方最新版本也支持了。

**Comment by qdpiaoliang** [comment]
@huqiliang 求教，怎么搞定的？

**Comment by qdpiaoliang** [comment]
> 搞定了就MR，官方最新版本也支持了。



> 我也自己搞定了。。。

怎么搞定的？
