### ISSUE TITLE
添加接口的地方无法修改接口方法

### ISSUE THREAD

**Issue by isheng5** [YMFE/yapi#69]
昨天部署的，手动部署方法，版本号1.2.7，下拉的组件报错导致无法选择请求方法。
![rajku 0 ctzb 3160cr 9](https://user-images.githubusercontent.com/16497636/33251057-b588dab0-d36f-11e7-85c3-492b25ed8a81.png)

![znbg 90sr662zfbw d i](https://user-images.githubusercontent.com/16497636/33251092-dcd9aa40-d36f-11e7-98ba-3cf0dce3c1a0.png)

**Comment by suxiaoxin** [comment]
部署 v1.2.5 版本试试

**Comment by isheng5** [comment]
好的 谢谢

**Comment by isheng5** [comment]
找到原因了，是谷歌浏览器的插件tampermonkey包中的一个叫做解除网页限制的插件的干扰造成的，希望以后对其他开发者有用处
