### ISSUE TITLE
API`运行`板块的一些建议

### ISSUE THREAD

**Issue by thREam** [YMFE/yapi#7]
RT

1. 建议支持`必需`参数的赋值检查, 未赋值不能`发送`
2. 建议`非必需`参数未赋值时, 不添加到发送请求时的 URL 里
3. 建议参数支持默认值

感谢贵团队开源这么好的项目

**Comment by suxiaoxin** [comment]
感谢您的反馈，目前加了一个 enable 选项，不过还没有更新到github，本周日会更新，请期待。
![image](https://user-images.githubusercontent.com/17695103/31651511-8ea3a17c-b2e1-11e7-8642-074bd4bb5732.png)
如果是必需填的参数，enable 是置灰并且开启的，非必需参数可以根据实际情况选择。
