### ISSUE TITLE
Request Headers 自动提示

### ISSUE THREAD

**Issue by zlab** [YMFE/yapi#71]
编辑接口页面，输入headers，没有autocomplete自动提示，postman有自动提示，
最好是全局headers，每个接口都一样，可以覆盖全局

![a9123d5b-f763-449b-a69e-e8c31ba4cf90](https://user-images.githubusercontent.com/2288630/33257791-640ff5e2-d392-11e7-91a4-9e7b4967ba63.png)

**Comment by suxiaoxin** [comment]
@zlab 有的，不知道你那边为什么没有
![image](https://user-images.githubusercontent.com/17695103/33259240-e5062eee-d321-11e7-986c-ce177834d21e.png)

**Comment by zlab** [comment]
名称有提示，值没有提示
