### ISSUE TITLE
功能建议：增加导出swagger的yaml的格式的功能

### ISSUE THREAD

**Issue by johnfwtest** [YMFE/yapi#714]
版本号
~

什么问题
希望支持导出swagger的yaml的格式。方便使用Swagger-editor生成代码

_Originally posted by @johnfwtest in https://github.com/YMFE/yapi/issues/674#issuecomment-445617357_

如何复现此问题
~

什么浏览器
~

什么系统（Linux, Windows, macOS）
~

**Comment by lioutall** [comment]
我也希望增加此功能
最好提供导出和http server两种方式, 因为两个功能是开发一致的.
swagger的yaml格式, 这种开发方式会慢慢变得通用起来.

**Comment by lioutall** [comment]
其实不光是yaml, 还有在线的接口, 可以通过http直接获取api的各个参数. 这功能肯定是会被大量应用的.  
当然 swagger json导出已经够我目前使用了.

**Comment by johnfwtest** [comment]
嗯,不太明白，你需要的通过http直接获取api参数的功能是怎样的，但你可以试试，通过导出接口获取全部的接口信息，再进行筛选，变相实现？
如下面的连接可以获取项目id为33187的接口列表的全部信息。
http://yapi.demo.qunar.com/api/plugin/export?type=json&pid=33187&status=all&isWiki=false

**Comment by lioutall** [comment]
我明白了

**Comment by tanlzhi** [comment]
导出swagger json 报错
{
errcode: 502,
errmsg: "下载出错",
data: null
}

**Comment by 0x0bit** [comment]
感觉还是需要支持一下的吧，最起码有个选择项。并不是所有的项目都是 json 格式😂
