### ISSUE TITLE
从swagger导入的接口不能正常测试

### ISSUE THREAD

**Issue by lichao0** [YMFE/yapi#73]
## Version
~ 1.2.7

从swagger导入的接口，不能正常测试：
GET请求提示"请求body json格式有误"
![image](https://user-images.githubusercontent.com/9666904/33367409-73d550ba-d529-11e7-8fe8-5fb8ca62d653.png)

发现调用的server地址为 /api/col/case_list/?col_id= ，而不是所选的Mock地址？

**Comment by suxiaoxin** [comment]
@lichao0 感谢反馈，下个版本修复。如果着急使用测试功能，可以编辑该接口为 post Method，然后在 request->body 选择 form,再修改为 get 请求

**Comment by suxiaoxin** [comment]
@lichao0  升级下 v1.2.8 版本, yapi update -v v1.2.8
