### ISSUE TITLE
Hi，希望加一个功能，能够复制测试集合

### ISSUE THREAD

**Issue by caozihao** [YMFE/yapi#74]
## Version
~ 1.2.8

## What is expected
~加一个功能，能够复制测试集合

## Step to reproduce
~ 
1，如题所示，公司业务需要，是否能加这个功能？
2，另外我问一下，因为业务需要，我想改动一点源码。现在开发和生产的环境下，调用的js都是静态的资源，我问一下在开发模式下，怎么用“client”下的资源，而不是打包后的呢？谢谢！
3，另外现在开发环境下，运行 npm run dev 后会报错，看了下，是文件没有引用对，@dev 没有被解析，您帮忙看一下

## Environment
~

**Comment by caozihao** [comment]
在二次开发中，我运行  `ykit pack -m`   后，报一堆错 
`PS D:\project\YAPI_DEV\vendors> ykit pack -m
[ykit] ykit@2.0.1
[error] multi react redux redux-thunk react-dom redux-promise react-router react-router-dom prop-types axios moment re
act-dnd-html5-backend react-dnd reactabular-table reactabular-dnd table-resolver
Module not found: Error: Can't resolve 'happypack/loader-loader' in 'D:\project\YAPI_DEV\vendors\client'
 @ multi react redux redux-thunk react-dom redux-promise react-router react-router-dom prop-types axios moment react-d
nd-html5-backend react-dnd reactabular-table reactabular-dnd table-resolver

[error] multi ./index.js
Module not found: Error: Can't resolve 'happypack/loader-loader' in 'D:\project\YAPI_DEV\vendors\client'
 @ multi ./index.js

[error] multi react redux redux-thunk react-dom redux-promise react-router react-router-dom prop-types axios moment re
act-dnd-html5-backend react-dnd reactabular-table reactabular-dnd table-resolver
Module not found: Error: Can't resolve 'happypack/loader-loader' in 'D:\project\YAPI_DEV\vendors\client'
 @ multi react redux redux-thunk react-dom redux-promise react-router react-router-dom prop-types axios moment react-d
nd-html5-backend react-dnd reactabular-table reactabular-dnd table-resolver

[error] multi react redux redux-thunk react-dom redux-promise react-router react-router-dom prop-types axios moment re
act-dnd-html5-backend react-dnd reactabular-table reactabular-dnd table-resolver
Module not found: Error: Can't resolve 'happypack/loader-loader' in 'D:\project\YAPI_DEV\vendors\client'
 @ multi react redux redux-thunk react-dom redux-promise react-router react-router-dom prop-types axios moment react-d
nd-html5-backend react-dnd reactabular-table reactabular-dnd table-resolver

[error] multi react redux redux-thunk react-dom redux-promise react-router react-router-dom prop-types axios moment re
act-dnd-html5-backend react-dnd reactabular-table reactabular-dnd table-resolver
Module not found: Error: Can't resolve 'happypack/loader-loader' in 'D:\project\YAPI_DEV\vendors\client'
 @ multi react redux redux-thunk react-dom redux-promise react-router react-router-dom prop-types axios moment react-d
nd-html5-backend react-dnd reactabular-table reactabular-dnd table-resolver

[error] multi react redux redux-thunk react-dom redux-promise react-router react-router-dom prop-types axios moment re
act-dnd-html5-backend react-dnd reactabular-table reactabular-dnd table-resolver
Module not found: Error: Can't resolve 'happypack/loader-loader' in 'D:\project\YAPI_DEV\vendors\client'
 @ multi react redux redux-thunk react-dom redux-promise react-router react-router-dom prop-types axios moment react-d
nd-html5-backend react-dnd reactabular-table reactabular-dnd table-resolver

[error] multi react redux redux-thunk react-dom redux-promise react-router react-router-dom prop-types axios moment re
act-dnd-html5-backend react-dnd reactabular-table reactabular-dnd table-resolver
Module not found: Error: Can't resolve 'happypack/loader-loader' in 'D:\project\YAPI_DEV\vendors\client'
 @ multi react redux redux-thunk react-dom redux-promise react-router react-router-dom prop-types axios moment react-d
nd-html5-backend react-dnd reactabular-table reactabular-dnd table-resolver

[error] multi brace mockjs json5 url
Module not found: Error: Can't resolve 'happypack/loader-loader' in 'D:\project\YAPI_DEV\vendors\client'
 @ multi brace mockjs json5 url

[error] multi react redux redux-thunk react-dom redux-promise react-router react-router-dom prop-types axios moment re
act-dnd-html5-backend react-dnd reactabular-table reactabular-dnd table-resolver
Module not found: Error: Can't resolve 'happypack/loader-loader' in 'D:\project\YAPI_DEV\vendors\client'
 @ multi react redux redux-thunk react-dom redux-promise react-router react-router-dom prop-types axios moment react-d
nd-html5-backend react-dnd reactabular-table reactabular-dnd table-resolver

[error] multi react redux redux-thunk react-dom redux-promise react-router react-router-dom prop-types axios moment re
act-dnd-html5-backend react-dnd reactabular-table reactabular-dnd table-resolver
Module not found: Error: Can't resolve 'happypack/loader-loader' in 'D:\project\YAPI_DEV\vendors\client'
 @ multi react redux redux-thunk react-dom redux-promise react-router react-router-dom prop-types axios moment react-d
nd-html5-backend react-dnd reactabular-table reactabular-dnd table-resolver

[error] multi brace mockjs json5 url
Module not found: Error: Can't resolve 'happypack/loader-loader' in 'D:\project\YAPI_DEV\vendors\client'
 @ multi brace mockjs json5 url

[error] multi react redux redux-thunk react-dom redux-promise react-router react-router-dom prop-types axios moment re
act-dnd-html5-backend react-dnd reactabular-table reactabular-dnd table-resolver
Module not found: Error: Can't resolve 'happypack/loader-loader' in 'D:\project\YAPI_DEV\vendors\client'
 @ multi react redux redux-thunk react-dom redux-promise react-router react-router-dom prop-types axios moment react-d
nd-html5-backend react-dnd reactabular-table reactabular-dnd table-resolver

[error] multi react redux redux-thunk react-dom redux-promise react-router react-router-dom prop-types axios moment re
act-dnd-html5-backend react-dnd reactabular-table reactabular-dnd table-resolver
Module not found: Error: Can't resolve 'happypack/loader-loader' in 'D:\project\YAPI_DEV\vendors\client'
 @ multi react redux redux-thunk react-dom redux-promise react-router react-router-dom prop-types axios moment react-d
nd-html5-backend react-dnd reactabular-table reactabular-dnd table-resolver

[error] multi react redux redux-thunk react-dom redux-promise react-router react-router-dom prop-types axios moment re
act-dnd-html5-backend react-dnd reactabular-table reactabular-dnd table-resolver
Module not found: Error: Can't resolve 'happypack/loader-loader' in 'D:\project\YAPI_DEV\vendors\client'
 @ multi react redux redux-thunk react-dom redux-promise react-router react-router-dom prop-types axios moment react-d
nd-html5-backend react-dnd reactabular-table reactabular-dnd table-resolver

[error] multi react redux redux-thunk react-dom redux-promise react-router react-router-dom prop-types axios moment re
act-dnd-html5-backend react-dnd reactabular-table reactabular-dnd table-resolver
Module not found: Error: Can't resolve 'happypack/loader-loader' in 'D:\project\YAPI_DEV\vendors\client'
 @ multi react redux redux-thunk react-dom redux-promise react-router react-router-dom prop-types axios moment react-d
nd-html5-backend react-dnd reactabular-table reactabular-dnd table-resolver

[error] multi brace mockjs json5 url
Module not found: Error: Can't resolve 'happypack/loader-loader' in 'D:\project\YAPI_DEV\vendors\client'
 @ multi brace mockjs json5 url

[error] multi brace mockjs json5 url
Module not found: Error: Can't resolve 'happypack/loader-loader' in 'D:\project\YAPI_DEV\vendors\client'
 @ multi brace mockjs json5 url

[error] multi react redux redux-thunk react-dom redux-promise react-router react-router-dom prop-types axios moment re
act-dnd-html5-backend react-dnd reactabular-table reactabular-dnd table-resolver
Module not found: Error: Can't resolve 'happypack/loader-loader' in 'D:\project\YAPI_DEV\vendors\client'
 @ multi react redux redux-thunk react-dom redux-promise react-router react-router-dom prop-types axios moment react-dnd-html5-backend react-dnd reactabular-table reactabular-dnd table-resolver
nd-html5-backend react-dnd reactabular-table reactabular-dnd table-resolver
                                                                                                                      act-dnd-html5-backend react-dnd reactabular-table reactabular-dnd table-resolver
[error] multi react redux redux-thunk react-dom redux-promise react-router react-router-dom prop-types axios moment re
act-dnd-html5-backend react-dnd reactabular-table reactabular-dnd table-resolver                                      nd-html5-backend react-dnd reactabular-table reactabular-dnd table-resolver
Module not found: Error: Can't resolve 'happypack/loader-loader' in 'D:\project\YAPI_DEV\vendors\client'
 @ multi react redux redux-thunk react-dom redux-promise react-router react-router-dom prop-types axios moment react-dact-dnd-html5-backend react-dnd reactabular-table reactabular-dnd table-resolver
nd-html5-backend react-dnd reactabular-table reactabular-dnd table-resolver
                                                                                                                      nd-html5-backend react-dnd reactabular-table reactabular-dnd table-resolver
[error] multi react redux redux-thunk react-dom redux-promise react-router react-router-dom prop-types axios moment re
act-dnd-html5-backend react-dnd reactabular-table reactabular-dnd table-resolver
Module not found: Error: Can't resolve 'happypack/loader-loader' in 'D:\project\YAPI_DEV\vendors\client'
 @ multi react redux redux-thunk react-dom redux-promise react-router react-router-dom prop-types axios moment react-d
nd-html5-backend react-dnd reactabular-table reactabular-dnd table-resolver

PS D:\project\YAPI_DEV\vendors>`

**Comment by suxiaoxin** [comment]
开发环境先 npm install 然后运行 npm run dev，不要在window下开发，用mac或者 linux
复制测试集功能已经收集了

**Comment by caozihao** [comment]
我擦..这么不友好啊..我用的就是windows

**Comment by suxiaoxin** [comment]
装个虚拟机吧

**Comment by caozihao** [comment]
还是等你们官方出带这个功能的版本吧~（期待）
