### ISSUE TITLE
测试报告body显示不完整

### ISSUE THREAD

**Issue by konamistan** [YMFE/yapi#75]
## Version
~ 1.2.7

## What is expected
~body显示完整

## Step to reproduce
~ 测试集测试出报告

## Environment
~ win10

![image](https://user-images.githubusercontent.com/11361799/33419138-0d4f66f8-d5e4-11e7-9e3c-47540c52f758.png)
![image](https://user-images.githubusercontent.com/11361799/33419142-1169d458-d5e4-11e7-9770-1dd780a56969.png)

**Comment by konamistan** [comment]
url显示也不完整

**Comment by suxiaoxin** [comment]
Fixed. v1.2.8
