### ISSUE TITLE
v1.4.3版本 无法取消项目私有权限

### ISSUE THREAD

**Issue by ZTTALTAI** [YMFE/yapi#752]
## 版本号
~ v1.4.3

## 什么问题
~ 新建项目/编辑项目 不能修改权限为公共项目

## 如何复现此问题
~ 新建项目/编辑项目

## 什么浏览器
~ chrome，safari

## 什么系统（Linux, Windows, macOS）
Linux

**Comment by hellosean1025** [comment]
新版开始，只有管理员才有权限设置为公开项目，联系管理员吧
