### ISSUE TITLE
swagger url数据导入，不支持参数传递吗？

### ISSUE THREAD

**Issue by yuezhongxin** [YMFE/yapi#753]
## 版本号
~ 1.4.2

## 什么问题
~ swagger url数据导入，不支持参数传递吗？比如`http://111.222.333.44:8088/v2/api-docs?token=ddh223dddd`

导入的时候报：`解析数据为空`错误。

没有加`token`参数的时候，导入成功。

## 如何复现此问题
~ 

## 什么浏览器
~ chrome

## 什么系统（Linux, Windows, macOS）
macOS

**Comment by yuezhongxin** [comment]
找到原因了，实际yapi请求的地址是：`https://yapi.xxxxx.com/api/project/swagger_url?url=http://111.222.333.44:8088/v2/api-docs?token=ddh223dddd`

所以不能直接加token参数，只能加载uri里面，比如`http://111.222.333.44:8088/v2/api-docs/ddh223dddd`

希望可以支持参数的形式，因为api的接口需要授权访问，如果api是公网部署，知道地址的话，api就会暴露。

**Comment by yuezhongxin** [comment]
需要注意，路径中不能有特殊字符，否则报402错误。

**Comment by hellosean1025** [comment]
最好能二次开发修复下问题，然后 pr
