### ISSUE TITLE
无法编译打包

### ISSUE THREAD

**Issue by zengnotes** [YMFE/yapi#76]
ykit] ykit@2.0.2
[error] ./client/styles/theme.less
Module build failed: ModuleParseError: Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @import '~antd/dist/antd.less';
| 
| @ant-prefix             : ant;
    at doBuild (/usr/local/lib/node_modules/ykit/node_modules/webpack/lib/NormalModule.js:303:19)
    at runLoaders (/usr/local/lib/node_modules/ykit/node_modules/webpack/lib/NormalModule.js:209:11)
    at /usr/local/lib/node_modules/ykit/node_modules/loader-runner/lib/LoaderRunner.js:370:3
    at iterateNormalLoaders (/usr/local/lib/node_modules/ykit/node_modules/loader-runner/lib/LoaderRunner.js:211:10)
    at /usr/local/lib/node_modules/ykit/node_modules/loader-runner/lib/LoaderRunner.js:202:4
    at /usr/local/lib/node_modules/ykit/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:70:14
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./client/styles/theme.less
 @ ./client/index.js
 @ multi ./index.js

[error] ./client/styles/theme.less
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @import '~antd/dist/antd.less';
| 
| @ant-prefix             : ant;
 @ ./client/styles/theme.less 4:14-39
 @ ./client/index.js
 @ multi ./index.js

**Comment by suxiaoxin** [comment]
npm install 成功了没？

**Comment by zengnotes** [comment]
npm install 成功了

$ npm run dev

> yapi@1.2.8 dev /Users/mebar/Desktop/yapi-1.2.8
> npm run dev-server & npm run dev-client


> yapi@1.2.8 dev-client /Users/mebar/Desktop/yapi-1.2.8
> ykit s -p 4000


> yapi@1.2.8 dev-server /Users/mebar/Desktop/yapi-1.2.8
>  nodemon server/app.js dev -L

[nodemon] 1.12.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: ~/yapi-1.2.8/server/**/* ~/yapi-1.2.8/common/**/* plugins ~/yapi-1.2.8/exts/**/*
[nodemon] starting `node server/app.js dev`
[ykit] ykit@2.0.2
[ykit] Serving at: ~/yapi-1.2.8
[info] Ready on: http://127.0.0.1:4000

load websocket...
log: the server is start at port 3000
log: mongodb load success...
✖ [08:46:14] 3 errors in compiling process.
[error] in ./client/components/Postman/CheckCrossInstall.js

~/yapi-1.2.8/client/components/Postman/CheckCrossInstall.js
  38:15  error  Expected indentation of 12 space characters but found 14  react/jsx-indent

✖ 1 problem (1 error, 0 warnings)

 @ ./client/containers/Project/Interface/InterfaceCol/InterfaceColContent.js 127:25-87
 @ ./client/containers/Project/Interface/Interface.js
 @ ./client/containers/Project/Project.js
 @ ./client/containers/index.js
 @ ./client/Application.js
 @ ./client/index.js
 @ multi (webpack)-hot-middleware/client.js?reload=true&path=http://127.0.0.1:4000/__webpack_hmr&timeout=9999999&overlay=false ./index.js

[error] in ./client/styles/theme.less
Module build failed: ModuleParseError: Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @import '~antd/dist/antd.less';
| 
| @ant-prefix             : ant;
 @ ./client/styles/theme.less
 @ ./client/index.js
 @ multi (webpack)-hot-middleware/client.js?reload=true&path=http://127.0.0.1:4000/__webpack_hmr&timeout=9999999&overlay=false ./index.js

[error] in ./client/styles/theme.less
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @import '~antd/dist/antd.less';
| 
| @ant-prefix             : ant;
 @ ./client/styles/theme.less 4:14-39 18:2-22:4 19:20-45
 @ ./client/index.js
 @ multi (webpack)-hot-middleware/client.js?reload=true&path=http://127.0.0.1:4000/__webpack_hmr&timeout=9999999&overlay=false ./index.js

✔ [08:46:15] 200 GET /prd/index@dev.css ( 82.01KB )
✔ [08:46:15] 200 GET /prd/manifest@dev.js ( 30.44KB )
✔ [08:46:15] 200 GET /prd/lib2@dev.js ( 2636.35KB )
✔ [08:46:15] 200 GET /prd/lib@dev.js ( 5098.59KB )
✔ [08:46:15] 200 GET /prd/index@dev.js ( 15333.66KB )
✖ [08:46:19] 3 errors in compiling process.
[error] in ./client/components/Postman/CheckCrossInstall.js

/Users/mebar/Desktop/yapi-1.2.8/client/components/Postman/CheckCrossInstall.js
  38:15  error  Expected indentation of 12 space characters but found 14  react/jsx-indent

✖ 1 problem (1 error, 0 warnings)

 @ ./client/containers/Project/Interface/InterfaceCol/InterfaceColContent.js 127:25-87
 @ ./client/containers/Project/Interface/Interface.js
 @ ./client/containers/Project/Project.js
 @ ./client/containers/index.js
 @ ./client/Application.js
 @ ./client/index.js
 @ multi (webpack)-hot-middleware/client.js?reload=true&path=http://127.0.0.1:4000/__webpack_hmr&timeout=9999999&overlay=false ./index.js

[error] in ./client/styles/theme.less
Module build failed: ModuleParseError: Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @import '~antd/dist/antd.less';
| 
| @ant-prefix             : ant;
 @ ./client/index.js 23:0-30
 @ multi (webpack)-hot-middleware/client.js?reload=true&path=http://127.0.0.1:4000/__webpack_hmr&timeout=9999999&overlay=false ./index.js

[error] in ./client/styles/theme.less
Module build failed: ModuleParseError: Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @import '~antd/dist/antd.less';
| 
| @ant-prefix             : ant;
 @ ./client/styles/theme.less
 @ ./client/index.js
 @ multi (webpack)-hot-middleware/client.js?reload=true&path=http://127.0.0.1:4000/__webpack_hmr&timeout=9999999&overlay=false ./index.js

**Comment by suxiaoxin** [comment]
不要用 ykit 2.0 版本，使用 0.6版本吧
