### ISSUE TITLE
接口返回数组对象，mock数据无效，预览看不到数组内的字段

### ISSUE THREAD

**Issue by xushujin** [YMFE/yapi#761]
## 版本号
1.4.3

## 什么问题
接口返回数组对象，mock数据无效，预览看不到数组内的字段

## 如何复现此问题
![image](https://user-images.githubusercontent.com/5311716/51167372-66a04b00-18e1-11e9-8356-8ea178ee58df.png)
![image](https://user-images.githubusercontent.com/5311716/51167380-6d2ec280-18e1-11e9-839c-60ba0b695cb1.png)
![image](https://user-images.githubusercontent.com/5311716/51167398-7881ee00-18e1-11e9-964f-34825b39ca85.png)

数据如下：
{"$schema":"http://json-schema.org/draft-04/schema#","type":"object","properties":{"field_1":{"type":"array","items":{"type":"object","properties":{"field_4":{"type":"string","mock":{"mock":"@string"}},"field_10":{"type":"string","mock":{"mock":"@string"}}},"required":["field_4","field_10"]}},"field_14":{"type":"string","mock":{"mock":"@string"}},"field_11":{"type":"object","properties":{"field_15":{"type":"object","properties":{"field_16":{"type":"string","mock":{"mock":"@string"}}},"required":["field_16"]}},"required":["field_15"]}},"required":["field_1","field_14","field_11"]}

## 什么浏览器
Goggle Chrome及360浏览器都是一样的效果

## 什么系统（Linux, Windows, macOS）
Windows

**Comment by zhishuai-tang** [comment]
配置一下数组的长度，大于1

**Comment by xushujin** [comment]
可以了，多谢！

**Comment by hopkinson** [comment]
能不能设置默认返回一个？

**Comment by Myayiba** [comment]
list的最小元素个数设置了1，预览list还是为空

**Comment by verseboys** [comment]
> list的最小元素个数设置了1，预览list还是为空

大于1，最好设置最大元素个数，就可以了。
