### ISSUE TITLE
建议增加node.js的crypto算法模块，用于测试加密数据

### ISSUE THREAD

**Issue by mzky** [YMFE/yapi#764]
## 版本号
~ V1.4.4

## 什么问题
~建议增加node.js的crypto算法模块，用于测试加密数据
![tim 20190116101130](https://user-images.githubusercontent.com/13345233/51222099-27bcd480-1977-11e9-90ef-8af545df2589.png)

## 如何复现此问题
~ 参考nodejs官方api手册：https://nodejs.org/api/crypto.html

## 什么浏览器
~ 火狐、谷歌

## 什么系统（Linux, Windows, macOS）
CentOS7

**Comment by hellosean1025** [comment]
可以自己开发下，然后 pr
