### ISSUE TITLE
无法建立公开项目

### ISSUE THREAD

**Issue by qiyulan** [YMFE/yapi#765]
## 版本号
~ 1.4.4

## 什么问题
~ 包括管理员权限在内所有人无法在新建项目时选择除了私有外的权限

## 如何复现此问题
~ 部署 1.4.4 版本,使用管理员权限新建项目,权限只有私有可选  
![image](https://user-images.githubusercontent.com/17901676/51222935-baab3e00-197a-11e9-87c2-b80b79fb193a.png)

## 什么浏览器
~ Chrome 71 64bit

## 什么系统（Linux, Windows, macOS）
Windows 10 1803

about #752

**Comment by hellosean1025** [comment]
先新建私有项目，然后让管理员修改为公开项目

**Comment by NoSugarCoffee** [comment]
> 先新建私有项目，然后让管理员修改为公开项目

这有点迷惑，毕竟看官方教程创建的时候说可以创建公开项目，希望更新文档

**Comment by lizy0329** [comment]
确实有点迷惑了，赶紧改回来吧，一万个问号
