### ISSUE TITLE
运行 body体显示异常,json显示成object

### ISSUE THREAD

**Issue by keepnode** [YMFE/yapi#77]
## Version
~ 1.2.7

## What is expected
~点击 发送，模拟请求时，输出的body其实是个json，但显示为object

## Step to reproduce
~ 点击 发送 的body内容
![image](https://user-images.githubusercontent.com/8043218/33470492-7f018ae6-d6a3-11e7-8b00-5f4bd656c114.png)
实际请求的body内容
![image](https://user-images.githubusercontent.com/8043218/33470532-c32faff4-d6a3-11e7-9e4f-37e9cb51c00f.png)

## Environment
~ windows 10

**Comment by suxiaoxin** [comment]
v1.2.8 版本已修复，尝试更新到 v1.2.8 吧
yapi update -v v1.2.8
