### ISSUE TITLE
服务端测试无法获取global变量

### ISSUE THREAD

**Issue by neowood** [YMFE/yapi#785]
## 版本号
~ 
1.4.1
## 什么问题
~
在环境配置中定义global类型的变量，正常测试没有问题，用服务端测试就报“message: global is not defined”
## 如何复现此问题
~ 
1. 定义一个global类型的变量，比如admin_name
2. 在 Pre-request Script 中引用该变量，如 console.log(global.admin_name)
3. 新建测试集合，点击服务端测试
4. 复制测试链接，粘贴至新的标签页中，回车，测试报告中显示“message: global is not defined”
## 什么浏览器
~ 
chrome
## 什么系统（Linux, Windows, macOS）
macOS

**Comment by gao520sun** [comment]
你解决了吗？

**Comment by neowood** [comment]
没有，已经没用yapi了
