### ISSUE TITLE
导入swagger数据时，json格式的接口参数和返回数据不能导入

### ISSUE THREAD

**Issue by lichao0** [YMFE/yapi#79]
## Version
~ 1.2.8

## What is expected
~导入swagger数据时，json格式的接口参数和返回数据不能导入，导入后Reqeust和Response都是空的

## Step to reproduce
~ 

## Environment
~

**Comment by suxiaoxin** [comment]
@lichao0 方便的话，提供下数据

**Comment by lichao0** [comment]
@suxiaoxin 不太方便提供原始数据，但发现一个可能的原因：definitions中ref的对象缺失的话，会导致导入的所有接口的Reqeust和Response都是空的。如下Response未定义User

"Response«User»":{
            "type":"object",
            "properties":{
                "code":{
                    "type":"string"
                },
                "data":{
                    "$ref":"#/definitions/User"
                },
                "desc":{
                    "type":"string"
                }                
            }
        }

**Comment by lichao0** [comment]
> [``](

- 

- [ ] 1. url

)

**Comment by suxiaoxin** [comment]
definitions ref对象缺失，说明了文档本身不规范把

**Comment by lichao0** [comment]
文档数据可能不规范，但是影响到其他正常的接口数据也不能正常导入

**Comment by suxiaoxin** [comment]
@lichao0 Fixed. v1.2.9
