### ISSUE TITLE
Yap 有办法置换Json 格式参数的某个值么？

### ISSUE THREAD

**Issue by 512433465** [YMFE/yapi#791]
场景：
A接口返回：tempOrderCode值e58f800f40bc4f46a78d511ee03278a2为临时变量

B接口需要参数：json格式的字符串。
{
  "reqDtos": {
    "tempOrderId": "e58f800f40bc4f46a78d511ee03278a2",
    "typeOrigin": 1,
    "adultNum": 1,
    "childNum": 0,
    "babyNum": 0,
    "elderNum": 0,
    "departureDate": "2019-06-28",
    "orderContactsDTO": {
      "name": "测试账号",
      "phone": "18817494688",
      "email": "1@qq.com"
    }}
如上，用A接口去的tempOrderCode 去作为B接口Json参数的一部分，置换B接口的中需要置换的变量值。
Yap 有办法置换Json 格式参数的某个值么？

**Comment by gtsam** [comment]
应该可以的，自动化测试的教程里面有说到这个功能的
https://yapi.ymfe.org/documents/case.html#%E7%AC%AC%E4%BA%8C%E6%AD%A5%EF%BC%8C%E7%BC%96%E8%BE%91%E6%B5%8B%E8%AF%95%E7%94%A8%E4%BE%8B

**Comment by 512433465** [comment]
确实可以，多谢 @gtsam
