### ISSUE TITLE
版本提醒："当前版本是：1.5.0  可升级到: 1.4.1   版本详情"

### ISSUE THREAD

**Issue by xhxu** [YMFE/yapi#796]
## 版本号
v1.5.0

## 什么问题
"当前版本是：1.5.0  可升级到: 1.4.1   版本详情"
## 如何复现此问题
~ 

## 什么浏览器
~ 

## 解决方法：
server\client\Notify\Notify.js
line : 25
`
const isShow = this.state.newVersion !== this.state.version;
`
改为：
`
const isShow = this.state.newVersion > this.state.version;
`
<img width="335" alt="wx20190202-180437 2x" src="https://user-images.githubusercontent.com/1581775/52162945-c6865680-2715-11e9-834c-37da8807b031.png">

**Comment by hellosean1025** [comment]
马上修复下

**Comment by hellosean1025** [comment]
Fixed  by the master

**Comment by JiaRG** [comment]
@hellosean1025 此问题又复现了。。。
https://github.com/YMFE/yapi/blob/3101e1aa680e53643e65fa65cff62613580078f1/client/components/Notify/Notify.js#L25
