### ISSUE TITLE
api参数问题

### ISSUE THREAD

**Issue by rocky9988** [YMFE/yapi#8]
我的api的地址是这样的格式
http://xx.com/get/info/{user_id}
{user_id}是动态获取的，也是后台根据传入的{user_id}去获取数据的
get请求，目前不知道怎么在这里面设置请求。。请求增加一个这样的功能

**Comment by suxiaoxin** [comment]
/get/info/:user_id
![image](https://user-images.githubusercontent.com/17695103/31700110-baaf03aa-b38c-11e7-852a-228230171ea7.png)
