### ISSUE TITLE
path中不能包含等于号导致导入接口失败

### ISSUE THREAD

**Issue by Pastel001** [YMFE/yapi#80]
## Version
~ v1.2.5

## What is expected
~path中是允许包含等于号的
期望能兼容/vehicles/city_id={cityId}/park_num
这样的接口，并且cityId作为path中的参数，进行参数化

## Step to reproduce
~ 保存/vehicles/city_id=:cityId/park_num这样的接口
或者导入包含/vehicles/city_id={cityId}/park_num这样接口的swagger文件
![image](https://user-images.githubusercontent.com/10250772/33660198-00c83f3e-dabe-11e7-9026-6309ef680d4a.png)
## Environment
~ 不相关

**Comment by suxiaoxin** [comment]
Fixed. v1.2.9
