### ISSUE TITLE
Chrome 72版本会过滤在环境设置中配置的Cookie

### ISSUE THREAD

**Issue by wwjay9** [YMFE/yapi#803]
## 版本号
1.4.1 

## 什么问题
在环境设置中设置的Cookie会被Chrome过滤掉

## 如何复现此问题
在Chrome 72.0.3626.109上可以重现，在Chrome 68、71的版本中正常使用

## 什么浏览器
Chrome 72.0.3626.109

## 什么系统（Linux, Windows, macOS）
Windows

**Comment by ZTTALTAI** [comment]
+1

**Comment by hellosean1025** [comment]
https://stackoverflow.com/questions/53175498/chrome-extension-requestheaders-object-doesnt-have-the-cookie-header

72 版本 chrome 有了不兼容的升级。。。

**Comment by hellosean1025** [comment]
我有时间想办法升级下

**Comment by hellosean1025** [comment]
Fixed.

https://chrome.google.com/webstore/detail/cross-request/cmnlfmgbjmaciiopcgodlhpiklaghbok?hl=zh-CN
