### ISSUE TITLE
返回字段定义为对象数组时候，模拟数据返回空[]

### ISSUE THREAD

**Issue by lichangfeng** [YMFE/yapi#807]
## 版本号
~ 
1.5.2
## 什么问题
~
使用json-schema模式，返回字段为对象数组，数组名定义为array|1-10，不起作用
## 如何复现此问题
~ 
1.创建一个接口，其中一个返回字段为对象数组，字段名 为array|1-10
2.调用Mock地址，返回的模拟数据，数组为空
## 什么浏览器
~ 
chrome浏览器
## 什么系统（Linux, Windows, macOS）
win10

**Comment by lichangfeng** [comment]
明白了，要点后面的设置

**Comment by zhaonoob** [comment]
> 明白了，要点后面的设置
请问应该怎么设置

**Comment by zhaonoob** [comment]
请问应该怎么设置？

**Comment by lichangfeng** [comment]
![image](https://user-images.githubusercontent.com/8101989/55041437-fb54c100-5067-11e9-9117-4aa5e5fe52e5.png)
@zhaonoob

**Comment by xiashei** [comment]
要设置最小最大值。
