### ISSUE TITLE
接口预览界面JSON显示不全

### ISSUE THREAD

**Issue by lichao0** [YMFE/yapi#81]
## Version
~ 1.2.8

## What is expected
~ 操作步骤：
1、项目列表页面点击某一个项目进入接口列表页面
2、点击一个参数较短的接口进入
![image](https://user-images.githubusercontent.com/9666904/33694336-8fe5e788-db32-11e7-8614-50f7c5c574cc.png)

3、再点击一个参数较长的接口进入，就会出现接口参数显示不完整的现象：
![image](https://user-images.githubusercontent.com/9666904/33694316-6bdd4660-db32-11e7-9c8b-d3c3ab53be43.png)

## Step to reproduce
~ 

## Environment
~

**Comment by suxiaoxin** [comment]
Fix. v1.2.9
