### ISSUE TITLE
安装时导入数据失败，登录后数据库group查不到数据空指针

### ISSUE THREAD

**Issue by mrdong916** [YMFE/yapi#815]
在使用 yapi-cli 1.5.1 和1.5.2 安装时，安装成功后登录进入首页显示正在加载中

报错信息：

TypeError: Cannot read property '_id' of null
    at t.<anonymous> (index@796c7c7bbc2a9684f831.js:203)
    at r (index@796c7c7bbc2a9684f831.js:31)
    at Generator._invoke (index@796c7c7bbc2a9684f831.js:31)
    at Generator.e.(anonymous function) [as next] (http://doc.d-jh.com/prd/index@796c7c7bbc2a9684f831.js:31:6019)
    at r (index@796c7c7bbc2a9684f831.js:31)
    at index@796c7c7bbc2a9684f831.js:31

F12查看得知 请求 http://xxxxxxx/api/group/get_mygroup 获取分组信息的时候返回数据如下
```
{
  "errcode": 0,
  "errmsg": "成功！",
  "data": null
}
```
获取不到分组的ID导致ID为空出现异常信息，应该就是初始化数据库时失败导致

**Comment by mrdong916** [comment]
> 在使用 yapi-cli 1.5.1 和1.5.2 安装时，安装成功后登录进入首页显示正在加载中
> 
> 报错信息：
> 
> TypeError: Cannot read property '_id' of null
> at t. ([index@796c7c7bbc2a9684f831.js](mailto:index@796c7c7bbc2a9684f831.js):203)
> at r ([index@796c7c7bbc2a9684f831.js](mailto:index@796c7c7bbc2a9684f831.js):31)
> at Generator._invoke ([index@796c7c7bbc2a9684f831.js](mailto:index@796c7c7bbc2a9684f831.js):31)
> at Generator.e.(anonymous function) [as next] (http://doc.d-jh.com/prd/index@796c7c7bbc2a9684f831.js:31:6019)
> at r ([index@796c7c7bbc2a9684f831.js](mailto:index@796c7c7bbc2a9684f831.js):31)
> at [index@796c7c7bbc2a9684f831.js](mailto:index@796c7c7bbc2a9684f831.js):31
> 
> F12查看得知 请求 http://xxxxxxx/api/group/get_mygroup 获取分组信息的时候返回数据如下
> 
> ```
> {
>   "errcode": 0,
>   "errmsg": "成功！",
>   "data": null
> }
> ```
> 获取不到分组的ID导致ID为空出现异常信息，应该就是初始化数据库时失败导致

**Comment by frowhy** [comment]
请问最后怎么解决的…

**Comment by danealiu** [comment]
出样同样问题，怎么解决

**Comment by danealiu** [comment]
这个解决了，在本是出现，在测试服务器布后就好了
