### ISSUE TITLE
测试集请求头header取本接口的key如1024，{{ $.1024.body}}，会取不到数据

### ISSUE THREAD

**Issue by konamistan** [YMFE/yapi#82]
## Version
~ 1.2.8

## What is expected
~

## Step to reproduce
~ 1 取本接口中的key值1024，如果取非本接口的值，值是可以获取的

## Environment
~

**Comment by suxiaoxin** [comment]
v1.2.9 版本已改成显示第一个到当前 case之前的 List，动态变量功能是为了获取请求过的接口参数和返回数据
