### ISSUE TITLE
开放api-服务端导入数据,可以导入但无法更新

### ISSUE THREAD

**Issue by bingxinranhuo** [YMFE/yapi#823]
## 版本号
~ yapi 1.52, node 7.6.0,  npm4.1.2

## 什么问题
~  [开放api](https://yapi.ymfe.org/openapi.html),服务端导入数据(swagger3.0)不能更新, 用了智能合并和完全覆盖都不可以

## 如何复现此问题
~ 1.首次导入数据(swagger3.0)ok, 2.修改文档再次导入(dataSync用了good和merge)

## 什么浏览器
~ chrome 72.0.3626.109

## 什么系统（Linux, Windows, macOS）
Windows 10

**Comment by hellosean1025** [comment]
文档里参数写错了

把 dataSync 改为 merge 吧

**Comment by hellosean1025** [comment]
![image](https://user-images.githubusercontent.com/17695103/53222052-1918ba00-36a7-11e9-9afd-676f6fcc8c12.png)

源码获取的 merge
