### ISSUE TITLE
对二次开发和插件开发有疑问

### ISSUE THREAD

**Issue by shouldnotappearcalm** [YMFE/yapi#825]
## 版本号
1.5.2

## 什么问题
打算针对我司的特殊需求做一些定制化开发，我是应该是插件开发还是二次开发，两者有什么区别吗。看见issue里面说开发不能用windows，是指用ykit打包的时候会出错吗，平时本地调试运行windows能否满足？

## 什么浏览器
Chrome

## 什么系统（Linux, Windows, macOS）
Windows

**Comment by wxxcarl** [comment]
看下文档，钩子列表，能否满足你们的需求，如果能的话，尽量用插件开发，插件开发就是在原来的基础上加东西，这样基本不影响以后yapi主体的版本更新，也不容易出错。如果深度定制化，就是改源代码了，难以保持更新，对源码不熟悉也容易出错。windows没试过

**Comment by shouldnotappearcalm** [comment]
好的，我懂了，谢谢，再问下如果我真的只能二次开发，岂不是我只能在本地commit然后pull  yapi的更新

**Comment by wxxcarl** [comment]
> 好的，我懂了，谢谢，再问下如果我真的只能二次开发，岂不是我只能在本地commit然后pull yapi的更新

是的，我是fetch之后自己合并。改动多的话，比较麻烦

**Comment by shouldnotappearcalm** [comment]
想问下你二次开发事用的windows吗，我用vscode配置debug模式配置文件 npm  run dev ，vscode报错`Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9229) `

**Comment by wxxcarl** [comment]
@shouldnotappearcalm 我用的是macos，ide也是vscode，但是没有用debug模式开发，所以不清楚

**Comment by shouldnotappearcalm** [comment]
好的，了解了，谢谢您
