### ISSUE TITLE
全局mock里面自定义对生成数据类型进行扩展，生效慢问题

### ISSUE THREAD

**Issue by shouldnotappearcalm** [YMFE/yapi#836]
## 版本号
V1.5.2
## 什么问题
我在全局mock里面定义脚本Random.extend扩展自己需要的数据类型生成规则，在接口编辑页面进行配置，在运行界面生成的值始终为 @注解名，隔了一天发现注解生效，生成数据正常

## 如何复现此问题
根据问题复现

## 什么浏览器
chrome
## 什么系统（Linux, Windows, macOS）
Linux

**Comment by hellosean1025** [comment]
不推荐这样用

**Comment by shouldnotappearcalm** [comment]
> 不推荐这样用

因为我觉得可能目前YApi提供的数据生成规则可能不全部符合我们的需求，那我怎么去扩展这些数据生成注解

**Comment by hellosean1025** [comment]
二次开发吧
