### ISSUE TITLE
最新版本的Chrome中，cross-request插件在请求raw数据时，不能正常的发送出数据

### ISSUE THREAD

**Issue by glenzcs** [YMFE/yapi#837]
## 版本号
~ 1.5.5

## 什么问题
~ 最新版本的Chrome中，cross-request插件在请求raw数据时，不能正常的发送出数据

## 如何复现此问题
~ 在最新版本的Chrome测试raw数据发送

## 什么浏览器
~ Chrame最新版

## 什么系统（Linux, Windows, macOS）
Windows

**Comment by hellosean1025** [comment]
最新版设置为 raw 时，需要手动定义 header
Content-Type

之前有个默认值，但导致了部分问题，新版按照 http 规范，去掉了这部分的默认处理
