### ISSUE TITLE
PUT、POST、DELETE接口request header设置Content-Type为application/json, 运行界面点击发送json结构错误

### ISSUE THREAD

**Issue by Pastel001** [YMFE/yapi#84]
## Version
~ V1.2.5

## What is expected
~PUT、POST、DELETE接口request header设置Content-Type为application/json,
可以发送body为空的请求，不应该提示错误，特别是DELETE接口，经常在path中传入id来删除某些资源，body通常为空，Content-Type可以设置为application/json
## Step to reproduce
~ 创建一个DELETE接口request header设置Content-Type为application/json
运行界面点击发送

## Environment
~ 不相关

**Comment by suxiaoxin** [comment]
请升级到 v1.2.8 版本
