### ISSUE TITLE
内网部署问题

### ISSUE THREAD

**Issue by sawsam** [YMFE/yapi#863]
## 版本号
~ 

## 什么问题
![image](https://user-images.githubusercontent.com/6177094/53677052-0cb6e180-3ce5-11e9-85dc-cfff535d2866.png)

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by a771853580** [comment]
此问题是你自己系统权限的问题，看正数第四行，有提示

**Comment by 1fengchen1** [comment]
我也是这个问题，应该怎么解决？ @a771853580 
![1](https://user-images.githubusercontent.com/29908615/53679157-d472cb80-3d03-11e9-82d0-4fb2988a8e67.png)

**Comment by a771853580** [comment]
我记得安装/home下无需权限，其他路径需要sudo

**Comment by 1fengchen1** [comment]
我是按照官网部署的，本机是centos，非home路径
https://yapi.ymfe.org/documents/redev.html

**Comment by 1fengchen1** [comment]
> 我记得安装/home下无需权限，其他路径需要sudo
我的就是root用户运行的呀

**Comment by a771853580** [comment]
![22](https://user-images.githubusercontent.com/28817971/53679198-c96c6b00-3d04-11e9-9495-8de225817cae.png)

**Comment by 1fengchen1** [comment]
![2](https://user-images.githubusercontent.com/29908615/53679402-4567b280-3d07-11e9-944f-22bb79ecdbc3.png)

**Comment by 1fengchen1** [comment]
我查看这个文件，居然在docker目录里，真奇怪，你有解决办法吗？
@a771853580 
[root@localhost yapi]# find / -name aesprim-browser.js
/var/lib/docker/overlay2/8d8870e9d05db9db28b222ecb5739b8f48590f0902db3fad43333f159933ba71/diff/var/lib/ghost/versions/2.4.0/node_modules/jsonpath/generated/aesprim-browser.js
/var/lib/docker/overlay2/d382b88890ccb2d436b2645a5ef0dc61db712cd425e20828997970d567e4b915/diff/var/lib/ghost/versions/2.4.0/node_modules/jsonpath/generated/aesprim-browser.js

**Comment by a771853580** [comment]
我没有使用docker，所以不太清楚什么情况

**Comment by sawsam** [comment]
把node安装目录用户组权限改成root:root问题解决了
