### ISSUE TITLE
cross-request插件在Chrome74版本运作失效

### ISSUE THREAD

**Issue by mijiawei** [YMFE/yapi#866]
## 版本号
2.10

## 什么问题
Uncaught TypeError: Cannot read property 'cross-response-unsafe-headers-list' of undefined
    at XMLHttpRequest.xhr.onload (response.js:300)

## 如何复现此问题
~ 

## 什么浏览器
Chrome 74

## 什么系统（Linux, Windows, macOS）
macOS

**Comment by hellosean1025** [comment]
chrome 最新版是 72

**Comment by benhouse1987** [comment]
我这边也坏了，chrome版本 73.0.3683.75

**Comment by benhouse1987** [comment]
麻烦抓紧修复下，很多人在用

**Comment by hellosean1025** [comment]
https://github.com/YMFE/yapi/issues/889
已修复

@benhouse1987  @mijiawei
