### ISSUE TITLE
二次开发：json-schema-editor-visual icon渲染了2个

### ISSUE THREAD

**Issue by amiezhang** [YMFE/yapi#869]
## 版本号
~ 1.5.2

## 什么问题
~ json-schema-editor-visual icon渲染了2个（svg、::before都渲染出来了）
![1](https://user-images.githubusercontent.com/15716269/53809619-16b03d00-3f90-11e9-9350-1c775c3f6ed3.jpg)

## 什么浏览器
~ chrome

## 什么系统（Linux, Windows, macOS）
windows macOS

## 尝试解决
发现json-schema-editor-visual antd版本没有锁定，但是yapi的antd版本锁定了
尝试解开yapi的antd的版本锁定，重新yarn，icon显示正常，但是报错了
![image](https://user-images.githubusercontent.com/15716269/53809660-27f94980-3f90-11e9-94d7-8d87869e3e0d.png)
![image](https://user-images.githubusercontent.com/15716269/53809797-6ee73f00-3f90-11e9-9190-bcc0b6e230bb.png)

期望能把yarn.lock，package.lock.json也发上来，避免一些版本升级带来的难以调试的问题

**Comment by amiezhang** [comment]
我到json-schema-editor-visual提issue吧

**Comment by gejiawen** [comment]
这个问题好像还没解决吧
