### ISSUE TITLE
执行测试集出现错误

### ISSUE THREAD

**Issue by guoming** [YMFE/yapi#87]
## Version
~ 1.2.8

## What is expected
~ response.js:330 POST http://127.0.0.1/pharmacyService/api/v1/Orders/create net::ERR_CONNECTION_REFUSED
sendAjaxByContent @ response.js:330
(anonymous) @ response.js:386
run @ response.js:369
(anonymous) @ response.js:411
response.js:396 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at formUrlencode (response.js:220)
    at sendAjaxByContent (response.js:246)
    at response.js:386
    at NodeList.forEach (<anonymous>)
    at run (response.js:369)
    at response.js:411

## Environment
~ chrome

**Comment by suxiaoxin** [comment]
如何复现？

**Comment by guoming** [comment]
测试用例使用变量时就会出现。

**Comment by guoming** [comment]
查询字符串中使用参数
![image](https://user-images.githubusercontent.com/13638177/33827448-571f99b6-dea3-11e7-83f8-03a530305f2c.png)

![image](https://user-images.githubusercontent.com/13638177/33827556-bd4de04e-dea3-11e7-970c-0c359efbb178.png)
