### ISSUE TITLE
希望新增Response-body的html解析功能,方便调试

### ISSUE THREAD

**Issue by railgun20001** [YMFE/yapi#881]
## 版本号
1.5.6

## 什么问题
希望新增Response-body的html解析功能,方便调试

如下图是postman
![image](https://user-images.githubusercontent.com/22837283/54068954-16b08580-428d-11e9-81bc-eb62967b5620.png)

**Comment by zoulux** [comment]
强烈需要 因为 laravel 的dd 函数 输出的也是 html

**Comment by sunbay** [comment]
+1

**Comment by sunbay** [comment]
这个真的需要，希望支持
