### ISSUE TITLE
path中包含等于号问题

### ISSUE THREAD

**Issue by Pastel001** [YMFE/yapi#90]
## Version
~ V1.2.9

## What is expected
~接口/vehicles/city_id=:cityId/park_num
第一个问题是运行界面，输入参数cityId的值，点击运行，提示404
![image](https://user-images.githubusercontent.com/10250772/34077297-8bc38da2-e33b-11e7-985d-fd2c9a241a0f.png)

第二个问题就是swagger导入之后cityId可以识别成一个参数，但是手动编辑一下接口/vehicles/city_id=:cityId/park_num，比如先删除park_num,然后再加回去，点保存。然后cityId就不会被识别成参数了，界面不能显示参数cityId
或者手动创建一个这样带等于号的接口，一个道理参数也不能被识别

## Step to reproduce
~ 1、swagger导入一个包含等于号的接口/vehicles/city_id=:cityId/park_num
2、手动创建一个这样带等于号的接口

## Environment
~ chrome

**Comment by suxiaoxin** [comment]
id={id}
