### ISSUE TITLE
前端没有热更新

### ISSUE THREAD

**Issue by 2015-lizaiyang** [YMFE/yapi#91]
修改前端无法热更新页面，而是要重新输入命令“npm run dev”重新打包。作者能否在ykit插件里加入这个功能。

**Comment by suxiaoxin** [comment]
npm run dev 支持热更新的，你修改的是哪个地方的前端代码？

**Comment by 1111mp** [comment]
请问 我现在在已经部署好的项目路径下修改前端的home.js中的代码 然后重新启动之后修改的代码没有生效 是需要重新编译吗？ 我也通过ykit pack -m重新打包 但是会报错，python环境也是ok的，能告知一下怎么才能让我修改之后的代码生效吗？
