### ISSUE TITLE
开发环境在 windows7下支持吗？

### ISSUE THREAD

**Issue by wangbow** [YMFE/yapi#92]
## Version
~ node V8.9.3

## What is expected
npm run dev-client的时候，报这个问题:
.--> LibSass 的二进制文件(D:\iuap\mock-server\qunawang\mock-yonyou\mock-yonyou\node_modules\node-sass-china\vendor\win32-x64-57\binding.node)缺失，请执行下面3条                               命令下载对应版本的二进制文件：（有可能引发此错误的原因是 Node 版本变更）
  mkdir -p D:\iuap\mock-server\qunawang\mock-yonyou\mock-yonyou\node_modules\node-sass-china\vendor\win32-x64-57
  cd D:\iuap\mock-server\qunawang\mock-yonyou\mock-yonyou\node_modules\node-sass-china\vendor\win32-x64-57
  curl -o binding.node http://cdn.npm.taobao.org/dist/node-sass/v4.5.0/win32-x64-57_binding.node
--> MacOS 、Unix/Linux 请根据权限使用 sudo

我按照这个命令安装了。还是报同样的错误。
# 请问该怎么解决呢？着急呢
~ 

## Environment
~

**Comment by suxiaoxin** [comment]
不支持，请在 mac linux运行
