### ISSUE TITLE
版本发布的时候能否增加说明

### ISSUE THREAD

**Issue by helloweb314** [YMFE/yapi#923]
## 版本号
~ 
所有
## 什么问题
~
版本更新有点频繁. 希望能增加版本发布一些明细哈, 了解到新功能相关信息, 可能增加的工作量, 实在不好意思
## 如何复现此问题
~ 
查看版本列表
## 什么浏览器
~ 
chrme

**Comment by Ryan-Miao** [comment]
更新挺方便的啊

**Comment by helloweb314** [comment]
是呀 非常方便,  就是不晓得增加的啥新功能 0.0

**Comment by hellosean1025** [comment]
https://github.com/YMFE/yapi/blob/master/CHANGELOG.md

**Comment by helloweb314** [comment]
非常感谢 @hellosean1025
