### ISSUE TITLE
google插件运行接口异常

### ISSUE THREAD

**Issue by lanux** [YMFE/yapi#927]
## 版本号
1.5.10

## 什么问题
google 插件，运行接口时候出错
错误
Error: Extension context invalidated.
上下文
http://***:33333/project/13/interface/api/30
堆叠追踪
response.js:405 (匿名函数)
response.js:371 (run)
response.js:420 (匿名函数)

## 如何复现此问题
~ 

## 什么浏览器
google，版本 72.0.3626.121（正式版本） （64 位）

## 什么系统（Linux, Windows, macOS）
部署服务器linux
浏览器所在服务器：win10

**Comment by hellosean1025** [comment]
确保 chrome 插件版本是 cross-request 3.0
![image](https://user-images.githubusercontent.com/17695103/55447086-e8f0ff00-55f4-11e9-90f7-9462ccb9ebed.png)

**Comment by lanux** [comment]
好的，谢谢，已经找到原因了，是配置的接口url错了，多了个http， 导致请求失败，但是我建议可以考虑把全局错误信息也抛出到界面上显示出来更直观
