### ISSUE TITLE
接口状态无法更新

### ISSUE THREAD

**Issue by xuliuzhu1834** [YMFE/yapi#93]
## Version 1.3.0
~ 

## What is expected
~ 接口状态变为以选择的状态

## Step to reproduce
~ 进入接口编辑,将未完成状态更新为已完成,提示更新成功,实际上并没有成功

## Environment
~ macos
![3ea162d8-546b-4212-bf44-d74a771629c8](https://user-images.githubusercontent.com/8508762/34239753-7c86133a-e644-11e7-9d88-bb3f6f2bd8e6.png)
![49a044c6-77fd-4109-b0d2-11649ca42b0c](https://user-images.githubusercontent.com/8508762/34239759-86476cc0-e644-11e7-95c1-b6d99d66fd88.png)

**Comment by gaoxiaomumu** [comment]
bug 已经修复
