### ISSUE TITLE
接口在浏览器直接打开是有值返回的，但是在yapi里运行返回为空，在chrome调试工具里的Network也显示返回是空

### ISSUE THREAD

**Issue by wizizm** [YMFE/yapi#932]
## 版本号
1.5.2

## 什么问题
接口在浏览器直接打开是有值返回的，在chrome调试工具里的Network显示正常，后台日志也显示有结果返回了。但是在yapi里运行返回为空，在chrome调试工具里的Network也显示返回是空，后台日志显示有结果返回。

## 如何复现此问题
每次运行均如此 

## 什么浏览器
chrome 

## 什么系统（Linux, Windows, macOS）
macOS

**Comment by wizizm** [comment]
![12567B24-4FDD-437D-A5C6-CB4EC20A640C](https://user-images.githubusercontent.com/1917012/55465508-dba53600-562f-11e9-962a-882346940f0b.png)
![73D44CD0-19AF-4E47-9821-5C84C6836E14](https://user-images.githubusercontent.com/1917012/55465510-dc3dcc80-562f-11e9-8585-b51fe17dcec4.png)

**Comment by wizizm** [comment]
上面图一是在浏览器直接返回是有数据返回的，图二是在yapi里跑，显示返回结果为空，两次在后台日志都是显示有值返回的。

**Comment by wizizm** [comment]
更新浏览器跨域插件后就正常了，close

**Comment by zmjrandy** [comment]
我的问题应该和你一样，你什么插件，哪个版本？

**Comment by Sparkinzy** [comment]
> 更新浏览器跨域插件后就正常了，close

更新到那个版本的跨域插件呢
