### ISSUE TITLE
根据http状态码来判断接口是否调用成功

### ISSUE THREAD

**Issue by EnwardZuLiu** [YMFE/yapi#94]
## Version
~ 1.3.0

## What is expected
~ 接口调用成功，讲道理应该是根据返回的状态码来判断调用是否失败吧，不然所有的接口都是调用成功的

## Step to reproduce
~ 

## Environment
~ cent os 6.6

**Comment by suxiaoxin** [comment]
![image](https://user-images.githubusercontent.com/17695103/34282120-d5ec8ad2-e688-11e7-88dd-2a535d8467cb.png)
加 httpcode 脚本实现吧
