### ISSUE TITLE
Path中包含等于号时使用请求的参数作为应答，应答内容被截断

### ISSUE THREAD

**Issue by Pastel001** [YMFE/yapi#96]
## Version
~ V1.2.9

## What is expected
~
能够正常以请求的参数作为应答

## Step to reproduce
~ 1、创建一个接口  /test/id={id}/what
应答为{“id”:"{$params.id}"}
2、运行界面输入id为123，实际返回的应答是{“id”:“1”}
运行界面输入id为abc，实际返回的应答是{“id”:“a”}
## Environment
~ windows 7

**Comment by gaoxiaomumu** [comment]
无法复现
![image](https://user-images.githubusercontent.com/21135585/34292599-7f423dee-e73c-11e7-93ef-4282943edbd9.png)

**Comment by Pastel001** [comment]
你这个都404了，都没应答怎么可能复现出来呢
完全按照我说的url试一下呗，谢谢

**Comment by gaoxiaomumu** [comment]
您的问题已经解决，将在下一个版本中发布
