### ISSUE TITLE
服务端测试  TypeError: Cannot read property 'res_body_is_json_schema' of null

### ISSUE THREAD

**Issue by franciszhang** [YMFE/yapi#963]
## 版本号
 v1.5.10

## 什么问题
服务端测试  TypeError: Cannot read property 'res_body_is_json_schema' of null

## 如何复现此问题
一直如此

## 什么浏览器
chrome
## 什么系统（Linux, Windows, macOS）
macOs
![image](https://user-images.githubusercontent.com/12781273/56076733-faad8000-5e06-11e9-8ce3-97b27d29a9a4.png)
![image](https://user-images.githubusercontent.com/12781273/56076757-22044d00-5e07-11e9-928c-e07bd2946b58.png)
![image](https://user-images.githubusercontent.com/12781273/56076763-30526900-5e07-11e9-898f-37fc595b6d89.png)
![image](https://user-images.githubusercontent.com/12781273/56076765-39433a80-5e07-11e9-8615-da112f4466f3.png)

**Comment by Moonzoe** [comment]
请问这个问题的原因是什么？怎么解决的啊？

**Comment by xuelucky** [comment]
同问题，请问怎么解决
