### ISSUE TITLE
获取不到最新的1.3.0版本

### ISSUE THREAD

**Issue by newjia** [YMFE/yapi#97]
## Version
~v1.2.9 

## What is expected
~当命令行输入yapi ls 能输出v1.3.0 并能通过 yapi  update 升级到1.3.0

## Step to reproduce
~
1 cd  {项目目录}
2 yapi ls //查看版本号列表.   获取不到最新的v1.3.0 ，只有v1.2.9
3 yapi update //升级到最新版本 只能更新到1.2.9

## Environment
~ UBUNTU v14.    NGINX

**Comment by suxiaoxin** [comment]
因 v1.3.0 存在部分影响功能的bug，已经下线，等待下周发布的 v1.3.1 版本吧

**Comment by newjia** [comment]
好的。收到！

**Comment by suxiaoxin** [comment]
@newjia 已经发布 v1.3.1 ，有空试用下
