### ISSUE TITLE
http://yapi.demo.qunar.com/ 我在网站创建的账号 用户不存在了  怎么回事

### ISSUE THREAD

**Issue by yh4922** [YMFE/yapi#970]

**Comment by Merbn** [comment]
我的也是。求告知

**Comment by liansky** [comment]
我的也是。求告知

**Comment by Ailor59** [comment]
刚发现了这个问题，我有点慌啊，官方也没有联系方式～我有数据在里面啊

**Comment by VeHan** [comment]
我也是，怎么回事啊

**Comment by jasonjoo2010** [comment]
你们为啥要往demo演示中放数据

**Comment by TJDjchao** [comment]
我也是，怎么回事啊，里面有挺多api的

**Comment by xjchenhao** [comment]
我也是。。。

**Comment by sijidong** [comment]
Please tell me what happen, my account has gone away

**Comment by nmxiaowei** [comment]
我们本地搭建的，还是本地搭建好

**Comment by clare-sang** [comment]
我也是，求公告，什么时候能够修复

**Comment by leochan2017** [comment]
我也是。。求恢复一下。我备份出来。。

**Comment by guiguzigang** [comment]
昨天开始都登不进了啊，清账号都不提前公告一下

**Comment by yh4922** [comment]
能不能恢复一下  让我备份出来

**Comment by hellosean1025** [comment]
demo 站点因昨天受到了不明网络供给，导致数据库数据丢失。
另外demo 是演示站点，正式使用请单独部署，请勿把重要数据和接口放到 demo 演示站点。

**Comment by miaozilong** [comment]
我本地搭建的 也提示用户不存在了 我用管理员登录进去改了用户名为英文也是不行  我无语了

**Comment by kongdetai** [comment]
同样的问题  本地搭建 config 里面的 用户 都提示不存在
