### ISSUE TITLE
测试接口：返回body为空

### ISSUE THREAD

**Issue by YoYoOk** [YMFE/yapi#983]
## 版本号
~ 1.5.2

## 什么问题
~Warning  
返回参数 data 应当是 object 类型

## 如何复现此问题
~ 某一个接口多次测试之后出现，而且导致所有接口测试返回都是一样了。

## 什么浏览器
~ 谷歌浏览器

## 什么系统（Linux, Windows, macOS）
windows10

**Comment by shavenG** [comment]
碰到同样的问题，原来正常，今天使用时发现所有接口都出现这个问题

**Comment by shouldnotappearcalm** [comment]
是服务端测试吗

**Comment by shavenG** [comment]
> 是服务端测试吗

客户端测试

**Comment by shouldnotappearcalm** [comment]
运行多次出现吗?确实没更新到1.6.0版本吧?

**Comment by shavenG** [comment]
> 运行多次出现吗?确实没更新到1.6.0版本吧?

版本: 1.4.3，所有接口原来测试正常的，现在每次运行时都出现这个问题。
docker部署，今天发现挂了，重新拉起来以后就这样了。

**Comment by zjpzjp** [comment]
1、服务端 yapi-cli 升级(用npm重装全局yapi-cli)
`npm install -g yapi-cli --registry https://registry.npm.taobao.org`
2、 运行 `yapi ls` 查看是否有1.6x版本出现 如果出现 说明yapi-cli 升级成功
3、到项目目录  vendors文件夹 的上一层目录 运行 yapi update 升级 yapi程序到1.6x 重新运行yapi服务
4、客户端 chrome扩展 cross-request 需要从2.x升级到3.0
至此 yapi升级完成 唯一遗憾是直接F12没法看到请求 和不支持file上传了
