### ISSUE TITLE
swagger 数据导入深层对象数据会丢失

### ISSUE THREAD

**Issue by xuliuzhu1834** [YMFE/yapi#99]
## Version 
~ 1.3.1

## What is expected
~ 完整显示数据

## Step to reproduce
~   ##将swagger数据导入

1. 第三层开始数据对象内的属性会丢失,
2. 如果一次导入大量接口, 接口内第三层数据有数组对象,那么这个字段会直接丢失
可能还有其它问题,暂时未发现

## Environment
~ macos  10.13.2 
chrome 63.0.3239.84

导入结果链接: http://yapi.demo.qunar.com/group/3495

源文件: [swagger.zip](https://github.com/YMFE/yapi/files/1586491/swagger.zip)

文件内包含一个多数据json 和两个单个接口的json

**Comment by gaoxiaomumu** [comment]
该问题已解决，会在下一个版本中发布
