### ISSUE TITLE
在pre-request script 如何获取当前选择的环境

### ISSUE THREAD

**Issue by swustdyd** [YMFE/yapi#990]
具体就是，希望根据当前选择的环境，去更行相应环境下的环境变量，比如我选择的是local，就希望在pre-request script中知道我选择的是local

**Comment by bizhen-yang** [comment]
hello 这样可以吗？
`if (context.hostname=="127.0.0.1"){
    context.requestHeader.token = "99cd0cfcc97c6848654187250263cb64d521b20d";
}
else if (context.hostname=="www.baidu.com"){
     context.requestHeader.token = "796779fe25ec260e11b50a0563e66e78034c7d4f"
}`

**Comment by bizhen-yang** [comment]
hello，这样可以吗？

`if (context.hostname=="127.0.0.1"){  
    context.requestHeader.token = "99cd0cfcc97c6848654187250263cb64d521b20d";  
}  
else if (context.hostname=="www.baidu.com"){  
     context.requestHeader.token = "796779fe25ec260e11b50a0563e66e78034c7d4f"  
}`

**Comment by bizhen-yang** [comment]
helo，这样可以吗？
```js
if (context.hostname=="127.0.0.1"){
    context.requestHeader.token = "99cd0cfcc97c6848654187250263cb64d521b20d";
}
else if (context.hostname=="www.baidu.com"){
     context.requestHeader.token = "796779fe25ec260e11b50a0563e66e78034c7d4f"
}
```

**Comment by swustdyd** [comment]
> helo，这样可以吗？
> 
> ```js
> if (context.hostname=="127.0.0.1"){
>     context.requestHeader.token = "99cd0cfcc97c6848654187250263cb64d521b20d";
> }
> else if (context.hostname=="www.baidu.com"){
>      context.requestHeader.token = "796779fe25ec260e11b50a0563e66e78034c7d4f"
> }
> ```

**Comment by swustdyd** [comment]
可以的，之前没想到，谢谢了
