### ISSUE TITLE
1.6.2版本删除项目失败

### ISSUE THREAD

**Issue by deanwong** [YMFE/yapi#991]
## 版本号
1.6.2

## 什么问题
无法删除项目

## 如何复现此问题
创建项目，删除

## 什么浏览器
Chrome

## 什么系统（Linux, Windows, macOS）
macOS
![Jietu20190419-112320](https://user-images.githubusercontent.com/4144156/56403818-b5210500-6295-11e9-81e5-7298bf8d3eb6.jpg)

**Comment by shouldnotappearcalm** [comment]
周末修复这个bug,到时候更新下个版本就好了.这个锅我背了,下次一定考虑到各种场景测试

**Comment by hellosean1025** [comment]
@deanwong 升级到 v1.5.14 解决
