### ISSUE TITLE
环境配置直接白屏

### ISSUE THREAD

**Issue by franciszhang** [YMFE/yapi#994]
## 版本号
1.6.2

## 什么问题
环境配置直接白屏

## 如何复现此问题
升级1.6.1 再升1.6.2

## 什么浏览器
chrome

## 什么系统（Linux, Windows, macOS）
macOS

![image](https://user-images.githubusercontent.com/12781273/56422918-5b8ff900-62dc-11e9-8a67-5e9ca393277a.png)

顺便请问一下，yapi数据存储在哪里？

**Comment by shouldnotappearcalm** [comment]
是一直点进去都白屏吗，yapi数据存储在mongodb

**Comment by hellosean1025** [comment]
发下 project/get 获取的数据

**Comment by franciszhang** [comment]
@hellosean1025 
{"errcode":0,"errmsg":"成功！","data":{"switch_notice":true,"is_mock_open":false,"is_sync_open":false,"strice":false,"is_json5":false,"_id":5,"name":"鉴权中心","basepath":"","project_type":"private","uid":11,"group_id":15,"icon":"code-o","color":"cyan","add_time":1555147119,"up_time":1555669495,"env":[{"header":[],"global":[null],"_id":"5cb547552d5a121c539fba03","name":"auth_online","domain":"https://xxx.xxx.com"},{"header":[],"global":[null],"_id":"5cb547132d5a121c539fba00","name":"新正式环境域名","domain":"http://online.xc.xxx.com/online"},{"header":[],"global":[null],"_id":"5cb546f32d5a121c539fb9fe","name":"新测试环境域名","domain":"http://test.xc.xxx.com/test"}],"tag":[],"pre_script":"","cat":[{"index":0,"_id":11,"name":"公共分类","project_id":5,"desc":"公共分类","uid":11,"add_time":1555147119,"up_time":1555147119,"__v":0},{"index":0,"_id":13,"name":"merchant-login-controller","project_id":5,"desc":"Merchant Login Controller","uid":11,"add_time":1555147180,"up_time":1555147180,"__v":0},{"index":0,"_id":15,"name":"new-login-controller","project_id":5,"desc":"New Login Controller","uid":11,"add_time":1555147180,"up_time":1555147180,"__v":0},{"index":0,"_id":17,"name":"old-login-controller","project_id":5,"desc":"Old Login Controller","uid":11,"add_time":1555147180,"up_time":1555147180,"__v":0},{"index":0,"_id":18,"name":"open-auth-controller","project_id":5,"desc":"Open Auth Controller","uid":11,"add_time":1555147180,"up_time":1555147180,"__v":0},{"index":0,"_id":19,"name":"simulate-login-controller","project_id":5,"desc":"Simulate Login Controller","uid":11,"add_time":1555147181,"up_time":1555147181,"__v":0},{"index":0,"_id":21,"name":"user-pass-controller","project_id":5,"desc":"User Pass Controller","uid":11,"add_time":1555147181,"up_time":1555147181,"__v":0},{"index":0,"_id":22,"name":"wx-auth-controller","project_id":5,"desc":"Wx Auth Controller","uid":11,"add_time":1555147181,"up_time":1555147181,"__v":0},{"index":0,"_id":25,"name":"yxt-login-controller","project_id":5,"desc":"Yxt Login Controller","uid":11,"add_time":1555147181,"up_time":1555147181,"__v":0},{"index":0,"_id":76,"name":"测试接口","project_id":5,"desc":null,"uid":17,"add_time":1555380521,"up_time":1555380521,"__v":0}],"role":"admin"}}

**Comment by franciszhang** [comment]
会不会跟 global":[null] 有关系，还有我要怎么才能把环境全删掉然后再建环境（因为1.5.11是可以用的），另外yapi数据存储在mongo的哪个库，我现在也找不到存储的数据 @shouldnotappearcalm @hellosean1025

**Comment by shouldnotappearcalm** [comment]
我知道问题了，我的锅，马上改

**Comment by shouldnotappearcalm** [comment]
数据在mongodb

**Comment by franciszhang** [comment]
@shouldnotappearcalm 辛苦辛苦，还有数据在mongodb的具体位置，是在哪个库，能告知一下吗？我已查看所有库里都没有找到yapi的数据 ，下图是我的Mongo
![image](https://user-images.githubusercontent.com/12781273/56459032-d0d4fa00-63c0-11e9-835a-5db3760e0afc.png)

**Comment by shouldnotappearcalm** [comment]
默认就在yapi吧，你这没看到啊

**Comment by franciszhang** [comment]
为何我的mongo里没有展示yapi这个库，真找不到。。。

**Comment by shouldnotappearcalm** [comment]
你看下你的gmail邮箱，加个qq详细说

**Comment by qianlongdoit** [comment]
> @shouldnotappearcalm 辛苦辛苦，还有数据在mongodb的具体位置，是在哪个库，能告知一下吗？我已查看所有库里都没有找到yapi的数据 ，下图是我的Mongo
> ![image](https://user-images.githubusercontent.com/12781273/56459032-d0d4fa00-63c0-11e9-835a-5db3760e0afc.png)

这一步你是不是漏了啊，没有初始化，初始化的数据库就是yapi啊
```bash
npm run install-server  # 安装程序会初始化数据库索引和管理员账号，管理员账号名可在 config.json 配置
```

**Comment by hellosean1025** [comment]
Fixed. v1.5.12

**Comment by hellosean1025** [comment]
@qianlongdoit
